In [2]:
import numpy as np

In [3]:
arr = [1,3,4,5]
a = np.array(arr)
print(a)

[1 3 4 5]


In [4]:
a = np.arange(1,10,0.5)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [5]:
a = np.eye(10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [6]:
a = np.random.random_integers(1,10)
a

C:\Users\guifei\AppData\Local\Temp\ipykernel_7992\346819877.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  a = np.random.random_integers(1,10)


np.int32(6)

In [7]:
b = np.random.normal(0,0.1,5)
b

array([-0.04579672, -0.15875562,  0.06664515, -0.11423671, -0.06887768])

In [8]:
a = np.array([(1,2),(3,4),(5,6)],dtype=np.float64)
a[0,1]
a[:,1]
a[1,:]

array([3., 4.])

In [9]:
a = np.array([(1,2),(3,4),(5,6)])
i,j = a[0]
for i,j in a:
    print(i,j)

1 2
3 4
5 6


In [10]:
import numpy as np
a = np.array([(1,2),(3,4),(5,6)])
print(3 in a)

True


In [11]:
print((1,2,3) in a)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [4]:
print(5 in a)

True


In [10]:
a = np.reshape(a,(2,3))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a = np.reshape(a,(1, 6))
a

array([[1, 2, 3, 4, 5, 6]])

In [14]:
a = np.reshape(a,(6, 1))
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
a = np.reshape(a,(3,2, 1))
a

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [18]:
a = np.array([(1,2,3),(3,4,5),(5,6,7)])
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [27]:
a.transpose()
b= a.transpose()
b

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7]])

In [25]:
c = b.flatten()
c

array([1, 2, 3, 3, 4, 5, 5, 6, 7])

In [28]:
a1 = np.array([(1,2,3),(3,4,5),(5,6,7)])
a1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [31]:
a1 = a1[:,:,np.newaxis]
a1.shape

(3, 1, 1, 1, 3)

In [33]:
a1.sum()

np.int64(36)

In [34]:
b

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7]])

In [36]:
print(b.max())
print(b.argmax())
print(b.argmin())

7
8
0


In [41]:
a = np.array([(1,2,3),(3,4,5),(5,6,7)])
b = np.array([(1,3,4),(3,5,7),(5,4,7)])
dot = np.dot(a,b)
print(np.dot(a,b))
print(a @ b)
print(a * b)
print(a + b)
print(a - b)

[[ 22  25  39]
 [ 40  49  75]
 [ 58  73 111]]
[[ 22  25  39]
 [ 40  49  75]
 [ 58  73 111]]
[[ 1  6 12]
 [ 9 20 35]
 [25 24 49]]
[[ 2  5  7]
 [ 6  9 12]
 [10 10 14]]
[[ 0 -1 -1]
 [ 0 -1 -2]
 [ 0  2  0]]


In [49]:
result = np.dot(a,b)
print(result)
np.save("result.npy", result)

[[ 22  25  39]
 [ 40  49  75]
 [ 58  73 111]]


In [50]:
result = np.load("result.npy")
print(result)

[[ 22  25  39]
 [ 40  49  75]
 [ 58  73 111]]


In [17]:
# broadcast 广播机制 一最后一维为参考，4x4 1x4 最后一维相同或者其中之一为1 则可按照此维度进行广播
# 如果两个值不相同且都不为1，则不能进行广播
# 广播只适用于矩阵的 + - * /等作用于每个元素的运算，不适用于矩阵运算，如dot
a = np.array([(1,2,3,5),(3,4,5,5),(5,6,7,7),(7,8,9,8)])
b= np.array([(1,3,4,3)])
print(a)
print(b)
print(a + b)
b = b.T # 4x1
print(b)
print(a+b)
c = a + b
print(c)

[[1 2 3 5]
 [3 4 5 5]
 [5 6 7 7]
 [7 8 9 8]]
[[1 3 4 3]]
[[ 2  5  7  8]
 [ 4  7  9  8]
 [ 6  9 11 10]
 [ 8 11 13 11]]
[[1]
 [3]
 [4]
 [3]]
[[ 2  3  4  6]
 [ 6  7  8  8]
 [ 9 10 11 11]
 [10 11 12 11]]
[[ 2  3  4  6]
 [ 6  7  8  8]
 [ 9 10 11 11]
 [10 11 12 11]]


In [25]:
# numpy 数组访问
c = np.array([(1,2,3,5),(3,4,5,5),(5,6,7,7),(7,8,9,8)])
# 取第一行
print(c[0])
# 取第一行第三个数据, 注意写法区别，建议按照第二种写法，方便理解
print(c[0,2])
print(c[0][2])
# 取第二行之后所有行
print(c[1:])
# # 取第二行, 注意此处是左闭右开
print(c[1:2])
# 取第一列
print(c[:, 0])

[1 2 3 5]
3
3
[[3 4 5 5]
 [5 6 7 7]
 [7 8 9 8]]
[[3 4 5 5]]
[1 3 5 7]


In [52]:
# numpy 数组遍历
d = np.array([(1,2,3,5),(3,4,5,5),(5,6,7,7),(7,8,9,8)])
# for i in d: # 遍历时是按照每一个行为 i 来取的
#     print(i)
# for j in d.T: # 转置后即可按照列取出
#     print(j)
# for i,j,k,h in d:
#     print(i,j,k,h)
# for i in d: # 遍历取出数组中所有元素，不建议这样取，可以按照下标来取
#     for j in i:
#         print(j)
dim = a.shape
# 先获取数组的形状，然后根据形状来获取下标，遍历下标数据获取
for k in range(0, dim[0], 1): # 二维数组的行坐标，0 开始 到 i-1 结束，不长为1（默认为1，可以不写）
    for l in range(0, dim[1], 1):  # 二维数组的列坐标，0 开始 到 j-1 结束，不长为1（默认为1，可以不写）
        print("第{}行,第{}列元素:{}".format(k, l, d[k][l]))
        print("第%s行,第%s列元素:%d",(k, l, d[k][l]))




第0行,第0列元素:1
第%s行,第%s列元素:%d (0, 0, np.int64(1))
第0行,第1列元素:2
第%s行,第%s列元素:%d (0, 1, np.int64(2))
第0行,第2列元素:3
第%s行,第%s列元素:%d (0, 2, np.int64(3))
第0行,第3列元素:5
第%s行,第%s列元素:%d (0, 3, np.int64(5))
第1行,第0列元素:3
第%s行,第%s列元素:%d (1, 0, np.int64(3))
第1行,第1列元素:4
第%s行,第%s列元素:%d (1, 1, np.int64(4))
第1行,第2列元素:5
第%s行,第%s列元素:%d (1, 2, np.int64(5))
第1行,第3列元素:5
第%s行,第%s列元素:%d (1, 3, np.int64(5))
第2行,第0列元素:5
第%s行,第%s列元素:%d (2, 0, np.int64(5))
第2行,第1列元素:6
第%s行,第%s列元素:%d (2, 1, np.int64(6))
第2行,第2列元素:7
第%s行,第%s列元素:%d (2, 2, np.int64(7))
第2行,第3列元素:7
第%s行,第%s列元素:%d (2, 3, np.int64(7))
第3行,第0列元素:7
第%s行,第%s列元素:%d (3, 0, np.int64(7))
第3行,第1列元素:8
第%s行,第%s列元素:%d (3, 1, np.int64(8))
第3行,第2列元素:9
第%s行,第%s列元素:%d (3, 2, np.int64(9))
第3行,第3列元素:8
第%s行,第%s列元素:%d (3, 3, np.int64(8))


In [59]:
# numpy 中八位占一个字节
e = np.array([(1,2,3,5),(3,4,5,5),(5,6,7,7)], dtype=np.uint8)
# 获取矩阵的维数
print(e.ndim)
# 获取矩阵的形状，返回一个元组
print(e.shape)
# 返回矩阵元素的个数
print(e.size)
# 返回数组中每个元素的字节单位长度, 默认是float8
print(e.itemsize)
print(e.dtype)
# mT是ndarray对象的一个属性，用于获取数组的转置。当数组是二维时，mT返回的是数组的转置视图；当数组是一维时，mT会抛出一个错误，因为一维数组没有转置的概
print(e.mT)
# T也是ndarray对象的一个属性，用于获取数组的转置。与mT不同，T可以用于一维数组，此时它会返回一个与原数组长度相同的新数组，而不是视图
print(e.T)

2
(3, 4)
12
1
uint8
[[1 3 5]
 [2 4 6]
 [3 5 7]
 [5 5 7]]
[[1 3 5]
 [2 4 6]
 [3 5 7]
 [5 5 7]]


In [61]:
# NumPy 数组的基本操作
f = np.array([(1,2,3,5),(3,4,5,5),(5,6,7,7)])
print(f.dtype)
# 检查某个数是否矩阵中的元素
print(5 in f)
print(8 in f)


int64
True
False


In [79]:
# 数组重拍
a1 = np.zeros([2,3,4,5]) # 返回以一个三维矩阵
print(a1)
# 重新指定矩阵的形状
print(a1.reshape(120,1)) # 指定其为一个 120 * 1的列向量
print(a1.reshape(1,120)) # 指定其为一个 1 * 120的行向量
a1.reshape(20,6) # 指定其为一个 20 * 6的矩阵
# 规律总结：如果一个详细的元素个数为N 个，重新执行形状后，新矩阵的各个维度的乘积必须等于N否者转换失败
# 例如：
# print(a1.reshape(20,5)) # 指定其为一个 1 * 120的行向量
# print(a1.reshape(20,7)) # 指定其为一个 1 * 120的行向量


[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [98]:
# 将多维数组转换为1为数组
a2 = np.array([(1,2,3,5),(3,4,5,5),(5,6,7,7)])
print(a2.flatten()) # flatten 为变平的意思
print(a2.shape)
# 增加维度
a3 = np.array([1,2,3])
a.shape
a4 = a3[:, np.newaxis]
a5 = a2[np.newaxis, :]
a6 = a2[:, np.newaxis,:]
print(a4.shape)
print(a5.shape)
print(a6.shape)
'''
np.newaxis和reshape的主要区别在于它们增加数组维度的方式和使用场景。‌

np.newaxis
np.newaxis用于增加数组的维度。它实际上是一个None对象的别名，通过在切片操作中使用np.newaxis，可以改变数组的维度，从而方便进行矩阵运算。使用np.newaxis会增加一个新的维度，但不会复制数据，只是增加一个新的维度标签，数据仍然共享相同的内存空间。例如：

a = np.ones((3,3)) 创建一个3x3的数组a。
b = a[:, np.newaxis] 会将a的维度从2维变为3维，形状变为(3, 1, 3)。
reshape
reshape函数用于重新调整数组的形状而不改变其数据。它不会增加新的维度，而是重新排列现有数据以匹配新的形状。使用reshape时，新形状的总元素数量必须与原数组相同。例如：

a = np.arange(12) 创建一个包含12个元素的数组a。
b = a.reshape(-1, 1) 将a重新塑形为12行1列的形状。
使用场景
np.newaxis‌：适用于需要增加维度进行矩阵运算的场景，如广播机制的应用。它常用于构造高维数组或进行特定的矩阵操作。
reshape‌：适用于需要改变数组形状但不改变数据内容的场景。它主要用于调整数组的布局以适应不同的数据处理需求。
'''


[1 2 3 5 3 4 5 5 5 6 7 7]
(3, 4)
(3, 1)
(1, 3, 4)
(3, 1, 4)


'\nnp.newaxis和reshape的主要区别在于它们增加数组维度的方式和使用场景。\u200c\n\nnp.newaxis\nnp.newaxis用于增加数组的维度。它实际上是一个None对象的别名，通过在切片操作中使用np.newaxis，可以改变数组的维度，从而方便进行矩阵运算。使用np.newaxis会增加一个新的维度，但不会复制数据，只是增加一个新的维度标签，数据仍然共享相同的内存空间。例如：\n\na = np.ones((3,3)) 创建一个3x3的数组a。\nb = a[:, np.newaxis] 会将a的维度从2维变为3维，形状变为(3, 1, 3)。\nreshape\nreshape函数用于重新调整数组的形状而不改变其数据。它不会增加新的维度，而是重新排列现有数据以匹配新的形状。使用reshape时，新形状的总元素数量必须与原数组相同。例如：\n\na = np.arange(12) 创建一个包含12个元素的数组a。\nb = a.reshape(-1, 1) 将a重新塑形为12行1列的形状。\n使用场景\nnp.newaxis\u200c：适用于需要增加维度进行矩阵运算的场景，如广播机制的应用。它常用于构造高维数组或进行特定的矩阵操作。\nreshape\u200c：适用于需要改变数组形状但不改变数据内容的场景。它主要用于调整数组的布局以适应不同的数据处理需求。\n'

In [109]:
# NumPy 数组的数学操作
a = np.ones((2,2))
b = np.array([(-1,3),(-1,2)])
print(a)
print(a.dtype)
print(b)
# 加减乘除 矩阵形状相同时，对应位置上元素的 加减乘除
print(a + b)
print(a - b)
print(a / b)
# 求和，矩阵所有元素相加
print(a.sum())
print(b.sum())
# 求积，矩阵所有元素相乘
print(a.prod())
print(b.prod())

[[1. 1.]
 [1. 1.]]
float64
[[-1  3]
 [-1  2]]
[[0. 4.]
 [0. 3.]]
[[ 2. -2.]
 [ 2. -1.]]
[[-1.          0.33333333]
 [-1.          0.5       ]]
4.0
3
1.0
6


In [112]:
# 平均数，⽅差，标准差，最⼤值，最⼩值
a7 = np.array([(1,2,3),(3,4,5),(5,6,7)])
# 求平均值
print(a7.mean())
# 求方差 ： 方差‌：衡量数据分布的离散程度，计算为各数据与均值差的平方的平均值。
print(a7.var())
# 求标准差：标准差‌：方差的平方根，消除量纲影响，与原始数据单位一致。
print(a7.std())
# 获取最小值
print(a7.min())
# 获取最大值
print(a7.max())
'''
对于高维矩阵，比如一个三维数组（样本×特征×时间），用户可能需要明确计算的维度。不同的计算方向会影响结果的意义。比如，沿着样本轴计算，可以得到每个特征在不同样本间的差异；沿着特征轴计算，可能反映每个样本在不同特征上的变化；而沿着时间轴可能展示每个特征随时间的变化情况。
关于含义，高维矩阵的方差和标准差能帮助理解不同维度上的数据波动。比如在图像处理中，每个像素点的方差可能表示亮度变化；在自然语言处理中，词向量的标准差可能反映词义的多样性。此外，降维处理前的方差分析可以帮助选择重要特征，异常检测中高方差可能提示异常点。
高维矩阵的方差和标准差通过‌指定计算维度‌量化不同方向上的数据波动性，其核心意义是：
‌定位重要维度‌（如高方差特征）；
‌揭示数据分布特性‌（如稳定性、异常性）；
‌支持决策‌（如降维、标准化、异常检测）。
通常对于高维矩阵，需要指定其轴，以反映其沿着某个轴变化的数据变化剧烈程度：
# 生成三维矩阵（样本×特征×时间）
data = np.random.rand(100, 5, 10)  # 100样本，5特征，10时间点

# 沿样本轴计算方差（每个特征-时间点的样本方差）
var_sample = np.var(data, axis=0)
std_sample = np.std(data, axis=0)

# 沿特征轴计算方差（每个样本-时间点的特征方差）
var_feature = np.var(data, axis=1)
std_feature = np.std(data, axis=1)
如果不指定轴：若不指定计算维度（即不设置 axis 参数），方差和标准差会将所有元素视为‌单一数据集‌进行全局计算；
关键结论‌
‌默认全局计算‌：简单但粗粒度，适用于整体评估，但牺牲局部信息。
‌优先指定维度‌：在结构化数据（如特征、时间、样本）中，明确指定计算维度更有利于精准分析。
‌决策建议‌：
若需保留维度特性（如特征工程），必须指定 axis；
若仅需宏观波动指标，可不指定维度。
'''


4.0
3.3333333333333335
1.8257418583505538
1
7


In [131]:
# 获取最大值索引
a8 = np.array([(1,2,8),(3,9,7),(5,6,8)])
print(a8.shape)
# 以行为轴，按列计算
print(a8.argmax(axis=0)) # [2 1 0] 结果解释：第一列最大值为 5 在第2行， 第二列最大值9 在第1行， 第三列最大值8 在第1行，如果出现相同大小的值，取第一个出现的位置
# 以列为轴，按行计算
print(a8.argmax(axis=1)) # [2 1 2] 结果解释：第一行最大值为 8 在第2列， 第二行最大值9在第1列， 第三行最大值8 在第2列，如果出现相同大小的值，取第一个出现的位置
# 获取矩阵在第一个维度上的最小值，返回其坐标
print(a8.argmin(axis=0))
# 获取矩阵在第二个维度上的最小值，返回其坐标
print(a8.argmin(axis=1))
# 如果不指定轴，会将矩阵按照以为向量处理
'''
np.argmax 和 np.argmin 通过‌索引定位极值‌，是数据分析中的高频工具。
‌优先指定 axis‌：明确计算维度，避免误用全局结果。
‌注意极值唯一性‌：多个相同极值时需谨慎处理索引逻辑。
'''

(3, 3)
[2 1 0]
[2 1 2]
[0 0 1]
[0 0 0]


In [132]:
a = np.array([1.2, 3.8, 4.9])
# 取元素的上限
print("ceil:", np.ceil(a))
# 取元素的下限
print("floor:", np.floor(a))
# 元素四舍五入
print("rint:", np.rint(a))

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [136]:
a9 = np.array([(8,2,8),(3,9,7),(5,6,8)])
# a9.sort(1)
a9.sort(0)

'''
np.sort的默认axis参数是-1，也就是最后一个轴。对于高维数组，比如三维数组，形状是（a, b, c），如果不指定axis，np.sort会沿着最后一个轴（即axis=2）进行排序。每个子数组沿着最后一个轴独立排序，保持其他轴的结构不变。例如，三维数组的每个二维切片在第三个维度上排序。(默认升序)
'''
a9

array([[3, 2, 7],
       [5, 6, 8],
       [8, 9, 8]])

In [138]:
# NumPy 线性代数
# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]] , dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]] , dtype=np.float32)
# 使⽤ np.dot 进⾏矩阵乘法
result_dot = np.dot(m1, m2)
# 使⽤ @ 运算符进⾏矩阵乘法
result_at = m1 @ m2
print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使⽤ np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使⽤ @ 运算符得到的矩阵乘法结果:")
print(result_at)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使⽤ np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使⽤ @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]


In [139]:
# 创建⼀个全零矩阵，⽤于存储⼿动推演的结果
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
# 外层循环：遍历 matrix1 的每⼀⾏
# i 表⽰结果矩阵的⾏索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每⼀列
    # j 表⽰结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i ⾏与 matrix2 的第 j 列对应元素的乘积之和
        # k 表⽰参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i ⾏第 k 列元素与 matrix2 的第 k ⾏第 j 列元素相乘，并累
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i + 1},{j + 1}]:{manual_result[i, j]}\n")
print("⼿动推演结果:")
print(manual_result)

1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

⼿动推演结果:
[[19. 22.]
 [43. 50.]]
