In [2]:
import torch
data = torch.tensor([[2,3,224,224],[2, 4, 5, 8]])
data

tensor([[  2,   3, 224, 224],
        [  2,   4,   5,   8]])

In [2]:
data2 = torch.ones_like(data, dtype=torch.float)
data2
print(data2)
data3 = torch.zeros_like(data, dtype=torch.float64)
print(data3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [3]:
data3.dtype

torch.float64

In [4]:
shape = (2,3,)
rand_tensor = torch.rand(shape, dtype=torch.float64)
print(rand_tensor)
rand_tensor1 = torch.randn(shape, dtype=torch.float64)
print(rand_tensor1)
print(rand_tensor.size())

tensor([[0.6654, 0.0060, 0.4682],
        [0.7218, 0.7890, 0.4860]], dtype=torch.float64)
tensor([[ 0.2291, -0.2962,  1.0932],
        [-0.5130,  0.1062, -1.4959]], dtype=torch.float64)
torch.Size([2, 3])


In [5]:
data4 = torch.rand(3,4, device=torch.device('cpu'))
print(data4.shape)
print(data4.dtype)
print(data4.device)

torch.Size([3, 4])
torch.float32
cpu


In [6]:
print(torch.cuda.is_available())

False


In [7]:
if torch.cuda.is_available():
    device = torch.device('cuda:0')
    data4.to(device)
print(data4)
print(data4.device)

tensor([[0.2441, 0.1784, 0.1411, 0.7382],
        [0.7357, 0.5336, 0.4127, 0.2003],
        [0.6950, 0.6695, 0.6646, 0.3763]])
cpu


In [8]:
data4 = torch.cat([data4, data4, data4])
print(data4)

tensor([[0.2441, 0.1784, 0.1411, 0.7382],
        [0.7357, 0.5336, 0.4127, 0.2003],
        [0.6950, 0.6695, 0.6646, 0.3763],
        [0.2441, 0.1784, 0.1411, 0.7382],
        [0.7357, 0.5336, 0.4127, 0.2003],
        [0.6950, 0.6695, 0.6646, 0.3763],
        [0.2441, 0.1784, 0.1411, 0.7382],
        [0.7357, 0.5336, 0.4127, 0.2003],
        [0.6950, 0.6695, 0.6646, 0.3763]])


In [9]:
rand_tensor

tensor([[0.6654, 0.0060, 0.4682],
        [0.7218, 0.7890, 0.4860]], dtype=torch.float64)

In [10]:
tenser = torch.tensor([[1,2,3,4,5],[3,4,5,6,7]], dtype=torch.int)
tenser.add_(5)
print(tenser)

tensor([[ 6,  7,  8,  9, 10],
        [ 8,  9, 10, 11, 12]], dtype=torch.int32)


In [14]:
import torch
from torchviz import make_dot
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=True)

'expression.png'

In [4]:
import torch
data = [[2,3,224,224],[2, 4, 5, 8]]
t_data = torch.tensor(data)
t_data

tensor([[  2,   3, 224, 224],
        [  2,   4,   5,   8]])

In [6]:
import numpy as np
a_data = np.array(data)
print(a_data)
t_data1 = torch.from_numpy(a_data)
t_data1

[[  2   3 224 224]
 [  2   4   5   8]]


tensor([[  2,   3, 224, 224],
        [  2,   4,   5,   8]])

In [7]:
t_ones = torch.ones_like(t_data1)
t_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [9]:
t_rand = torch.rand_like(t_data1, dtype=torch.float)
t_rand

tensor([[0.0861, 0.9751, 0.0745, 0.9248],
        [0.1348, 0.9531, 0.0178, 0.8612]])

In [13]:
shape = (2,3,)
t_ones1 = torch.ones(shape, dtype=torch.float)
print(t_ones1)
t_zero = torch.zeros(shape, dtype=torch.float)
print(t_zero)
t_rand1 = torch.randn(shape, dtype=torch.float)
t_rand2 = torch.rand(shape, dtype=torch.float)
print(t_rand1)
print(t_rand2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.2040, -2.1837,  0.3315],
        [-1.1453,  2.2091, -0.4164]])
tensor([[0.8164, 0.6985, 0.7513],
        [0.8843, 0.8006, 0.2845]])


In [15]:
cat = torch.cat((t_rand1, t_rand2), dim=0)
print(cat)
stack = torch.stack((t_rand1, t_rand2), dim=0)
stack


tensor([[ 0.2040, -2.1837,  0.3315],
        [-1.1453,  2.2091, -0.4164],
        [ 0.8164,  0.6985,  0.7513],
        [ 0.8843,  0.8006,  0.2845]])


tensor([[[ 0.2040, -2.1837,  0.3315],
         [-1.1453,  2.2091, -0.4164]],

        [[ 0.8164,  0.6985,  0.7513],
         [ 0.8843,  0.8006,  0.2845]]])

In [16]:
y = cat @ cat.T
y

tensor([[ 4.9202, -5.1959, -1.1096, -1.4736],
        [-5.1959,  6.3653,  0.2951,  0.6375],
        [-1.1096,  0.2951,  1.7188,  1.4949],
        [-1.4736,  0.6375,  1.4949,  1.5039]])

In [17]:
y = cat.matmul(cat.T)
y

tensor([[ 4.9202, -5.1959, -1.1096, -1.4736],
        [-5.1959,  6.3653,  0.2951,  0.6375],
        [-1.1096,  0.2951,  1.7188,  1.4949],
        [-1.4736,  0.6375,  1.4949,  1.5039]])

In [19]:
agg = y.sum()
agg_item = agg.item()
print(agg_item)

3.8050661087036133


In [22]:
array1 = y.numpy()
print(array1)

[[ 4.9202027  -5.1958675  -1.1096333  -1.4736046 ]
 [-5.1958675   6.3653307   0.29513296  0.6374641 ]
 [-1.1096333   0.29513296  1.7188363   1.4949098 ]
 [-1.4736046   0.6374641   1.4949098   1.5038939 ]]


In [32]:
print(array1.shape)
array2 = np.ones_like(array1)
print(array2)
array1 = array1 + array2
print(array1)
print(y)

(4, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 6.9202027  -3.1958675   0.8903667   0.52639544]
 [-3.1958675   8.365331    2.295133    2.637464  ]
 [ 0.8903667   2.295133    3.7188363   3.4949098 ]
 [ 0.52639544  2.637464    3.4949098   3.5038939 ]]
tensor([[ 4.9202, -5.1959, -1.1096, -1.4736],
        [-5.1959,  6.3653,  0.2951,  0.6375],
        [-1.1096,  0.2951,  1.7188,  1.4949],
        [-1.4736,  0.6375,  1.4949,  1.5039]])


In [33]:
from sklearn.datasets import load_iris
data = load_iris()
print(data.target_names)

['setosa' 'versicolor' 'virginica']
