In [1]:
import numpy as np

In [2]:
# 创建ndarray数组
arr = np.array([1,3,5,7,9], float)
arr

array([1., 3., 5., 7., 9.])

In [3]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)],float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [5]:
a1 = np.zeros((5,9), dtype=np.float32)
a1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [6]:
a2 = np.arange(1,10, 0.2)
a2

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [7]:
a3 = np.eye(5)
a3  # one-hot编码

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
a4 = np.random.random(10)  # 模型运算参数初始值
a4

array([0.44166267, 0.51974264, 0.90648682, 0.1560971 , 0.42396847,
       0.28781428, 0.30132369, 0.46598114, 0.59993326, 0.43258172])

In [9]:
a5 = np.random.normal(0, 0.1, 6)  # 模型运算参数初始值
a5

array([ 0.15461968, -0.21860199,  0.20861163,  0.00478073,  0.13372515,
        0.13863931])

In [10]:
a6 = np.array([(1,2), (3,4), (5,6)])
print(a6[:,:])

[[1 2]
 [3 4]
 [5 6]]


In [11]:
a7 = np.array([(1,2), (3,4), (5,6)])
for i,j in a7:
    print(i,j)


1 2
3 4
5 6


In [12]:
a = np.array([(1,2,3), (4,5,6), (7,8,9),(10,16,15)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (4, 3)
size 12
dtype int64


In [13]:
print(3 in a)
print(0 in a)

True
False


In [16]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,3,1)
print(a7)

print(a7.shape)



[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [17]:
print(a)
print(a.T)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 16 15]]
[[ 1  4  7 10]
 [ 2  5  8 16]
 [ 3  6  9 15]]


In [30]:
a = a.flatten()
print(a)

[1 4 7 2 5 8 3 6 9]


In [21]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,:,np.newaxis]  # [3,1,2]
print(a8.shape)
print(a8)

(3, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [22]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]


In [23]:
a.sum()

4.0

In [24]:
a.prod()

1.0

In [27]:
a = np.array([10,8,1])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

mean: 6.333333333333333
var: 14.888888888888891
std: 3.8586123009300755


In [28]:
a = np.array([1.02, 9.5, 3.3])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 1
argmin: 0
ceil: [ 2. 10.  4.]
floor: [1. 9. 3.]
rint: [ 1. 10.  3.]


In [32]:
a = np.array([16,31,12,28,22,31,48])
a.sort()  # 排序
a

array([12, 16, 22, 28, 31, 31, 48])

In [38]:
import torch
tensor = torch.arange(1,5, dtype=torch.float32).reshape(2, 2)

print(tensor.dtype)


y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)



z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


tensor([[ 1.,  4.],
        [ 9., 16.]])

In [57]:
a9 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[4,5,6],[7,8,9]])

a9 * b9

array([[ 4, 10, 18],
       [28, 40, 54]])

In [39]:
import numpy as np


m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)



result_dot = np.dot(m1, m2)


result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)


manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)


for i in range(m1.shape[0]):
    for j in range(m2.shape[1]):
        manual_result[i, j] = 0
        for k in range(m1.shape[1]):
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            manual_result[i, j] += m1[i, k] * m2[k, j]
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [40]:
np.save('result.npy',manual_result)

In [41]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [43]:
a = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
b = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])