In [19]:
import torch

data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
data

tensor([[1., 2.],
        [3., 4.]])

In [20]:
import numpy as np

np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4]])

In [21]:
data2.dtype

torch.int64

In [22]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.9090, 0.9247],
        [0.3446, 0.9096]])

In [23]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8176, 0.3426, 0.7427],
        [0.3807, 0.4333, 0.3260]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [24]:
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

print(m.size())

# 均匀
print(torch.rand(5,3))
# 标准正态
print(torch.randn(5,3))
# 离散正态
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([5, 3])
tensor([[0.7848, 0.1031, 0.0462],
        [0.3533, 0.4529, 0.8046],
        [0.5605, 0.2099, 0.1306],
        [0.0966, 0.4450, 0.8923],
        [0.3023, 0.4044, 0.0474]])
tensor([[ 1.1280,  0.2927,  1.1017],
        [-2.0955,  0.8791,  0.1994],
        [ 0.7146, -0.7436, -0.2422],
        [-1.7103,  0.9483, -0.4753],
        [-0.6994, -0.9840, -1.1945]])
tensor([[-0.1610,  1.8128, -0.1641],
        [-0.3701,  1.9159, -0.7135],
        [-0.6089, -1.2283,  0.0324],
        [-1.0636,  1.3286,  0.5649],
        [-0.3240, -0.3296, -0.4637]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [25]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [26]:
# 是否支持GPU??
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# 使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.3932, 0.5944, 0.1009, 0.4234],
        [0.3209, 0.1513, 0.8973, 0.4428],
        [0.4121, 0.2233, 0.6563, 0.1522]])
cpu
tensor([[0.3932, 0.5944, 0.1009, 0.4234],
        [0.3209, 0.1513, 0.8973, 0.4428],
        [0.4121, 0.2233, 0.6563, 0.1522]], device='mps:0')
mps:0


In [27]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.]])
torch.Size([4, 12])


In [29]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)


y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)



z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [30]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

45.0 <class 'float'>


In [31]:
np_arr = z1.numpy()
np_arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [32]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)
tensor = tensor + 5
print(tensor)
tensor += 5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
tensor([[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])
tensor([[16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])


In [33]:
tensor

tensor([[16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])

In [34]:
import torch
from torchviz import make_dot


A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)



result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
dot
# 不知道为啥只支持画svg，png的不支持，还在找解决方法
dot.render('expression', format='svg', cleanup=True, view=False)

'expression.svg'