In [3]:
#什么是numpy，就是python中的一个数学工具库，用于处理各类数学问题
import numpy as np
a = [1,2,3]
b = np.array(a)
#nyumpy的数组，可以理解为python（js）中的列表，但是比列表更灵活,需要将列表转化为numpy的数组，被numpy包一层，才能使用numpy的各类方法
c= np.array([1,2,3],float) #float表示数据类型，默认为int
c
#创建多维数组,类似矩阵
d = np.array([[1,2,3],[4,5,6]])
d

#创建指定类型的数组
#创建二维数组，类型为int,2可以理解为2行，3可以理解为3列，zeros表示元素的值都是0，ones表示元素的值都是1
e = np.zeros((2,3),dtype=int)
e
# 创建等差数列，从1开始，到10结束，步长为2
f = np.arange(1,10,2)
f
#创建单位矩阵
g = np.eye(4)
g

#创建随机数组,[0,1)之间的5个随机数
i = np.random.random(5)
# print(i)
#创建随机矩阵
h = np.random.rand(4,4)
h

#创建正态分布的数组，均值为1，标准差为0.5，一共5位
j = np.random.normal(1,0.5,5)
j

#数组的访问，切割
a = np.array([(1,2,3),(5,8,10),(6,9,12)])
# print(a)
a[0]#数组第一项 等同s方法
a[:,:2]#矩阵第一列,:表示从第0列开始，一直截取到第2列 （要从矩阵的维度看截取结果）

#数组遍历（循环），普通的一维数组可使用for循环，多维时for循环有多个参数
# a = np.array([(2,2,6),(2,3,7),(4,5,8)])
# for i,j,k in a:
    # print("i是"+str(i))#和js写法不一样，要声明i的类型
    # print(j)
    # print(k)
    
#数组的常见属性
a = np.array([(1,2,3),(4,5,6)])
# print(a)
a.ndim#维度,也就是秩 2（什么是秩，就是矩阵的每一行的非零元素都在该行的主对角线上，且后续行的非零元素都位于前一行的非0元素之下，非0行下的数量就是矩阵的秩）
a.shape#形状，就是行数和列数，比如上面二维数组，就是(2,3)
a.size#元素个数，就是上面的6
a.dtype#数据类型，就是上面的int32

#数组的基本操作
a = np.array([(1,2,3),(4,5,6)])
#检测是元素（这里的元素指的是矩阵中的所有数字）否在数组中,返回是布尔值
# print(6 in a)

a= np.zeros([2,3,4,5])#可以理解为最外层是2个数组，每个数组有3个数组。。。以此类推
a
# a.reshape(2,3,20)#重新定义数组的维度，但是元素个数必须一致，否则会报错

#转置（行变列，列变行）a.T  a.transpose()
a = np.array([(1,2,3),(4,5,6)])
a.T

#多维变一维
a = np.array([(1,2,3),(4,5,9)])
a.flatten()

#增加维度
a = np.array([(1,2,3),(4,5,9)])
a.shape #(2,3)
a = a[:,np.newaxis]
a.shape #(2,1,3)




(2, 1, 3)

In [ ]:
#数组之间的运算
a = np.array([(1,2),(4,5)])
b = np.array([(6,7),(8,9)])

a+b 
# array([[ 7,  9],
    #    [12, 14]])
    
a-b
# array([[-5, -5],
#        [-4, -4]])

a*b
# array([[ 6, 14],
#        [32, 45]])

a/b
# array([[ 0.16666667,  0.28571429],
#        [ 0.25     ,  0.28571429]])

a = np.array([2,3])
a.sum()
a.prod()#求积6
a.mean()#平均值2.5
a.var()#方差0.25
a.std()#标准差0.5
a.max()#最大值3
a.min()#最小值2
a.argmax()#最大值对应的索引位置1,等同js数组的索引
a.argmin()#最小值对应的索引位置0

a = np.array([1.1,2.2,3.3])
np.ceil(a)#向上取整  array([2., 3., 4.])
np.floor(a)#向下取整  array([1., 2., 3.])
np.rint(a)#四舍五入  array([1., 2., 3.])

#排序
a = np.array([9,2,3,4,5])
a.sort() #array([2, 3, 4, 5, 9])
#倒序排列
b= np.sort(a)[::-1]
b


array([9, 5, 4, 3, 2])

In [ ]:
#numpy在线性代数中的应用
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A,B))#矩阵乘法
print(A @ B)#矩阵乘法

[[19 22]
 [43 50]]
-2.0000000000000004
[[19 22]
 [43 50]]


In [94]:
#文件读写操作
a = np.array([1,2,3,4,5])
np.save('test.npy',a) #保存为二进制文件
np.savetxt('test.txt',a)

b = "你好\n,世界"
with open('test.txt','w') as f: #保存为文本文件
    f.write(b)
    
#读取
a = np.load('test.npy')
a
with open('test.txt','r') as f: #读取文本文件
    b = f.read()
    print(b)

你好
,世界


In [4]:
#广播机制，如果数组的shape不同，那么就会进行广播机制,会将数组进行扩展，使得两个数组的shape相同
#要求数组的维度必须相同
a = np.array([1,2,3]) #shape = (3,)
print(a.shape)
b = np.array([(1,2,3),(4,5,6)]) #shape = (2,3)
a + b



(3,)


array([[2, 4, 6],
       [5, 7, 9]])