In [ ]:

import torch
import numpy as np
# print(torch.__version__)
# pytorch 基础
# 张量的概念：可以理解为pytorch的一个容器，存储在张量中后，可以使用pytorch中的各种方法

a = torch.tensor([[1,2,3],[4,5,6]])
# tensor([[1, 2, 3],
#         [4, 5, 6]])
# 和numpy的数组一样

b = torch.from_numpy(np.array([[1,2,3],[4,5,6]]))  #将numpy的数组转化为tensor
# tensor([[1, 2, 3],
#         [4, 5, 6]], dtype=torch.int32)

#创建张量----start
a = torch.tensor([[1,2,3],[4,5,6]])
c = torch.ones_like(a) #复制一个和a维度相同的张量

c = torch.rand_like(a,dtype=torch.float)
# tensor([[0.3169, 0.8875, 0.1362],
#         [0.6102, 0.6056, 0.3477]])

#使用元组描述张量的形状 shape(2,3),两行三列的数组张量
shape = (2,3)
a = torch.rand(shape)
# tensor([[0.2119, 0.2783, 0.9457],
#         [0.2253, 0.2563, 0.5904]])

a = torch.ones(shape)
# tensor([[1., 1., 1.],
#         [1., 1., 1.]])

a = torch.zeros(shape)
# tensor([[0., 0., 0.],
#         [0., 0., 0.]])

#根据现有的张量，使用新值填充
a = torch.ones(5,3) 
# tensor([[1., 1., 1.],
#         [1., 1., 1.],
#         [1., 1., 1.],
#         [1., 1., 1.],
#         [1., 1., 1.]])
b = torch.rand_like(a,dtype=torch.float)
# tensor([[0.4586, 0.4012, 0.0854],
#         [0.0264, 0.5998, 0.6201],
#         [0.2773, 0.7187, 0.4918],
#         [0.8486, 0.3453, 0.0867],
#         [0.2213, 0.5754, 0.6798]])

#均匀分布
a = torch.rand(2,2)
# tensor([[0.8327, 0.5940],
#         [0.8428, 0.5488]])
#正态分布
a = torch.randn(2,2)
# tensor([[-0.7394, -1.0774],
#         [ 0.8092, -0.1784]])

#张量的属性： shape维度 dtype数据类型 device设备
print(f"a.shape:{a.shape},a.dtype:{a.dtype},a.device:{a.device}")
#a.shape:torch.Size([2, 2]),
# a.dtype:torch.float32,
# a.device:cpu

#张量的索引和切片
a = torch.rand(2,3)
# print(a)
# print(a[1,2]) #取第二行第三列的值
# tensor([[0.2167, 0.4578, 0.0491],
#         [0.4738, 0.8109, 0.5083]])
# tensor(0.5083)

# print(a[:,1]) #取第二列的值(:表示所有行,1表示第二列)

#张量的拼接,dim表示的是拼接的维度,dim的值不能超过维度的值（类似于js的cat方法）
a = torch.rand(2,2,1)
b = torch.rand(2,2,1)
c = torch.cat((a,b),dim=0)
# print(a)
# print(b)
# tensor([[0.6781, 0.5850],
#         [0.4806, 0.7051]])
# tensor([[0.5098, 0.8435],
#         [0.3154, 0.9998]])
# tensor([[0.6781, 0.5850],
#         [0.4806, 0.7051],
#         [0.5098, 0.8435],
#         [0.3154, 0.9998]])

c = torch.cat((a,b),dim=1)
# tensor([[0.1699, 0.0819],
#         [0.3661, 0.7415]])
# tensor([[0.6392, 0.8773],
#         [0.1647, 0.3192]])
# tensor([[0.1699, 0.0819, 0.6392, 0.8773],
#         [0.3661, 0.7415, 0.1647, 0.3192]])

c = torch.cat((a,b),dim=2)
# tensor([[[0.5121],
#          [0.9650]],

#         [[0.1660],
#          [0.8392]]])
# tensor([[[0.8425],
#          [0.8639]],

#         [[0.7704],
#          [0.1845]]])
# tensor([[[0.5121, 0.8425],
#          [0.9650, 0.8639]],

#         [[0.1660, 0.7704],
#          [0.8392, 0.1845]]])

#张量之间的计算
x = torch.ones(2,2)
y = torch.ones(2,2)
print(x)
print(y)
res1 = x @ y.T #矩阵乘法
res3 = torch.matmul(x,y.T) #矩阵乘法

res4 = torch.mul(x,y) #元素级别的乘法
res2 = x * y #元素级别的乘法

#单元素张量，可以使用 .item() 方法将张量转换为 Python 的标量。
tensor = torch.tensor([1,2,3])
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))  #6 <class 'int'>

#in-place操作,就地操作，会导致数据在某个节点丢失，不推荐使用
tensor = torch.ones(2,2)
# print(tensor)
# tensor([[1., 1.],
#         [1., 1.]])
tensor.add_(5)
# print(tensor)
# tensor([[6., 6.],
#         [6., 6.]])

#numpy和tensor的转换，共享一个内存，一个改变另一个也会改变（等同js中object的概念）
m = np.ones(5) 
n = torch.from_numpy(m)

n.add_(1)
# print(m)
# print(n)
# [2. 2. 2. 2. 2.]
# tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [1]:
#计算图，用于展示深度学习中所有的计算路径，逐行执行代码

import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\23924\AppData\Local\Temp\ipykernel_11916\4139203267.py:14: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression.png'