In [3]:
import numpy as np
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [4]:
c=np.zeros((5,5),dtype=float)
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
d=np.ones((4,4) ,dtype=int)
print(d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [6]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [7]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
a=np.random.random(3)
a

array([0.59846876, 0.19108314, 0.45589236])

In [9]:
mu,sigma=5,1
np.random.normal(mu,sigma,5)

array([5.45347212, 4.89284612, 5.03213252, 5.07019533, 6.10061372])

In [10]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a[0]

array([1, 2, 3])

In [12]:
a[1]

array([4, 5, 6])

In [13]:
a[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [15]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [16]:
a[2,2]

9

In [17]:
a=np.array([1,2,3,4,5])
for i in a:
    print(i)

1
2
3
4
5


In [18]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
for i,j,k in a:
    print(i+j+k)

6
15
24


In [19]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print("ndim:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)
print("dtype:",a.dtype)

ndim: 2
shape: (3, 3)
size: 9
dtype: int32


In [20]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(4 in a)
print(100 in a)

True
False


In [21]:
a=np.zeros([5,6])
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
a.reshape(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [24]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [27]:
a=a[:,np.newaxis]
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [28]:
a.shape

(5, 1)

In [29]:
a=np.ones((3,3))
b=np.array([[1,1,1],[2,2,2],[3,3,3]])
a+b


array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [30]:
a-b

array([[ 0.,  0.,  0.],
       [-1., -1., -1.],
       [-2., -2., -2.]])

In [31]:
a*b

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [32]:
a.dot(b)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [33]:
a@b


array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [34]:
a.sum()

9.0

In [35]:
a.prod()

1.0

In [36]:
a = np.array([1,2,3])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())
print("max:", a.max())
print("min:", a.min())

mean: 2.0
var: 0.6666666666666666
std: 0.816496580927726
max: 3
min: 1


In [37]:
a = np.array([3.4, 2.8, 9.77])
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("rint:", np.rint(a))

argmax: 2
argmin: 1
ceil: [ 4.  3. 10.]
floor: [3. 2. 9.]
rint: [ 3.  3. 10.]


In [38]:
a=np.array([1,3,444,2,333,22222,888,9,32321])
a.sort()
a

array([    1,     2,     3,     9,   333,   444,   888, 22222, 32321])

In [39]:
a = np.array([2,2,3,111])
b = np.array([9,1,2,3])
a + b

array([ 11,   3,   5, 114])

In [40]:
a=np.array([1,1])
b=np.array([[1,1],[2,2],[3,3],[4,4]])
a+b

array([[2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [41]:
import torch
import numpy as np
data=[[1,1],[2,2],[3,3],[4,4]]
x_data=torch.tensor(data)
x_data

C:\Users\wsm\AppData\Local\Temp\ipykernel_35052\771880421.py:4: UserWarning: Failed to initialize NumPy: DLL load failed while importing _multiarray_umath: 找不到指定的模块。 (Triggered internally at C:\b\abs_fakvb73nko\croot\pytorch-select_1730848725921\work\torch\csrc\utils\tensor_numpy.cpp:84.)
  x_data=torch.tensor(data)


tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [42]:
np_array = np.array(data)
np_array


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [43]:
# x_np = torch.from_numpy(np_array)
# x_np 

In [44]:
x_ones = torch.ones_like(x_data) # 保留of x_data的属性
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # 覆盖 x_data的数据类型
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6854, 0.6028],
        [0.9005, 0.1886],
        [0.7643, 0.0735],
        [0.8635, 0.0824]]) 



In [45]:
shape = (1,4,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5105, 0.8671, 0.7591, 0.9016]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.]])


In [46]:
# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(4,2, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)
# 获取tensor的⼤⼩
print(m.size()) # torch.Size([5,3])
print(m)
print(n)
# 均匀分布
torch.rand(5,3)
# 标准正态分布
torch.randn(5,3)
# 离散正态分布
torch.normal(mean=.0,std=1.0,size=(5,3))
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
torch.linspace(start=1,end=10,steps=20)

torch.Size([4, 2])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[0.4798, 0.5606],
        [0.1495, 0.8157],
        [0.7399, 0.5628],
        [0.5965, 0.9454]])


tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [47]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [48]:
torch.cuda.is_available()

False

In [49]:
tensor = torch.ones(5, 5)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1., 1.])
tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]])


In [50]:
t1 = torch.cat([tensor, 2*tensor, tensor,3*tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 2., 0., 2., 2., 2., 1., 0., 1., 1., 1., 3., 0., 3.,
         3., 3.],
        [1., 0., 1., 1., 1., 2., 0., 2., 2., 2., 1., 0., 1., 1., 1., 3., 0., 3.,
         3., 3.],
        [1., 0., 1., 1., 1., 2., 0., 2., 2., 2., 1., 0., 1., 1., 1., 3., 0., 3.,
         3., 3.],
        [1., 0., 1., 1., 1., 2., 0., 2., 2., 2., 1., 0., 1., 1., 1., 3., 0., 3.,
         3., 3.],
        [1., 0., 1., 1., 1., 2., 0., 2., 2., 2., 1., 0., 1., 1., 1., 3., 0., 3.,
         3., 3.]])


In [51]:
# 计算两个张量之间矩阵乘法的⼏种⽅式。 y1, y2, y3 最后的值是⼀样的 dot
tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(tensor)
print(y3)   
torch.matmul(tensor, tensor.T, out=y3)
print(y3)   
# 计算张量逐元素相乘的⼏种⽅法。 z1, z2, z3 最后的值是⼀样的。
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z3)   

tensor([[14., 32.],
        [32., 77.]])
tensor([[14., 32.],
        [32., 77.]])
tensor([[0.8171, 0.0539, 0.5328],
        [0.9701, 0.2367, 0.2753]])
tensor([[14., 32.],
        [32., 77.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


C:\Users\wsm\AppData\Local\Temp\ipykernel_35052\2125470676.py:9: UserWarning: An output with one or more elements was resized since it had shape [2, 3], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\b\abs_fakvb73nko\croot\pytorch-select_1730848725921\work\aten\src\ATen\native\Resize.cpp:35.)
  torch.matmul(tensor, tensor.T, out=y3)


In [52]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(21.)
21.0 <class 'float'>


In [53]:
print(tensor)
tensor.add_(10)
print(tensor)


tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[11., 12., 13.],
        [14., 15., 16.]])


In [54]:
# t = torch.ones(5)
# print(f"t: {t}")
# n = t.numpy()
# print(f"n: {n}")

In [55]:
# n = np.ones(5)
# t = torch.from_numpy(n)

In [56]:
import torch
from torchviz import make_dot
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\wsm\AppData\Local\Temp\ipykernel_35052\1108873558.py:9: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\b\abs_fakvb73nko\croot\pytorch-select_1730848725921\work\aten\src\ATen\native\TensorShape.cpp:3679.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression.png'