### Numpy

In [1]:
import numpy as np

In [8]:
# 1、创建数组
a = [1,2,3,4,5,6]
b = np.array(a)
c = np.array([1,2,3],np.float32)
print(f'b:{b}')
print(f'c:{c}')

b:[1 2 3 4 5 6]
c:[1. 2. 3.]


In [18]:
#创建多维数组必须使用[]方括号括起来,最外层
a = np.array([[1,2,3],[3,2,1]])
print(f'a:{a}')
b=np.array([(1,2,3),(3,2,1)])
print(f'b:{b}')
b.dtype

a:[[1 2 3]
 [3 2 1]]
b:[[1 2 3]
 [3 2 1]]


dtype('int32')

In [20]:
a = np.zeros((2,3),dtype = np.float32)
a

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [21]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a = np.arange(0,10,2) #最后一位小于10的等差数列
a

array([0, 2, 4, 6, 8])

In [25]:
#独-热编码，单位矩阵，也就是主对角线元素为 1(从左上角到右下角)
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
#生成在[0,1)左闭右开的平均分布的随机数组
a = np.random.random(5)
a

array([0.30923372, 0.30664765, 0.69533629, 0.86095467, 0.32596294])

In [29]:
# 均值为0，标准差为0.1 的正态分布随机数组
mu, std = 0, 0.1
a = np.random.normal(mu,std,5)
a

array([ 0.22828978,  0.10862551, -0.09901926,  0.15521773,  0.10166598])

In [35]:
#数组的访问
a = np.arange(0,9).reshape(3,3)
a = np.array(a)
print(a)
print(a[1])
print(a[:,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]
[1 4 7]


In [37]:
# 数组遍历
for i in a:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [39]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(3, 3)
9
int32


In [40]:
a = np.array([(2,1),(1,2)])
print(3 in a)
print(1 in a)

False
True


In [50]:
#将3维数组转成一维数组 ，reshape可以改变数组维度，如果只拉成一维度还可以用flatten
a = np.zeros([2,2,3])
# a = a.reshape(-1)
b = a.flatten()
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
#转置 .T == transpose
a = np.array([[1,2],[3,4]])
print(a)
print(a.T)
print(np.transpose(a))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [53]:
#增加维度 newaxis
a = np.array([1,2,3])
print(a.shape)
b = a[:,np.newaxis]
b.shape

(3,)


(3, 1)

In [59]:
#numpy 数学操作
a = np.ones((2,2))
b = np.array([(-1,1),(1,-1)])
print(a)
print(b)
print(a+b)
print(a-b)
print(a * b)
print(a / b)
print(a.sum())
print(a.prod()) #乘积
print(a.mean()) # 平均
print(a.var()) #方差
print(a.std()) #标准差 
print(f'max:{a.max()},min:{a.min()}')

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [ 1 -1]]
[[0. 2.]
 [2. 0.]]
[[2. 0.]
 [0. 2.]]
[[-1.  1.]
 [ 1. -1.]]
[[-1.  1.]
 [ 1. -1.]]
4.0
1.0
1.0
0.0
0.0
max:1.0,min:1.0


In [65]:
a = np.array([1.1,2.8,3.9])
print(f'最大索引：{np.argmax(a)}，最小索引：{np.argmin(a)}') #索引位置下标
print(f'向上取整：{np.ceil(a)},向下取整：{np.floor(a)}，四舍五入{np.rint(a)}')

最大索引：2，最小索引：0
向上取整：[2. 3. 4.],向下取整：[1. 2. 3.]，四舍五入[1. 3. 4.]


In [75]:
#排序操作
a = np.arange(10)
print(a)
print(sorted(a,reverse = True)) #python方法
print(a[::-1]) #切片，[start:stop:step] -1表示倒着取，前面两个省略
print(np.flip(a))

[0 1 2 3 4 5 6 7 8 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


In [76]:
a = np.array([-1,2,3])
print(np.abs(a))

[1 2 3]


In [81]:
#numpy 线性代数 矩阵乘法 dot == @
m1 = np.array([[1,2],[3,4]],dtype=np.float32)
m2 = np.array([[5,6],[7,8]],dtype=np.int16)
m3 = np.dot(m1,m2)
print(f'{m3}、{m3.dtype}')
m4 = m1 @ m2
print(f'{m4}、{m4.dtype}')

[[19. 22.]
 [43. 50.]]、float32
[[19. 22.]
 [43. 50.]]、float32


In [84]:
a = np.array([1,2,3])
np.savetxt('w01file.txt',a)
b = np.loadtxt('w01file.txt')
b

array([1., 2., 3.])

In [86]:
#numpy 广播机制是将自动低纬度转换为高纬度,不同形状运算时自动的,numpy的广播机制允许较小的数组在某些维度上自动扩展，以匹配较大数组的形状。
a = np.array([[1,2],[3,4]])
b = np.array([0,1])
print(a+b)

[[1 3]
 [3 5]]


### pytroch
#### Tensor

In [5]:
import torch
import numpy as np

In [16]:
#直接将list将张量复制过去
data = [(3,4),(1,2)]
x_data = torch.tensor(data)
x_data

tensor([[3, 4],
        [1, 2]])

In [13]:
#也可以通过下面函数直接将ndarray转到tensor中
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[3, 4],
        [1, 2]], dtype=torch.int32)

In [18]:
#除非明确覆盖，否则新张量会保留原参数张量的属性(形状、数据类型)
print(x_data.dtype)
x_ones = torch.ones_like(x_data)
print(x_ones)
print(x_ones.dtype)

torch.int64
tensor([[1, 1],
        [1, 1]])
torch.int64


In [23]:
x_rand = torch.rand_like(x_data,dtype=torch.float)  #显性覆盖数据的类型
print(x_rand)
print(x_rand.dtype)

tensor([[0.6682, 0.5392],
        [0.9839, 0.4410]])
torch.float32


In [25]:
#使用随机值或常量值
#shape是张量维度的 元组，定义张量的维度
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [26]:
print(f'rand_tensor:{rand_tensor}')
print(f'ones_tensor:{ones_tensor}')
print(f'zeros_tensor:{zeros_tensor}')

rand_tensor:tensor([[0.2159, 0.3228, 0.2255],
        [0.8520, 0.1426, 0.0299]])
ones_tensor:tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor:tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [31]:
#其他创建tensor方法
#1、基于现有tensor构建，用其他值填充
m = torch.ones(2,3,dtype=torch.double)
n = torch.rand_like(m,dtype = torch.float) #显性覆盖
print(m)
print(n)
print(f'tensor size:{n.size()}')
print(f'n dtype:{n.dtype}')
n.itemsize

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.9393, 0.2197, 0.3774],
        [0.8613, 0.4851, 0.5660]])
tensor size:torch.Size([2, 3])
n dtype:torch.float32


4

In [34]:
#还有一些创建方式
#1、均匀分布
n = torch.rand(3,3)
print(n)
#2、标准正态分布：
n = torch.randn(3,3)
print(n)
#3、离散正态分布：
n = torch.normal(mean=0,std=1.0,size=(3,3)) 
print(n)
#4、线性间隔向量  在【start，end，steps】 
m = torch.linspace(0,10,20)
print(m)

tensor([[0.7900, 0.8216, 0.2864],
        [0.4356, 0.2832, 0.7208],
        [0.1996, 0.3182, 0.5262]])
tensor([[-0.6064, -0.1542, -0.7684],
        [ 0.1952, -0.8798,  1.8673],
        [ 2.7691, -1.8670,  0.8467]])
tensor([[-0.1256,  0.3606, -0.1536],
        [-0.6904, -0.7967, -0.4320],
        [ 0.5472,  0.4532, -2.0684]])
tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])


In [36]:
#张量的常用属性 shape dtype device
print(m.shape,m.dtype)
print(m.device)

torch.Size([20]) torch.float32
cpu


In [38]:
device = torch.device('cuda:0' if torch.cuda.is_available else 'cpu')
device

device(type='cuda', index=0)

In [48]:
#张量索引、切片
tensor = torch.ones(3,3)
print(tensor[0])#第一行
print(tensor[:,1]) #行不变，查看下标1列
print(tensor[...,-1])#前面维度不管，查看最后一列
tensor[:,1]=0 #修改第一列的值
print(tensor)

tensor([1., 1., 1.])
tensor([1., 1., 1.])
tensor([1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


In [51]:
#张亮拼接cat 、stack具有类似功能
t= torch.cat([tensor,tensor,tensor],dim = 1) #下标第1维度拼接，因为是二维的就是列
t

tensor([[1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.]])

In [55]:
t= torch.stack([tensor,tensor,tensor],dim = 1) #下标第1维度拼接，因为是二维的就是列
t

tensor([[[1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.]],

        [[1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.]],

        [[1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.]]])

In [58]:
#张量计算也可以用dot和@
y1 = tensor @ tensor.T #乘积
y2 = tensor * tensor  #y2 == y3
y3 = tensor.mul(tensor)
print(y2)
print(y3)

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


In [60]:
#单元素张量操作，张量的值聚合计算 可以使用item()方法转换为Python数值
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item,type(agg_item))

tensor(6.)
6.0 <class 'float'>


In [62]:
#in-place操作，会直接修改变量本身的值(勿用) 如x.copy_(y),x.t_(),x自身值直接改变,数据丢失
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
tensor([[6., 5., 6.],
        [6., 5., 6.],
        [6., 5., 6.]])


In [64]:
#与numpy之间的转换：CPU和Numpy数组上的张量共享底层内存位置，一个改变另一个也会改变
t = torch.ones(5)
print(t)
n=t.numpy()
print(n)
#numpy 数组到张量
n = torch.from_numpy(n) #不管修改numpy上的还是CPU上的tensor都会改变另一个值
print(n) 

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


In [78]:
#计算图
from torchviz import make_dot
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)

result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# 生成计算图节点
dot = make_dot(result, params={'A':A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

In [70]:
%pip install torchviz