
标量、向量、矩阵 和 张量 分别具有零、一、二和任意数量的轴。
1. 张量 tensor
2. 矩阵 matrix 
3. 向量 vector
4. 标量 scalar


In [4]:
import torch
import numpy as np
# 什么是张量 tensor?
# 张量是一个多维数组, 张量的维度是张量的阶数, 张量的形状是张量的维度的长度

np_array = np.array([[1,2],[3,4]])
print("\nnumpy array: ",np_array) 
print("\nnumpy array 的形状: ",np_array.shape)
# 把numpy array 转换成 tensor
data = torch.from_numpy(np_array)
print("\n把numpy array 转换成 tensor: ",data) 
print("\n把numpy array 转换成 tensor 的形状: ",data.shape)

# 创建二阶张量, 数据类型为float32
data = torch.tensor([[1,2,3],[3,4,5]], dtype=torch.float32)
print("\n创建二阶张量: ",data)


numpy array:  [[1 2]
 [3 4]]

numpy array 的形状:  (2, 2)

把numpy array 转换成 tensor:  tensor([[1, 2],
        [3, 4]])

把numpy array 转换成 tensor 的形状:  torch.Size([2, 2])

创建二阶张量:  tensor([[1., 2., 3.],
        [3., 4., 5.]])


In [5]:
# rand_like 函数: 创建一个与给定张量形状相同的张量，其元素是随机生成的。
#
# 语法: torch.rand_like(input, dtype=None)
# 参数:
# input: 输入张量。
# dtype: 数据类型。


# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
print("\ntorch.rand_like: ", data3)


torch.rand_like:  tensor([[0.2538, 0.6233, 0.2574],
        [0.8358, 0.7575, 0.3916]])


In [6]:
shape = (2,3,) # 元组类型

rand_tensor = torch.rand(shape) # 随机初始化
ones_tensor = torch.ones(shape) # 全 1 初始化
zeros_tensor = torch.zeros(shape) # 全 0 初始化

print(f"随机初始化 torch.rand: \n {rand_tensor} \n")
print(f"全 1 初始化 torch.ones: \n {ones_tensor} \n")
print(f"全 0 初始化 torch.zeros: \n {zeros_tensor} \n")

print(f"rand_tensor.shape: {rand_tensor.shape}")
print(f"rand_tensor.dtype: {rand_tensor.dtype}")
print(f"rand_tensor.device: {rand_tensor.device}")

随机初始化 torch.rand: 
 tensor([[0.3699, 0.8394, 0.7078],
        [0.9751, 0.1148, 0.4316]]) 

全 1 初始化 torch.ones: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

全 0 初始化 torch.zeros: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

rand_tensor.shape: torch.Size([2, 3])
rand_tensor.dtype: torch.float32
rand_tensor.device: cpu


In [7]:
import torch

# rand 函数:
# 函数原型: torch.rand(*sizes) → Tensor
# 功能: 返回一个张量，包含了从区间[0, 1)的 均匀分布 中抽取一组随机数。张量的形状由参数sizes定义。
print(f'\ntorch.rand(2,3):\n {torch.rand(2,3)}')

# randn 函数:
# 函数原型: torch.randn(*sizes) → Tensor
# 功能: 返回一个张量，包含了从标准正态分布（均值为0，方差为1，即高斯白噪声）中抽取一组随机数。张量的形状由参数sizes定义。
print(f'\ntorch.randn(2,3):\n {torch.randn(2,3)}')

# normal 函数:
# 函数原型: torch.normal(mean, std, size) → Tensor
# 功能: 返回一个张量，包含了从给定参数mean,std的离散正态分布中抽取一组随机数。mean,std形状不要求一致。
# mean=.0 的意思是: 均值为0
# std=1.0 的意思是: 标准差为1
# size=(2,3) 的意思是: 张量的形状为2行3列
print(f'\ntorch.normal(mean=0.0,std=1.0,size=(2,3)):\n {torch.normal(mean=0.0,std=1.0,size=(2,3))}')  

# linspace 函数:
# 函数原型: torch.linspace(start, end, steps) → Tensor
# 功能: 返回一个1维张量，包含在区间start和end上均匀间隔的steps个点。输出张量的长度由steps决定。 
print(f'\ntorch.linspace(0,10,steps=4):\n {torch.linspace(0,10,steps=4)}')


torch.rand(2,3):
 tensor([[0.9473, 0.1332, 0.7462],
        [0.4419, 0.0996, 0.4389]])

torch.randn(2,3):
 tensor([[-0.6224, -0.4634, -0.0183],
        [ 1.2603, -0.0949, -1.1625]])

torch.normal(mean=0.0,std=1.0,size=(2,3)):
 tensor([[-1.3863, -1.1715,  1.2062],
        [-0.2880, -0.7726,  1.5295]])

torch.linspace(0,10,steps=4):
 tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


In [8]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
# 使用下标 tensor[i, j] 来访问单个元素。
print(tensor[0, 0], tensor[1,1])

# 使用 : 来进行切片，获取行或列。
# ... 表示“省略其他维度”
print('第一行: ', tensor[0]) 
print('第一行: ', tensor[0, :])

print('第一列: ', tensor[..., 0])
print('第一列: ', tensor[:, 0]) 

print('最后一列:', tensor[:, -1])
print('最后一列:', tensor[..., -1])

# 切片: 前两行，前三列
sub_tensor = tensor[:2, :3]
print(sub_tensor)

# 创建一个 3D 数组，形状为 (4, 3, 2)
arr = torch.rand(4, 3, 2)  
print(arr.shape)
# 使用 ... 来获取 arr 的第二行
print('arr[1] 结果: ', arr[1])  
# arr[1, ...] 就相当于 arr[1, :, :]
print('arr[1, ...] 结果: ', arr[1, ...]) 
print('arr[1, :, :] 结果: ', arr[1, :, :])

tensor(1) tensor(5)
第一行:  tensor([1, 2, 3])
第一行:  tensor([1, 2, 3])
第一列:  tensor([ 1,  4,  7, 10])
第一列:  tensor([ 1,  4,  7, 10])
最后一列: tensor([ 3,  6,  9, 12])
最后一列: tensor([ 3,  6,  9, 12])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([4, 3, 2])
arr[1] 结果:  tensor([[0.8736, 0.5376],
        [0.9717, 0.6956],
        [0.7228, 0.4483]])
arr[1, ...] 结果:  tensor([[0.8736, 0.5376],
        [0.9717, 0.6956],
        [0.7228, 0.4483]])
arr[1, :, :] 结果:  tensor([[0.8736, 0.5376],
        [0.9717, 0.6956],
        [0.7228, 0.4483]])


In [9]:
# cat 函数:
# 功能：将多个张量连接起来
tensor = torch.rand(2,3)
t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim=0 按行连接，dim=1 按列连接
print(t1)
print(t1.shape)

tensor([[0.0482, 0.1962, 0.8828, 0.0482, 0.1962, 0.8828, 0.0482, 0.1962, 0.8828],
        [0.8042, 0.9774, 0.7429, 0.8042, 0.9774, 0.7429, 0.8042, 0.9774, 0.7429]])
torch.Size([2, 9])


In [10]:
import torch
# arange 函数
# 生成一个从 start 到 end 的张量，步长为 step。
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)
print(f"tensor: \n {tensor}")
print(f'tensor.T:\n {tensor.T}') # 转置

# 矩阵乘法的两种方法。 y1, y2 结果是一样的。
y1 = tensor @ tensor.T # @ 运算符: 矩阵乘法
y2 = tensor.matmul(tensor.T) # matmul 函数: 矩阵乘法

# y3 结果也是一样
y3 = torch.zeros_like(tensor)
# out 是输出张量给 y3, 用out可以节省内存。
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)


tensor: 
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor.T:
 tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])


In [11]:
tensor = torch.tensor([[0, 1, 2], [3, 4, 5]], dtype=torch.float32)
# 逐个元素相乘 也叫 Hadamard积
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)
print(z2)


z3 = torch.zeros_like(tensor)
torch.mul(tensor, tensor, out=z3)


print(z3)

agg = tensor.sum() # 求和

agg_item = agg.item() # 转换成python的数字类型, 只有一个元素的tensor可以转换成python的数字类型
print(agg_item, type(agg_item))

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])
15.0 <class 'float'>


In [12]:
tensor = torch.ones(4, 4)
print(tensor, "\n")
# 原地更新: 减少内存使用
tensor.add_(2) 
print(tensor)

# 非原地更新
tensor = tensor + 2
print(tensor)

# 原地更新
tensor += 2
print(tensor)

# [:] 的作用: 对 tensor 中的元素进行修改, 原地更新
tensor[:] = tensor + 2
print(tensor)



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])
tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])
tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]])


In [13]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10, requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10, requires_grad=True)
c = torch.randn(1, requires_grad=True)
x = torch.randn(10, requires_grad=True)

# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.dot(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

/var/folders/88/fy3s8rzx7cdfb19k40rx8_zc0000gn/T/ipykernel_22568/286211319.py:11: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3729.)
  result = torch.matmul(A, x.T) + torch.dot(b, x) + c


'expression.png'