In [1]:
import numpy as np

创建ndarray数组
1.np.array(数组，dtype=数组类型)
2.list转换


In [2]:
# 创建ndarray数组
import numpy as np
arr1 = np.array([1,2,3,4,5], float)
arr2 = [4,5,6]
arr2 = np.array(arr2)
print(arr2, type(arr2))

[4 5 6] <class 'numpy.ndarray'>


二维数组，括号内为行

In [ ]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

全0数组，全1数组

In [6]:
a1 = np.zeros((2,3), dtype=np.float32)
a2 = np.ones((4,5), dtype=int)
print(a1)
a2

[[0. 0. 0.]
 [0. 0. 0.]]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

arange:生成制定长度数组 参数：首项，末项，步长
# 数组生成左闭右开，不包含末项
# 步长为负：首项 < 末项

In [11]:
a2 = np.arange(1,6, 0.3)
a3 = np.arange(1,6,-0.3)
a4 = np.arange(6,1,-0.3)
print("a2: ", a2)
print("a3: ", a3)
print("a4: ", a4)

a2:  [1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9 5.2 5.5 5.8]
a3:  []
a4:  [6.  5.7 5.4 5.1 4.8 4.5 4.2 3.9 3.6 3.3 3.  2.7 2.4 2.1 1.8 1.5 1.2]


one hot编码：将抽象的数据张量转换成神经网络可接受的形式
# 例：RGB = np.eye(3)

In [12]:
a3 = np.eye(4)
a3  # one-hot编码

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

随机设置【0，1）间的参数
random:随机分布
normal:正态分布
binomial:二项分布

In [17]:
a4 = np.random.random(10)  # 模型运算参数初始值
a4

array([0.76333519, 0.49213642, 0.86058971, 0.43400458, 0.04935594,
       0.12344001, 0.46146072, 0.42201422, 0.42345174, 0.51311822])

In [20]:
a5 = np.random.normal(0, 0.1, 5)  # 模型运算参数初始值
print(a5)
a6 = np.random.binomial(10, 0.5, size=5)
print(a6)

[-0.0723492  -0.02208821  0.15312087 -0.14942344  0.00191361]
[6 3 7 6 3]


数组切片

In [ ]:
a6 = np.array([(1,2), (3,4), (5,6)])
# print(a6) 获取第一列
print(a6[:,1])
a6 = np.array([(4,1), (5,1), (6,1), (7,1)])
# 除第一行以外的所有元素
print(a6[1:])

[2 4 6]
[[5 1]
 [6 1]
 [7 1]]


数组打印
nditer：遍历数组所有元素

In [27]:
a7 = np.array([(1,2), (3,4), (5,6)])
# i,j = a7[0]
for i,j in a7:
    print(i,j)

for x in np.nditer(a7):
    print(x, end=" ")

1 2
3 4
5 6
1 2 3 4 5 6 

ndim	维度数，即数组的轴数（几维数组）	2（二维数组）
shape	数组的形状（各轴上的元素数量）	(3, 3)（3行3列）
size	数组中的元素总数	9（3×3=9）
dtype	数组元素的数据类型
nbytes  数组占用子节数

In [33]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)
print(a.nbytes) 

ndim: 2
shape: (3, 3)
size 9
dtype int64
72


判断数字是否在数组里

In [32]:
print(3 in a)
print(239587234986720345 in a)

True
False


reshape：重置矩阵维度

In [39]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,3,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

a7 = np.arange(0,8)
print(a7)
print(a7.shape)

a7 = a7.reshape(2,2,2)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)


[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)
[0 1 2 3 4 5 6 7]
(8,)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2)


矩阵转置：沿对角线方向转换
三维数组会交换其轴（维度）的顺序。默认情况下，使用 .T 只会交换最后两个轴（行和列），如果想要自定义顺序，需要使用 np.transpose()。

In [42]:
a = a7.T
print(a)

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


用于将多维NumPy数组展平（变成一维数组），即按元素顺序将矩阵拉直。

In [43]:
a = a.flatten()
print(a)

[0 4 2 6 1 5 3 7]


增加维度

In [46]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,:,np.newaxis]  # [3,1,2]
print(a8.shape)

a = np.array([1,2,3])
a.shape
a = a[ :, np.newaxis]
a

(3, 2, 1)


array([[1],
       [2],
       [3]])

In [52]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)
#求和
a.sum()
#求积
a.prod()
#矩阵相乘
print(a*b)
#矩阵相除
print(a/b)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]
[[-1.  1.]
 [-1.  1.]]
[[-1.  1.]
 [-1.  1.]]


In [ ]:
# 数组，矩阵、维度

# 数组、矩阵  ： 数据组织结构形式

# 维度： 通讯地址

mean:均值
var：方差
std：标准差
max:最大值
min:最小值

In [53]:
a = np.array([5,3,5])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())
print("max:", a.max())
print("min:", a.min())

mean: 4.333333333333333
var: 0.888888888888889
std: 0.9428090415820634
max: 5
min: 3


注：python四舍五入是取最近的偶数而不是严格四舍五入，为避免运算中全部四舍五入之后差值太大

In [ ]:
a = np.array([1.02, 3.8, 459.5])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入
a = np.array([16,31,12,28,22,31,48])
a.sort(axis=0)
print(a) # 按维度排序，1维数组不能超过1

argmax: 2
argmin: 0
ceil: [  2.   4. 460.]
floor: [  1.   3. 459.]
rint: [  1.   4. 460.]
[12 16 22 28 31 31 48]


In [70]:
m1 = np.array(([1, 2], [3, 4]), dtype=np.float32)
m2 = np.array(([5, 6], [7, 8]), dtype=np.float32)

result_dot = np.dot(m1, m2)

result_at = m1 @ m2
print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print(result_dot)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
[[19. 22.]
 [43. 50.]]


@ 运算符（矩阵乘法）
matmul() 方法
mul() 方法（逐元素相乘）

In [ ]:
import torch
tensor = torch.arange(5,9, dtype=torch.float32).reshape(2, 2)

print(tensor)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y1)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[5., 6.],
        [7., 8.]])
tensor([[ 61.,  83.],
        [ 83., 113.]])


tensor([[25., 36.],
        [49., 64.]])

In [ ]:
m1 = np.array([[4, 2], [3, 4]], dtype=int)
m2 = np.array([[5, 6], [6, 1]], dtype=int)

print("m1: \n", m1)
print("m2: \n", m2)
result_dot = np.dot(m1, m2)
result_at = m1 @ m2
print(result_dot)
print(result_at)

manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=int)


for i in range(m1.shape[0]):

    for j in range(m2.shape[1]):
        manual_result[i, j] = 0

        for k in range(m1.shape[1]):
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            manual_result[i, j] += m1[i, k] * m2[k, j]

print(manual_result)

m1: 
 [[4 2]
 [3 4]]
m2: 
 [[5 6]
 [6 1]]
[[32 26]
 [39 22]]
[[32 26]
 [39 22]]
4 * 5 = 20
2 * 6 = 12
4 * 6 = 24
2 * 1 = 2
3 * 5 = 15
4 * 6 = 24
3 * 6 = 18
4 * 1 = 4
[[32 26]
 [39 22]]


In [71]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [77]:
np.save('result.npy',manual_result)

In [78]:
result_np = np.load('result.npy')
result_np

array([[32, 26],
       [39, 22]])

广播机制（Broadcasting是NumPy处理不同形状数组运算的一种方式。允许NumPy自动扩展较小的数组，使其与较大的数组兼容，以便执行逐元素运算而不会真正复制数据，提高了计算效率。

In [80]:
a = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
b = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])

2. 广播规则

NumPy 从后向前 逐维比较数组的 shape，并根据以下规则进行 扩展：
	1.	维度相同，直接计算。
	2.	某个维度为 1，可以沿该维度扩展，使其与另一个数组形状匹配。
	3.	维度不相同且不为 1，则无法广播，会报错。

In [81]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2,3)
b = np.array([[10, 20]])              # shape (1,2)

print(a + b)

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 