张量：运算的数据
直接从数据创建
numpy数据转换

In [13]:
import torch
import numpy as np

data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
data_list = [[1, 2],[3, 4]]
x_data = torch.tensor(data_list)
np_array = np.array(data_list)
data2 = torch.from_numpy(np_array)
print(x_data)
print(data2)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


# 通过已知张量维度，创建新张量
# 若不指定类型和其他参数会保留原有数据的参数

In [ ]:
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.8637, 0.4410],
        [0.8152, 0.5091]])

In [16]:
shape = (2,3,2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.0859, 0.2889],
         [0.0730, 0.2180],
         [0.6112, 0.7144]],

        [[0.6928, 0.6590],
         [0.5607, 0.6399],
         [0.6981, 0.0459]]]) 

Ones Tensor: 
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


In [22]:


# 均匀分布
print(torch.rand(3,3))
# 标准正态分布
print(torch.randn(3,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(3,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=33))
# 二项分布
n = 10  # 试验次数
p = 0.5  # 成功概率
print(torch.distributions.Binomial(total_count=n, probs=p).sample((5,3)))

tensor([[0.0810, 0.4683, 0.4497],
        [0.7775, 0.8305, 0.9239],
        [0.6519, 0.8945, 0.5876]])
tensor([[-0.8348, -1.3803,  1.0398],
        [ 0.0965, -0.7770, -1.5152],
        [ 0.4665,  0.0518, -1.8303]])
tensor([[-1.4107,  1.5149,  1.4070],
        [ 0.7769,  0.9783,  0.1827],
        [-0.0038, -0.8180, -0.3337]])
tensor([ 1.0000,  1.2812,  1.5625,  1.8438,  2.1250,  2.4062,  2.6875,  2.9688,
         3.2500,  3.5312,  3.8125,  4.0938,  4.3750,  4.6562,  4.9375,  5.2188,
         5.5000,  5.7812,  6.0625,  6.3438,  6.6250,  6.9062,  7.1875,  7.4688,
         7.7500,  8.0312,  8.3125,  8.5938,  8.8750,  9.1562,  9.4375,  9.7188,
        10.0000])
tensor([[5., 6., 8.],
        [4., 4., 3.],
        [7., 4., 3.],
        [1., 6., 3.],
        [4., 6., 2.]])


In [ ]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([5, 3])
tensor([[6.3174e-01, 1.2625e-01, 4.2581e-01],
        [6.8463e-01, 3.4225e-01, 1.6435e-01],
        [2.2296e-01, 4.8706e-01, 7.9733e-01],
        [3.1114e-04, 3.0108e-01, 4.2377e-01],
        [4.4821e-01, 1.3078e-01, 2.0527e-01]])
tensor([[ 1.4362,  0.5236,  1.3130],
        [ 0.3669, -0.2108, -1.0469],
        [-1.4308, -0.3567,  0.5221],
        [-1.1639, -0.7706,  0.6081],
        [-0.3173,  0.0666, -0.5036]])
tensor([[-0.9276,  0.2195,  2.2426],
        [ 0.3561, -0.2410, -0.6539],
        [ 0.8776,  1.2666, -1.0316],
        [ 0.6072, -0.3642,  0.5667],
        [-0.8244, -0.5023, -0.1325]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])
tensor([[3., 0., 0.],
        [0., 3., 4.],
        [3., 2., 2.],
        [3., 0., 1.],
        [3., 2., 1.]])


shape：维度
dtype：类型
device：存储位置

In [37]:
tensor = torch.rand(2,2,2)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


默认情况，张量在cpu上创建，但可以切换到gpu(.to())

In [ ]:

if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

if torch.backends.mps.is_available():
    print("yes")
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.0986, 0.3187, 0.6553, 0.3893],
        [0.6511, 0.0113, 0.3531, 0.5864],
        [0.7492, 0.1733, 0.7749, 0.5443]], device='mps:0')
mps:0
yes
tensor([[0.0986, 0.3187, 0.6553, 0.3893],
        [0.6511, 0.0113, 0.3531, 0.5864],
        [0.7492, 0.1733, 0.7749, 0.5443]], device='mps:0')
mps:0


In [ ]:
tensor = torch.ones(3, 3, 3)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)
# 切片遵循左闭右开原则

First row:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
First column:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Last column: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1., 1.],
         [0., 0., 0.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [0., 0., 0.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [0., 0., 0.],
         [1., 1., 1.]]])


	torch.cat() 用于拼接多个张量
	dim=1 表示在列方向拼接，所以原来的 3x3 变成 3x(3+3+3) = 3x9

In [40]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[[3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.],
         [3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.],
         [3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.],
         [3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.],
         [3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.],
         [3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.],
         [3., 3., 3.],
         [0., 0., 0.],
         [3., 3., 3.]]])
torch.Size([3, 9, 3])


In [41]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


如果一个单元素张量，例如将张量的值聚合计算，可以使用 item()方法将其转换为数值

In [32]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

45.0 <class 'float'>


类型转换 tensor -》 numpy

In [42]:
np_arr = z1.numpy()
print(type(np_arr))

<class 'numpy.ndarray'>


In [34]:
print(tensor, "\n")
tensor.add_(5)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


torch 用于创建张量和计算梯度。
torchviz.make_dot 用于生成计算图
requires_grad=True 使变量成为可求导张量，以便进行梯度计算。


计算公式：
	•	torch.matmul(A, x.T) 计算矩阵 A 和向量 x 的乘积，得到一个 10 维向量。
	•	torch.matmul(b, x) 计算向量 b 和 x 的点积，得到一个标量。
	•	c 是一个标量，加到最终结果。
绘制图片：
	•	dot.render('expression', format='png', cleanup=True, view=False) 作用：
	•	‘expression’：输出文件的名称（即 expression.png）。
	•	format='png'：生成 PNG 图片。
	•	cleanup=True：清理临时文件。
	•	view=False：不自动打开图片（可改为 True 直接查看）

In [44]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

'expression.png'