In [5]:
import numpy as np

In [3]:
a = np.array([1,2,3],float)
print(a)


[1. 2. 3.]


In [31]:
a = [(1,2,3)]
b = np.array(a)
b

array([[1, 2, 3]])

In [40]:
# 创建多维数组
a = np.array([(1,2,3),(4,6,5),(7,8,9)], dtype = float)
a


array([[1., 2., 3.],
       [4., 6., 5.],
       [7., 8., 9.]])

In [13]:
# 创建全是1的数组（4,5）（四行五列）
a = np.zeros((2,3))
a


array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# 创建全是1的数zu（4,5）（四行五列）
a= np.ones((4,5))
a


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
#创建等差数列，从1 开始，5结束，等差数列为0.5
a = np.arange(1,5,0.6)
a


array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6])

In [35]:
#创建单位矩阵
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# ⽣成指定⻓度，在(0,1)之间平均分布的随机数组：
np.random.random(5)


array([0.49741061, 0.01441961, 0.55064346, 0.05954128, 0.12244554])

In [39]:
# ⽣成指定⻓度，符合正态分布的随机数组，指定其均值为0，标准差为0.1
mu,sigma = 0,0.1
np.random.normal(mu,sigma,5)


array([ 0.04006598, -0.09268486, -0.20311973, -0.19166551,  0.10603129])

In [51]:
# numPy数组的访问
# 和list 的访问形式基本⼀致，⽀持切⽚操作，
a = np.array([(1,2),(3,4),(5,6)])
a[:]#输出的是每行
a[:,:1]#前面是切片，后面是输出每列第一个
a[1][1]


np.int64(4)

In [52]:
# numpy的遍历：
a = np.array([1,2,3])
for i in a:
    print(i)


1
2
3


In [53]:
# 多维数组的遍历？
a = np.array([(1,2),(3,4),(5,6)])
for i,j in a:
    print(i*j)
#每列之间相乘

2
12
30


In [55]:
#numpy数组的常用属性
# 比较常用的属性有：
# ndarray.ndim：数组的维度（数组轴的个数）等于秩
# ndarray.shape:数组的大小。为一个表示数组在每个维度上大小的整数元组例如⼆维
# 数组中，表⽰数组的ʼʼ⾏数ʼʼ和ʼʼ 列数ˮ 
# ndarray.size：数组元素的总个数，等于shape属性中元素的乘积
# ndarray.dtype:表示数组中元素类型的对象

a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a.ndim)#二维
print(a.shape)#三行三列
print(a.size)#9个元素
print(a.dtype)


2
(3, 3)
9
int64


In [57]:
# NumPy数组的基本操作
a = np.array([(1,2),(3,4)])
print(3 in a)
print(6 in a)


True
False


In [59]:
#reshape函数，数组的重排列，例如将一个三维数组转为1维（元素个数一定要保持不变）
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a
a.reshape(9)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
#tanspose:转置（可以直接.T）
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a.T  #第一行变成第一列，第二行变成第二列，第三行变成第三列


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [61]:
#flatten：把多维数组转换成一维数组，注意每个长度是相等的
a = np.array([(1,2),(3,4),(5,6)])
a.flatten()


array([1, 2, 3, 4, 5, 6])

In [65]:
#newaxis:增加维度
a = np.array([1,2,3])
a.shape
a = a[:,np.newaxis]
a
#a.T#可还原


array([[1],
       [2],
       [3]])

In [72]:
# numpy数组的数学操作
# 加减乘除
# 星乘表示矩阵内各对应位置相乘，点乘表示求矩阵内积，二维数组和岗位矩阵积（mastrix product）
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
a + b
a - b
a * b#（a1*b1 a2*b2）
a / b


[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]


array([[-1.,  1.],
       [-1.,  1.]])

In [78]:
#求和，求积
a = np.array([1,2,1])
# a.sum()
# a.prod()#内积（1*2*1）
#平均数，⽅差，标准差，最⼤值，最⼩值
print(a.mean())#平均数
print(a.var())#⽅差
print(a.std())#标准差
print(a.max())
print(a.min())


1.3333333333333333
0.2222222222222222
0.4714045207910317
2
1


In [82]:
#最⼤与最⼩值对应的索引值：argmax,argmin:
#取元素值上限，下限，四舍五⼊：ceil, floor, rint
a = np.array([1.2,3.8,4.9])
print(a.argmax())#返回下标
print(a.argmin())#返回下标
print(np.ceil(a))#向上取整
print(np.floor(a))#向下取整
print(np.rint(a))#四舍五入


2
0
[2. 4. 5.]
[1. 3. 4.]
[1. 4. 5.]
4.9


In [85]:
#排序：sort
a = np.array([12,14,10,1.6,8.9])
a.sort()
a

array([ 1.6,  8.9, 10. , 12. , 14. ])

In [88]:
#NumPy线性代数
# 有关线性代数的运算均在numpy.linalg 中
# 矩阵(matrix) 是array的分⽀matrix 和 array 在很多时候都是通⽤的，
# ⽤哪⼀个都⼀样。官⽅建议⼤家如果两个可以通⽤，那就选择array，因为array 更灵活，速度更快。
# array 的优势就是不仅仅表⽰⼆维，还能表⽰3、4、5... 维，⽽且在⼤部分Python 程序⾥，array 也是更常⽤的。

#dot:矩阵乘法：
# 对于两个⼀维的数组，计算的是这两个数组对应下标元素的乘积和 (数学上称之为内积)；
# 对于⼆维数组，计算的是两个数组的矩阵乘积；
# 对于多维数组，它的通⽤计算公式如下，即结果数组中的每个元素都是：
# 数组a 的最后⼀维上的所有元素与数组b 的倒数第⼆位上的所有元素的乘积和：
#dot(a,b)[i,j,k,m] = sum(a[i,j,:])*b[k,:,m]

m1 = np.array([[1,2],[3,4]],dtype = np.float32)
m2 = np.array([[5,6],[7,8]],dtype = np.float32)
result_dot = np.dot(m1,m2)
print(result_dot)
result_at = m1 @ m2
print(result_at)
# #矩阵乘法：
# 1 2
# 3 4

# 5 6
# 7 8
# a1 = 1*5+2*7
# a2 = 2*6+2*8
# b3 = 3*5+3*7
# b4 = 4*6+4*8

#其它函数
# eig：特征值，特征向量
# inv：逆
# qr：QR分解
# svd：奇异值分解
# aolve：解线性方程Ax=b
# istsq：计算Ax=b的最小二乘解


[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [89]:
#文件操作：
# 二进制文件：np.save、np.load
# 文本文件：np.loadtxt、np.savetxt
# 二进制文件会存储为.npy的格式

In [96]:
# Numpy广播机制：
# ⼴播(Broadcast) 是numpy 对不同形状(shape) 的数组进⾏数值计算的⽅式，
# 对数组的算术运算通常在相应的元素上进⾏。如果两个数组a 和b 形状相同，
# 即满⾜a.shape == b.shape，那么a*b 的结果就是a与b 数组对应位相乘。
# 这要求维数相同，且各维度的⻓度相同。

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
a * b * c


array([ 28,  80, 162])

In [92]:
a = np.array([(1,2),(2,2),(3,3),(4,4)])  # shape(4,2)
b = np.array([-1,1])
a * b


array([[-1,  2],
       [-2,  2],
       [-3,  3],
       [-4,  4]])