In [5]:
# 张量（Tensor）：
# 张量（Tensor）是pytorch中的基本单位，也是深度学习框架构成的重要组成。
# 我们可以先把张量看做是⼀个容器，⾥⾯承载了需要运算的数据。
import numpy as np
import torch


In [6]:
# 张量可以直接从数据中创建。数据类型是⾃动推断的。
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)


tensor([[1, 2],
        [3, 4]])


In [7]:
#从NumPy数组,张量可以从NumPy数组创建
data = [[1,2],[3,4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)



In [15]:
#从另⼀个张量：除非明确覆盖，否则新张量保留参数张量的属性（形状，数据类型）
x_ones = torch.ones_like(x_data)#创建一个像x_datade张量
print(x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)#覆盖x_data的数据类型
print(x_rand)#生成一个像x_data的张量，随机生成0-1的浮点数


tensor([[1, 1],
        [1, 1]])
tensor([[0.9467, 0.2822],
        [0.2803, 0.0779]])


In [18]:
#使用随机值或者常量
#shape 是张量维度的元组。在下⾯的函数中，它决定了输出张量的维度。
shape = (2,3)#2行3列
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)


tensor([[0.0859, 0.1515, 0.1170],
        [0.9136, 0.1658, 0.0716]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
#其它⼀些创建⽅法
# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(5,3,dtype=torch.double)
n = torch.rand_like(m,dtype=torch.float)
print(m,n)
print(m.size())

#均匀分布（二维）
torch.rand(5,3)#（0-1之间随机采样）
#标准正态分布
torch.randn(5,3)#每个元素都是从标准正态分布（均值为 0，标准差为 1 的正态分布）中随机采样，
# 离散正态分布
torch.normal(mean=.0,std=1.0,size=(5,3))#生成0-1之间的随机数，
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
torch.linspace(start=1,end=10,steps=20)#在1-10之间均匀的生成20个数


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) tensor([[0.5262, 0.5300, 0.6766],
        [0.0137, 0.5506, 0.4628],
        [0.6640, 0.8951, 0.5696],
        [0.2458, 0.9017, 0.3241],
        [0.5237, 0.4176, 0.3019]])
torch.Size([5, 3])


tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [61]:
# 张量的属性：
# 张量的属性描述了张量的形状、数据类型和存储它们的设备。
# 以对象的⻆度来判断，张量可以看做是具有特征和⽅法的对象。
tensor = torch.rand(3,4)
print(tensor.dtype)
print(tensor.shape)
print(tensor.device)#在哪运行


torch.float32
torch.Size([3, 4])
cpu


In [9]:
# 张量运算：
# 默认情况下，张量是在 CPU 上创建的。我们可以使⽤使⽤.to() ⽅法明确地将张量移动到 GPU (GPU可⽤的情况下)。
#设置张量在GPU上运算
# if torch.cuda.is_available():
#     tensor = tensor.to'cuda')
    

In [69]:
#张量的索引和切⽚：
tensor = torch.ones(4,4)
# print(tensor[0])
# print(tensor[0:3])
# tensor[:,0]#取弟0列所有元素
# tensor[...,-1]#取第负一列的所有数据（取出所有列表中最后一个特征）
tensor[:,1] = 0 #取出所有列表中第一个特征（第一列）赋值为0
print(tensor)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [63]:
# 张量的拼接
# 可以使⽤ torch.cat ⽤来连接指定维度的⼀系列张量。
# 另⼀个和 torch.cat 功能类似的函数是torch.stack
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [64]:
# 算数运算：计算两个张量之间矩阵乘法的集中方式y1, y2, y3 最后的值是⼀样的 dot
y1 = tensor @ tensor.T#协方差矩阵可以通过 X @ X.T 来计算（其中 X 是数据矩阵）
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)
#以上三种方法都一样，（钟意第一种）
print(y3)
# 计算张量逐元素相乘的⼏种⽅法。 z1, z2, z3 最后的值是⼀样的。
z1 = tensor * tensor#每个元素和自己相乘
print(f'z1的值是',{z1})

z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)



tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1的值是 {tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])}


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [65]:
# 单元素张量:如果⼀个单元素张量，例如将张量的值聚合计算，可以使⽤ item() ⽅法将其转换为Python 数值
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))


12.0 <class 'float'>


In [70]:
#in-place操作：把计算结果存储到当前操作数中的操作就称为就地操作。
#含义和pandas中inPlace参数的含义⼀样
#pytorch中，这些操作是由带有下划线 _ 后缀的函数表⽰。
#例如：x.copy_(y) ,  x.t_() , 将改变 x ⾃⾝的值。

print(tensor,'\n')
# tensor.add_(5)
# print(tensor)

# In-place操作虽然节省了⼀部分内存，但在计算导数时可能会出现问题，因为它会⽴即丢失历史记录。
# 因此，不⿎励使⽤它们。

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [71]:
#与numpy之间的转换
# CPU 和 NumPy 数组上的张量共享底层内存位置，所以改变⼀个另⼀个也会变。

In [73]:
#张量到numpy数组
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [75]:
# 张量值的变更也反映在关联的NumPy 数组中
t.add_(1)
print(t)
print(n)


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [78]:
#Numpy数组到张量
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [79]:
#NumPy 数组的变化也反映在张量中。
np.add(n,1,out=n)
print(t)


tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
