In [1]:
# numpy基础数组创建
import numpy as np
a = [1,2,3]
print(a)
b = np.array(a)
print(b)
a1 = np.array([1,2,3])
print(a1)

[1, 2, 3]
[1 2 3]
[1 2 3]


In [5]:
# 多维数组的创建
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#Numpy 特殊数组创建
a1 = np.zeros([2,3])
a1 
a2 = np.zeros([2,3],dtype = float)
a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
a1 = np.ones([6,6])
a1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
a = np.arange(1,5,0.5)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [13]:
a = np.eye(2)
print(a)
a1 = np.eye(3)
print(a1)
a2 = np.eye(4)
print(a2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [1]:
import numpy as np
np.random.random(5)

array([0.12689644, 0.44627751, 0.86396062, 0.26944623, 0.2521725 ])

In [2]:
mu,sigma = 0,0.1
np.random.normal(mu,sigma,5)

array([-0.09810413,  0.05622152, -0.14504504, -0.07464451, -0.13733059])

In [15]:
#numpy数组访问
a = np.array([[1,2],[3,4],[5,6]])
a[1][1]

np.int64(4)

In [16]:
#数组的遍历
a = np.array([1,2,3])
for i in a:
    print(i)

1
2
3


In [17]:
a = np.array([[1,2],[3,4],[5,6]])
for i,j in a:
    print(i*j)

2
12
30


In [19]:
#numpy的常用属性
a = np.array([[1,2],[3,4],[5,6]])
print("ndim:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)
print("dtype",a.dtype)

ndim: 2
shape: (3, 2)
size: 6
dtype int64


In [24]:
#numpy 数组的基本操作
a = np.array([[1,2],[3,4]])
print(3 in a)
print(0 in a)

True
False


In [ ]:
a = np.zeros([2,3,4])
b = a
print(b)
b1 = a.reshape(24)
print(b1)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b1 = a
print(b1)
b2 = a.transpose()
print(b2)
b3 = a.T
print(b3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [31]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
b1 = a.flatten()
print(b1)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [36]:
a = np.array([1,2,3])
print(a)
b = a.shape
print(b)

[1 2 3]
(3,)


In [41]:
a = np.array([1,2,3])
print(a)
a = a[:,newaxis]
a

[1 2 3]


NameError: name 'newaxis' is not defined

In [ ]:
#numpy数组的数学操作
a = np.ones((2,2),type(int))
b = np.array([[-1,1],[-1,1]],type(int))
print(a)
print(b)
c = a+b
print(c)

[[1 1]
 [1 1]]
[[-1 1]
 [-1 1]]
[[0 2]
 [0 2]]


In [49]:
a = np.array([1,2,2])
b1 = a.sum()
print(b1)
b2 = a.prod()
print(b2)

5
4


In [50]:
a = np.array([5,3,1])
print("mean:",a.mean())
print("var:",a.var())
print("std",a.std())
print("max",a.max())
print("min:",a.min())

mean: 3.0
var: 2.6666666666666665
std 1.632993161855452
max 5
min: 1


In [52]:
a = np.array([1.2,3.8,4.9])
print("argmax:",a.argmax())
print("argmin:",a.argmin())
print("ceil:",np.ceil(a))
print("floor:",np.floor(a))
print("rint:",np.rint(a))

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [55]:
a = np.array([16,31,12,28,22,31,48])
a.sort
a

array([16, 31, 12, 28, 22, 31, 48])

In [56]:
#numpy 广播机制
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [57]:
a = np.array([[1,2],[2,2],[3,3],[4,4]])
b = np.array([-1,1])
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])