In [ ]:
#直接从数据
import torch
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [13]:
#从numpy数组
import numpy as np
np_array = np.array([1,2])
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[1 2]
tensor([1, 2])


In [15]:
x_ones = torch.ones_like(x_data)
print("Ones Tensor:\n {x_ones} \n")
x_rand = torch.rand_like(x_data,dtype = torch.float)
print(f"Random Tensor:\n {x_rand} \n")

Ones Tensor:
 {x_ones} 

Random Tensor:
 tensor([[0.6275, 0.9388],
        [0.8184, 0.9562]]) 



In [24]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor:\n {rand_tensor} \n")
print(f"Ones Tensor:\n {ones_tensor} \n")
print(f"Zeros Tensor:\n {zeros_tensor} \n")

Random Tensor:
 tensor([[0.6596, 0.5374, 0.6829],
        [0.4719, 0.5662, 0.7561]]) 

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [4]:
# 基于现有tensor构建，但使用新值填充
import torch
m = torch.ones(5,3, dtype = torch.double)
n = torch.rand_like(m, dtype = torch.float)
#获取tensor大小
print("tensor大小:",m.size())
#均匀正态分布
print("均匀分布:",torch.rand(5,3))
#标准正态分布
print("标准正态分布:",torch.randn(5,3))
#离散正态分布
print("离散正态分布:",torch.normal(mean = .0, std = 1.0, size = (5,3)))
#线性间隔向量（返回1个1维张量，包含在区间start和end上均匀间隔的steps个点）
print("线性间隔向量:", torch.linspace(start = 1, end = 10, steps = 2))

tensor大小: torch.Size([5, 3])
均匀分布: tensor([[0.7256, 0.4797, 0.3477],
        [0.0225, 0.4847, 0.4486],
        [0.4196, 0.2427, 0.5288],
        [0.7488, 0.0816, 0.8895],
        [0.3221, 0.5823, 0.1590]])
标准正态分布: tensor([[ 1.1043, -0.6216,  0.0381],
        [-0.1079,  1.9860,  0.7866],
        [ 1.5295, -1.7750,  0.9918],
        [ 2.8878, -0.6834,  1.4195],
        [ 1.2079, -0.5800, -0.2673]])
离散正态分布: tensor([[ 1.1144,  1.0319, -1.2978],
        [ 0.0374, -0.9366, -0.8577],
        [-0.1560,  0.6148,  2.0899],
        [-0.5353,  1.2735, -0.5444],
        [-2.2436, -0.4417, -0.5683]])
线性间隔向量: tensor([ 1., 10.])


In [5]:
#Tensor属性
tensor = torch.rand(3,4)
print(f"shape of tensor:{tensor.shape}")
print(f"datetype of tensor:{tensor.dtype}")
print(f"device tensor is stored on:{tensor.device}")

shape of tensor:torch.Size([3, 4])
datetype of tensor:torch.float32
device tensor is stored on:cpu


In [6]:
#Tensor的索引和切片
tensor = torch.ones(4,4)
print("first row:",tensor[0])
print("first column:",tensor[:,0])
print("last column:",tensor[...,-1])
tensor[:,1] = 0
print(tensor)

first row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [7]:
#tensor的拼接
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [9]:
tensor = torch.arange(1,10,dtype=torch.float32).reshape(3,3)
print(tensor)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])


In [10]:
#单元素张量
tensor = torch.arange(2,10)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))

44 <class 'int'>


In [12]:
# in place
tensor = torch.arange(1,6)
print("tensor值:",tensor)
print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor值: tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5]) 

tensor([ 6,  7,  8,  9, 10])
