# Numpy part

In [2]:
import numpy as np

In [3]:
# create narray
arr = np.array([2,3,4,5,6], float)
arr

array([2., 3., 4., 5., 6.])

In [4]:
a = np.array([(2,3,4), (5,6,7), (8,9,10)])
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
a1 = np.zeros((3,4), dtype=np.float32)
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [ ]:
a2 = np.arange(2,7, 1.5)
a2

array([2. , 3.5, 5. , 6.5])

In [11]:
a3 = np.eye(4)
a3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# random number
a4 = np.random.random(6) # [0,1]
print(a4)
a5 = np.random.normal(1, 1.2, 6) # mean=1, std=1.2 normal distribution
print(a5)

[0.48858791 0.37875103 0.0070976  0.26421533 0.61849031 0.78463181]
[ 0.91516242  0.31498549 -1.00909096  0.47308164  0.32549532  2.13120475]


In [19]:
# slice
a6 = np.array([(2,3), (4,5), (6,7)])
print(a6[1,:])

[4 5]


In [20]:
a7 = np.array([(2,3,4), (5,6,7), (8,9,10)])
print("ndim:", a7.ndim)
print("shape:", a7.shape)
print("size", a7.size)
print("dtype", a7.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int32


In [23]:
# reshape
a8 = a7.reshape(3,3,1)  # 维度大小乘积 == 元素个数
a8

array([[[ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10]]])

In [24]:
a9 = a8.flatten()
a9

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# 加一个维度
b = np.array([(2,3), (4,5), (6,7)])
print(b)
b = b[:,:,np.newaxis]
print("b.newaxis = \n",b)
print(b.shape)

[[2 3]
 [4 5]
 [6 7]]
b.newaxis = 
 [[[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]]
(3, 2, 1)


In [36]:
# 运算
print(b.sum())
print(b.prod())
m1 = np.array([[2, 3], [4, 5]], dtype=np.float32)
m2 = np.array([[6, 7], [8, 9]], dtype=np.float32)
print("m1*m2 = ", m1*m2)
print("m1@m2 = ", m1@m2)


7.300000000000001
10.8
m1*m2 =  [[12. 21.]
 [32. 45.]]
m1@m2 =  [[36. 41.]
 [64. 73.]]


In [ ]:
b = np.array([1.2,2.5,3.6])
print("mean:",b.mean())
print("var:", b.var())
print("std:", b.std())
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("rint:", np.rint(a))  # 四舍五入

mean: 2.4333333333333336
var: 0.9622222222222222
std: 0.9809292646374774
argmax: 8
argmin: 0
ceil: [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
floor: [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
rint: [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [ ]:
# 排序
a = np.array([17,32,13,29,23,32,49])
a.sort()
a

array([13, 17, 23, 29, 32, 32, 49])

In [37]:
# numpy存文件 读文件
np.save('a.npy', a)
load_a = np.load('a.npy')
load_a

array([13, 17, 23, 29, 32, 32, 49])

In [40]:
# 自对齐特性 broadcast
a = np.array([(2,3), (3,3), (4,4), (5,5)])  # shape(4,2)
b = np.array([-2,2])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-2,2],[-2,2],[-2,2],[-2,2]]
a + b

array([[0, 5],
       [1, 5],
       [2, 6],
       [3, 7]])

# pytorch

## Tensor

In [3]:
# tensor
import torch
data = torch.tensor([[3,4],[5,6]], dtype=torch.float32)  # 创建 PyTorch 张量
print(data)
np_array = np.array([[3,4],[5,6]])
data1 = torch.from_numpy(np_array)  # 创建 PyTorch 张量
print(data1)

tensor([[3., 4.],
        [5., 6.]])
tensor([[3, 4],
        [5, 6]], dtype=torch.int32)


In [4]:
# 通过已知张量维度，创建新张量
data2 = torch.rand_like(data1, dtype=torch.float)  # 创建 PyTorch 张量
data3 = torch.zeros_like(data2)
data3

tensor([[0., 0.],
        [0., 0.]])

In [5]:
shape = (4,5,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9647, 0.4927, 0.5925, 0.4146, 0.7792],
        [0.0955, 0.8000, 0.7223, 0.1609, 0.4407],
        [0.4969, 0.6626, 0.1960, 0.2981, 0.7286],
        [0.5702, 0.9408, 0.9007, 0.5933, 0.6320]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [6]:
# 获取tensor的大小
print(data3.size())
# 均匀分布
print(torch.rand(7,5))
# 标准正态分布
print(torch.randn(7,5))
# 离散正态分布
print(torch.normal(mean=.2,std=2.5,size=(7,5)))
# 线性间隔向量(返回一个3维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=3,end=12,steps=23))

torch.Size([2, 2])
tensor([[0.1828, 0.5127, 0.4884, 0.2342, 0.9813],
        [0.7232, 0.3636, 0.4135, 0.3200, 0.5750],
        [0.2175, 0.0799, 0.1562, 0.1157, 0.8324],
        [0.1140, 0.9643, 0.4149, 0.4868, 0.6632],
        [0.7681, 0.2698, 0.5973, 0.1255, 0.2898],
        [0.9669, 0.4391, 0.3267, 0.6780, 0.6982],
        [0.1094, 0.4757, 0.1360, 0.7573, 0.6924]])
tensor([[-0.8800,  0.5871, -1.6324, -0.2208,  0.0557],
        [ 0.2653, -0.5559,  0.2231,  1.0320, -0.2768],
        [ 0.8179, -0.1694,  1.4879, -1.9091, -0.2732],
        [-0.2534,  0.5466,  2.5303, -1.0794, -2.1106],
        [-1.0652,  0.2844, -0.9048, -0.2970, -0.5849],
        [ 1.2141,  0.6582,  0.2611, -0.1235,  0.9719],
        [ 0.7099, -0.2025,  0.5758, -0.8394,  0.4096]])
tensor([[ 3.3265,  1.8947,  1.0219,  1.5532,  2.5418],
        [-1.8440,  1.0710, -0.6345,  0.1897, -1.8819],
        [-5.2972, -0.3488, -0.4522, -0.7139,  0.7276],
        [ 2.4123,  0.4490,  5.0093,  0.0164, -3.3957],
        [ 2.9425,  1.009

In [7]:
tensor = torch.rand(5,6)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [10]:
# 转移到cuda
if torch.cuda.is_available():
    device = torch.device("cuda")  # 创建 PyTorch 张量
    tensor = tensor.to(device)
    print(tensor.device)

cuda:0


In [11]:
# Slice
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1]) # 偷懒写法
tensor[:,1] = 0 # 每行第二列
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
# 拼接，横向
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [13]:
# 算数运算
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

# 计算两个张量之间矩阵乘法的几种方式。 y1=y2=y3 卷积
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3) # 结果填充到y3
print(y1)
print(y3)
# 计算张量逐元素相乘的几种方法。 z1= z2=z3
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [14]:
# 张量求和
agg = tensor.sum()
agg_item = agg.item() # 转换为python 数值
print(agg_item, type(agg_item))

45.0 <class 'float'>


In [15]:
arr = z3.numpy()
arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [ ]:
# 更新原来tensor的值，效率更高
print(tensor, "\n")
tensor.add_(5)
# tensor = tensor + 5 == （tensor += 5）
print(tensor)

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]]) 

tensor([[11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])


In [19]:
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=True)

'expression.png'