In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5], float)
arr

array([1., 2., 3., 4., 5.])

In [9]:
a = [1,2,3]
b = np.array(a, float)
b

array([1., 2., 3.])

In [14]:
a1 = np.array([(1,2,3),(4,5,6)])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a2 = np.zeros((2,3), dtype=np.float16)
a2

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [19]:
a3 = np.ones((2,3), dtype=int)
a3

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
a4 = np.arange(1,5,1)
a4

array([1, 2, 3, 4])

In [23]:
a5 = np.eye(4)
a5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
a6 = np.random.random(5)
a6

array([0.44236226, 0.82561532, 0.50860927, 0.76665146, 0.94964781])

In [28]:
a7 = np.random.normal(0, 0.1, 5)
a7

array([ 0.13624653, -0.1544767 ,  0.00269389, -0.05509126, -0.02572655])

In [3]:
a8 = np.random.normal(0,0.1,5)
a8

array([-0.01805144, -0.0124912 , -0.01666683,  0.08661237,  0.136441  ])

In [5]:
a9 = np.array([(1,2),(3,4),(5,6)])
#print(a9)

print(a9[:,1])
print(a9[1,:])
#print(a8[1,:].dtype)


[2 4 6]
[3 4]


In [11]:
a10 = np.array([1,2,3,4])
for i in a10:
    print(i)

1
2
3
4


In [18]:
a11 = np.array([(1,2),(3,4),(5,6)])
# i,j = a11[0]
# print(i)
# print(j)
for i,j in a11:
    print(i,j)
    print(i*j)
    

1 2
2
3 4
12
5 6
30


In [29]:
a12 = np.array([(1,2,3), (4,5,6), (7,8,8)])
print(a11.ndim)
print(a12.shape)
print(a12.size)
print(a12.dtype)
if 9 in a12:
    print("true")
else:
    print("false")

print((1,2,3) in a12)

#print((1,2) in a12)

2
(3, 3)
9
int32
false
True


In [34]:
a12 = np.arange(1, 10)
print(a12.shape)
a12.reshape(3,3)
a12.reshape(3,3,1)

(9,)


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [43]:
a12 = np.arange(1, 10)
a12 = a12.reshape(3,3)

a12 = a12.T
a12.transpose()
a12.flatten()

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [48]:
a13 = np.array([(1,2),(24,25)])
a13 = a13[:,:,np.newaxis]
a13.shape

(2, 2, 1)

In [ ]:
a14 = np.ones((2,2))
a15 = np.array([(-1,2), (3,4)])
print(a14 + a15)
print(a15 - a14)

print(a15.prod())
print(a14 * a15)

print(a15.max())
print(a15.sort())

print(np.rint(a15))
print(a15.argmax())




[[0. 3.]
 [4. 5.]]
[[-2.  1.]
 [ 2.  3.]]
-24
[[-1.  2.]
 [ 3.  4.]]
4
None
[[-1.  2.]
 [ 3.  4.]]
3


In [16]:
a16 = np.array([1.2, -3.8, 4.9])
a16.sort()
a16
a16 = np.abs(a16)
a16

array([3.8, 1.2, 4.9])

In [21]:
np.save('result.npy', a16)

a17 = np.load('result.npy')
a17

array([3.8, 1.2, 4.9])

In [24]:
a18=np.array([[1,2],[3,4],[5,6],[7,8]])
a19 = np.array([-1,1])
a18 * a19

array([[-1,  2],
       [-3,  4],
       [-5,  6],
       [-7,  8]])