In [4]:
import torch
data = torch.tensor([[1,2],[3,4]])
data

tensor([[1, 2],
        [3, 4]])

In [3]:
import numpy as np
np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [25]:
data3 = torch.ones_like(data2)
data3

#data4 = torch.zeros_like(data3)
#data4
print(data3.dtype)
data5 = torch.rand_like(data3, dtype=torch.float)
data5

shape = (2,3)
data6 = torch.rand(shape)
print(data6)
torch.zeros(shape)
torch.ones(shape)




torch.int32
tensor([[0.9868, 0.8271, 0.1428],
        [0.9056, 0.8925, 0.6068]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [44]:
m = torch.ones(5,3, dtype=torch.double)
m
n = torch.rand_like(m)
n.shape
torch.rand(5,3)


tensor([[0.0048, 0.4103, 0.5198],
        [0.8055, 0.9578, 0.7996],
        [0.2903, 0.1072, 0.8283],
        [0.4392, 0.9939, 0.5507],
        [0.1781, 0.2478, 0.0422]])

In [5]:
tensor = torch.rand(3,4)
tensor.device
tensor.dtype

if torch.cuda.is_available():
    print(torch.cuda.is_available())
print(torch.cuda.is_available())

# device = torch.device("cuda")
# tensor = tensor.to(device)

False


In [61]:
tensor = torch.rand(5,3)
tensor[0]
tensor[0][1]
tensor[:,1]
tensor[...,2]

tensor[:,1] = 1
tensor

tensor([[0.4637, 1.0000, 0.9814],
        [0.1513, 1.0000, 0.9997],
        [0.5219, 1.0000, 0.5734],
        [0.1023, 1.0000, 0.1505],
        [0.9081, 1.0000, 0.9784]])

In [72]:

tensor = torch.cat([tensor,tensor], dim=1)
print(tensor)
tensor.shape

tensor([[0.9326, 0.2738, 0.7217, 0.9326, 0.2738, 0.7217, 0.9326, 0.2738, 0.7217,
         0.9326, 0.2738, 0.7217, 0.9326, 0.2738, 0.7217, 0.9326, 0.2738, 0.7217,
         0.9326, 0.2738, 0.7217, 0.9326, 0.2738, 0.7217],
        [0.1446, 0.4732, 0.5788, 0.1446, 0.4732, 0.5788, 0.1446, 0.4732, 0.5788,
         0.1446, 0.4732, 0.5788, 0.1446, 0.4732, 0.5788, 0.1446, 0.4732, 0.5788,
         0.1446, 0.4732, 0.5788, 0.1446, 0.4732, 0.5788],
        [0.0239, 0.7798, 0.7916, 0.0239, 0.7798, 0.7916, 0.0239, 0.7798, 0.7916,
         0.0239, 0.7798, 0.7916, 0.0239, 0.7798, 0.7916, 0.0239, 0.7798, 0.7916,
         0.0239, 0.7798, 0.7916, 0.0239, 0.7798, 0.7916],
        [0.6854, 0.2550, 0.0612, 0.6854, 0.2550, 0.0612, 0.6854, 0.2550, 0.0612,
         0.6854, 0.2550, 0.0612, 0.6854, 0.2550, 0.0612, 0.6854, 0.2550, 0.0612,
         0.6854, 0.2550, 0.0612, 0.6854, 0.2550, 0.0612],
        [0.5863, 0.2040, 0.5917, 0.5863, 0.2040, 0.5917, 0.5863, 0.2040, 0.5917,
         0.5863, 0.2040, 0.5917, 0.5863

torch.Size([5, 24])