In [6]:
#pytorch基础
#1.张量tensor  pytorch的基本单位 用于装数据的容器
import torch
data = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.int)
data
data.shape
print(data)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)


In [7]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
a 
a.shape
b=torch.from_numpy(a)
print(b)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)


In [28]:
#观察张量中元素的类型
b.dtype

torch.int32

In [31]:
#通过已知的张量维度，创建新的张量
torch.ones_like(b)
torch.zeros_like(b)
torch.rand_like(b,dtype=torch.float)

tensor([[0.6790, 0.8630],
        [0.1285, 0.5639],
        [0.3299, 0.6983]])

In [41]:
shape = (3,2,3)
tensor_a = torch.rand(shape)
tensor_b = torch.ones(shape)
tensor_c = torch.zeros(shape)
print(f'random tensor:\n {tensor_a}\n')
print(f'random tensor:\n {tensor_b}\n')
print(f'random tensor:\n {tensor_c}\n')

random tensor:
 tensor([[[0.7078, 0.9877, 0.3076],
         [0.4377, 0.4503, 0.3828]],

        [[0.0472, 0.9050, 0.5853],
         [0.3809, 0.4570, 0.2367]],

        [[0.9042, 0.9212, 0.8794],
         [0.9406, 0.1450, 0.5878]]])

random tensor:
 tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

random tensor:
 tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])



In [ ]:
# 基于现有tensor构建，但使⽤新值填充
a = torch.ones(3,3, dtype=torch.int)
b = torch.rand_like(a,dtype = torch.float)
print(a)
print()
print(b)
#张量的大小
print(b.size(),a.size())
#直接生成
#torch.rand(5,5)
#标准正态分布
#torch.randn(5,5)
#离散正态分布
#torch.normal(mean=.0,std=1.0,size=(3,3))
#线性间隔向量（返回一个1维张量，包含在区间start和end上均匀间隔的steps个点）
torch.linspace(start = 1 ,end = 10 ,steps = 21)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

tensor([[0.4670, 0.8335, 0.9887],
        [0.5118, 0.7614, 0.7576],
        [0.1094, 0.2368, 0.0787]])
torch.Size([3, 3]) torch.Size([3, 3])


tensor([  1.0000,   6.2105,  11.4211,  16.6316,  21.8421,  27.0526,  32.2632,
         37.4737,  42.6842,  47.8947,  53.1053,  58.3158,  63.5263,  68.7368,
         73.9474,  79.1579,  84.3684,  89.5789,  94.7895, 100.0000])

In [73]:
#张量的属性
tensor1 = torch.rand(5,5) 
print(tensor1)
print(f"shape {tensor1.shape}")
print(f"datatype {tensor1.dtype}")
print(f"device {tensor1.device}")

tensor([[0.4609, 0.6349, 0.6990, 0.5637, 0.6328],
        [0.9243, 0.0741, 0.1765, 0.0147, 0.8784],
        [0.0042, 0.0783, 0.0163, 0.1354, 0.0982],
        [0.9250, 0.6975, 0.7734, 0.0625, 0.0826],
        [0.1875, 0.1241, 0.2082, 0.1762, 0.6742]])
shape torch.Size([5, 5])
datatype torch.float32
device cpu


In [91]:
#检查是否支持Gpu
print(torch.cuda.is_available())
#device = torch.device("cuda")
#tensor = tensor.to(device)
#mac M系统芯片
if torch.backends.mps.is_available():
    print('yes')
else:  print('no')
print(tensor.device)


False
no
cpu


In [108]:
#张量的索引 和切片
tensor2 = torch.rand(4,5)
print(tensor2) 
print()
print(tensor2[0])
print()
print(tensor2[:,0])
print()
print(tensor2[:])
print()
print(tensor2[:,1])
print()
#取所有维最后一列
print(tensor2[...,-1])
print()
print(tensor2[:,-1])
#张量的赋值
tensor2 [: 1] = 10
print(tensor2)

tensor([[0.7580, 0.9786, 0.0543, 0.1356, 0.7746],
        [0.9519, 0.0214, 0.1047, 0.2476, 0.9307],
        [0.1590, 0.8282, 0.6923, 0.0543, 0.9360],
        [0.6664, 0.1380, 0.5304, 0.6336, 0.4258]])

tensor([0.7580, 0.9786, 0.0543, 0.1356, 0.7746])

tensor([0.7580, 0.9519, 0.1590, 0.6664])

tensor([[0.7580, 0.9786, 0.0543, 0.1356, 0.7746],
        [0.9519, 0.0214, 0.1047, 0.2476, 0.9307],
        [0.1590, 0.8282, 0.6923, 0.0543, 0.9360],
        [0.6664, 0.1380, 0.5304, 0.6336, 0.4258]])

tensor([0.9786, 0.0214, 0.8282, 0.1380])

tensor([0.7746, 0.9307, 0.9360, 0.4258])

tensor([0.7746, 0.9307, 0.9360, 0.4258])
tensor([[10.0000, 10.0000, 10.0000, 10.0000, 10.0000],
        [ 0.9519,  0.0214,  0.1047,  0.2476,  0.9307],
        [ 0.1590,  0.8282,  0.6923,  0.0543,  0.9360],
        [ 0.6664,  0.1380,  0.5304,  0.6336,  0.4258]])


In [20]:
#张量的拼接 cat(行相同进行列拼接) stack(列相同进行行拼接)
tensor1 = torch.rand(3,3)
tensor2 = torch.rand(3,4)
tensor3 = torch.rand(4,3)
print(tensor1)
print()
print(tensor2)
print()
print(tensor3)
print()
t1 = torch.cat([tensor1,tensor2],dim=1)
print(t1)
print()
t2 = torch.cat([tensor1,tensor3],dim=0)
print(t2)


tensor([[0.0334, 0.5193, 0.9772],
        [0.3785, 0.8462, 0.8689],
        [0.5581, 0.7680, 0.0452]])

tensor([[0.4178, 0.0221, 0.3290, 0.0211],
        [0.8410, 0.7758, 0.9910, 0.8778],
        [0.0300, 0.5317, 0.7893, 0.3292]])

tensor([[0.8115, 0.5481, 0.8446],
        [0.7672, 0.9756, 0.7471],
        [0.5871, 0.6963, 0.9692],
        [0.1949, 0.1939, 0.2087]])

tensor([[0.0334, 0.5193, 0.9772, 0.4178, 0.0221, 0.3290, 0.0211],
        [0.3785, 0.8462, 0.8689, 0.8410, 0.7758, 0.9910, 0.8778],
        [0.5581, 0.7680, 0.0452, 0.0300, 0.5317, 0.7893, 0.3292]])

tensor([[0.0334, 0.5193, 0.9772],
        [0.3785, 0.8462, 0.8689],
        [0.5581, 0.7680, 0.0452],
        [0.8115, 0.5481, 0.8446],
        [0.7672, 0.9756, 0.7471],
        [0.5871, 0.6963, 0.9692],
        [0.1949, 0.1939, 0.2087]])


In [35]:
tensor = torch.arange(1,10,dtype= torch.float32).reshape(3,3)
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [51]:
#张量的算数
a = torch.randint(0,5,(3,3))
b = torch.randint(0,5,(3,3))
print(a)
print()
print(b)
print()
print(a+b)
print()
print(a @ b)
c = a.matmul(b.T)
print()
d = (b.T)
print(d)
print()
print(c)

tensor([[1, 4, 3],
        [4, 0, 4],
        [0, 3, 3]])

tensor([[2, 1, 1],
        [0, 0, 2],
        [1, 0, 4]])

tensor([[3, 5, 4],
        [4, 0, 6],
        [1, 3, 7]])

tensor([[ 5,  1, 21],
        [12,  4, 20],
        [ 3,  0, 18]])

tensor([[2, 0, 1],
        [1, 0, 0],
        [1, 2, 4]])

tensor([[ 9,  6, 13],
        [12,  8, 20],
        [ 6,  6, 12]])


In [ ]:
#继续乘法matmul
tensor = torch.arange(1,10,dtype= torch.float32).reshape(3,3)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out = y3)
print(y1)
print()
print(y2)
print()
print(y3)
#三种计算方式得到结果是一样的 

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])


In [70]:
#张量的乘法
c1 = tensor * tensor
c2 = tensor.mul(tensor)
c3 = torch.rand_like(tensor)
torch.mul(tensor,tensor, out = c3)
print(c1)
print()
print(c2)
print()
print(c3)
c4 = tensor * 3 
print()
print(c4)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.],
        [21., 24., 27.]])


In [75]:
#将pytorch 还原python，numpy等环境 
agg = tensor.sum()
agg
agg_item = agg.item()
agg_item
print(agg_item,type(agg_item))

45.0 <class 'float'>


In [78]:
#还原高维的
back = c1.numpy()
back
print(back,back.shape)

[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]] (3, 3)


In [87]:
#in_place 直接修改tensor内部的值
#加下划线  = 直接更新 不返回
#只进行基本计算 不推荐模型更新 会丢失中间记录
tensor
print(tensor,"\n")
tensor.add_(5)
print(tensor)
print()
tensor += 3
print(tensor)
print()

tensor([[22., 23., 24.],
        [25., 26., 27.],
        [28., 29., 30.]]) 

tensor([[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]])

tensor([[30., 31., 32.],
        [33., 34., 35.],
        [36., 37., 38.]])



In [ ]:
#tensor和转化后的numpy用的是一个存储，修改的时候会同步变更

In [92]:
#计算图
#深度学习 即将复杂的数学计算进行计算机流程化
#数学中的求导 = 梯度计算 梯度下降 ,用结果作为参数继续计算以缩小差异 精确化
#计算 x.T * A + b * x + c
#1.定义张量，向量，常数
#requires_grad 表示需要求导
A = torch.randn(10,10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10,requires_grad=True)
s = torch.matmul(A,x.T) + torch.matmul(b,x) + c
print(A)
print()
print(b)
print()
print(c)
print()
print(x)
print()
print(s)

tensor([[-1.0748,  0.9393, -0.6226,  0.2086, -1.5493, -0.9291, -0.8037,  2.0960,
         -0.6040,  1.0168],
        [ 0.2579, -1.0646, -1.1564, -0.7577,  0.9609, -0.3273, -0.8793,  0.5228,
         -1.3264,  1.7398],
        [-2.2641,  0.9292, -0.1391,  0.4022,  0.5137, -0.7588,  0.8937, -0.0973,
         -0.4428,  2.4694],
        [-1.4379, -0.3474, -0.6540, -0.6844, -0.6821,  0.9562,  1.2686,  0.7180,
          0.4079,  0.1116],
        [-0.4487,  1.1314,  0.6974,  0.5303,  0.2558,  0.6852, -0.9963, -0.3036,
         -0.6557,  0.3288],
        [-0.7171,  1.5028,  0.2442, -0.6096,  0.1022,  0.0687,  0.3871, -2.1600,
         -1.2958,  1.8958],
        [-0.0775, -1.1793,  0.1410, -0.7562, -1.0659, -0.1444,  0.4864, -0.7882,
          0.4314, -0.3560],
        [ 0.9716,  0.9846, -0.2931, -1.6228,  1.8900,  0.2662, -0.4781, -0.4046,
          2.6499, -0.0624],
        [-1.9188,  0.3578, -1.5806,  0.2668,  1.0678,  0.4269, -1.0624, -2.0552,
          0.0867,  0.4967],
        [-0.0558,  

In [ ]:
#上面绘制计算图需要进行
#import torch 
#from torchviz import make_dot
#环境暂时不支持
#静态计算图 编写 布置 速度快
#动态计算图 灵活
#矩阵乘积 a * b  <>  b * a 不能随意换位 