In [1]:
import numpy as np

In [2]:
arr = np.array([1, 3, 5, 7, 9], float)
arr

array([1., 3., 5., 7., 9.])

In [3]:
arr = np.array([[3, 4], [5, 6]], int)
arr

array([[3, 4],
       [5, 6]])

In [4]:
arr = np.zeros((3,3), dtype=np.float32)
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [5]:
arr = np.arange(0, 10, 0.5, dtype=np.float32)
arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5], dtype=float32)

In [6]:
arr = np.eye(3, k=0, dtype=np.float32)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [7]:
a = np.random.random(4) #一般是模型运算参数初始值
a

array([0.04369468, 0.8377995 , 0.8790267 , 0.99695613])

In [8]:
a = np.random.randint(0, 100, 4) #一般是模型运算参数初始值
a

array([58, 39,  4, 93])

In [9]:
a = np.random.normal(0, 1, 4) #一般是模型运算参数初始值
a

array([-1.88101388, -0.83610534,  0.8916232 ,  0.36341595])

In [10]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[:, 1]) 
#arr.shape

[2 4 6]


In [11]:
arr = np.array([(1, 2, 3), (4, 5, 6)], dtype=np.float32)
print(arr.shape)
for k,m,j in arr:
    print(k, j)

(2, 3)
1.0 3.0
4.0 6.0


In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float32)
a.ndim #维度 2
a.shape #形状 (3, 2)
a.size # 2*3 = 6
a.dtype #float32

dtype('float32')

In [13]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float32)
#(1, 3) in a #true
#[1, 3] in a
print((1, 3) in a)

True


In [14]:
a = np.arange(1, 10)
#a
#a.shape = 3, 3
#a
#a.shape
a = a.reshape(3, 3, 1)
a.shape

(3, 3, 1)

In [15]:
a = np.array([(1,2), (3,4), (5,6)])
a = a[:,:,np.newaxis]
a.shape #3行2列1深度
a

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [16]:
a = np.ones((3, 3), dtype=np.float32)
a
b = np.array([(-1, 1, 0), (-1, 1, 0), (-2, 2, 0)])
b
a + b #广播

array([[ 0.,  2.,  1.],
       [ 0.,  2.,  1.],
       [-1.,  3.,  1.]])

In [17]:
a.sum()

9.0

In [18]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float32)
a.prod()
b = 24 * 30
print(a.prod() == b)

True


In [19]:
a = np.array([1, 2, 3], dtype=np.int32)
a # array([72, 60, 24])
print(a.mean() == (1 + 2 + 3) / 3) #平均数 true
a.var() #方差  方差（Variance）是统计学中用来衡量一组数据离散程度（即数据的波动性或分散性）的指标。它表示数据点与数据集平均值（均值）之间的偏离程度的平方的平均值。
print(a.var() == ((1-2)**2 + (2-2)**2 + (3-2)**2) / 3) #方差 true
a.std() #标准差
#标准差越大，表示数据点与均值的偏离程度越大，数据的波动性越强，分布越分散。
#标准差越小，表示数据点更集中在均值附近，数据的波动性越小，分布越集中。
#标准差为 0 时，表示所有数据点的值都相同。

#方差是数据点与均值之间偏离程度的平方的平均值。
#标准差是方差的平方根。
print(a.std() == np.sqrt(((1-2)**2 + (2-2)**2 + (3-2)**2) / 3)) #标准差 true


True
True
True


In [20]:
#loc（默认值：0.0）：
#
#正态分布的均值（μ），即分布的中心位置。
#
#生成的随机数会围绕 loc 对称分布。
#
#scale（默认值：1.0）：
#
#正态分布的标准差（σ），用于控制分布的宽度。
#
#scale 越大，数据分布越分散；scale 越小，数据分布越集中。
#
#size（默认值：None）：
#
#输出的形状。可以是一个整数或元组。
#
#如果 size 是整数，则返回一个包含 size 个随机数的一维数组。
#
#如果 size 是元组（如 (m, n)），则返回一个形状为 (m, n) 的数组。
a = np.random.normal(0, 5, 3) 
print(a)
a.argmax() #最大值索引
a.argmin() #最小值索引
print(np.ceil(a)) #向上取整
print(np.floor(a)) #向下取整

[ 6.28695344 -2.92930927 -0.98626924]
[ 7. -2. -0.]
[ 6. -3. -1.]


In [21]:
a = np.random.randint(0, 10, 5)
print(a)
a.sort() # 注意： sort() 方法会直接修改原数组
print(a) #排序

[9 0 6 6 2]
[0 2 6 6 9]


In [22]:
a = np.array([[2, 2], (3, 3)])
b = np.array([[1, 1], (3, 3)])
print(np.dot(a, b)) #矩阵乘法
print(a @ b)
print(np.dot(b, a))
print(np.linalg.inv(a)) #逆矩阵
print(np.linalg.det(a)) #行列式
print(np.linalg.eig(a)) #特征值和特征向量

[[ 8  8]
 [12 12]]
[[ 8  8]
 [12 12]]
[[ 5  5]
 [15 15]]


LinAlgError: Singular matrix

In [ ]:
np.save('a.npy', a)
print(np.load('a.npy'))
np.savetxt('a.txt', a)
np.loadtxt('a.txt')

[[2 2]
 [3 3]]


array([[2., 2.],
       [3., 3.]])