In [3]:
import torch
print(torch.__version__)

2.4.1+cpu


In [13]:
tensor = torch.tensor([1, 2, 3])
tensor = torch.arange(0, 10, dtype=torch.float32)
print(tensor)
print(tensor.dtype)
a = tensor @ tensor.T
a
b = tensor.matmul(tensor.T)
b == a
c = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=c)
c
print(tensor)
z1 = tensor * tensor
z1
z2 = tensor.mul(tensor)
z2
z3 = torch.rand_like(tensor)
z3
torch.mul(tensor, tensor, out=z3)
z3

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


C:\Users\Administrator\AppData\Local\Temp\ipykernel_13776\3727893581.py:10: UserWarning: An output with one or more elements was resized since it had shape [10], which does not match the required output shape []. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:35.)
  torch.matmul(tensor, tensor.T, out=c)


tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [17]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4,5,6],[7,8,9]])
a * b
a + b
a - b
a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667]])

In [29]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
b = torch.from_numpy(a)
print(b)
print(b.numpy())
print(b.dtype)


tensor([[1., 2., 3.],
        [4., 5., 6.]])
[[1. 2. 3.]
 [4. 5. 6.]]
torch.float32


In [33]:
shape = (2, 3, 4)
a = torch.rand(shape)
print(a)
b = torch.ones(shape)
print(b)
zeros = torch.zeros(shape)
print(zeros)

tensor([[[0.8798, 0.8275, 0.9177, 0.8224],
         [0.5567, 0.9537, 0.6984, 0.0901],
         [0.2466, 0.3866, 0.9663, 0.4802]],

        [[0.7076, 0.3988, 0.0489, 0.0380],
         [0.6747, 0.9516, 0.0609, 0.7804],
         [0.3974, 0.6758, 0.8475, 0.4813]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [47]:
a = torch.ones(5, 3, dtype=torch.double)
print(a)
b = torch.rand_like(a, dtype=torch.float)
print(b)
print(a.size())
print(a.shape)
# 均匀分布
print(torch.rand(2, 3, 4))
# 标准正态分布
print(torch.randn(2, 3, 4))
# 离散正态分布
a = torch.normal(mean=.0,std=1.0,size=(5,3))
print(a)
print(torch.linspace(start=10,end=100,steps=10))
print(a.dtype)
print(a.size())
print(a.shape)
print(a.device)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.2862, 0.1453, 0.9127],
        [0.0747, 0.8596, 0.4418],
        [0.9977, 0.3061, 0.1079],
        [0.2165, 0.3965, 0.1539],
        [0.8704, 0.6419, 0.3295]])
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[[0.5286, 0.4641, 0.7719, 0.7112],
         [0.3146, 0.9886, 0.9504, 0.1641],
         [0.8578, 0.5709, 0.8061, 0.0792]],

        [[0.5197, 0.1191, 0.2710, 0.9169],
         [0.4706, 0.6387, 0.7229, 0.2274],
         [0.6096, 0.5715, 0.1181, 0.6640]]])
tensor([[[ 0.9158,  0.1950,  0.6838,  0.8177],
         [ 0.0980, -0.4943,  0.6943,  0.3765],
         [-0.6196, -0.2967, -0.2931,  1.7789]],

        [[ 0.4280,  0.0257,  1.0548, -0.3680],
         [-0.6422, -0.7895,  0.4922,  0.7680],
         [ 0.6599,  1.0543, -0.3890, -1.7407]]])
tensor([[ 0.7793, -1.1179,  0.3973],
        [ 0.4645,  1.0438, -0.6048],
        [-0.7320, -1.8417,  1.2309],


In [48]:
if torch.cuda.is_available():
    a = a.to('cuda')
    print(a)
    print(a.device)
    print(a.to('cpu'))

In [60]:
tensor = torch.ones(3, 3, dtype=torch.int32)
print(tensor)
print(tensor.float())
print(tensor[0])
print(tensor[0].shape)
print(tensor[ :,0])
print(tensor[...,-1])
tensor[:,1] = 0
print(tensor)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([1, 1, 1], dtype=torch.int32)
torch.Size([3])
tensor([1, 1, 1], dtype=torch.int32)
tensor([1, 1, 1], dtype=torch.int32)
tensor([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]], dtype=torch.int32)


In [67]:
t = torch.cat((tensor, tensor, tensor), dim=1)
print(t)
print(t * 3)
print(t.shape)

tensor([[1, 0, 1, 1, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 0, 1, 1, 0, 1]], dtype=torch.int32)
tensor([[3, 0, 3, 3, 0, 3, 3, 0, 3],
        [3, 0, 3, 3, 0, 3, 3, 0, 3],
        [3, 0, 3, 3, 0, 3, 3, 0, 3]], dtype=torch.int32)
torch.Size([3, 9])


In [83]:
tensor = torch.arange(1,10, dtype=torch.float32)
print(tensor)
print(tensor.shape)
tensor = tensor.reshape(3, 3)
print(tensor)
print(tensor.sum())
print(tensor.sum(axis=0))
print(tensor.sum().item())
print(type(tensor.sum().item()))
nparr = tensor.numpy()
print(nparr)
print(tensor.add_(1))
print(tensor)


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor(45.)
tensor([12., 15., 18.])
45.0
<class 'float'>
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])
tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])


In [96]:
import torch
from torchviz import make_dot
a = torch.randn(3, 3,requires_grad=True)
print(a)
b = torch.randn(3, requires_grad=True)
print(b)
c = torch.randn(1, requires_grad=True)
print(c)
x = torch.randn(3, requires_grad=True)
print(x)
# 计算 x^T * A + b * x + c
result = torch.matmul(x.T, a) + torch.matmul(b, x) + c
print(result)
dot = make_dot(result, params={'x': x, 'a': a, 'b': b, 'c': c})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)


tensor([[-1.5671,  0.2750,  1.0378],
        [-0.5409,  0.9125,  0.9757],
        [-1.2410, -1.1409,  1.9771]], requires_grad=True)
tensor([-2.7620,  0.0205,  0.2523], requires_grad=True)
tensor([-1.6108], requires_grad=True)
tensor([ 0.0282, -1.3146,  1.0239], requires_grad=True)
tensor([-2.0612, -3.8174, -0.6862], grad_fn=<AddBackward0>)


ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH