In [2]:
import numpy as np

In [9]:
a1 = range(10)

arr1 = np.array(a1,np.float32)
print(arr1)

arr2 = np.array(a1,np.int32)
print(arr2)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
# 创建ndarray数组
a1 = [1,2,3,4,5]
arr = np.array(a1, int)
print(arr)

arr1 = np.array(a1, float)
print(arr1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [16]:
# a = [1,2,3]
# b = [4,5,6]
# c = [7,8,9]
a = (1,2,3)
b = (4,5,6)
c = (7,8,9)

# a,b,c 可以是元组/列表
d = np.array((a, b, c)) 
print(d)
print()

d = np.array([a, b, c]) 
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
a1 = np.zeros((2,3), dtype=np.float32)
print(a1)
print()

a1 = np.zeros((4,3), dtype=np.int32)
print(a1)
a1

[[0. 0. 0.]
 [0. 0. 0.]]

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
a2 = np.ones((3,3), dtype=np.float32)
print(a2)
a2

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [21]:
a1 = np.ones_like(a2, dtype=np.float32)
print(a1)
a1

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [22]:
a2 = np.arange(1,6, 1, dtype=np.int32)
print(a2)
a2

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [23]:
a3 = np.eye(3)
print(a3)
a3  # one-hot编码

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
a4 = np.random.random(10)  # 模型运算参数初始值，0到1之间平均分布的随机数
a4

array([0.72740671, 0.68340077, 0.27896472, 0.86920986, 0.01554767,
       0.75522996, 0.33076822, 0.15319782, 0.21447345, 0.01171307])

In [25]:
a5 = np.random.normal(0, 0.1, 10)  # 模型运算参数初始值,均值为0，标准差为0.1，数量为10的随机数
a5

array([ 0.06363844, -0.0072685 , -0.0488202 , -0.21703377,  0.06470532,
        0.01090629,  0.16227556, -0.11800072,  0.03288325, -0.14486278])

In [26]:
a6 = np.array([(1,2,11,22), (3,4,33,44), (5,6,55,66)])
print(a6)
print()
print(a6[1])
print()
print(a6[:2,2])
print()
print(a6[:3,2])
print()
print(a6[2,2])
print()
print(a6[2][1])

[[ 1  2 11 22]
 [ 3  4 33 44]
 [ 5  6 55 66]]

[ 3  4 33 44]

[11 33]

[11 33 55]

55

6


In [27]:
a7 = np.array([(1,2), (3,4), (5,6)])
i,j = a7[0]
print(i,j)
print()

for i,j in a7:
    print(i,j)



1 2

1 2
3 4
5 6


In [31]:
# a = np.array([(3,6,7), (4,7,6), (7,8,9)])
a = np.eye(4)
print(a)
print("ndim:", a.ndim) #维度
print("shape:", a.shape) #形状
print("size", a.size) #数量
print("dtype", a.dtype) #数据类型

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
ndim: 2
shape: (4, 4)
size 16
dtype float64


In [32]:
print(3 in a)
print(1 in a)

False
True


In [37]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)
print()

a7 = a7.reshape(3,3,1)  # 维度大小乘积 == 元素个数
print(a7)
print()

a7 = a7.reshape(3,3)  # 维度大小乘积 == 元素个数
print(a7)
print()

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[1 2 3 4 5 6 7 8 9]
(9,)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

(3, 3)


In [41]:
print(a7)
print()

a7 = a7.T
print(a7)
print()

a7 = a7.transpose()
print(a7)

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
a7 = a7.flatten() #展平
print(a7)

[1 4 7 2 5 8 3 6 9]


In [43]:
a8 = np.array([(1,2,12), (3,4,34), (5,6,56)])
print(a8)
print()

a8 = a8[:,np.newaxis,:] 
print(a8.shape)
print()

print(a8)

[[ 1  2 12]
 [ 3  4 34]
 [ 5  6 56]]

(3, 1, 3)

[[[ 1  2 12]]

 [[ 3  4 34]]

 [[ 5  6 56]]]


In [46]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print()
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1.]
 [1. 1.]]

[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]


In [48]:
a.sum()

4.0

In [ ]:
a +=1
print(a)
a.prod() #求乘积

[[2. 2.]
 [2. 2.]]


16.0

In [ ]:
# 数组，矩阵、维度

# 数组、矩阵  ： 数据组织结构形式

# 维度： 通讯地址

In [49]:
a = np.array([1,2,3,4,5,6])
print("mean:",a.mean()) #平均值
print("var:", a.var()) #方差
print("std:", a.std()) #标准差

mean: 3.5
var: 2.9166666666666665
std: 1.707825127659933


In [51]:
a = np.array([1.02, 3.8, 4.9, -123.6, 123.7])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 4
argmin: 3
ceil: [   2.    4.    5. -123.  124.]
floor: [   1.    3.    4. -124.  123.]
rint: [   1.    4.    5. -124.  124.]


In [52]:
a = np.array([16,31,12,28,22,31,48,10,16])
a.sort()  # 排序
print(a)
b = np.sort(a)[::-1]
print(b)

[10 12 16 16 22 28 31 31 48]
[48 31 31 28 22 16 16 12 10]


In [54]:
import torch
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)
print(tensor)
print()

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor
print(y1)
print()

y2 = tensor.matmul(tensor)
print(y2)
print()

y3 = torch.rand_like(tensor)
print(y3)
print()

torch.matmul(tensor, tensor, out=y3)
print(y3)
print()

# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

torch.float32
tensor([[ 90., 100., 110., 120.],
        [202., 228., 254., 280.],
        [314., 356., 398., 440.],
        [426., 484., 542., 600.]])

tensor([[ 90., 100., 110., 120.],
        [202., 228., 254., 280.],
        [314., 356., 398., 440.],
        [426., 484., 542., 600.]])

tensor([[0.5965, 0.8637, 0.5051, 0.5690],
        [0.5701, 0.3904, 0.3648, 0.5527],
        [0.9913, 0.9655, 0.4575, 0.7287],
        [0.3472, 0.1698, 0.7708, 0.7100]])

tensor([[ 90., 100., 110., 120.],
        [202., 228., 254., 280.],
        [314., 356., 398., 440.],
        [426., 484., 542., 600.]])



tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])

In [61]:
a9 = np.array(range(1,17)).reshape(4,4)
b9 = a9
print(a9)
print()
print(b9)
print()

c = a9 * b9
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]


In [64]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array(a9, dtype=np.float32)
m2 = np.array(a9, dtype=np.float32)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

矩阵 1:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
矩阵 2:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
使用 np.dot 得到的矩阵乘法结果:
[[ 90. 100. 110. 120.]
 [202. 228. 254. 280.]
 [314. 356. 398. 440.]
 [426. 484. 542. 600.]]
使用 @ 运算符得到的矩阵乘法结果:
[[ 90. 100. 110. 120.]
 [202. 228. 254. 280.]
 [314. 356. 398. 440.]
 [426. 484. 542. 600.]]


In [ ]:
np.save('result.npy',result_at) #以二进制的方式讲数据保存到文件

In [76]:
result_np = np.load('result.npy') #从文件中读取数据
print(result_np)

[[ 90. 100. 110. 120.]
 [202. 228. 254. 280.]
 [314. 356. 398. 440.]
 [426. 484. 542. 600.]]


In [77]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [78]:
a = np.array(range(8)).reshape(2,4)  # shape(4,2)
b = np.array([-1,1]).reshape(2,1)

print(a)
print()
print(b)
print()
print(np.shape(b))
print()
a + b

[[0 1 2 3]
 [4 5 6 7]]

[[-1]
 [ 1]]

(2, 1)



array([[-1,  0,  1,  2],
       [ 5,  6,  7,  8]])