In [2]:
import torch

data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
print(data)
print()

data = torch.tensor([[1,2],[3,4]], dtype=torch.int32)
print(data)

tensor([[1., 2.],
        [3., 4.]])

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
import numpy as np
print(np.__version__)
print(torch.__version__)

1.26.4
2.4.1+cpu


In [8]:
import numpy as np

np_array = np.array(range(9)).reshape(3,3)
data2 = torch.from_numpy(np_array)
data2

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)

In [7]:
data2.dtype

torch.int32

In [ ]:
# 通过已知张量维度，创建新随机张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.9843, 0.7961, 0.4247],
        [0.2183, 0.1842, 0.7360],
        [0.7865, 0.4933, 0.2088]])

In [11]:
shape = (4,4)
rand_tensor = torch.rand(shape) #随机张量
ones_tensor = torch.ones(shape) #全为1
zeros_tensor = torch.zeros(shape) #全为0

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9118, 0.1711, 0.8242, 0.9695],
        [0.1619, 0.9684, 0.6180, 0.1874],
        [0.6997, 0.7820, 0.0972, 0.3703],
        [0.2678, 0.7012, 0.3329, 0.9226]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [13]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=20))

torch.Size([5, 3])
tensor([[0.4624, 0.0881, 0.6554],
        [0.9020, 0.2808, 0.8022],
        [0.8236, 0.6049, 0.0307],
        [0.5206, 0.6282, 0.4797],
        [0.6381, 0.2432, 0.1014]])
tensor([[-0.0700,  1.5548, -2.4374],
        [-0.3357, -1.5111,  1.2640],
        [ 0.8685, -0.7651,  0.4317],
        [ 0.3604,  1.3296,  1.2360],
        [ 0.4609,  0.6390,  1.6991]])
tensor([[ 0.3395, -1.3210,  0.7091],
        [-0.5748, -1.2705, -0.2666],
        [-0.9621,  1.7797, -0.8900],
        [-0.4303,  0.6655, -1.2343],
        [ 2.3350, -1.0902, -0.4905]])
tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])


In [14]:
tensor = torch.rand(5,2)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([5, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [16]:
print(torch.cuda.is_available())
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

False
tensor([[0.6222, 0.4525],
        [0.3788, 0.3858],
        [0.6362, 0.3520],
        [0.5430, 0.8331],
        [0.0353, 0.0178]])
cpu
tensor([[0.6222, 0.4525],
        [0.3788, 0.3858],
        [0.6362, 0.3520],
        [0.5430, 0.8331],
        [0.0353, 0.0178]])
cpu


In [17]:
tensor = torch.tensor(range(1,10)).reshape(3,3)
print(tensor)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 2
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
First row:  tensor([1, 2, 3])
First column:  tensor([1, 4, 7])
Last column: tensor([3, 6, 9])
tensor([[1, 2, 3],
        [4, 2, 6],
        [7, 2, 9]])


In [19]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) #dim=1 表示沿列方向拼接
print(t1)
print(t1 * 3)
print(t1.shape)

t1 = torch.cat([tensor, tensor, tensor], dim=0) #dim=0 表示沿行方向拼接
print(t1)
print(t1.shape)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 2, 6, 4, 2, 6, 4, 2, 6],
        [7, 2, 9, 7, 2, 9, 7, 2, 9]])
tensor([[ 3,  6,  9,  3,  6,  9,  3,  6,  9],
        [12,  6, 18, 12,  6, 18, 12,  6, 18],
        [21,  6, 27, 21,  6, 27, 21,  6, 27]])
torch.Size([3, 9])
tensor([[1, 2, 3],
        [4, 2, 6],
        [7, 2, 9],
        [1, 2, 3],
        [4, 2, 6],
        [7, 2, 9],
        [1, 2, 3],
        [4, 2, 6],
        [7, 2, 9]])
torch.Size([9, 3])


In [23]:
import torch
tensor = torch.arange(9, dtype=torch.float32).reshape(3, 3)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor
y2 = tensor.matmul(tensor)

print(y1)
print()
print(y2)
print()

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor, out=y3)
print(y3)
print()


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print()
print(z3)

tensor([[ 15.,  18.,  21.],
        [ 42.,  54.,  66.],
        [ 69.,  90., 111.]])

tensor([[ 15.,  18.,  21.],
        [ 42.,  54.,  66.],
        [ 69.,  90., 111.]])

tensor([[ 15.,  18.,  21.],
        [ 42.,  54.,  66.],
        [ 69.,  90., 111.]])

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.],
        [36., 49., 64.]])

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.],
        [36., 49., 64.]])


In [24]:
agg = tensor.sum() ## 创建一个 3x3 的张量
agg_item = agg.item() ## 将结果转换为 Python 标量
print(agg_item, type(agg_item))

36.0 <class 'float'>


In [ ]:
np_arr = z1.numpy() #将 tensor 转化为 numpy
np_arr

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]], dtype=float32)

In [27]:
print(tensor, "\n")
tensor.add_(1)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[ 5.,  6.,  7.],
        [ 8.,  9., 10.],
        [11., 12., 13.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [28]:
tensor

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])

In [29]:
import torch
from torchviz import make_dot

# 定义矩阵 a，向量 b 和常数 c
a = torch.randn(10, 10, requires_grad=True)  # requires_grad=True 表示我们要对 A 求导/梯度
b = torch.randn(10, 10, requires_grad=True)
c = torch.randn(1, requires_grad=True)
x = torch.randn(10, requires_grad=True)

# 计算 x^T * A + b * x + c
result = torch.matmul(a, x.T) + torch.mul(b, x) + c

# # 生成计算图节点
dot = make_dot(result, params={'a': a, 'b': b, 'c': c, 'x': x})
# # 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)


C:\Users\TianXiang\AppData\Local\Temp\ipykernel_13976\4011233948.py:11: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  result = torch.matmul(a, x.T) + torch.mul(b, x) + c


'expression.png'