In [5]:
import numpy as np

In [6]:
# 创建ndarray数组
arr = np.array([11,22,33,44,55], float)
arr

array([11., 22., 33., 44., 55.])

In [7]:
a = np.array([(10,20,30),(40,50,60),(70,80,90)])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
a1 = np.zeros((3, 2), dtype=np.float32)
a1

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [9]:
a2 = np.arange(3,4, 0.04)
a2

array([3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28, 3.32, 3.36, 3.4 ,
       3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72, 3.76, 3.8 , 3.84,
       3.88, 3.92, 3.96])

In [10]:
a3 = np.eye(5)
a3  # one-hot编码

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
# 0,1之间随机数
a4 = np.random.random(6) # 模型运行参数初始值
a4

array([0.55954264, 0.02842119, 0.66482771, 0.06435505, 0.35250668,
       0.67520742])

In [12]:
# 正态分布随机数
a5 = np.random.normal(0, 0.2, 6)
a5

array([ 0.0501574 , -0.10956018, -0.11188618, -0.02631989,  0.07898997,
       -0.0853423 ])

In [13]:
# 切片
a6 = np.array([(10,20),(30,40),(50,60)])
print(a6)
print(a6[:,0])

[[10 20]
 [30 40]
 [50 60]]
[10 30 50]


In [14]:
a7 = np.array([(10,20),(30,40),(50,60)])
i, j = a7[2]
print("第三个元素：",i, j)
# 获取元素
for i, j in a7:
    print(i, j)

第三个元素： 50 60
10 20
30 40
50 60


In [15]:
a = np.array([(10,20,30), (40,50,60), (70,80,90)])
print("数组纬度 ndim:", a.ndim)
print("数组的大小 shape:", a.shape)
print("数组元素的总数 size", a.size)
print("数组中元素类型的对象 dtype", a.dtype)

数组纬度 ndim: 2
数组的大小 shape: (3, 3)
数组元素的总数 size 9
数组中元素类型的对象 dtype int64


In [ ]:
# 查看元素是否存在与数组中
print(10 in a)
print(100 in a)

True
False


In [47]:
a7 = np.arange(10,26)
print(a7)
print(a7.shape)

a7 = a7.reshape(4,4)
print(a7)

print(a7.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
(16,)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
(4, 4)


In [54]:
# 转置
print(a)
a = a.T
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [ ]:
# 增加维度
a8 = np.array([(10, 20), (30, 40), (50, 60)])
print(a8)
a8 = a8[:, :, np.newaxis]
print(a8)
print(a8.shape)


[[10 20]
 [30 40]
 [50 60]]
[[[10]
  [20]]

 [[30]
  [40]]

 [[50]
  [60]]]
(3, 2, 1)


In [66]:
a = np.ones((3,3))
b = np.array([(-10,10,20),(10,-10,-30),[20,10,-10]])
print(a)
print(b)
print("加")
print(a+b)
print("减")
print(a-b)
print("乘")
print(a*b)
print("除")
print(a/b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[-10  10  20]
 [ 10 -10 -30]
 [ 20  10 -10]]
加
[[ -9.  11.  21.]
 [ 11.  -9. -29.]
 [ 21.  11.  -9.]]
减
[[ 11.  -9. -19.]
 [ -9.  11.  31.]
 [-19.  -9.  11.]]
乘
[[-10.  10.  20.]
 [ 10. -10. -30.]
 [ 20.  10. -10.]]
除
[[-0.1         0.1         0.05      ]
 [ 0.1        -0.1        -0.03333333]
 [ 0.05        0.1        -0.1       ]]


In [77]:

a = np.array([1,2,10,5])
print(a)
# 求和
print(a.sum())
# 求积
print(a.prod())

# 平均数
print(a.mean())
# ⽅差
print(a.var())
# 标准差
print(a.std())
# 最⼤值
print(a.max())
# 最⼩值
print(a.min())

[ 1  2 10  5]
18
100
4.5
12.25
3.5
10
1


In [82]:
a = np.array([1.3,2.9,10.09,5.8])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 2
argmin: 0
ceil: [ 2.  3. 11.  6.]
floor: [ 1.  2. 10.  5.]
rint: [ 1.  3. 10.  6.]


In [85]:
# 数组排序
a = np.array([89,90,30,40,50])
a.sort()
print(a)

[30 40 50 89 90]


In [ ]:
# pytorch
import torch
# 创建张量 生成从 1 到 16 的 连续整数 指定数据类型为 float32 变成 4×4 的矩阵
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
print(y1)
print(y2)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32
tensor([[ 30.,  70., 110., 150.],
        [ 70., 174., 278., 382.],
        [110., 278., 446., 614.],
        [150., 382., 614., 846.]])
tensor([[ 30.,  70., 110., 150.],
        [ 70., 174., 278., 382.],
        [110., 278., 446., 614.],
        [150., 382., 614., 846.]])
tensor([[0.5487, 0.3597, 0.2752, 0.7352],
        [0.5646, 0.3012, 0.3548, 0.9234],
        [0.7804, 0.2904, 0.3591, 0.0636],
        [0.3866, 0.8172, 0.4306, 0.2180]])


tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])

In [120]:
a9 = np.array([[1,2,30],[4,59,6]])
b9 = np.array([[4,55,6],[71,8,9]])

a9 * b9

array([[  4, 110, 180],
       [284, 472,  54]])

In [88]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [91]:
np.save('result.npy',manual_result)

In [92]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [93]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [94]:
a = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
b = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])

In [95]:
import torch

data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
data

tensor([[1., 2.],
        [3., 4.]])

In [96]:
import numpy as np

np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4]])

In [97]:
data2.dtype

torch.int64

In [98]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.0483, 0.9865],
        [0.9470, 0.3108]])

In [99]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0822, 0.8526, 0.4009],
        [0.2289, 0.0959, 0.2177]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [100]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([5, 3])
tensor([[0.3159, 0.2777, 0.9304],
        [0.8123, 0.4299, 0.9497],
        [0.3123, 0.1156, 0.0087],
        [0.4237, 0.3934, 0.6939],
        [0.0147, 0.1780, 0.7986]])
tensor([[-0.3461, -1.5793,  0.1931],
        [ 1.3182,  1.4008,  0.8309],
        [-0.6988, -0.2084,  1.3177],
        [ 0.7664,  1.0877, -0.2568],
        [ 1.2999,  0.5453,  0.3749]])
tensor([[-1.8954e-01, -3.8496e-01, -1.5826e+00],
        [ 4.2710e-01, -1.2705e+00,  3.6379e-01],
        [-1.3409e+00,  1.4249e-01,  6.7403e-01],
        [-1.8045e+00, -4.3351e-01, -7.6993e-01],
        [ 4.2673e-04, -1.4960e+00,  5.3095e-01]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [101]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [102]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.7097, 0.7529, 0.2835, 0.2860],
        [0.7321, 0.1796, 0.8890, 0.0326],
        [0.1499, 0.1447, 0.2931, 0.1691]])
cpu
tensor([[0.7097, 0.7529, 0.2835, 0.2860],
        [0.7321, 0.1796, 0.8890, 0.0326],
        [0.1499, 0.1447, 0.2931, 0.1691]])
cpu


In [103]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [104]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.]])
torch.Size([4, 12])


In [ ]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

In [105]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [106]:
print(tensor, "\n")
tensor.add_(5)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [107]:
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [2]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(200, 200,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(200,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(200, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression0308', format='png', cleanup=True, view=False)

'expression0308.png'