In [1]:
# 使用sklearn数据集训练逻辑回归模型
from sklearn.datasets import load_iris

X,y = load_iris(return_X_y=True)
X[:100]  # 取前100个数据
y[:100]  # 取前100个标签(0,1)

# 调整学习率，样本数据拆分比率，观察训练结果
# 把模型训练参数保存到文件，在另一个代码中加载参数实现预测功能

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [2]:
X.shape

(150, 4)

In [3]:
X[0]  # 花萼长度，花萼宽度，花瓣长度，花瓣宽度


array([5.1, 3.5, 1.4, 0.2])

In [4]:
y.shape

(150,)

In [17]:
X[:100]  # 取前100个数据

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y[:100]  # 取前100个标签(0,1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
from sklearn.model_selection import train_test_split
import numpy as np

In [79]:


# 模型计算函数
def forward(x, theta, bias):
    # 线性运算
    z = np.dot(theta, x.T) + bias
    # sigmoid激活函数
    y_hat = 1 / (1 + np.exp(-z))
    return y_hat

# 损失函数
def loss(y, y_hat):
    minimum = 1e-8
    return -y * np.log(y_hat + minimum) - (1 - y) * np.log(1 - y_hat + minimum)

# 计算梯度
def calc_gradient(x, y, y_hat):
    m = x.shape[0]
    # theta梯度计算
    d_theta = np.dot((y_hat - y), x) / m
    # bias梯度计算
    d_bias = np.mean(y_hat - y)
    # 返回梯度
    return d_theta, d_bias


def train_model(test_size=0.2, lr=0.1, epochs=500, save=False):
    X_train, X_test, y_train, y_test = train_test_split(X[:100], y[:100], test_size=test_size)

    # 权重参数
    theta = np.random.randn(1, 4)
    # 偏差
    bias = 0

    # 模型训练
    for i in range(epochs):
        # 前向计算
        y_hat = forward(X_train, theta, bias)
        # 计算损失
        loss_val = loss(y_train, y_hat)
        # 计算梯度
        d_theta, d_bias = calc_gradient(X_train, y_train, y_hat)
        # 更新参数
        theta -= lr * d_theta
        bias -= lr * d_bias
        if i % 10 == 0:
            acc = np.mean(np.round(y_hat) == y_train)  # [False,True,...,False] -> [0,1,...,0]
            print('epoch:', i, 'loss:', np.mean(loss_val), 'acc:', acc)

    # 模型推理
    idx = np.random.randint(len(X_test)) # 随机选择一个测试样本索引
    # x_test_data = X_test[idx]
    # y_test_data = y_test[idx]

    predict = np.round(forward(X_test, theta, bias)).astype(int)
    # print(f"y: {y_test}")
    # print(f"p: {predict[0]}")
    # print(predict[0] == y_test)
    print('每个元素都预测正确', np.all(predict[0] == y_test))

    if save:
        np.save('theta.npy', theta)
        np.save('bias.npy', bias)

In [77]:
train_model(test_size=0.3, epochs=50)
# train_model(test_size=0.5, epochs=50)
# train_model(test_size=0.8, epochs=50)
# train_model(test_size=0.9, epochs=50)
# train_model(test_size=0.95, epochs=50)
train_model(test_size=0.96, epochs=50)
train_model(test_size=0.97, epochs=50)
train_model(test_size=0.98, epochs=50)


epoch: 0 loss: 1.617336558748663 acc: 0.5142857142857142
epoch: 10 loss: 0.4272028099197743 acc: 0.9857142857142858
epoch: 20 loss: 0.27535676756288785 acc: 1.0
epoch: 30 loss: 0.19918304142756496 acc: 1.0
epoch: 40 loss: 0.15491056750371598 acc: 1.0
每个元素都预测正确 True
epoch: 0 loss: 1.8530342472945815 acc: 0.25
epoch: 10 loss: 0.9350701935037984 acc: 0.25
epoch: 20 loss: 0.5235321456866953 acc: 1.0
epoch: 30 loss: 0.336140452609228 acc: 1.0
epoch: 40 loss: 0.24090411239941364 acc: 1.0
每个元素都预测正确 True
epoch: 0 loss: 2.340551138263298 acc: 0.6666666666666666
epoch: 10 loss: 1.7608396801128834 acc: 0.6666666666666666
epoch: 20 loss: 1.2874965434793355 acc: 0.6666666666666666
epoch: 30 loss: 0.8772047124068107 acc: 0.6666666666666666
epoch: 40 loss: 0.5805538053258176 acc: 0.6666666666666666
每个元素都预测正确 False
epoch: 0 loss: 3.009950817713623 acc: 0.0
epoch: 10 loss: 0.007631360835505142 acc: 1.0
epoch: 20 loss: 0.004828807253129606 acc: 1.0
epoch: 30 loss: 0.0035370270767488116 acc: 1.0
epoch: 4

In [80]:
train_model(test_size=0.3, epochs=50, save=True)

epoch: 0 loss: 1.755688899397967 acc: 0.5
epoch: 10 loss: 0.1558782224962504 acc: 1.0
epoch: 20 loss: 0.12779049027567724 acc: 1.0
epoch: 30 loss: 0.10820598784774342 acc: 1.0
epoch: 40 loss: 0.09381298642006336 acc: 1.0
每个元素都预测正确 True
