****导入numpy包**
-创建ndarray数组**

In [21]:
import numpy as np 

--最后一行为显示数组，之前的输出会被覆盖

In [18]:
 a = np.array([3,4,6,7],float)
 b = np.array([1,2,8],int)
 a
 b

array([1, 2, 8])

--多维数组是几个数组逗号隔开，在array数组里

In [24]:
b = np.array([(3,4),(7,8),(2,9)],float)
b

array([[3., 4.],
       [7., 8.],
       [2., 9.]])

--特殊数组创建Zeros；Ones；等差数列(不包含结束值)；单位矩阵；随机数组[0-1)之间平均分布；正态分布的随机数组(指定参数：均值，标准差)

In [34]:
c = np.zeros([3,2],dtype=np.float16)
c

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float16)

In [36]:
c1 = np.ones([2,3],dtype=float)
c1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
c2 = np.arange(0,10,2)
c2

array([0, 2, 4, 6, 8])

<< one-hot编码会用到 >>

In [39]:
c3 = np.eye(4)
c3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<<随机数组：模型运算参数初始值>>

In [40]:
c4 = np.random.random(3)
c4

array([0.32846043, 0.10942105, 0.04027877])

<<正态分布：模型运算参数初始值>>

In [45]:
mu,sigma=0,0.5
c5 = np.random.normal(mu,sigma,6)
c5

array([-0.04227751, -0.82856992,  0.52918918, -0.13858821, -0.93106989,
       -0.77321362])

**Numpy数组访问**（冒号：的意思是所有范围）
 ---( :2是指前两个; 2:是指第2个开始之后的)

In [84]:
b = np.array([(2,3,5),(1,4,6),(4,2,1),(2,2,2)])
print(b[1])
print(b[2:])
print()
print(b[:2])
print()
print(b[:,:2])
print()
print(b[:,2:])
print()
print(b[2:,:])
print()
print(b[:2,:])
print()
print(b[1][2])


[1 4 6]
[[4 2 1]
 [2 2 2]]

[[2 3 5]
 [1 4 6]]

[[2 3]
 [1 4]
 [4 2]
 [2 2]]

[[5]
 [6]
 [1]
 [2]]

[[4 2 1]
 [2 2 2]]

[[2 3 5]
 [1 4 6]]

6


**Numpy数组遍历**

In [70]:
a = np.array([(2,4,6),(1,3,5),(1,1,1)])
#i,j,t = a[1]
for i,j,t in a:
   print(i,j,t)
   print(j)

2 4 6
4
1 3 5
3
1 1 1
1


**Numpy数组常用属性**（维度ndim(秩=数组轴的个数)，数组大小shape，数组个数size（shape元素的乘积），元素类型对象dtype）

In [71]:
a1 = np.array([(2,4,6,8),(1,3,5,7),(3,4,5,6)])
print("ndim:",a1.ndim)
print("shape:",a1.shape)
print("size",a1.size)
print("dtype",a1.dtype)

ndim: 2
shape: (3, 4)
size 12
dtype int32


**Numpy数组基本操作**

<< in（是否存在，确保维度对齐）>>

In [ ]:
print((1,3,5,7) in a1)
print((9 in a1)) #只能进行单一判断or对齐维度判断

True
False


<< reshape（数组重排列）--维度大小乘积=元素个数>>
   ---高维矩阵，每个维度都有意义。 
       -如加载图像数据：image.shape = [1,3,120,120] (1个样本，3个颜色通道，120高，120宽)

In [ ]:
a2 = np.arange(2,6)
print(a2)
print(a2.size)

a2 = a2.reshape(2,2,1)  #乘积==个数
print(a2)
print(a2.shape)  #（层，行，列）

[2 3 4 5]
4
[[[2]
  [3]]

 [[4]
  [5]]]
(2, 2, 1)


<< transpose（转置.T >>

In [ ]:
a3 = np.array([(1,2),(3,5),(6,9)])
print(a3)
a3 = a3.T # a3.transpose()
print(a3)

[[1 2]
 [3 5]
 [6 9]]
[[1 3 6]
 [2 5 9]]


<< flatten（多维转一维，且每个数组长度必相同）>>

In [ ]:
a3 = a3.flatten()
print(a3)  #按上面最后一个a3

[1 3 6 2 5 9]


In [ ]:
a4 = np.array([(1,3,8),(2,6,9)])
print(a4.shape)
a4 = a4[:,np.newaxis,:] #增加了1行
print(a4.shape)
print(a4)

(2, 3)
(2, 1, 3)
[[[1 3 8]]

 [[2 6 9]]]


<< newaxis（增加维度）>>

In [ ]:
a = np.ones([3,3])
b = np.eye(3) # 维度必须保持对齐
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]

[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


<< 求和，积>>

In [90]:
a.sum()

9.0

In [91]:
a.prod()

1.0