# week01 torch 基础

## numpy

In [17]:
import numpy as np

### 创建

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a[0] = 10
print(a[:3])
print(a[3:])


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[1, 3])


#### 特殊数组创建


In [ ]:
a = np.zeros((2, 3), dtype=float)
print(a)

a = np.ones((2, 3), dtype=int)
print(a)


#### 创建等差数列

In [ ]:
a = np.arange(1, 5, 0.5)
a


#### 创建单位矩阵

In [ ]:
a = np.eye(3)
a


### 生成指定长度, 在[0,1) 之间平均分配的随机数组

In [ ]:
a = np.random.random(5)
a


#### 均值为 0， 标准差为 0.1

In [ ]:
mu, sigma = 0, 0.1
a = np.random.normal(mu, sigma, 5)
a


#### 数组的访问

In [ ]:
a = np.array([(1, 2), (3, 4), (5, 6)])
print(a[0])
print(a[1:])
print(a[:, :1])
print(a[1][1])


#### 数组的遍历

In [ ]:
a = np.array([1,2,3])
for i in a:
    print(i)


#### 多维数组的数组的遍历

In [ ]:
a = np.array([(1, 2), (3, 4), (5, 6)])
for i, j in a:
    print(i * j)


### 数组的常用属性

* ndarray.ndim: 数组的维度(数组轴的个数)， 等于秩
* ndarray.shape: 数组的维度，对于矩阵，n 行 m 列
* ndarray.size: 数组元素的总个数，等于 n * m
* ndarray.dtype: ndarray 对象的元素类型


In [ ]:
a = np.array([[(1,1), (2,2)], [(4,4), (5,5)], [(7,7), (8,8)]])
print(a)
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)
print("dtype:", a.dtype)


### 数组的基本操作

#### `in`: 检测数值是否在数组中

In [ ]:
a = np.array([(1, 2), (3,4)])
print(3 in a)
print(5 in a)

#### `reshape`: 数组的重新排列

In [ ]:
a = np.zeros([2, 3, 4])
a.reshape(2, 2, 2, 3)

#### `tanspose`: 转置(可以直接.T)

In [ ]:
a = np.array([(1, 2, 3, 10), (4, 5, 6, 11), (7, 8 ,9, 12)])
print(a.transpose())
print(a.T)

#### `flattern`: 多维转一 维

In [ ]:
a = np.array([(1,2), (3,4), (5, 6)])
print(a.flatten())

#### `newaxis`: 增加维度

In [ ]:
a = np.array([1,2,3])

a = a[:, np.newaxis]

print(a)


### 数学操作

#### 加减乘除

In [ ]:
a = np.ones((2,2))
b = np.array([(-1, 1), (-1, 1)])
print(a)
print(b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)


#### 求和求积

In [ ]:
a = np.array([1,2,1])
print(a.sum())
print(a.prod())


#### 平均数，方差，标准差，最大值，最小值

In [ ]:
a = np.array([5,3,1])
print("mean:", a.mean())
print("var:", a.var())
print("std:", a.std())
print("max:", a.max())
print("min:", a.min())


#### 最大值，最小值对应的的索引, 上限，下限，四舍五入

In [ ]:
a = np.array([1.2, 3.8, 4.9])
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("round:", np.round(a))


#### 排序

In [ ]:
a = np.array([16,31,12,28,22,31,48])
b = np.sort(a)
print(b)

c = np.sort(a)[::-1]
print(c)


### 线性代数

#### `dot`: 矩阵乘法

In [4]:
m1 = np.array([[1,2],[3,4]], dtype=np.float32)
m2 = np.array([[5,6],[7,8]], dtype=np.float32)

print(m1)
print(m2)

print(m1.dot(m2))

print(m1 @ m2)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


##### 手动推演

In [ ]:
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

print(manual_result)

for i in range(m1.shape[0]):
    for j in range(m2.shape[1]):
        for k in range(m1.shape[1]):
            print(f"m1[i,k]*m2[k, j] = {m1[i,k]*m2[k, j]}")
            manual_result[i,j] += m1[i,k]*m2[k,j]
            
        print(f"结果矩阵[{i+1}, {j+1}]:{manual_result[i,j]}\n")
        
print("手动推演结果")
print(manual_result)

##### 其他函数

* `eig`: 特征值
* `inv`: 逆
* `qr`: QR 分解
* `svd`: 奇异值分解
* `solve`: 解线性方程 Ax = b
* `lstsq`: 计算 Ax = b 的最小二乘解

### 文件操作

In [ ]:
a = np.array([1,2,3,4,5])
np.save("a.npy", a)

b = np.load("a.npy")
print(b)

np.savetxt("c.txt", a)

c = np.loadtxt("c.txt")
print(c)

### 广播机制

In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


#### 不同形状 

In [ ]:
a = np.array([(1,2), (2,2), (3,3), (4,4)])
b = np.array([-1,1])

a + b

## torch

In [2]:
import torch

### 张量

#### 直接从数据

In [19]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

#### 从 NumPy 数组

In [21]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

#### 从另一个张量

In [ ]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

#### 使用随机值或常量值

`shape` 是张量维度的元组

In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

#### 其他一些创建方法

##### 基于现有 tensor 创建，但使用新值填充

In [29]:
m = torch.ones(5, 3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

print(m)
print(n)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.2152, 0.7965, 0.5439],
        [0.0156, 0.4587, 0.5040],
        [0.1243, 0.0665, 0.7975],
        [0.4329, 0.1313, 0.6241],
        [0.9563, 0.7754, 0.4717]])


##### 获取 tensor 的大小

In [ ]:
print(m.size())

print(m.shape)

##### 均匀分布

In [ ]:
torch.rand(5, 3)

##### 标准正态分布

In [ ]:
torch.randn(5, 3)

##### 离散正态分布

In [35]:
torch.normal(mean=.0, std=1.0, size=(5, 3))

tensor([[-2.6656,  1.1436, -2.1135],
        [ 1.2190,  0.4288,  1.4103],
        [ 0.9212,  0.2494,  0.3741],
        [-0.8644, -0.8041,  0.9160],
        [-0.9319, -0.2577,  1.2858]])

##### 线性间隔向量(返回一个一维张量,包含在区间start和end上均匀间隔的steps个点)

In [ ]:
torch.linspace(start=1, end=10, steps=20)

#### 张量的属性

In [ ]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"DataType of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

#### 张量运算

##### 设置张量在 GPU 上运算

In [38]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    
print(f"Device of tensor: {tensor.device}")

Device of tensor: cuda:0


##### 张量的索引和切片

In [4]:
tensor = torch.ones(4, 4)
tensor[:, 3] = 0
tensor[:, 1] = 2
print(tensor)
print("First row:", tensor[0])
print("Fist column", tensor[:, 0])
print("Fist column", tensor[..., 0])
print("Last column", tensor[..., -1])
print("Last column", tensor[:, -1])

tensor([[1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.],
        [1., 2., 1., 0.]])
First row: tensor([1., 2., 1., 0.])
Fist column tensor([1., 1., 1., 1.])
Fist column tensor([1., 1., 1., 1.])
Last column tensor([0., 0., 0., 0.])
Last column tensor([0., 0., 0., 0.])


##### 张量的拼接

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

##### 算术运算

矩阵乘法

In [ ]:
y1 = tensor @ tensor.T
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

y3 = torch.rand_like(tensor)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

逐元相乘

In [ ]:
z1 = tensor * tensor
print(z1)

z2 = tensor.mul(tensor)
print(z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z3)

单元素张量

可以使用 `item()` 方法将张量转换为 Python 数值

In [10]:
agg = tensor.sum()
print(agg)

agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(16.)
16.0 <class 'float'>


In-place 操作

In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

与 numpy 之间的转换

In [22]:
t = torch.ones(5)
print(f"t:{t}")
n = t.numpy()
print(f"n:{n}")

t.add_(1)

print(f"t:{t}")
print(f"n:{n}")


t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]
t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


numpy 数组到张量

In [21]:
n = np.ones(5)
t = torch.from_numpy(n)

print(t)

np.add(n, 1, out=n)
print(f"t:{t}")

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### 计算图

#### 可视化计算图

In [27]:
from torchviz import make_dot

A = torch.randn(10, 10, requires_grad=True)
b = torch.randn(10, requires_grad=True)
c = torch.randn(1, requires_grad=True)
x = torch.randn(10, requires_grad=True)

result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

dot = make_dot(result, params={'A': A, 'b': b, "c": c, 'x': x})

dot.render('expression', format='png', cleanup=True, view=False)

'expression.png'