In [3]:
import numpy as np

In [ ]:
# 创建ndarray数组
arr = np.array([2,4,6,8,10],float)
arr

In [13]:
# 三维数组，每个数组分别是一个元组
a = np.array([(1,4,6),(2,5,7),(3,6,9)])
a

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 9]])

In [11]:
# 4行5列的0数组数据类型float32
a1 = np.zeros((4,5),dtype=np.float32)
a1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [17]:
# 等差数列 左闭右开
a2 = np.arange(1,10,0.5)
a2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [19]:
# one-hot编码 (4 * 4 的单位矩阵，对角线为1，其他为0)
a3 = np.eye(4)
a3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
# 模型运算参数初始值，10个维度的随机值，0-1范围 ， 均匀分布的随机数
a4 = np.random.random(10)
a4

array([0.60978013, 0.8444086 , 0.1930087 , 0.24776652, 0.99238868,
       0.24582662, 0.56692405, 0.64523231, 0.27398492, 0.16301272])

In [25]:
# 模型运算参数初始值, 正态分布（高斯分布）的随机数,均值=0，标准差=0.2
a5 = np.random.normal(0,0.2,10)
a5

array([-0.07942029, -0.01526367,  0.16352615,  0.2688252 , -0.13734071,
        0.01039792,  0.28720485,  0.10773415,  0.17866335, -0.39691472])

In [35]:
# 4行 * 3列 矩阵，取第1行，第2列 （共0-3行，0-2列）
a6 = np.array([(1,4,6),(2,5,7),(3,6,9),(0,10,11)])
print(a6[1,])
print(a6[:,2])

[2 5 7]
[ 6  7  9 11]


In [55]:
# 遍历矩阵元素，i,j,k 的个数要和每个元组的个数一致
a7 = np.array([(1,4,6),(2,5,7),(3,6,9),(0,10,11)])
# i,j,k = a7[0]
# print(i,j,k)
for i,j,k in a7:
    print(i,j,k)

1 4 6
2 5 7
3 6 9
0 10 11


In [57]:
# 数组属性 维度等
a8 = np.array([(1,4,6),(2,5,7),(3,6,9),(0,10,11)])
print("ndim:", a8.ndim)
print("shape:", a8.shape)
print("size", a8.size)
print("dtype", a8.dtype)

ndim: 2
shape: (4, 3)
size 12
dtype int64


In [67]:
print(12 in a8)

False


In [73]:
# 从1-13（不包含13）的等差数列，步长默认为 1
a9 = np.arange(1,13)
print(a9)
print(a9.shape)

a9 = a9.reshape(3,4,1)  # 维度大小乘积 == 元素个数
print(a9)

print(a9.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
(3, 4, 1)


In [77]:
# 转置
print(a8)
a8 = a8.T
print(a8)

[[ 1  4  6]
 [ 2  5  7]
 [ 3  6  9]
 [ 0 10 11]]
[[ 1  2  3  0]
 [ 4  5  6 10]
 [ 6  7  9 11]]


In [81]:
# 展平为一维数组
a8 = a8.flatten()
print(a8)

[ 1  2  3  0  4  5  6 10  6  7  9 11]


In [99]:
# 添加一个新的轴（维度）,非常常用
a8 = np.array([(1,4,6),(2,5,7),(3,6,9),(0,10,11)])
a8 = a8[:,:,np.newaxis]
print(a8.shape)
print(a8)

(4, 3, 1)
[[[ 1]
  [ 4]
  [ 6]]

 [[ 2]
  [ 5]
  [ 7]]

 [[ 3]
  [ 6]
  [ 9]]

 [[ 0]
  [10]
  [11]]]


In [101]:
a = np.ones((3,3))
b = np.array([(-1,1,0),(-1,1,0),(-1,0,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[-1  1  0]
 [-1  1  0]
 [-1  0  1]]

[[0. 2. 1.]
 [0. 2. 1.]
 [0. 1. 2.]]

[[2. 0. 1.]
 [2. 0. 1.]
 [2. 1. 0.]]


In [103]:
# 元素之和
a.sum()

np.float64(9.0)

In [107]:
# 所有元素的乘积
a.prod()

np.float64(1.0)

In [ ]:
# 数组，矩阵、维度
# 数组、矩阵  ： 数据组织结构形式
# 维度： 通讯地址

In [111]:
a = np.array([9,7,5,3,1])
print("mean:",a.mean()) # 均值
print("var:", a.var())  # 方差
print("std:", a.std())  # 标准差

mean: 5.0
var: 8.0
std: 2.8284271247461903


In [113]:
a = np.array([1.02, 7.8, 3.9])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引
print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入，“round to nearest integer”的缩写，四舍五入到最近的整数

argmax: 1
argmin: 0
ceil: [2. 8. 4.]
floor: [1. 7. 3.]
rint: [1. 8. 4.]


In [115]:
a = np.array([6,3,12,8,45,9,48])
a.sort()  # 排序
a

array([ 3,  6,  8,  9, 12, 45, 48])

In [123]:
# 矩阵乘法和逐元素相乘的多种实现方式
import torch
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)
print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor) # 一个和tensor相似的张量，值随机
torch.matmul(tensor, tensor.T, out=y3)  # 矩阵相乘，数据存放在y3中
print(y3)
# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32
tensor([[ 30.,  70., 110., 150.],
        [ 70., 174., 278., 382.],
        [110., 278., 446., 614.],
        [150., 382., 614., 846.]])


tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])

In [125]:
a9 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[4,5,6],[7,8,9]])
a9 * b9

array([[ 4, 10, 18],
       [28, 40, 54]])

In [5]:
# 定义两个简单的矩阵
m1 = np.array([[1, 2], [4, 8]], dtype=np.float32)
m2 = np.array([[3, 6], [5, 10]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [4. 8.]]
矩阵 2:
[[ 3.  6.]
 [ 5. 10.]]
使用 np.dot 得到的矩阵乘法结果:
[[ 13.  26.]
 [ 52. 104.]]
使用 @ 运算符得到的矩阵乘法结果:
[[ 13.  26.]
 [ 52. 104.]]
1.0 * 3.0 = 3.0
2.0 * 5.0 = 10.0
结果矩阵[1,1]:13.0

1.0 * 6.0 = 6.0
2.0 * 10.0 = 20.0
结果矩阵[1,2]:26.0

4.0 * 3.0 = 12.0
8.0 * 5.0 = 40.0
结果矩阵[2,1]:52.0

4.0 * 6.0 = 24.0
8.0 * 10.0 = 80.0
结果矩阵[2,2]:104.0

手动推演结果:
[[ 13.  26.]
 [ 52. 104.]]


In [7]:
np.save('result.npy',manual_result)

In [9]:
result_np = np.load('result.npy')
result_np

array([[ 13.,  26.],
       [ 52., 104.]], dtype=float32)

In [11]:
a = np.array([1,12,13])
b = np.array([4,15,16])
a + b

array([ 5, 27, 29])

In [21]:
a = np.array([(1,1), (2,2), (3,3), (4,4)])  # shape(4,2)
b = np.array([-1,-2])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,-2],[-1,2],[-1,2],[-1,2]]
print(b.shape)
a + b

(2,)


array([[ 0, -1],
       [ 1,  0],
       [ 2,  1],
       [ 3,  2]])