In [1]:
import torch
data = torch.tensor([[1,5],[2,8]], dtype=torch.float32)
data

tensor([[1., 5.],
        [2., 8.]])

In [3]:
import numpy as np
np_array = np.array([[1,5],[2,8]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 5],
        [2, 8]])

In [5]:
data2.dtype

torch.int64

In [7]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.7492, 0.6759],
        [0.6448, 0.0173]])

In [11]:
shape = (3,4,)
rand_tensor = torch.rand(shape)  #随机生成
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2544, 0.0962, 0.6635, 0.0509],
        [0.4577, 0.0638, 0.1960, 0.5788],
        [0.1589, 0.1396, 0.2234, 0.3906]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [15]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,4, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size

# 均匀分布
print(torch.rand(5,4))
# 标准正态分布
print(torch.randn(5,4))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,4)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=7))

torch.Size([5, 4])
tensor([[0.7906, 0.4485, 0.0013, 0.7930],
        [0.2730, 0.7670, 0.8893, 0.3897],
        [0.2857, 0.6027, 0.2052, 0.5629],
        [0.2915, 0.3232, 0.3799, 0.6186],
        [0.0423, 0.3334, 0.3582, 0.2934]])
tensor([[ 0.3454,  0.4936,  1.1182,  0.1088],
        [-2.1822,  0.6124,  2.2167,  0.3496],
        [ 0.3112,  0.3493,  1.0148,  0.6740],
        [-0.0736, -0.4267,  0.6606,  0.0205],
        [ 0.3668, -0.2827, -0.4817,  1.1950]])
tensor([[-0.8686, -0.2047, -0.8359,  1.1987],
        [-0.4706, -1.4949,  0.0501, -1.2105],
        [-0.2238,  1.4845, -0.6870,  0.1249],
        [ 0.8772,  1.5240, -0.7408, -0.5223],
        [ 0.7034,  1.0125, -1.0057, -0.0570]])
tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000])


In [17]:
tensor = torch.rand(5,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([5, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [19]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)
print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.9046, 0.6535, 0.2259, 0.3493],
        [0.6062, 0.7489, 0.1662, 0.8256],
        [0.4729, 0.0231, 0.8086, 0.3342],
        [0.6636, 0.9437, 0.5752, 0.5544],
        [0.2144, 0.2374, 0.8352, 0.8527]])
cpu
tensor([[0.9046, 0.6535, 0.2259, 0.3493],
        [0.6062, 0.7489, 0.1662, 0.8256],
        [0.4729, 0.0231, 0.8086, 0.3342],
        [0.6636, 0.9437, 0.5752, 0.5544],
        [0.2144, 0.2374, 0.8352, 0.8527]])
cpu


In [21]:
tensor = torch.ones(3, 3)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1.])
First column:  tensor([1., 1., 1.])
Last column: tensor([1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


In [25]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)  #3行9列

tensor([[3., 0., 3., 3., 0., 3., 3., 0., 3.],
        [3., 0., 3., 3., 0., 3., 3., 0., 3.],
        [3., 0., 3., 3., 0., 3., 3., 0., 3.]])
torch.Size([3, 9])


In [43]:
import torch
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)

# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])


In [47]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

136.0 <class 'float'>


In [49]:
np_arr = z1.numpy()
np_arr

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.],
       [ 81., 100., 121., 144.],
       [169., 196., 225., 256.]], dtype=float32)

In [59]:
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)
print(tensor, "\n")
tensor.add_(7)
print(tensor)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]) 

tensor([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]])


In [61]:
tensor

tensor([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]])

In [2]:
import torch
from torchviz import make_dot

In [3]:
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(8, 8,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(8,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(8, requires_grad=True)

# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})

C:\Users\jianm\AppData\Local\Temp\ipykernel_13752\2271837825.py:8: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:3729.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


In [4]:
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

'expression.png'