In [109]:
import numpy as np

a = [1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [129]:
a1 = np.array([1,2,3], float)
a1


array([1., 2., 3.])

In [130]:
a2 = np.array([(1,2,3), (4,5,6), (7,8,9)])
a2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
# 特殊数组创建
a3 = np.zeros((2,3), dtype = float)
a3


array([[0., 0., 0.],
       [0., 0., 0.]])

In [132]:
# 创建一个全为1的数组
a4 =  np.ones((3, 3))
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [133]:
# 等差数列
a5 = np.arange(1, 5, 0.5)
a5


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [134]:
# 单位矩阵
a6 = np.eye(3)
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [135]:
# ⽣成随机数组，指定其均值为 0，标准差为 0.1：
np.random.normal(0, 0.1, 5)

array([-0.03147279, -0.04196463, -0.13094255,  0.01513747,  0.12733112])

In [136]:
# numpy数组访问
a = np.array([(1,2), (3,4), (5,6)])
print(a)
print("------------------")
print(a[1:])
print("------------------")
print(a[:1])
print("------------------")
print(a[:,:1])


[[1 2]
 [3 4]
 [5 6]]
------------------
[[3 4]
 [5 6]]
------------------
[[1 2]]
------------------
[[1]
 [3]
 [5]]


In [137]:
# NumPy 数组的遍历
a = np.array([1,2,3])
for i in a:
    print(i)

print("------------------")
# 多维数组的遍历：
a2 = np.array([(1,2), (3,4), (5,6)])
for i,j in a2:
    print(i*j)


1
2
3
------------------
2
12
30


In [138]:
# NumPy 数组的常⽤属性
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int32


In [139]:
# NumPy 数组的基本操作
# in :检测数值是否在数组中
a = np.array([(1,2), (3,4)])
print(3 in a)
print(5 in a)

print("------------------")

# reshape : 数组的重排列
ar = np.zeros([2,3,4])
print(ar)
ar.reshape(24)
print("------------------")

# tanspose ：转置 (可以直接.T）
at = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(at)
print(at.transpose())
print("------------------")
at1 = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(at1)
print(at1.T)
print("------------------")

# flatten : 把多维数组转换为⼀维数组
af = np.array([(1,21), (32,4), (54,68)])
print("af.flatten()=",af.flatten())
print("------------------")

# newaxis : 增加维度
an = np.array([(1,2,3), (4,5,6), (7,8,9)])
an = an[:,:,np.newaxis]
print(an.shape)



True
False
------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
------------------
af.flatten()= [ 1 21 32  4 54 68]
------------------
(3, 3, 1)


In [140]:
# NumPy 数组的数学操作
a = np.ones((2,2))
b = np.array([(-1,2),(-1,3)])
print(a)
print("------------------")
print(b)
print("------------------")
print(a+b)
print("------------------")
print(a-b)
print("------------------")
print(a*b)
print("------------------")
print(a/b)
print("------------------")


[[1. 1.]
 [1. 1.]]
------------------
[[-1  2]
 [-1  3]]
------------------
[[0. 3.]
 [0. 4.]]
------------------
[[ 2. -1.]
 [ 2. -2.]]
------------------
[[-1.  2.]
 [-1.  3.]]
------------------
[[-1.          0.5       ]
 [-1.          0.33333333]]
------------------


In [141]:
# 求和、求积
a = np.array([1,2,1])
print(a.sum())

print(a.prod())

4
2


In [142]:
# 平均数，⽅差，标准差，最⼤值，最⼩值
a = np.array([5,3,1])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

print("max:", a.max())
print("min:", a.min())

mean: 3.0
var: 2.6666666666666665
std: 1.632993161855452
max: 5
min: 1


In [143]:
# 最⼤与最⼩值对应的索引值：argmax,argmin
# 取元素值上限，下限
a = np.array([1.2, 3.8, 4.9])
print("最⼤值索引 argmax:", a.argmax())
print("最小值索引 argmin:", a.argmin())
print("向上取整 ceil:", np.ceil(a))
print("向下取整 floor:", np.floor(a))
print("四舍五入 rint:", np.rint(a))

最⼤值索引 argmax: 2
最小值索引 argmin: 0
向上取整 ceil: [2. 4. 5.]
向下取整 floor: [1. 3. 4.]
四舍五入 rint: [1. 4. 5.]


In [144]:
# 排序
a = np.array([16,31,12,28,22,31,48])
a.sort()
print("排序 ",a)

排序  [12 16 22 28 31 31 48]


In [145]:
# NumPy 线性代数
# dot 矩阵乘法
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
# 使⽤ np.dot 进⾏矩阵乘法
result_dot = np.dot(m1, m2)
print("使⽤ np.dot 得到的矩阵乘法结果 ",result_dot)
# 使⽤ @ 运算符进⾏矩阵乘法
result_at = m1 @ m2
print("使⽤ @ 运算符进⾏矩阵乘法 ",result_at)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使⽤ np.dot 得到的矩阵乘法结果  [[19. 22.]
 [43. 50.]]
使⽤ @ 运算符进⾏矩阵乘法  [[19. 22.]
 [43. 50.]]


In [146]:
# 全零矩阵储⼿动推演
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
# 外层循环：遍历 matrix1 的每⼀⾏
# i 表⽰结果矩阵的⾏索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每⼀列 j 表⽰结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i ⾏与 matrix2 的第 j 列对应元素的乘积之和; k 表⽰参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i ⾏第 k 列元素与 matrix2 的第 k ⾏第 j 列元素相乘，并累
            manual_result[i, j] += m1[i, k] * m2[k, j]
            # 打印当前位置计算完成后的结果
            print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("⼿动推演结果:" , manual_result)

1.0 * 5.0 = 5.0
结果矩阵[1,1]:5.0

2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
结果矩阵[1,2]:6.0

2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
结果矩阵[2,1]:15.0

4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
结果矩阵[2,2]:18.0

4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

⼿动推演结果: [[19. 22.]
 [43. 50.]]


In [147]:
# NumPy ⼴播机制
# ⼴播 (Broadcast) 是 numpy 对不同形状 (shape) 的数组进⾏数值计算的⽅式，对数组的算术运算通常在相应的元素上进⾏。
# 如果两个数组 a 和 b 形状相同，即满⾜a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的⻓度相同

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print("------------------")

# 当运算中的 2 个数组的形状不同时，numpy 将⾃动触发⼴播机制
a1 = np.array([(1,2), (2,2), (3,3), (4,4)]) # shape(4,2)
b1 = np.array([-1,1]) # shape(2)-> shape(1,2) -> shape(4,2) [ -1,1],[-1,1],[-1,1],[-1
a1 + b1
print(a1 + b1)
print("------------------")


[5 7 9]
------------------
[[0 3]
 [1 3]
 [2 4]
 [3 5]]
------------------
