In [18]:
import numpy as np


a = [1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [21]:
a1 = np.array([1,2,3], float)
a1


array([1., 2., 3.])

In [22]:
a2 = np.array([(1,2,3), (4,5,6), (7,8,9)])
a2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
# 特殊数组创建
a3 = np.zeros((2,3), dtype = float)
a3


array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# 创建一个全为1的数组
a4 =  np.ones((3, 3))
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
# 等差数列
a5 = np.arange(1, 5, 0.5)
a5


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [38]:
# 单位矩阵
a6 = np.eye(3)
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
# ⽣成随机数组，指定其均值为 0，标准差为 0.1：
np.random.normal(0, 0.1, 5)

array([-0.14246891, -0.02941114,  0.01220402,  0.06615381, -0.08200752])

In [48]:
# numpy数组访问
a = np.array([(1,2), (3,4), (5,6)])
print(a)
print("------------------")
print(a[1:])
print("------------------")
print(a[:1])
print("------------------")
print(a[:,:1])


[[1 2]
 [3 4]
 [5 6]]
------------------
[[3 4]
 [5 6]]
------------------
[[1 2]]
------------------
[[1]
 [3]
 [5]]


In [56]:
# NumPy 数组的遍历
a = np.array([1,2,3])
for i in a:
    print(i)

print("------------------")
# 多维数组的遍历：
a2 = np.array([(1,2), (3,4), (5,6)])
for i,j in a2:
    print(i*j)


1
2
3
------------------
2
12
30


In [57]:
# NumPy 数组的常⽤属性
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int32


In [75]:
# NumPy 数组的基本操作
# in :检测数值是否在数组中
a = np.array([(1,2), (3,4)])
print(3 in a)
print(5 in a)

print("------------------")

# reshape : 数组的重排列
ar = np.zeros([2,3,4])
print(ar)
ar.reshape(24)
print("------------------")

# tanspose ：转置 (可以直接.T）
at = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(at)
print(at.transpose())
print("------------------")
at1 = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(at1)
print(at1.T)
print("------------------")

# flatten : 把多维数组转换为⼀维数组
af = np.array([(1,21), (32,4), (54,68)])
print("af.flatten()=",af.flatten())
print("------------------")

# newaxis : 增加维度
an = np.array([(1,2,3), (4,5,6), (7,8,9)])
an = an[:,:,np.newaxis]
print(an.shape)



True
False
------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
------------------
af.flatten()= [ 1 21 32  4 54 68]
------------------
(3, 3, 1)


In [84]:
# NumPy 数组的数学操作
a = np.ones((2,2))
b = np.array([(-1,2),(-1,3)])
print(a)
print("------------------")
print(b)
print("------------------")
print(a+b)
print("------------------")
print(a-b)
print("------------------")
print(a*b)
print("------------------")
print(a/b)
print("------------------")


[[1. 1.]
 [1. 1.]]
------------------
[[-1  2]
 [-1  3]]
------------------
[[0. 3.]
 [0. 4.]]
------------------
[[ 2. -1.]
 [ 2. -2.]]
------------------
[[-1.  2.]
 [-1.  3.]]
------------------
[[-1.          0.5       ]
 [-1.          0.33333333]]
------------------


In [86]:
# 求和、求积
a = np.array([1,2,1])
print(a.sum())

print(a.prod())

4
2


In [87]:
# 平均数，⽅差，标准差，最⼤值，最⼩值
a = np.array([5,3,1])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

print("max:", a.max())
print("min:", a.min())

mean: 3.0
var: 2.6666666666666665
std: 1.632993161855452
max: 5
min: 1


In [93]:
# 最⼤与最⼩值对应的索引值：argmax,argmin
# 取元素值上限，下限
a = np.array([1.2, 3.8, 4.9])
print("最⼤值索引 argmax:", a.argmax())
print("最小值索引 argmin:", a.argmin())
print("向上取整 ceil:", np.ceil(a))
print("向下取整 floor:", np.floor(a))
print("四舍五入 rint:", np.rint(a))

最⼤值索引 argmax: 2
最小值索引 argmin: 0
向上取整 ceil: [2. 4. 5.]
向下取整 floor: [1. 3. 4.]
四舍五入 rint: [1. 4. 5.]


In [97]:
# 排序
a = np.array([16,31,12,28,22,31,48])
a.sort()
print("排序 ",a)

排序  [12 16 22 28 31 31 48]
