In [2]:
import numpy as np

指定数据集生成
##
dtType可选参数指定数据类型

In [5]:
_ = np.array([1, 2], dtype=float)
_

array([1., 2.])

指定生成多维

In [6]:
_ = np.array([[1, 2, 3], [2, 3, 4]])
_

array([[1, 2, 3],
       [2, 3, 4]])

构建几行几列的值都为1的矩阵

In [9]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

构建几行几列的值都为0的矩阵

In [7]:
a1 = np.zeros((2, 3))
a1

array([[0., 0., 0.],
       [0., 0., 0.]])

生成等差数据 前闭后开

In [11]:
_ = np.arange(1, 5, 1)
_

array([1, 2, 3, 4])

添加单位矩阵 对角线都为1

In [13]:
_ = np.eye(5)
_

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

生成[0,1)范围内指定数量的随机数据据

In [20]:
_ = np.random.random(4)
_

array([0.70796837, 0.77421071, 0.65362806, 0.62886411])

生成均值为1 标准差为1指定数量的随机数据:均值不为1是数据量足够大时趋近于1

In [24]:
_ = np.random.normal(0, 1, 4)
_

array([ 2.03796257,  0.66220711,  0.92722308, -0.09519438])

切片

In [28]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a4 = a2[0]
print(a4)
a3 = a2[1:, 1:]
a3

[1 2 3]


array([[5, 6],
       [8, 9]])

遍历

In [30]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for i, j, k in a2:
    print(i * j * k)

6
120
504


In [4]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'数据的维度{a2.ndim}')
print(f'数据的大小{a2.shape}')
print(f'数据的个数{a2.size}')
print(f'数据的类型{a2.dtype}')

数据的维度2
数据的大小(3, 3)
数据的个数9
数据的类型int32


均值 (1,2,3) a=(1+2+3)/3
方差 b=((1-a)^2 +(2-a)^2+(3-a)^2)/3
标准差c=根号b

In [5]:
a4 = np.mean(a2)
a5 = np.var(a2)
a6 = np.std(a2)
print(f'均值{a4}')
print(f'方差{a5}')
print(f'标准差{a6}')

均值5.0
方差6.666666666666667
标准差2.581988897471611


判断元素是否在数组中 

In [7]:
print(10 in np.arange(10))
print(1 in np.arange(10))

False
True


## 向上取整
## 向下取整
## 四舍五入
## 最大值的索引
## 最小值的索引
## 最大值的索引沿x轴
## 最小值的索引沿x轴
## 最大值的索引沿y轴
## 最小值的索引沿y轴

In [55]:
a2 = np.array([(1.1, 2.2),
               (2.6, 3.3,),
               (1.1, 3.9)])
a7 = np.ceil(a2)
a8 = np.floor(a2)
a9 = np.rint(a2)
a10 = np.argmax(a2)
a11 = np.argmin(a2)
a12 = np.argmax(a2, axis=0)
a13 = np.argmin(a2, axis=0)
a14 = np.argmax(a2, axis=1)
a15 = np.argmin(a2, axis=1)
print(a7)
print(a8)
print(a9)
print(a10)
print(a11)
print(a12)
print(a13)
print(a14)
print(a15)

[[2. 3.]
 [3. 4.]
 [2. 4.]]
[[1. 2.]
 [2. 3.]
 [1. 3.]]
[[1. 2.]
 [3. 3.]
 [1. 4.]]
5
0
[1 2]
[0 0]
[1 1 1]
[0 0 0]


数组排序

In [57]:
_ = np.array([(1, 5, 2, 6, 3, 7, 4, 8)])
_.sort()
_

array([[1, 2, 3, 4, 5, 6, 7, 8]])

# 数组结构重排序
## T和transpose 转置行转列
## reshape 返回新的内容 数据数量不一致时报错
## resize 修改原内容  数据数量不一致时填充或截取
## 多维转一维


In [29]:
a2 = np.array([[1, 2, 3, 5], [4, 5, 6, 6]])
print(a2.T)
print(a2.transpose())
a2.resize((2, 4))
print(a2)
# print(a3)
print('--------------')
print(a2.reshape(4, 2))
print('--------------')
print(a2.flatten())

[[1 4]
 [2 5]
 [3 6]
 [5 6]]
[[1 2 3 5]
 [4 5 6 6]]
--------------
[[1 2]
 [3 5]
 [4 5]
 [6 6]]
--------------
[1 2 3 5 4 5 6 6]


增加维度

In [38]:
_ = np.ones((3, 4), dtype=int)
print(_)
print(_.shape)
_ = _[:, :, np.newaxis]
print(_.shape)
print(_)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)
(3, 4, 1)
[[[1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]]]


数据运算
## 加法  数组间的每个位置数之和
## 减法  数组间的每个位置数之差
## 乘法  数组间的每个位置数之积
## 除法  数组间的每个位置数之除

In [46]:
a1 = np.ones((3, 2), dtype=int)
a2 = np.array([(1, 1), (2, 2), (3, 3)])
print(a1)
print('--------')
print(a2)
print('--------')
print(a1 + a2)
print('--------')
print(a1 - a2)
print('--------')
print(a1 * a2)
print('--------')
print(a1 / a2)

[[1 1]
 [1 1]
 [1 1]]
--------
[[1 1]
 [2 2]
 [3 3]]
--------
[[2 2]
 [3 3]
 [4 4]]
--------
[[ 0  0]
 [-1 -1]
 [-2 -2]]
--------
[[1 1]
 [2 2]
 [3 3]]
--------
[[1.         1.        ]
 [0.5        0.5       ]
 [0.33333333 0.33333333]]


数组求和/求积

In [48]:
_ = np.array([(3, 4), (5, 6)])
print(_.sum())
print(_.prod())

18
360


线代
## np.dot和@ 矩阵乘法 [1,1]=1x7+2x4 [1,2]=1x8+2x5 [2,1]=4x7+5x4 [2,2]=4x8+5x5

In [58]:
b1 = np.array([[1, 2],
               [4, 5]])
b2 = np.array([[7, 8],
               [4, 5]])
b4 = np.dot(b1, b2)
b5 = b1 @ b2
print(b4)
print(b5)

[[15 18]
 [48 57]]
[[15 18]
 [48 57]]


In [61]:
_ = np.array([(1, 2, 3)])
np.save('numpy/data.npy', _)
_ = np.load('numpy/data.npy')
print(_)
np.savetxt('numpy/data.txt', _)
_ = np.loadtxt('numpy/data.txt')
print(_)

[[1 2 3]]
[1. 2. 3.]


广播 形状不同时自动触发升维
## c2->[-1.2],[-1,2] 升维 拷贝自身 低维->高维

In [62]:
c1 = np.array([(1, 1), (2, 2)])
c2 = np.array([-1, 2])
c3 = c1 + c2
c3

array([[0, 3],
       [1, 4]])

T转置 行转列


In [4]:
c1 = np.array([(1, 3), (2, 4)])
c4 = c1.trace()
print(c1)
print(c4)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


生成三维数组

In [5]:
d1 = np.zeros([2, 3, 4])
d1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])