创建一个未初始化的张量 不包含任何确切的值

In [1]:
import torch

a = torch.empty(5, 4)
a

tensor([[ 0.0000e+00,  0.0000e+00, -3.0347e-36,  6.1237e-43],
        [ 1.1771e-43,  0.0000e+00,  1.3032e-43,  1.8037e+28],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.4013e-44,  0.0000e+00,  1.5414e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.4013e-44,  0.0000e+00]])

创建一个随机数的张量 高斯分布 均值为0 方差为1
#
torch.rand(4, 2)：生成的是[0, 1)区间内均匀分布的随机数。
#
torch.randn(4, 2)：生成的是均值为0，方差为1的标准正态分布随机数。

In [4]:
a1 = torch.randn(4, 2, device="cuda")
a1

tensor([[-1.0591,  0.8531],
        [ 1.9666, -0.0130],
        [ 1.1879, -0.5566],
        [ 0.0860,  0.5483]], device='cuda:0')

*全矩阵为0且指定数据元素的类型为long

In [11]:
a2 = torch.zeros((5, 3), dtype=torch.long)
a2

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

*全矩阵为1且指定数据元素的类型为long

In [12]:
a2 = torch.ones((5, 3), dtype=torch.long)
a2

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

*通过数据创建

In [6]:
a3 = torch.tensor([2.5, 3.5])
a3

tensor([2.5000, 3.5000])

通过已有的张量创建相同尺寸的新张量
#
new_ones:矩阵内容全为1 new_ones可重新指定大小
randn_like:随机数 高斯分配 不可指定
# 
a2与a4不会存在数据上的内容关联 存放地址会保持一致 
#
可选按照a2的矩阵大小和数据类型生成
a2.new_ones(a2.size()),dtype=torch.double)
randn_like会根据模板中的size生成均匀

In [10]:
a4 = a2.new_ones(2, 2, dtype=torch.double)
print(a4)
a4 = torch.randn_like(a2, dtype=torch.float)
print(a4)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[ 2.2718,  0.1945,  0.8392],
        [-1.3175,  0.1312, -0.4787],
        [-0.3626, -0.7453,  0.0386],
        [-1.2123,  0.7305, -0.8259],
        [-0.6018,  0.4820,  0.9370]])


根据其他的张量创建类似的张量，保留形状和属性

In [15]:
_ = torch.ones_like(a2)
print(_)
_ = torch.zeros_like(a2)
print('---------')
print(_)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
---------
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## rand均匀分布 
## randn标准正态分布
## normal离散正态分布 mean均值 std标准差
## linspace[start,end]等差数列

In [19]:
_ = torch.rand(2, 3)
print(_)
_ = torch.randn(2, 3)
print(_)
_ = torch.normal(mean=.0, std=1.1, size=(2, 3))
print(_)

_ = torch.linspace(start=1, end=20, steps=10)
print(_)

tensor([[0.0555, 0.6121, 0.4497],
        [0.0522, 0.6280, 0.3700]])
tensor([[-1.0699, -0.0926,  0.0834],
        [ 0.6546, -0.8661,  0.0937]])
tensor([[-1.8292, -0.3627, -0.0715],
        [-1.2439,  2.3822, -1.5954]])
tensor([ 1.0000,  3.1111,  5.2222,  7.3333,  9.4444, 11.5556, 13.6667, 15.7778,
        17.8889, 20.0000])


张量属性

In [21]:
_ = torch.ones((2, 3))
print(f'尺寸{_.size()}')
print(f'尺寸{_.shape}')
print(f'数据类型{_.dtype}')
print(f'张量位置{_.device}')

尺寸torch.Size([2, 3])
尺寸torch.Size([2, 3])
数据类型torch.float32
张量位置cpu


*view改变张量形状 view(总数)为平铺 view(-1,x) -1代表行数为total/x

In [14]:
a5 = torch.rand(4, 4)
a6 = a5.view(16)
print(a5)
print(a6)

tensor([[0.9708, 0.2777, 0.6909, 0.1032],
        [0.5955, 0.3348, 0.5300, 0.7151],
        [0.3286, 0.5423, 0.7002, 0.8647],
        [0.3275, 0.1470, 0.3169, 0.7049]])
tensor([0.9708, 0.2777, 0.6909, 0.1032, 0.5955, 0.3348, 0.5300, 0.7151, 0.3286,
        0.5423, 0.7002, 0.8647, 0.3275, 0.1470, 0.3169, 0.7049])


*torch中只有一个值时可以使用取出 会以python number形式输出;一般用于损失值

In [15]:
a7 = torch.rand(1)
print(a7.item())

0.14267945289611816


torch.tolist转列表

In [18]:
a8 = torch.rand(2, 2)
a9 = a8.tolist()
a9

[[0.40513527393341064, 0.9360982775688171],
 [0.837430477142334, 0.24525201320648193]]

*torch和numpy相互转换(除了ChartTensor)，共享底层内存空间。数据有着相同的物理地址

In [22]:
a10 = torch.ones(5)
a11 = a10.numpy()
a12 = torch.from_numpy(a11)
print(a10)
print(a11)
print(a12)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


张量索引和切片

In [28]:
_ = torch.rand(4, 4)
print(_)
print(f'第一行{_[0]}')
print(f'第一列{_[:, 0]}')
print(f'最后一列{_[:, -1]}')

tensor([[0.8589, 0.0458, 0.2084, 0.7922],
        [0.2908, 0.3417, 0.0392, 0.6765],
        [0.8436, 0.7635, 0.0838, 0.8913],
        [0.9059, 0.3328, 0.1794, 0.1751]])
第一行tensor([0.8589, 0.0458, 0.2084, 0.7922])
第一列tensor([0.8589, 0.2908, 0.8436, 0.9059])
最后一列tensor([0.7922, 0.6765, 0.8913, 0.1751])


张量拼接
## cat拼接张量的维度需要保持一致且不会修改张量返回新的张量 dim表示按照那个维度进行拼接。在现有维度上拼接张量，指定的维度大小会增加，其他维度的大小保持不变
## stack 在新的维度上堆叠张量，会在最前面增加一个新的维度，其他维度的大小保持不变

In [43]:
_ = torch.randn((2, 3))
_1 = torch.cat([_, _], dim=0)
print('-------')
print(_1.shape)
_2 = torch.stack([_, _], dim=2)
print('-------')
print(_2.shape)

tensor([[ 0.4780, -0.1433,  1.6600],
        [ 1.9918,  0.3839, -0.5865]])
-------
torch.Size([4, 3])
-------
torch.Size([2, 3, 2])


张量运算:矩阵乘法

In [50]:
tensor1 = torch.tensor([[1, 2],
                        [3,4]])
print(tensor1)
print(tensor1.T)
tensor3 = tensor1 @ tensor1.T
tensor4 = tensor1.matmul(tensor1.T)
tensor5 = torch.ones_like(tensor1)
torch.matmul(tensor1, tensor1.T,out=tensor5)
print(tensor3)
print(tensor4)
print(tensor5)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 3],
        [2, 4]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])
tensor([[ 5, 11],
        [11, 25]])


矩阵元素相乘

In [52]:
tensor1 = torch.tensor([[1, 2],
                        [3,4]])
_=tensor1*tensor1
print(_)
_=torch.mul(tensor1,tensor1)
print(_)
_=torch.multiply(tensor1,tensor1)
print(_)
tensor2=torch.ones_like(tensor1)
torch.mul(tensor1,tensor1,out=tensor2)
print(tensor2)

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


矩阵In-place操做 所有的运算方法后有_.修改原张量(不建议使用)

In [49]:
tensor1 = torch.tensor([[1, 2],
                        [3,4]])
print(tensor1)
tensor1.add_(tensor1.new_tensor([1, 2]))
print(tensor1)

tensor([[1, 2],
        [3, 4]])
tensor([[2, 4],
        [4, 6]])


*torch.cuda.is_available判断是否可以使用gpu
#
tensor迁移至gpu时需填cuda或cuda:0 gpu迁移至cpu时指定cpu即可 相同设备下才可以进行操作符计算

In [53]:
import torch

a13 = torch.rand(1)
if torch.cuda.is_available():
    device = torch.device('cuda')
    print(device)
    a14 = torch.rand(1, device=device)
    a13 = a13.to(device)
    a15 = a13 + a14
    print(a15)
    print(a15.to('cpu', dtype=torch.double))

cuda
tensor([0.4497], device='cuda:0')
tensor([0.4497], dtype=torch.float64)


计算图

In [57]:
from torchviz import make_dot
a = torch.randn(5, 5, requires_grad=True)
b = torch.randn(5, requires_grad=True)
c = torch.randn(1, requires_grad=True)
x = torch.randn(5, requires_grad=True)
result = torch.multiply(a,x.T) + torch.multiply(b,x)+ c
dot=make_dot(result,params={'A':a,'b':b,'c':c,'x':x})
dot.render('a',format='png',cleanup=True,view=False)

'a.png'