pytorch 模型定义


In [16]:
import torch
# 简单实现
import torch.nn as nn
# X输入 shape(,784)
# 隐藏层 shape(784, 64) 参数矩阵
# 隐藏层 shape(64,) 偏置项bias
# 输出层 shape(64, 10) # 参数矩阵
# 输出层 shape(10,) 偏置bias
# Y输出 shape(,10) 10个类别

In [17]:
# 线性层
linear = nn.Linear(in_features=784,out_features=64, bias=True) # bias 默认是true
# 非线性(激活函数)
act = nn.Sigmoid()
# 输出层
linear2 = nn.Linear(in_features=64,out_features=10,bias=True)

# 模拟输入
x = torch.randn(10, 784) # 十个样本，784 个特征
out = linear(x)
out2 = act(out)
out3 = linear2(out2)
softmax = nn.Softmax(dim=1)
print(softmax(out3))

tensor([[0.0835, 0.0975, 0.1001, 0.0662, 0.1073, 0.1467, 0.1398, 0.0791, 0.0930,
         0.0868],
        [0.0895, 0.1007, 0.1034, 0.0611, 0.1198, 0.1339, 0.1360, 0.0866, 0.0871,
         0.0820],
        [0.0865, 0.1030, 0.0939, 0.0754, 0.1309, 0.1263, 0.1321, 0.0837, 0.0901,
         0.0782],
        [0.0890, 0.0942, 0.1001, 0.0687, 0.1169, 0.1286, 0.1465, 0.0750, 0.0994,
         0.0816],
        [0.0907, 0.0794, 0.0982, 0.0848, 0.1190, 0.1350, 0.1366, 0.0856, 0.0900,
         0.0805],
        [0.0836, 0.0858, 0.1029, 0.0738, 0.1255, 0.1291, 0.1400, 0.0896, 0.0898,
         0.0798],
        [0.0824, 0.0941, 0.0989, 0.0747, 0.1273, 0.1277, 0.1158, 0.0895, 0.0981,
         0.0914],
        [0.0874, 0.1098, 0.0869, 0.0800, 0.1376, 0.1161, 0.1266, 0.0879, 0.0852,
         0.0826],
        [0.0873, 0.0905, 0.1017, 0.0783, 0.1359, 0.1236, 0.1270, 0.0817, 0.0969,
         0.0771],
        [0.0859, 0.0969, 0.0951, 0.0696, 0.1462, 0.1399, 0.1183, 0.0855, 0.0861,
         0.0765]], grad_fn=<

In [18]:
# 模型定义, 所有机构串联在一起
model = nn.Sequential(
    nn.Linear(in_features=784,out_features=64),
    nn.Sigmoid(),
    nn.Linear(in_features=64,out_features=10)
)

In [19]:
# 定制损失函数
loss_fun = nn.CrossEntropyLoss() # 交叉熵损失

In [20]:
# 优化器
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
[param for param in model.parameters()]

[Parameter containing:
 tensor([[-0.0015,  0.0041,  0.0075,  ..., -0.0063, -0.0014,  0.0225],
         [-0.0102,  0.0229,  0.0131,  ..., -0.0299, -0.0239,  0.0263],
         [-0.0342,  0.0287, -0.0027,  ..., -0.0219, -0.0199, -0.0342],
         ...,
         [-0.0309, -0.0153, -0.0297,  ..., -0.0128,  0.0077, -0.0231],
         [-0.0239, -0.0177, -0.0235,  ...,  0.0098, -0.0313, -0.0123],
         [-0.0229,  0.0134,  0.0082,  ...,  0.0340, -0.0162, -0.0343]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0011,  0.0124, -0.0318,  0.0028,  0.0002, -0.0182, -0.0004, -0.0155,
         -0.0276,  0.0019,  0.0259,  0.0185, -0.0354,  0.0355, -0.0233,  0.0232,
         -0.0114,  0.0258,  0.0007,  0.0229,  0.0309,  0.0036, -0.0040,  0.0316,
         -0.0160,  0.0050,  0.0340, -0.0014, -0.0166,  0.0200, -0.0184, -0.0354,
          0.0316,  0.0151,  0.0166,  0.0188,  0.0099, -0.0289,  0.0319,  0.0106,
          0.0016, -0.0250, -0.0078,  0.0244,  0.0002,  0.0057, -0.0239, -0.0024