In [1]:
import numpy as np

In [2]:
a = [15, 12, 3]
b = np.array(a)
b

array([15, 12,  3])

In [3]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros((2, 3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [7]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.random(10)

array([0.81386081, 0.66026368, 0.53919384, 0.44226838, 0.23207257,
       0.39230172, 0.85517518, 0.50369856, 0.20732913, 0.92627919])

In [10]:
miu, sigma = 0, 0.1
np.random.normal(miu, sigma, 10)

array([ 0.1071061 , -0.14551396,  0.06610095, -0.03023483,  0.06661132,
       -0.20063237,  0.10907815,  0.10478288,  0.0219311 ,  0.18877029])

In [11]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a[0]

array([1, 2])

In [12]:
a[1:]

array([[3, 4],
       [5, 6]])

In [13]:
a[:, :1]

array([[1],
       [3],
       [5]])

In [14]:
a[1][1]

4

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [16]:
a = np.array([[1, 2], [4, 5]])
for i, j in a:
    print(i, j)

1 2
4 5


In [17]:
a = np.array([[1, 2], [4, 5]])
print("ndim: ", a.ndim)
print("shape: ", a.shape)
print("size: ", a.size)
print("dtype: ", a.dtype)

ndim:  2
shape:  (2, 2)
size:  4
dtype:  int32


In [18]:
a = np.array([[1, 2], [4, 5]])
print(3 in a)
print(4 in a)

False
True


In [19]:
a = np.zeros((2, 3, 4), dtype=int)
a

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [20]:
a.reshape(24)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [21]:
a = np.array([[1, 2], [4, 5]])
a.transpose()

array([[1, 4],
       [2, 5]])

In [22]:
a.T

array([[1, 4],
       [2, 5]])

In [23]:
a = np.array([[1, 2], [4, 5]])
a.flatten()

array([1, 2, 4, 5])

In [24]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [25]:
a = a[:, np.newaxis]
a

array([[1],
       [2],
       [3]])

In [26]:
a.shape

(3, 1)

In [27]:
a = np.ones((2, 2))
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)

[[1. 1.]
 [1. 1.]]
[[1 2]
 [3 4]]


In [28]:
a + b

array([[2., 3.],
       [4., 5.]])

In [29]:
a - b

array([[ 0., -1.],
       [-2., -3.]])

In [30]:
a * b

array([[1., 2.],
       [3., 4.]])

In [31]:
a / b

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ]])

In [32]:
a = np.array([[1, 2], [4, 5]])
a.sum()

12

In [33]:
a.prod()

40

In [34]:
a = np.array([[1, 2], [4, 5]])
print("mean: ", a.mean())
print("var: ", a.var())
print("std: ", a.std())
print("max: ", a.max())
print("min: ", a.min())

mean:  3.0
var:  2.5
std:  1.5811388300841898
max:  5
min:  1


In [35]:
a = np.array([[1.7, 2.5], [4.3, 5.1]])
print("argmax: ", a.argmax())
print("argmin: ", a.argmin())
print("ceil: ", np.ceil(a))
print("floor: ", np.floor(a))
print("rint: ", np.rint(a))
print("round: ", np.round(a))

argmax:  3
argmin:  0
ceil:  [[2. 3.]
 [5. 6.]]
floor:  [[1. 2.]
 [4. 5.]]
rint:  [[2. 2.]
 [4. 5.]]
round:  [[2. 2.]
 [4. 5.]]


In [36]:
a = np.array([15, 32, 45, 78, 12, 45, 78, 96, 45, 32])
a.sort()
a

array([12, 15, 32, 32, 45, 45, 45, 78, 78, 96])

In [37]:
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)

result_dot = np.dot(m1, m2)
result_at = m1 @ m2

print("矩阵1: ")
print(m1)
print("矩阵2: ")
print(m2)
print("点乘结果: ")
print(result_dot)
print("@结果: ")
print(result_at)


矩阵1: 
[[1. 2.]
 [3. 4.]]
矩阵2: 
[[5. 6.]
 [7. 8.]]
点乘结果: 
[[19. 22.]
 [43. 50.]]
@结果: 
[[19. 22.]
 [43. 50.]]


In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [39]:
a = np.array([[1, 1], [2, 2], [3, 3], [4, 4]])

b = np.array([-1, -1])

a + b


array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3]])

In [40]:
np.save("a.npy", a)

In [41]:
b = np.load("a.npy")
b

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])