In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [6]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.8697, 0.6894],
        [0.0472, 0.2308]]) 



In [7]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.8765, 0.2085, 0.5505],
        [0.0396, 0.7982, 0.9695]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [8]:
m = torch.ones(5, 3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

print(m.size())

torch.Size([5, 3])


In [9]:
torch.rand(5, 3)

tensor([[0.9459, 0.4560, 0.6215],
        [0.0827, 0.2497, 0.7854],
        [0.3505, 0.1594, 0.1207],
        [0.7878, 0.3065, 0.9716],
        [0.4367, 0.0665, 0.2674]])

In [10]:
torch.randn(5, 3)

tensor([[ 0.0763, -0.0978,  1.8819],
        [ 0.4698,  0.1311, -0.4334],
        [ 0.2988,  2.1428, -1.5268],
        [-0.7491,  0.2227,  0.0319],
        [ 0.0559, -0.0434,  1.0383]])

In [11]:
torch.normal(mean=0, std=2, size=(5, 3))

tensor([[ 0.6359,  0.9470,  0.0535],
        [-2.0055, -2.7047,  2.3331],
        [ 1.6784,  0.0851,  1.4933],
        [-0.8853,  2.6619, -1.8675],
        [ 0.2272,  2.0681, -1.3977]])

In [12]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [13]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [14]:
print(f"torch.cuda.is_available(): {torch.cuda.is_available()}")

if torch.cuda.is_available():
    tensor = tensor.to('cuda')



torch.cuda.is_available(): False


In [15]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])   
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)


First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [17]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.cat((a, b), dim=0)  # 输出：tensor([1,2,3,4,5,6]) [9,10](@ref)
result

tensor([1, 2, 3, 4, 5, 6])

In [18]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
result = torch.cat((a, b), dim=0)  # 输出形状为 (4, 2) [4,5](@ref)
result

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [19]:
result = torch.cat((a, b), dim=1)  # 输出形状为 (4, 2) [4,5](@ref)
result

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [20]:
t1 = torch.stack([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [21]:
a = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
b = torch.tensor([[10,20,30], [40,50,60], [70,80,90]])

In [22]:
c = torch.stack([a, b], dim=0)
print(c)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])


In [23]:
c = torch.stack([a, b], dim=1)
print(c)

tensor([[[ 1,  2,  3],
         [10, 20, 30]],

        [[ 4,  5,  6],
         [40, 50, 60]],

        [[ 7,  8,  9],
         [70, 80, 90]]])


In [24]:
c = torch.stack([a, b], dim=2)
print(c)

tensor([[[ 1, 10],
         [ 2, 20],
         [ 3, 30]],

        [[ 4, 40],
         [ 5, 50],
         [ 6, 60]],

        [[ 7, 70],
         [ 8, 80],
         [ 9, 90]]])


In [25]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [26]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print("y1: ", y1)
print("y2: ", y2)
print("y3: ", y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print("z1: ", z1)
print("z2: ", z2)
print("z3: ", z3)


y1:  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2:  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3:  tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1:  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2:  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3:  tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [27]:
agg = tensor.sum()
agg

tensor(12.)

In [28]:
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [29]:
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [30]:
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [31]:
t = torch.ones(5)

print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [32]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [33]:
n = np.ones(5)
t = torch.from_numpy(n) 

n += 1
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [34]:
import torch
from torchviz import make_dot

A = torch.randn(10, 10, requires_grad=True)
b = torch.randn(10, requires_grad=True)
c = torch.randn(1, requires_grad=True)
x = torch.randn(10, requires_grad=True)

result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

dot = make_dot(result, params={"A": A, "b": b, "c": c, "x": x})
dot.render("expression", format="png", cleanup=True, view=False)



'expression.png'