In [55]:
##测试模型
###2、前向计算
import numpy as np
def forward(x,theta,bias):
    z=np.dot(theta,x.T)+bias 
    ##sigmoid
    y_hat=1/(1+np.exp(-z))
    return y_hat

 


In [68]:
import pandas as pd 
import numpy as np
def predict(x):    
    pred=forward(x,theta,bias)[0]   
    return [1 if i>0.5 else 0 for i in pred]

##读取验证数据，theta、 bias
test_x = pd.read_csv("test_x.csv")   
test_y=pd.read_csv("test_y.csv") 
theta=pd.read_csv("theta.csv")
bias=pd.read_csv("bias.csv")


###把dataframe 转ndarray
test_x=test_x.values
test_y=test_y.values
theta=theta.values
bias=bias.values
print(f"test_y:{test_y}")
test_y=np.reshape(test_y,(1,20))
print(f"reshape test_y:{test_y}")

print(f"test_x:{test_x}")

pred=predict(test_x)
print(f"预测值：{pred}\n 真实值：{test_y},\n 相减{pred-test_y}")


print(np.sum(pred-test_y))

test_y:[[1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]]
reshape test_y:[[1 1 0 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 0 1]]
test_x:[[6.3 2.3 4.4 1.3]
 [5.8 2.6 4.  1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.4 1.7 0.2]
 [4.7 3.2 1.6 0.2]
 [5.2 3.4 1.4 0.2]
 [5.8 2.7 3.9 1.2]
 [5.7 2.8 4.5 1.3]
 [5.4 3.  4.5 1.5]
 [5.8 4.  1.2 0.2]
 [5.6 2.5 3.9 1.1]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [4.6 3.6 1.  0.2]
 [5.6 3.  4.5 1.5]
 [4.3 3.  1.1 0.1]
 [6.2 2.9 4.3 1.3]
 [5.  3.  1.6 0.2]
 [5.  3.5 1.6 0.6]
 [6.1 2.8 4.  1.3]]
预测值：[1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1]
 真实值：[[1 1 0 0 0 0 1 1 1 0 1 1 1 0 1 0 1 0 0 1]],
 相减[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
0
