In [1]:
import numpy as np

np.array([1,2])

array([1, 2])

In [2]:
import numpy as np
a = np.array([(1,2,3,4),(2,3,4,5),(3,4,5,6),(4,5,6,7)])
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [4]:
a1 = np.zeros((5,6), dtype=np.float16)
a1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float16)

In [5]:
a2 = np.arange(5,12, 0.3)
a2

array([ 5. ,  5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7,  8. ,
        8.3,  8.6,  8.9,  9.2,  9.5,  9.8, 10.1, 10.4, 10.7, 11. , 11.3,
       11.6, 11.9])

In [6]:
a3 = np.eye(5)
a3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
a4 = np.random.random(8)
a4

array([0.84681035, 0.35419564, 0.15537165, 0.52806011, 0.08616093,
       0.87506371, 0.16162223, 0.2165123 ])

In [9]:
a5 = np.random.normal(0, 0.2, 6)
a5

array([-0.13879199, -0.17226621, -0.14322486,  0.06222623,  0.13397236,
        0.32633628])

In [10]:
a6 = np.array([(1,2,3), (3,4,5), (5,6,7),(7,8,9)])
print(a6[:,2])

[3 5 7 9]


In [11]:
a7 = np.array([(1,2), (3,4), (5,6),(7,8)])
for i, j in a7:
    print(i,j)

1 2
3 4
5 6
7 8


In [13]:
a = np.array([(1,2,3,4), (4,5,6,7), (7,8,9,10),(10,11,12,13)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (4, 4)
size 16
dtype int32


In [16]:
print([(1,2,3,4)]in a)

True


In [20]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)
a7 = a7.reshape(3,3,1) 
print(a7)
print(a7.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [22]:
print(a)
a = a.T
print(a)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]
 [ 4  7 10 13]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]]


In [23]:
a = a.flatten()
print(a)

[ 1  2  3  4  4  5  6  7  7  8  9 10 10 11 12 13]


In [25]:
a8 = np.array([(1,2), (3,4), (5,6),(7,8)])
a8 = a8[:,:,np.newaxis]
a8.shape

(4, 2, 1)

In [27]:
a = np.ones((3,3,3))
b = np.array([(-1,1,-1),(-1,1,1),(1,1,-1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[-1  1 -1]
 [-1  1  1]
 [ 1  1 -1]]

[[[0. 2. 0.]
  [0. 2. 2.]
  [2. 2. 0.]]

 [[0. 2. 0.]
  [0. 2. 2.]
  [2. 2. 0.]]

 [[0. 2. 0.]
  [0. 2. 2.]
  [2. 2. 0.]]]

[[[2. 0. 2.]
  [2. 0. 0.]
  [0. 0. 2.]]

 [[2. 0. 2.]
  [2. 0. 0.]
  [0. 0. 2.]]

 [[2. 0. 2.]
  [2. 0. 0.]
  [0. 0. 2.]]]


In [28]:
a.sum()

27.0

In [29]:
a.prod()

1.0

In [30]:
a = np.array([5,4,3,2,1])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

mean: 3.0
var: 2.0
std: 1.4142135623730951


In [31]:
a = np.array([3.4, 7.5, 10.3,15.6])
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("rint:", np.rint(a))

argmax: 3
argmin: 0
ceil: [ 4.  8. 11. 16.]
floor: [ 3.  7. 10. 15.]
rint: [ 3.  8. 10. 16.]


In [32]:
a = np.array([18,3,67,2,14,16])
a.sort()
a

array([ 2,  3, 14, 16, 18, 67])

In [36]:
a9 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
b9 = np.array([[4, 5, 6, 7], [7, 8, 9, 10]])
a9 * b9

array([[ 4, 10, 18, 28],
       [28, 40, 54, 70]])

In [42]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [43]:
np.save('result.npy',manual_result)

In [44]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)