In [1]:
import torch
data = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float32)
data

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [2]:
import numpy as np

np_array = np.array([[1,2],[3,4],[5,6]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [3]:
data3 = torch.ones_like(data2)
data3

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [4]:
data4 = torch.zeros_like(data2)
data4

tensor([[0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)

In [5]:
data2.dtype

torch.int32

In [6]:
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.7641, 0.7394],
        [0.5023, 0.6619],
        [0.1841, 0.1362]])

In [7]:
shape = (2,3,4,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.7047, 0.7271, 0.9476, 0.9278],
         [0.1242, 0.2456, 0.3473, 0.0050],
         [0.7810, 0.6911, 0.8195, 0.9314]],

        [[0.0167, 0.6421, 0.6457, 0.7420],
         [0.1923, 0.6783, 0.0590, 0.4805],
         [0.5656, 0.5089, 0.8536, 0.2279]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [8]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(6,2, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([6,2])

# 均匀分布
print(torch.rand(6,2))
# 标准正态分布
print(torch.randn(6,2))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(6,2)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([6, 2])
tensor([[0.7097, 0.4098],
        [0.5599, 0.8016],
        [0.4513, 0.4955],
        [0.9920, 0.0723],
        [0.7838, 0.1027],
        [0.2275, 0.4617]])
tensor([[-1.4276, -1.7849],
        [-0.5524,  0.4634],
        [ 0.8392, -0.9012],
        [ 0.1354,  0.8801],
        [ 0.9899, -1.8241],
        [-1.6547,  0.7906]])
tensor([[ 0.7463,  0.2748],
        [ 0.3512, -0.9824],
        [ 0.3976,  1.4606],
        [-1.6041, -0.6310],
        [-1.1980, -0.7944],
        [ 1.0960,  0.9808]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [9]:
tensor = torch.rand(5,6,7)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([5, 6, 7])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
print(torch.cuda.is_available())

False


In [11]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[[0.6734, 0.1144, 0.7898, 0.6560, 0.2566, 0.2961, 0.5442],
         [0.6413, 0.7586, 0.0422, 0.3821, 0.8601, 0.0159, 0.5696],
         [0.1167, 0.3498, 0.0657, 0.2656, 0.3054, 0.1698, 0.3311],
         [0.8813, 0.3700, 0.5338, 0.2467, 0.9353, 0.2275, 0.2384],
         [0.8599, 0.0042, 0.3774, 0.2871, 0.9406, 0.2840, 0.3462],
         [0.9526, 0.5302, 0.3800, 0.0256, 0.3795, 0.5176, 0.4627]],

        [[0.1718, 0.9272, 0.1675, 0.1559, 0.0283, 0.4831, 0.7799],
         [0.6624, 0.8038, 0.0478, 0.5290, 0.6054, 0.1216, 0.6652],
         [0.4222, 0.4805, 0.6916, 0.3675, 0.3278, 0.0986, 0.6967],
         [0.6143, 0.1386, 0.5116, 0.0734, 0.7567, 0.1900, 0.2747],
         [0.7598, 0.5796, 0.9814, 0.1371, 0.6874, 0.2259, 0.0982],
         [0.0657, 0.3203, 0.5706, 0.9574, 0.8165, 0.9207, 0.1846]],

        [[0.0837, 0.9689, 0.4318, 0.3821, 0.4040, 0.7695, 0.5972],
         [0.3198, 0.7645, 0.8959, 0.3178, 0.4035, 0.2456, 0.6449],
         [0.5837, 0.1197, 0.6690, 0.4448, 0.2820, 0.8804, 

In [13]:
tensor = torch.ones(5, 4)
print('First row: ', tensor[1])
print('First column: ', tensor[:, 1])
print('Last column:', tensor[..., -1])
tensor[:,3] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])
torch.Size([5, 12])


In [17]:
import torch
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)
print(tensor)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])


In [18]:
import torch
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

tensor([[ 30.,  70., 110., 150.],
        [ 70., 174., 278., 382.],
        [110., 278., 446., 614.],
        [150., 382., 614., 846.]])
tensor([[ 30.,  70., 110., 150.],
        [ 70., 174., 278., 382.],
        [110., 278., 446., 614.],
        [150., 382., 614., 846.]])


In [19]:
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[ 30.,  70., 110., 150.],
        [ 70., 174., 278., 382.],
        [110., 278., 446., 614.],
        [150., 382., 614., 846.]])


In [21]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])


In [22]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

136.0 <class 'float'>


In [23]:
np_arr = z1.numpy()
np_arr

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.],
       [ 81., 100., 121., 144.],
       [169., 196., 225., 256.]], dtype=float32)

In [25]:
print(tensor, "\n")
tensor.add_(8)
print(tensor)

tensor([[ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]]) 

tensor([[14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])


In [4]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH