In [1]:
import numpy as np

In [2]:
# 创建ndarray数组
arr = np.array([5,6,7,8,9], float)
arr

array([5., 6., 7., 8., 9.])

In [3]:
a = np.array([(7,8,9), (4,5,6),(1,2,3) ])
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [5]:
a1 = np.zeros((2,3), dtype=np.float32)
a1

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [7]:
a2 = np.arange(1,6, 0.31)
a2

array([1.  , 1.31, 1.62, 1.93, 2.24, 2.55, 2.86, 3.17, 3.48, 3.79, 4.1 ,
       4.41, 4.72, 5.03, 5.34, 5.65, 5.96])

In [9]:
a3 = np.eye(4)
a3  # one-hot编码

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
a4 = np.random.random(5)  # 模型运算参数初始值
a4

array([0.62956158, 0.67699758, 0.33606091, 0.73008685, 0.29832258])

In [11]:
a5 = np.random.normal(0, 0.1, 5)  # 模型运算参数初始值
a5

array([-0.04916817,  0.10999997, -0.04088736,  0.01172338, -0.08826034])

In [13]:
a6 = np.array([(1,2), (3,4), (5,6)])
# print(a6)
print(a6[:,0])

[1 3 5]


In [15]:
a7 = np.array([(1,2), (3,4), (5,6)])
# i,j = a7[0]
for i,j in a7:
    print(i,j)

1 2
3 4
5 6


In [18]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(a)
print("ndim",a.ndim)#获取维度
print("shape",a.shape)# 获取数组大小
print("size",a.size)#获取数组元素个数
print("dtype",a.dtype)#获取数组元素的类型

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape (3, 3)
size 9
dtype int32


In [17]:
print(4 in a)

True


In [ ]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,3,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [29]:
print(a)
a = a.T
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
a = a.flatten()#展平
print(a)

[1 4 7 2 5 8 3 6 9]


In [21]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,:,np.newaxis]  # newaxis 添加一个维度
print(a8)
a8.shape


[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


(3, 2, 1)

In [37]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]


In [38]:
a.sum()

4.0

In [ ]:
a.prod() #  矩阵的乘积

1.0

In [ ]:
# 数组，矩阵、维度

# 数组、矩阵  ： 数据组织结构形式

# 维度： 通讯地址

In [22]:
a = np.array([5,3,1])
print("mean",a.mean())#平均数
print("var",a.var())# 方差
print("std",a.std())#标准差

mean 3.0
var 2.6666666666666665
std 1.632993161855452


In [25]:
a = np.array([2.02, 4.8, 5.9])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 2
argmin: 0
ceil: [3. 5. 6.]
floor: [2. 4. 5.]
rint: [2. 5. 6.]


In [26]:
a = np.array([36,41,12,38,261,31,48])
a.sort()  # 排序
a

array([ 12,  31,  36,  38,  41,  48, 261])

In [28]:
import torch
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])

In [30]:
a9 = np.array([[2,3,4],[5,6,7]])
b9 = np.array([[4,5,6],[7,8,9]])

a9 * b9

array([[ 8, 15, 24],
       [35, 48, 63]])

In [12]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[2, 3], [4, 5]], dtype=np.float32)
m2 = np.array([[6, 7], [8, 9]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[2. 3.]
 [4. 5.]]
矩阵 2:
[[6. 7.]
 [8. 9.]]
使用 np.dot 得到的矩阵乘法结果:
[[36. 41.]
 [64. 73.]]
使用 @ 运算符得到的矩阵乘法结果:
[[36. 41.]
 [64. 73.]]
2.0 * 6.0 = 12.0
3.0 * 8.0 = 24.0
结果矩阵[1,1]:36.0

2.0 * 7.0 = 14.0
3.0 * 9.0 = 27.0
结果矩阵[1,2]:41.0

4.0 * 6.0 = 24.0
5.0 * 8.0 = 40.0
结果矩阵[2,1]:64.0

4.0 * 7.0 = 28.0
5.0 * 9.0 = 45.0
结果矩阵[2,2]:73.0

手动推演结果:
[[36. 41.]
 [64. 73.]]


In [13]:
np.save('result.npy',manual_result)

In [14]:
result_np = np.load('result.npy')
result_np

array([[36., 41.],
       [64., 73.]], dtype=float32)

In [9]:
a = np.array([4,5,6])
b = np.array([7,8,9])
a + b

array([11, 13, 15])

In [10]:
a = np.array([(23,3), (4,5), (6,7), (8,4)])  # shape(4,2)
b = np.array([-1,12])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

array([[22, 15],
       [ 3, 17],
       [ 5, 19],
       [ 7, 16]])