In [2]:
import torch

data = torch.tensor([[3,4],[5,6]], dtype=torch.float32)
data

tensor([[3., 4.],
        [5., 6.]])

In [3]:
import numpy as np

np_array = np.array([[3,4],[5,6]])
data2 = torch.from_numpy(np_array)
data2

tensor([[3, 4],
        [5, 6]], dtype=torch.int32)

In [4]:
data2.dtype

torch.int32

In [5]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.0649, 0.1717],
        [0.3843, 0.0237]])

In [6]:
shape = (3,4,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5984, 0.9397, 0.6136, 0.4505],
        [0.7483, 0.7631, 0.3861, 0.1460],
        [0.2352, 0.9545, 0.4156, 0.0377]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(6,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([6, 3])
tensor([[0.4472, 0.8368, 0.9726],
        [0.3272, 0.7882, 0.5382],
        [0.4799, 0.5598, 0.6728],
        [0.3205, 0.4863, 0.5367],
        [0.7392, 0.9898, 0.4982]])
tensor([[ 0.8935, -1.5974,  1.3524],
        [-0.7167,  1.2612,  1.8039],
        [ 0.6171, -0.0448,  0.2248],
        [-0.7323,  0.7985,  0.1053],
        [-0.4647, -0.2773, -0.3485]])
tensor([[-0.9084, -0.2196,  1.7395],
        [-0.8749,  1.1228,  1.1995],
        [-0.7252, -0.7535,  0.4610],
        [ 0.5491,  0.9478, -0.8907],
        [-0.1181,  1.1642, -1.5523]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [9]:
tensor = torch.rand(4,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([4, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.9011, 0.9365, 0.7718, 0.9692],
        [0.8960, 0.6840, 0.0419, 0.0058],
        [0.8294, 0.5587, 0.8540, 0.9522],
        [0.0384, 0.0256, 0.7128, 0.3143]])
cpu
tensor([[0.9011, 0.9365, 0.7718, 0.9692],
        [0.8960, 0.6840, 0.0419, 0.0058],
        [0.8294, 0.5587, 0.8540, 0.9522],
        [0.0384, 0.0256, 0.7128, 0.3143]])
cpu


In [14]:
tensor = torch.ones(5, 5)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1., 1.])
tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]])


In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[3., 0., 3., 3., 3., 3., 0., 3., 3., 3., 3., 0., 3., 3., 3.],
        [3., 0., 3., 3., 3., 3., 0., 3., 3., 3., 3., 0., 3., 3., 3.],
        [3., 0., 3., 3., 3., 3., 0., 3., 3., 3., 3., 0., 3., 3., 3.],
        [3., 0., 3., 3., 3., 3., 0., 3., 3., 3., 3., 0., 3., 3., 3.],
        [3., 0., 3., 3., 3., 3., 0., 3., 3., 3., 3., 0., 3., 3., 3.]])
torch.Size([5, 15])


In [16]:
import torch
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])


In [17]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

136.0 <class 'float'>


In [18]:
np_arr = z1.numpy()
np_arr

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.],
       [ 81., 100., 121., 144.],
       [169., 196., 225., 256.]], dtype=float32)

In [21]:
print(tensor, "\n")
tensor.add_(5)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.],
        [23., 24., 25., 26.]]) 

tensor([[16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.]])


In [22]:
tensor

tensor([[16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.]])

In [23]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\willi\AppData\Local\Temp\ipykernel_39908\604160287.py:12: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3641.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression.png'