In [19]:
import numpy as np

In [11]:
#创建ndarray数组
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [12]:
arr = np.array([1,2,3],float)
arr

array([1., 2., 3.])

In [8]:
a = np.array([(1,2,3), (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a1 = np.zeros((2,3),dtype=np.float32)
a1

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [22]:
a3 = np.eye(3)
a3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.random(5)  #随机数

array([0.21155582, 0.71581276, 0.93327558, 0.04301819, 0.62216103])

In [25]:
a5 = np.random.normal(0,0.1,5)
a5

array([ 0.04008568, -0.05974592,  0.03784104, -0.11840776, -0.10182915])

In [29]:
a6 = np.array([(1,2),(3,4),(5,6)])
print(a6[:,1])

[2 4 6]


In [34]:
a7 = np.array([(1,2), (3,4), (5,6)])
for i,j in a7:
    print(i*j)

2
12
30


In [35]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int64


In [46]:
a8 = np.array([(1,2), (3,4)])
print(3 in a8)
print(5 in a8)

True
False


In [39]:
print(3 in a)
print(5 in a)

True
False


In [43]:
a = np.arange(9)
a
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
print(a)
a = a.T
print(a)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [50]:

a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
a8 = np.array([(1,2),(3,4),(5,6)])
a8 = a8[ :,:, np.newaxis]
a8.shape

(3, 2, 1)

In [55]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]


In [56]:
a.sum()


np.float64(4.0)

In [57]:
a.prod()


np.float64(1.0)

In [58]:
a = np.array([1.2, 3.8, 4.9])
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("rint:", np.rint(a))

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [62]:
import numpy as np
# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4] ], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8] ], dtype=np.float32)
# 使⽤ np.dot 进⾏矩阵乘法
result_dot = np.dot(m1, m2)
# 使⽤ @ 运算符进⾏矩阵乘法
result_at = m1 @ m2
print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使⽤ np.dot 得到的矩阵乘法结果:")
print(result_dot)

print("使⽤ @ 运算符得到的矩阵乘法结果:")
print(result_at)
# 创建⼀个全零矩阵，⽤于存储⼿动推演的结果
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
# 外层循环：遍历 matrix1 的每⼀⾏
# i 表⽰结果矩阵的⾏索引
for i in range(m1.shape[0]):
 # 中层循环：遍历 matrix2 的每⼀列
 # j 表⽰结果矩阵的列索引
 for j in range(m2.shape[1]):
 # 初始化当前位置的结果为 0
   manual_result[i, j] = 0
 # 内层循环：计算 matrix1 的第 i ⾏与 matrix2 的第 j 列对应元素的乘积之和
 # k 表⽰参与乘法运算的元素索引
 for k in range(m1.shape[1]):
 # 打印当前正在计算的元素
   print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
 # 将 matrix1 的第 i ⾏第 k 列元素与 matrix2 的第 k ⾏第 j 列元素相乘，并累manual_result[i, j] += m1[i, k] * m2[k, j]
 # 打印当前位置计算完成后的结果
 print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")
print("⼿动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使⽤ np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使⽤ @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:0.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:0.0

⼿动推演结果:
[[0. 0.]
 [0. 0.]]


In [63]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [64]:
a = np.array([(1,2), (2,2), (3,3), (4,4)]) # shape(4,2)
b = np.array([-1,1]) # shape(2)-> shape(1,2) -> shape(4,2) [ -1,1],[-1,1],[-1,1],[-1
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])