### NumPy 基数组创建
NumPy 数组有多种创建方式，一般常用方式是list 转换np.array():

1. 使用python  list ---> np.array

- a ----> list

- np.array(a)  -----> array

In [2]:
import numpy as np 
a =[20,25,2,26,20,11,16]
b = np.array(a)
b

array([20, 25,  2, 26, 20, 11, 16])

2. 直接使用数据创建数组，定义数据类型
- numpy.array([],float)

In [5]:
a= np.array([20,25,2,26,20,1,16],float)
a

array([20., 25.,  2., 26., 20.,  1., 16.])

3. 创建多维数组

In [8]:
a = np.array([[1,2,3],[2,3,7]],dtype=np.float16)
a

array([[1., 2., 3.],
       [2., 3., 7.]], dtype=float16)

4. 特殊数组创建
NumPy提供一些占位符创建数组的函数 ，例如  np.zeros((2,3),dtype = float)

In [ ]:
# 生成全是零的数组，6行6列，数据类型为浮点数
a = np.zeros((6,6),dtype = float)
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
#生成全是1的数组，9行9列，数据类型是浮点型
b = np.ones((9,9),dtype = float)
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
#等差数列，从1 开始，100 结束，步长为2 ，不包含100
a = np.arange(1,100,2)
a
# count = 0
# for i in a:
#     count +=1 
# print(count)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [30]:
# 创建单位矩阵
a = np.eye(16)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

5. 额定范围内容的随机数组： [0,1)

In [32]:
#  16:个数
a  = np.random.random(16)
a

array([0.81112771, 0.52842608, 0.22823994, 0.67650702, 0.3506663 ,
       0.29556109, 0.63337457, 0.78494682, 0.72648032, 0.22817133,
       0.84548121, 0.60157879, 0.26589715, 0.86900882, 0.01962868,
       0.10673535])

6. 指定长度，符合正态分布的随机数组，指定其均值为0，标准差为0.1

In [35]:
mu,sigma = 666,0.2
a = np.random.normal(mu,sigma,6)
a

mu,sigma = 0 ,0.1
b = np.random.normal(mu,sigma,6)
b


array([-0.06943728, -0.12187381,  0.17252799,  0.05848461, -0.01092373,
        0.18579328])

### NumPy数组的访问

1. 切片操作

In [ ]:
a = np.array([["I","fall","asleep"],["everyday","is","working"],["for","the","deadline"]])
print(a)
#访问数组
#组词： the deadline is falling
special = a[1,2]
print(specail)
word = a[2,1]+" "+a[2,2]+" "+a[1,1]+" "+a[0,1]+special[4:7]
print(word)

# :表示所有行
# 1表示第二列
a[:,1]
print(a[:,1])

# :表示所有行
# :3表示前三列

a[:,:3]
print(a[1])

print("ndim:{}".format(a.ndim))
shape = a.shape
print("shape:{} ,shape's data type is {}".format(a.shape,type(shape)))
print("row is {} , clounm is {}".format(shape[0],shape[1]))

# 访问对角线元素 I is deadline
for i in range(shape[0]):
    print(a[i,i],end=" ")




[['I' 'fall' 'asleep']
 ['everyday' 'is' 'working']
 ['for' 'the' 'deadline']]
working
the deadline is falling
['fall' 'is' 'the']
['everyday' 'is' 'working']
ndim:2
shape:(3, 3) ,shape's data type is <class 'tuple'>
row is 3 , clounm is 3
I is deadline 

### NumPy数组的遍历

In [ ]:
#遍历a 数组
for i in a:
    print(i)


for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j],end=" ")
        if(i == 0 and j==2):
            print(",",end=" ")
print(".")


#多维数组的遍历
for i,j in enumerate(a):
    print(i,j)

numArray = np.array([(20,25,2,26),(20,1,1,16)])
for i in numArray:
    print(i)
    for j in i:
        print(j,end=" ")
    
    print("")



In [9]:

#一行多值输出
numArrayTwoCol = np.array([(2,26),(20,25)])
i ,j = numArrayTwoCol[0]
print(i,j)
for i,j in numArrayTwoCol:
    print(i,j,end=' ')

numArrayTwoCol = np.array([(2,26,90),(20,25,666)])
i ,j,k = numArrayTwoCol[0]
print(i,j,k)


2 26
2 26 20 25 2 26 90


### Numpy数组的常用属性


In [92]:
#打印数组
print(numArray)
#ndim 维度
print("numArray's ndim: {}".format(numArray.ndim))
#shape 形状
print("numArray's shape:{}".format(numArray.shape))
#size 元素个数
print("numArray's size:{}".format(numArray.size))
#dtype 数据类型
print("numArray's dtype:{}".format(numArray.dtype))


[[20 25  2 26]
 [20  1  1 16]]
numArray's ndim: 2
numArray's shape:(2, 4)
numArray's size:8
numArray's dtype:int32


### NumPy 数组的基本操作

In [94]:
# 检测数值是否在数组中
print(25 in numArray)


isContain = np.in1d(numArray, [25, 26])
print(isContain)

True
[False  True False  True False False False False]


In [110]:
#数组的重排列
# [个数，行，列]
numZeros = np.zeros([2,3,4])
numZeros
print(" numZeros's ndim is {}".format(numZeros.ndim))
print("numZeros's shape is {}".format(numZeros.shape))
print("numeZeros's size is {}".format(numZeros.size))
# 多维转一维
numZeros.reshape(numZeros.size)

#多维转一维
numZeros.flatten()

 numZeros's ndim is 3
numZeros's shape is (2, 3, 4)
numeZeros's size is 24


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [109]:
#转置 T
a.T
a.transpose()

array([['I', 'everyday', 'for'],
       ['fall', 'is', 'the'],
       ['asleep', 'working', 'deadline']], dtype='<U8')

In [118]:
#增加维度
numArray.shape
numArray = numArray[:,np.newaxis]
numArray

array([[[[[[[[20],
             [25],
             [ 2],
             [26]]],


           [[[20],
             [ 1],
             [ 1],
             [16]]]]]]]])

### NumPy 数组的数学操作

- 星乘 矩阵内个对应位置相乘 、 点乘表示矩阵内积, 二维数组称为矩阵积

In [ ]:
#加减乘除
ones = np.ones((3,3))
print(ones)

array = np.array([(-1,1,-1),(1,-1,1),(1,-1,1)])
print(array)

print("ones + array")
print(ones+array)

print("ones - array")
print(ones-array)

print("ones * array")
print(ones*array)

print("ones / array")
print(ones/array)

#求和
ones.sum()

#求积
allTimeArray  =  np.array([1,90,12,12])
allTimeArray.prod()

#平均数
allTimeArray.mean()

#最大值
allTimeArray.max()
#最小值
allTimeArray.min()

#方差
allTimeArray.var()

#标准差
allTimeArray.std()




In [14]:
floatArray = np.array([10,1.02, 3.8, 4.9])
print("argmax:", floatArray.argmax()) # 最大值的索引
print("argmin:", floatArray.argmin()) # 最小值的索引
print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 0
argmin: 1
ceil: [20. 25.  2. 26. 20. 11. 16.]
floor: [20. 25.  2. 26. 20. 11. 16.]
rint: [20. 25.  2. 26. 20. 11. 16.]


In [25]:
#sort 排序
floatArray.sort()
print(floatArray)

angleArray =np.array([30,-45])
angleArray = np.abs(angleArray)
print(angleArray)

[ 1.02  3.8   4.9  10.  ]
[30 45]


### Numpy 线性代数

- numpy.linalg 提供线性代数

In [28]:
#矩阵 （matrix） array 分支
a9 = np.array([[20,25,2],[27,2,3]])
b9 = np.array([[20,25,6],[17,2,3]])
a9*b9
#dot 矩阵内积
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)


矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [45]:
import torch
tensor = torch.arange(2,20,2, dtype=torch.float32).reshape(3, 3)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


tensor([[  4.,  16.,  36.],
        [ 64., 100., 144.],
        [196., 256., 324.]])

In [31]:
np.save('result.npy',manual_result)

In [32]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [35]:
a = np.array([1,9,3])
b = np.array([4,9,6])
a + b

array([ 5, 18,  9])

In [46]:
a = np.array([(1,9), (6,2), (3,8), (8,4)])  # shape(4,2)
b = np.array([-1,1])  
a + b

array([[ 0, 10],
       [ 5,  3],
       [ 2,  9],
       [ 7,  5]])