In [5]:
import torch

data = torch.tensor([[11,21],[33,44]], dtype=torch.float32)
data


print(data.device)

cpu


In [17]:
import numpy as np
import torch

np_array = np.array([[78,90],[55,99]])

data2 = torch.from_numpy(np_array)

TypeError: expected np.ndarray (got numpy.ndarray)

In [23]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
data3

tensor([[0.7843, 0.3258],
        [0.6320, 0.3768]])

In [24]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
data3

tensor([[0.1375, 0.5398],
        [0.4013, 0.6443]])

In [25]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
data3

tensor([[0.0281, 0.8198],
        [0.3582, 0.0265]])

In [26]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
data3

tensor([[0.7582, 0.7894],
        [0.5040, 0.6104]])

In [27]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
data3

tensor([[0.0545, 0.2036],
        [0.0857, 0.4974]])

In [28]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
data3

tensor([[0.9419, 0.4444],
        [0.6071, 0.7186]])

In [29]:
data.dtype

torch.float32

In [30]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
data3

tensor([[0.8089, 0.6987],
        [0.4028, 0.8204]])

In [31]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data, dtype=torch.float)
data3

tensor([[0.0206, 0.4577],
        [0.1743, 0.6733]])

In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4631, 0.1627, 0.2323],
        [0.3508, 0.4262, 0.3539]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([5, 3])
tensor([[0.4259, 0.8331, 0.7320],
        [0.2567, 0.0096, 0.6257],
        [0.1107, 0.0636, 0.6657],
        [0.8275, 0.8246, 0.8835],
        [0.1004, 0.0046, 0.7678]])
tensor([[-0.4522,  0.7546, -0.2702],
        [-0.5254, -0.7705, -0.8633],
        [ 1.3086, -1.6296,  0.6684],
        [ 0.6231,  0.7556, -0.4679],
        [-0.9587, -1.7325, -1.2347]])
tensor([[ 0.7425, -0.3892,  1.9623],
        [ 0.6942, -0.1991,  0.3018],
        [ 0.4206,  0.4395,  0.2504],
        [-0.7068, -1.1019,  1.8449],
        [ 3.4960,  0.9682, -0.0154]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [33]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [34]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.0296, 0.5399, 0.2091, 0.4702],
        [0.7408, 0.9124, 0.1646, 0.0764],
        [0.9009, 0.5347, 0.7390, 0.7740]])
cpu
tensor([[0.0296, 0.5399, 0.2091, 0.4702],
        [0.7408, 0.9124, 0.1646, 0.0764],
        [0.9009, 0.5347, 0.7390, 0.7740]])
cpu


In [35]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [36]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.]])
torch.Size([4, 12])


In [37]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [38]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

45.0 <class 'float'>


In [39]:
np_arr = z1.numpy()
np_arr

TypeError: __array_wrap__() argument 1 must be numpy.ndarray, not numpy.ndarray

In [40]:
print(tensor, "\n")
tensor.add_(5)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [41]:
tensor

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])

In [20]:
import os
os.environ["PATH"] += r";C:\Program Files\Graphviz\bin"
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

'expression.png'