In [4]:
import torch
import numpy as np

In [5]:
data=[(1,2,3),(4,5,6),(7,8,9)]
x_data=torch.tensor(data)

array = np.array(data,dtype=int)
x_np = torch.from_numpy(array)

# 保留某张量的属性,形状和数据类型等
x_np2 = torch.ones_like(x_data)
print(x_np2)

# 覆盖 x_data的数据类型
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

# 定义矩阵的行列
shape=(4,4)
 # 矩阵每个元素数值随机
rand_tensor=torch.rand(shape) 
print(f"Random Tensor: \n {rand_tensor} \n")

# 矩阵每个元素数值为1
ones_tensor=torch.ones(shape)
print(f"Random Tensor: \n {ones_tensor} \n")

#  矩阵每个元素数值为0
zeros_tensor=torch.zeros(shape)
print(f"Random Tensor: \n {zeros_tensor} \n")


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
Random Tensor: 
 tensor([[0.2247, 0.5393, 0.3594],
        [0.8551, 0.2177, 0.5036],
        [0.9438, 0.9063, 0.7433]]) 

Random Tensor: 
 tensor([[0.4182, 0.1111, 0.8442, 0.4043],
        [0.7867, 0.7173, 0.4871, 0.8099],
        [0.9835, 0.3711, 0.9577, 0.3019],
        [0.7215, 0.3276, 0.1539, 0.2679]]) 

Random Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Random Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 



In [ ]:

# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(5,5, dtype=torch.int)
print('初始化的张量',m)
n = torch.rand_like(m, dtype=torch.float)
print('张量填充随机数',n)

print('张量的大小',n.size())


# 均匀分布
torch.rand(5,3)
# 标准正态分布
torch.randn(5,3)
# 离散正态分布
torch.normal(mean=.0,std=1.0,size=(5,3))
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
torch.linspace(start=1,end=10,steps=20)

# 张量
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")



初始化的张量 tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)
张量填充随机数 tensor([[0.8052, 0.4133, 0.8215, 0.6297, 0.4981],
        [0.2058, 0.8705, 0.4446, 0.5108, 0.4274],
        [0.4558, 0.5686, 0.3074, 0.4652, 0.4336],
        [0.3587, 0.0231, 0.4880, 0.7236, 0.5096],
        [0.7608, 0.9349, 0.6422, 0.4871, 0.4598]])
张量的大小 torch.Size([5, 5])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [12]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


# 计算两个张量之间矩阵乘法的⼏种⽅式。 y1, y2, y3 最后的值是⼀样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# 计算张量逐元素相乘的⼏种⽅法。 z1, z2, z3 最后的值是⼀样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [2]:
from graphviz import Graph
from torchviz import make_dot
import torch
# graph = Graph(engine='D:/Program Files/Graphviz/bin/dot.exe')


# 定义矩阵 a，向量 b 和常数 c
a = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * a + b * x + c
d = x.T
result = torch.matmul(a, d) + torch.matmul(b, x) + c
print(result)

# ⽣成计算图节点
dot = make_dot(result, params={'a': a, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\HUAWEI\AppData\Local\Temp\ipykernel_13000\844321487.py:13: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  d = x.T


tensor([14.1837, 11.1824,  6.2966,  9.6357,  9.7605,  6.6688,  8.1148, 11.0316,
         8.7014,  8.5876], grad_fn=<AddBackward0>)


'expression.png'

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement make_dot (from versions: none)
ERROR: No matching distribution found for make_dot
