## 第一周  torch基础

In [7]:
import numpy as np

In [11]:
arr = np.array([1.1,2.2,3.3,4.33,5.0,22], float)    # 创建ndarray数组
arr

array([ 1.1 ,  2.2 ,  3.3 ,  4.33,  5.  , 22.  ])

In [17]:
a = np.array([(1,2,3,5), (4,5,6,5), (7,8,9,5)])
a

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [7, 8, 9, 5]])

In [27]:
a1 = np.zeros((5,5), dtype=np.int64)
a1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [33]:
a2 = np.arange(2,21, 0.5)
a2

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. ,
       18.5, 19. , 19.5, 20. , 20.5])

In [39]:
a3 = np.eye(4)
a3 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
a4 = np.random.random(3)  
a4

array([0.54745352, 0.33762347, 0.27134311])

In [49]:
a5 = np.random.normal(0, 1, 5)  
a5

array([ 1.51005024,  1.40351273, -0.23337164,  1.45401238, -0.09536447])

In [53]:
a6 = np.array([(1,2,3), (3,4,3), (5,6,3)])
# print(a6)
print(a6[:,1])

[2 4 6]


In [55]:
a7 = np.array([(1,2.1), (3,4.231), (5.1,6.312)])
for i,j in a7:
    print(i,j)

1.0 2.1
3.0 4.231
5.1 6.312


In [57]:
a = np.array([(1.11,2.1,32), (4.3,5.1,6), (7,8.123,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype float64


In [59]:
print(3 in a)

False


In [65]:
a7 = np.arange(1,13)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,4,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape) 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]
(3, 4, 1)


In [67]:
print(a)
a = a.T
print(a)

[[ 1.11   2.1   32.   ]
 [ 4.3    5.1    6.   ]
 [ 7.     8.123  9.   ]]
[[ 1.11   4.3    7.   ]
 [ 2.1    5.1    8.123]
 [32.     6.     9.   ]]


In [69]:
a = a.flatten()
print(a)

[ 1.11   4.3    7.     2.1    5.1    8.123 32.     6.     9.   ]


In [71]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,:,np.newaxis]  # [3,1,2]
a8.shape

(3, 2, 1)

In [77]:
a = np.ones((4,2))
b = np.array([(-1,1),(-1,1),(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]
 [-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]
 [0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]
 [2. 0.]
 [2. 0.]]


In [79]:
a.sum()

8.0

In [81]:
a.prod()

1.0

In [83]:
a = np.array([5,3.2,1.1,1.1,23.1])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

mean: 6.7
var: 69.36400000000002
std: 8.328505268053807


In [85]:
a = np.array([1.022, 3.8, 5.9])
print("argmax:", a.argmax()) 
print("argmin:", a.argmin()) 

print("ceil:", np.ceil(a))  
print("floor:", np.floor(a)) 
print("rint:", np.rint(a)) 

argmax: 2
argmin: 0
ceil: [2. 4. 6.]
floor: [1. 3. 5.]
rint: [1. 4. 6.]


In [89]:
a = np.array([16,31,1.2,28,22,31,4.8,-21])
a.sort()  # 排序
a

array([-21. ,   1.2,   4.8,  16. ,  22. ,  28. ,  31. ,  31. ])

In [91]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

print(tensor.dtype)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [93]:
a9 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[4,5,6],[7,8,9]])

a9 * b9

array([[ 4, 10, 18],
       [28, 40, 54]])

In [95]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[2, 2], [4, 4]], dtype=np.float32)
m2 = np.array([[66, 6], [55, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[2. 2.]
 [4. 4.]]
矩阵 2:
[[66.  6.]
 [55.  8.]]
使用 np.dot 得到的矩阵乘法结果:
[[242.  28.]
 [484.  56.]]
使用 @ 运算符得到的矩阵乘法结果:
[[242.  28.]
 [484.  56.]]
2.0 * 66.0 = 132.0
2.0 * 55.0 = 110.0
结果矩阵[1,1]:242.0

2.0 * 6.0 = 12.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:28.0

4.0 * 66.0 = 264.0
4.0 * 55.0 = 220.0
结果矩阵[2,1]:484.0

4.0 * 6.0 = 24.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:56.0

手动推演结果:
[[242.  28.]
 [484.  56.]]


In [97]:
np.save('result.npy',manual_result)

In [99]:
result_np = np.load('result.npy')
result_np

array([[242.,  28.],
       [484.,  56.]], dtype=float32)

In [103]:
a = np.array([2.1,-2,3])
b = np.array([4,0.1,6])
a + b

array([ 6.1, -1.9,  9. ])

In [105]:
a = np.array([(1,-3), (2,2.3), (3,3), (4,4)]) 
b = np.array([-1,1]) 
a + b

array([[ 0. , -2. ],
       [ 1. ,  3.3],
       [ 2. ,  4. ],
       [ 3. ,  5. ]])

#### torch部分

In [109]:
import torch

data = torch.tensor([[1.22,2],[-3,4]], dtype=torch.int64)
data

tensor([[ 1,  2],
        [-3,  4]])

In [113]:
import numpy as np

np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [115]:
data2.dtype

torch.int32

In [117]:
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.9243, 0.8976],
        [0.2261, 0.0765]])

In [121]:
shape = (3,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[1.2939e-01, 6.4910e-01, 3.8337e-01],
        [1.1860e-01, 9.5664e-02, 6.6221e-04],
        [1.2983e-02, 7.1168e-01, 2.7900e-01]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [129]:
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

print(m.size()) # torch.Size([5,3])


print(torch.rand(5,3))

print(torch.randn(5,3))

print(torch.normal(mean=.0,std=1.0,size=(5,3)))

print(torch.linspace(start=1,end=5,steps=23))

torch.Size([5, 3])
tensor([[0.0253, 0.5634, 0.7158],
        [0.0409, 0.2538, 0.4257],
        [0.4102, 0.8232, 0.6657],
        [0.5244, 0.1739, 0.0332],
        [0.9824, 0.4972, 0.6443]])
tensor([[ 0.4652,  0.6326,  1.5525],
        [ 2.4014,  0.8585, -1.3350],
        [-0.2401,  0.9674, -0.7421],
        [ 0.0852,  0.1484,  0.6778],
        [ 0.0176, -1.2343,  0.1053]])
tensor([[ 0.1613,  1.4550,  0.3578],
        [ 0.3535,  0.1019,  1.9520],
        [-1.2587, -0.0879, -1.3987],
        [-0.1704, -0.0927,  1.1030],
        [ 0.5359, -1.4332,  0.2473]])
tensor([1.0000, 1.1818, 1.3636, 1.5455, 1.7273, 1.9091, 2.0909, 2.2727, 2.4545,
        2.6364, 2.8182, 3.0000, 3.1818, 3.3636, 3.5455, 3.7273, 3.9091, 4.0909,
        4.2727, 4.4545, 4.6364, 4.8182, 5.0000])


In [131]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [135]:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor = tensor.to(device)

print(tensor)
print(tensor.device)


tensor([[0.5017, 0.2891, 0.7540, 0.9164],
        [0.4219, 0.8838, 0.9351, 0.3876],
        [0.7259, 0.7434, 0.9578, 0.1590]])
cpu


In [137]:
tensor = torch.ones(5, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [143]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1 * 3.1)
print(t1.shape)

tensor([[3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000],
        [3.1000, 0.0000, 3.1000, 3.1000]])
torch.Size([15, 4])


In [145]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [147]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

45.0 <class 'float'>


In [149]:
np_arr = z1.numpy()
np_arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [151]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)
tensor = tensor + 5
tensor += 5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
tensor([[16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])


In [153]:
tensor

tensor([[16., 17., 18.],
        [19., 20., 21.],
        [22., 23., 24.]])

In [5]:

import os
import torch
from torchviz import make_dot

os.environ["PATH"] += os.pathsep + r"C:\Program Files\Graphviz\bin"

A = torch.randn(10, 10,requires_grad=True)  
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)

result = torch.matmul(A, x.T) + torch.matmul(b, x) + c    # 计算 x^T * A + b * x + c

dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})

dot.render('expression', format='png', cleanup=True, view=False)

'expression.png'