一 numpy数组的生成

In [ ]:
import numpy as np
a1 = [12,23456,35444]
b = np.array(a1)  #创建数组，一维数组
b

array([   12, 23456, 35444])

In [ ]:
a2 =np.array([1,3,5,7,9],dtype=np.float_)  #指定数据类型
a2

array([1., 3., 5., 7., 9.])

In [8]:
#创建多维数组
a3 = np.array([[16,27,12],[4,5,6],[7,8,9]])
a3

array([[16, 27, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
#特殊数组1、创建一个3行4列的元素全0数组
a3 =np.zeros((3,4))  
a3
#print('zeros方法创建的结果：\n',a3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:

 #2、创建一个4行6列的数组，元素都是1
a4 =np.ones((4,6),dtype=int) 
a4
#print('ones方法创建的结果：\n',a4)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [32]:
#3、创建一个3行3列的数组，元素都是对角线为1，其余为0
a5 = np.eye(3) 
a5
#print('eye方法创建的结果：\n',a5)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#4、创建一个从12开始，到108结束，步长为9的数组
a6 =np.arange(12,108,9) 
a6
#print('arange方法创建的结果：\n',a6)

array([ 12,  21,  30,  39,  48,  57,  66,  75,  84,  93, 102])

In [36]:
#⽣成指定⻓度，在 [0,1) 之间平均分布的随机数组：元素15个
a7 = np.random.random(15)
a7

array([0.2525429 , 0.11942399, 0.35275027, 0.54133738, 0.3030544 ,
       0.26748248, 0.45593334, 0.59700514, 0.4147056 , 0.48817895,
       0.01449008, 0.05422279, 0.48555342, 0.27557688, 0.57753058])

In [37]:
#⽣成指定⻓度，符合正态分布的随机数组，指定其均值为 2，标准差为 0.3：
mu,sigma = 2, 0.3
a8 = np.random.normal(mu, sigma, 8)
a8

array([2.07146716, 2.28669462, 2.26940267, 1.86454735, 2.41801151,
       2.01243796, 1.89839497, 2.23699609])

二 numpy数组的访问

In [ ]:
#数组切片和索引
a9 =np.array([(1,9,773,46),(5,6,7,8),(49,10,17,12)])
#print(a9)
#a9[2]#  #输出第3个 
#a9[1:]   #输出第2行之后的
# a9[:,:1]
# a9[:,:3]   
# a9[:,:5]
a9[2][3]  #索引从0开始的，0,1,2,3


12

In [ ]:
#一维数组遍历
for i in a1:  #别忘记末尾有个冒号
    print(i)

#多维数组遍历
# for i,j,z,y in a9:
#     print(i*j*z*y)


12
23456
35444


三、数组的属性

In [56]:
#数组的属性
a10 =np.array([(1,922,773,46,23),(5,6,7,8,34),(49,10,17,12,34)])
print("ndim:",a10.ndim)  #维度  #因为这里是二维数组，
#所以是2
print("shape:",a10.shape)  #形状
print("size:",a10.size)  #元素个数
print("dtype:",a10.dtype)  #元素类型

ndim: 2
shape: (3, 5)
size: 15
dtype: int32


In [ ]:
a9 =np.array([(1,9,773,46),(5,6,7,8),(49,10,17,12)])
print("ndim:",a9.ndim)  #维度  #因为这里是二维数组，所以是2
print("shape:",a9.shape)  #形状
print("size:",a9.size)  #元素个数
print("dtype:",a9.dtype)  #元素类型

ndim: 2
shape: (3, 4)
size: 12
dtype: int32


In [ ]:
a11 = np.array([[[[16,27,12],[4,5,6],[7,8,9]],[1,2,3]]],dtype=object)  #这里要指定为object类型，否则报错
print("ndim:",a11.ndim)  #维度
print("shape:",a11.shape)  #形状,
print("size:",a11.size)  #元素个数
print("dtype:",a11.dtype)  #元素类型

ndim: 3
shape: (1, 2, 3)
size: 6
dtype: object


In [ ]:
a2 =np.array([1,3,5,7,9],dtype=np.float64) 
print("ndim:",a2.ndim)  #维度  #一维数组，所以是1
print("shape:",a2.shape)  #形状
print("size:",a2.size)  #元素个数
print("dtype:",a2.dtype)  #元素类型

ndim: 1
shape: (5,)
size: 5
dtype: float64


四、数组的操作

In [71]:
#1、in:检测数值是否在数组中
print(3 in a2)

True


In [ ]:
#2、reshape: 数组的重排列，例如将⼀个 3 维数组转变为 1 维（元素数⼀定要保持不变）
a = np.zeros([2,3,4]) #创建一个3维数组
b1 = a.reshape(2,12)   #将3维数组转变为2维数组        
# b2 = a.reshape(2,2,6)
b3 = a.reshape(24)       #将3维数组转变为1维数组
print(b1)
# print(b2)
print(b3)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [78]:
#3、tanspose：转置 (可以直接.T）
a9 =np.array([(1,9,773,46),(5,6,7,8),(49,10,17,12)])
a12 =a9.transpose()
a12

array([[  1,   5,  49],
       [  9,   6,  10],
       [773,   7,  17],
       [ 46,   8,  12]])

In [79]:
#4、flatten: 把多维数组转换为⼀维数组，注意每个元组的⻓度是相同的
a13 = a12.flatten()
a13


array([  1,   5,  49,   9,   6,  10, 773,   7,  17,  46,   8,  12])

In [ ]:
#5、newaxis: 增加列维度
a3 = np.array([[16,27,12],[4,5,6],[7,8,9]])
# a3.shape

a14 = a3[:,np.newaxis]     #增加列维度
a14
# a14.shape




(3, 1, 3)

In [94]:
# 5、newaxis: 增加行维度
a3 = np.array([[16,27,12],[4,5,6],[7,8,9]])
a15 = a3[np.newaxis,:]     #增加行维度
# a15
a15.shape

(1, 3, 3)

In [ ]:
#6、数学操作：加减乘除、求和、求积、求平均值、求最⼤最⼩值、求中位数、求标准差、求方差、求最⼤最⼩值的位置
a = np.ones((2,2))
b = np.array([(1,1),(6,9)])
print(a)
print(b)
print(a+b)  #加法
print(a-b)  #减法
print(a*b)  #乘法
print(a/b)  #除法
print(np.sum(b))  #求和
print(np.prod(b))  #求积
print(np.mean(b))  #求平均值
print(np.max(b))  #求最⼤值
print(np.min(b))  #求最⼩值
print(np.median(b))  #求中位数
print(np.std(b))  #求标准差
print(np.var(b))  #求方差
print(np.argmax(b))  #求最⼤值的位置
print(np.argmin(b))  #求最⼩值的位置


[[1. 1.]
 [1. 1.]]
[[1 1]
 [6 9]]
[[ 2.  2.]
 [ 7. 10.]]
[[ 0.  0.]
 [-5. -8.]]
[[1. 1.]
 [6. 9.]]
[[1.         1.        ]
 [0.16666667 0.11111111]]
17
54
4.25
9
1
3.5
3.418698582794336
11.6875
3
0


In [97]:
#取元素值上限，下限，四舍五⼊，向上取整，向下取整
a = np.array([2.89,23,29.08,212,5.0])
print(np.ceil(a))  #向上取整
print(np.floor(a))  #向下取整
print(np.rint(a))  #四舍五⼊
print(np.around(a))  #四舍五⼊
print(np.trunc(a))  #取元素值上限
sorted(a)  #排序    

[  3.  23.  30. 212.   5.]
[  2.  23.  29. 212.   5.]
[  3.  23.  29. 212.   5.]
[  3.  23.  29. 212.   5.]
[  2.  23.  29. 212.   5.]


[2.89, 5.0, 23.0, 29.08, 212.0]

五 numpy线性代数


In [99]:
m1 = np.array([[13,21], [5,6]], dtype=np.float32)    
m2 = np.array([[15, 16], [1,6]], dtype=np.float32)
result_dot = np.dot(m1, m2)    
result_at = m1 @ m2
print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使⽤ np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使⽤ @ 运算符得到的矩阵乘法结果:")
print(result_at)

矩阵 1:
[[13. 21.]
 [ 5.  6.]]
矩阵 2:
[[15. 16.]
 [ 1.  6.]]
使⽤ np.dot 得到的矩阵乘法结果:
[[216. 334.]
 [ 81. 116.]]
使⽤ @ 运算符得到的矩阵乘法结果:
[[216. 334.]
 [ 81. 116.]]


In [100]:
# 创建⼀个全零矩阵，⽤于存储⼿动推演的结果
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
# 外层循环：遍历 matrix1 的每⼀⾏
# i 表⽰结果矩阵的⾏索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每⼀列
    # j 表⽰结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i ⾏与 matrix2 的第 j 列对应元素的乘积之和
        # k 表⽰参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i ⾏第 k 列元素与 matrix2 的第 k ⾏第 j 列元素相乘，并累
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")
print("⼿动推演结果:")
print(manual_result)

13.0 * 15.0 = 195.0
21.0 * 1.0 = 21.0
结果矩阵[1,1]:216.0

13.0 * 16.0 = 208.0
21.0 * 6.0 = 126.0
结果矩阵[1,2]:334.0

5.0 * 15.0 = 75.0
6.0 * 1.0 = 6.0
结果矩阵[2,1]:81.0

5.0 * 16.0 = 80.0
6.0 * 6.0 = 36.0
结果矩阵[2,2]:116.0

⼿动推演结果:
[[216. 334.]
 [ 81. 116.]]


六 numpy文件操作

In [102]:
   
c = np.save('outfile.npy', a12)
c
d =np.load('outfile.npy')
print(d)


[[  1   5  49]
 [  9   6  10]
 [773   7  17]
 [ 46   8  12]]


七、NumPy 广播机制

In [112]:
#当运算中的 2 个数组的形状不同时，numpy 将⾃动触发⼴播机制
# a12.shape
# a12  (4,3)
# a6
a6.shape

a6 +a12

ValueError: operands could not be broadcast together with shapes (11,) (4,3) 

In [120]:
#当运算中的 2 个数组的形状不同时，numpy 将⾃动触发⼴播机制
a3 = np.array([[16,27,12],[4,5,6],[7,8,9]])
a16 =np.array([0,1,2])
# a3.shape  #(3,3)
# print(a3)
a3 + a16

array([[16, 28, 14],
       [ 4,  6,  8],
       [ 7,  9, 11]])