In [5]:

import torch
import numpy as np
#张量直接从数据中创建
data = [[1,4],[2,8]]
x_data = torch.tensor(data)
print(x_data)

#  张量从numpy数组中创建 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

#张量从另外一个张量创建,保留of x_data的属性
x_data = torch.ones_like(x_data)
print(f"ones tensor: \n {x_data}\n")

#张量从另外一个张量创建,覆盖 x_data的属性
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"random tensor: \n {x_rand}\n")


tensor([[1, 4],
        [2, 8]])
tensor([[1, 4],
        [2, 8]], dtype=torch.int32)
ones tensor: 
 tensor([[1, 1],
        [1, 1]])

random tensor: 
 tensor([[0.6037, 0.4700],
        [0.8506, 0.3789]])



In [ ]:
#shape是张量的维度.使用随机值创建张量
shape = (2,3,)  #2行3列
rand_tensor = torch.rand(shape) #创建一个随机张量   
ones_tensor = torch.ones(shape)     #创建一个全是1的张量   
zeros_tensor = torch.zeros(shape)   #创建一个全是0的张量    

In [8]:
m = torch.ones(5,3,dtype=torch.double)
n = torch.ones(5,3,dtype=torch.float)
print(f"m: {m}\n")
print(f"n: {n}\n")
print(m.size())  #获取张量的大小
print(m.shape)  #获取张量的形状

tensor = torch.rand(5,3)
print(f"shape of tensor: {tensor.shape}")
print(f"datatype of tensor: {tensor.dtype}")
print(f"device of tensor: {tensor.device}")


m: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

n: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

torch.Size([5, 3])
torch.Size([5, 3])
shape of tensor: torch.Size([5, 3])
datatype of tensor: torch.float32
device of tensor: cpu


In [ ]:
#设置张量在GPU上运算
# if torch.cuda.is_available():
#     tensor = tensor.to('cuda')



In [ ]:
#张量的索引与切片
tensor = torch.ones(4,4)
tensor[:,1] = 0   #将第二列的所有元素设置为0
print(tensor)

print("first row: ",tensor[0])  #获取第一行
print("first column: ",tensor[:,0])  #获取第一列
print("last column: ",tensor[...,-1])  #获取最后一列
print("last column: ",tensor[:,-1])  #获取最后一列



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
first row:  tensor([1., 0., 1., 1.])
first column:  tensor([1., 1., 1., 1.])
last column:  tensor([1., 1., 1., 1.])
last column:  tensor([1., 1., 1., 1.])


In [14]:

#张量的拼接
t1 = torch.cat([tensor,tensor,tensor],dim=1) #在第二维度上拼接
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [25]:
tensor1 = torch.tensor([[1,13],[2,45]])
# print(tensor1)#

# y1 = tensor1 @ tensor1.T  #矩阵乘法
# y2 = tensor1.matmul(tensor1.T)  #矩阵乘法
# y3 = torch.rand_like(tensor1)  #创建一个与tensor相同形状的张量
#这里要在后面加上 dtype=torch.float
# torch.matmul(tensor1,tensor1.T,out=y3)  #矩阵乘法
# print(y1)   
# print(y2)  
# print(y3)

y4 = tensor1 * tensor1  #对应元素相乘
print(y4)
y5 = tensor1.mul(tensor1)  #对应元素相乘
print(y5)
y6 = torch.rand_like(tensor1,dtype=torch.float)  #创建一个与tensor相同形状的张量
torch.mul(tensor1,tensor1,out=y6)  #对应元素相乘        
print(y6)


tensor([[   1,  169],
        [   4, 2025]])
tensor([[   1,  169],
        [   4, 2025]])
tensor([[1.0000e+00, 1.6900e+02],
        [4.0000e+00, 2.0250e+03]])


In [27]:
agg = tensor1.sum()  #求和
print(agg)
agg_item = agg.item()  #将张量的值转换为python数值
print(agg_item)

tensor(61)
61


In [30]:
print(tensor1)
print(tensor1.numpy())  #将张量转换为numpy数组 

tensor2 =tensor1.add(5)  #加法
print(tensor2)

#
n = np.ones(5)
t =torch.from_numpy(n)  #将numpy数组转换为张量
print(t)
n = t.numpy()  #将张量转换为numpy数组
print(n)


tensor([[ 1, 13],
        [ 2, 45]])
[[ 1 13]
 [ 2 45]]
tensor([[ 6, 18],
        [ 7, 50]])
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.]
