一 张量的创建

In [3]:
import numpy as np
import torch
#张量直接从数据中创建
a = [[16,12],[4,6]]
ts1 = torch.tensor(a)
print(ts1)

#  张量从numpy数组中创建 
b = np.array([[16,27,12],[4,5,6],[7,8,9]])
ts2 = torch.from_numpy(b)
print(ts2)

#张量从另外一个张量创建,保留of x_data的属性
ts3 = torch.ones_like(ts2)
print(f"ones tensor: \n {ts3}\n")

#张量从另外一个张量创建,覆盖 x_data的属性
ts4 = torch.rand_like(ts1, dtype=torch.float)
print(f"random tensor: \n {ts4}\n")

tensor([[16, 12],
        [ 4,  6]])
tensor([[16, 27, 12],
        [ 4,  5,  6],
        [ 7,  8,  9]], dtype=torch.int32)
ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

random tensor: 
 tensor([[0.9223, 0.0058],
        [0.2308, 0.7205]])



In [4]:
#随机值创建张量
shape =(4,5)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3233, 0.4934, 0.2579, 0.2368, 0.6110],
        [0.4387, 0.4332, 0.3634, 0.3094, 0.2486],
        [0.3811, 0.7582, 0.5013, 0.2447, 0.8084],
        [0.9252, 0.4102, 0.4594, 0.2842, 0.7794]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [10]:
# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)
# 获取tensor的⼤⼩
print(m.size()) # torch.Size([5,3])
# 均匀分布
torch.rand(5,3)
# 标准正态分布
torch.randn(5,3)
# 离散正态分布
torch.normal(mean=.0,std=1.0,size=(5,3))
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
torch.linspace(start=1,end=10,steps=20)

torch.Size([5, 3])


tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [11]:
#张量的属性
print(f"tensor shape: {ts1.shape}")
print(f"tensor dtype: {ts1.dtype}")
print(f"tensor device: {ts1.device}")


tensor shape: torch.Size([2, 2])
tensor dtype: torch.int64
tensor device: cpu


二 张量运算

In [12]:
## 设置张量在GPU上运算
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [ ]:
#张量的索引和切⽚：
ts5 = torch.tensor([[1,7,3],[8,5,34],[7,34,339]])
# ts2[0]  展示第⼀⾏tensor([1, 7, 3])
# ts5[0:2]  # 展示前两⾏  
# ts5[0:2,1]  # 展示前两⾏的第⼆列tensor([7, 5])


# ts2[0,2]  第⼀⾏第三列   tensor(3)
# ts5[:,0]  # 展示第⼀列 tensor([1, 8, 7])
# ts5[...,0]  # 第⼀列
ts5[1,2]   # 第⼆⾏第三列
# ts5[1,2] = 100  # 修改张量的值


tensor(34)

In [27]:
#张量的拼接
ts6 = torch.cat([ts5, ts2,ts3], dim=1)
ts6

tensor([[  1,   7,   3,   1,   7,   3,   1,   1,   1],
        [  8,   5,  34,   8,   5,  34,   1,   1,   1],
        [  7,  34, 339,   7,  34, 339,   1,   1,   1]])

In [28]:
#算术运算
ts5 = torch.tensor([[1,7,3],[8,5,34],[7,34,339]])
ts7 = torch.tensor([[51,0,9],[1,2,4],[34,22,339]])
# 加法
print(f"ts5 + ts7 = {ts5 + ts7}")
# 减法
print(f"ts5 - ts7 = {ts5 - ts7}")
# 乘法
print(f"ts5 * ts7 = {ts5 * ts7}")
# 除法
print(f"ts5 / ts7 = {ts5 / ts7}")


ts5 + ts7 = tensor([[ 52,   7,  12],
        [  9,   7,  38],
        [ 41,  56, 678]])
ts5 - ts7 = tensor([[-50,   7,  -6],
        [  7,   3,  30],
        [-27,  12,   0]])
ts5 * ts7 = tensor([[    51,      0,     27],
        [     8,     10,    136],
        [   238,    748, 114921]])
ts5 / ts7 = tensor([[0.0196,    inf, 0.3333],
        [8.0000, 2.5000, 8.5000],
        [0.2059, 1.5455, 1.0000]])


In [ ]:
ts5 = torch.tensor([[1,7,3],[8,5,34],[7,34,339]])
ts7 = torch.tensor([[51,0,9],[1,2,4],[34,22,339]])
s =ts5 @ ts7
print(f"ts5 @ ts7 = {s}")
u = ts5.matmul(ts7)
print(f"ts5.matmul(ts7) = {u}")



ts5 @ ts7 = tensor([[   160,     80,   1054],
        [  1569,    758,  11618],
        [ 11917,   7526, 115120]])
ts5.matmul(ts7) = tensor([[   160,     80,   1054],
        [  1569,    758,  11618],
        [ 11917,   7526, 115120]])


NameError: name 'tensor' is not defined

In [31]:
#单元素张量聚合转换数值可以使⽤item()⽅法将其转换为 Python 数值
H = ts7.sum()
H_item = H.item()
print(H_item, type(H_item))

462 <class 'int'>


In [35]:
#In-place操作把计算结果存储到当前操作数中的操作
ts2 =torch.tensor([[12,33],[212,11]])
print(ts2, "\n")
ts2.add_(3232)
print(ts2)

tensor([[ 12,  33],
        [212,  11]]) 

tensor([[3244, 3265],
        [3444, 3243]])


In [2]:
#与numpy之间的转换---张量到numpy数组
print(ts7)
npy1 =ts7.numpy()
print(npy1)
# print(f'npy1:{n}')
ts7.add_(2)
print(npy1)

NameError: name 'ts7' is not defined

In [2]:
#与numpy之间的转换---Numpy数组到张量
b = np.array([[16,27,12],[4,5,6],[7,8,9]])
ts2 = torch.from_numpy(b)
print(ts2)
np.add(b, 21, out=b)
print(b)

tensor([[16, 27, 12],
        [ 4,  5,  6],
        [ 7,  8,  9]], dtype=torch.int32)
[[37 48 33]
 [25 26 27]
 [28 29 30]]


三 pytorch计算图可视化

In [1]:
import torch
from torchviz import make_dot
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)






d:\soft\anacona-tool\envs\py12\lib\site-packages\ipykernel_launcher.py:9: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3281.)
  if __name__ == "__main__":


'expression.png'