**练习 1.1：矩阵的特征值与特征向量
题目：创建一个随机的 3×3 矩阵，并计算其特征值和特征向量。**

In [ ]:
import numpy as np

# 创建一个随机的 3×3 矩阵
matrix = np.random.rand(3, 3)

# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("矩阵：\n", matrix)
print("特征值：\n", eigenvalues)
print("特征向量：\n", eigenvectors)

矩阵：
 [[0.51166035 0.53710759 0.13081581]
 [0.15652108 0.10612971 0.23807403]
 [0.67909128 0.03740372 0.82356746]]
特征值：
 [1.14604782+0.j         0.14765485+0.14506471j 0.14765485-0.14506471j]
特征向量：
 [[ 0.40225808+0.j          0.67034222+0.j          0.67034222-0.j        ]
 [ 0.26141548+0.j         -0.30197978+0.21666069j -0.30197978-0.21666069j]
 [ 0.87741118+0.j         -0.62540319-0.14621395j -0.62540319+0.14621395j]]



**练习 1.2：矩阵分解 题目：创建一个 4×4 的随机矩阵，并对其进行奇异值分解（SVD）**

In [ ]:
# 创建一个 4×4 的随机矩阵
matrix = np.random.rand(4, 4)

# 进行奇异值分解
U, S, Vt = np.linalg.svd(matrix)

print("矩阵 U：\n", U)
print("奇异值 S：\n", S)
print("矩阵 V^T：\n", Vt)

矩阵 U：
 [[-0.5870957   0.25972029 -0.45974213 -0.61359692]
 [-0.35211436 -0.8926161   0.20413088 -0.1938622 ]
 [-0.39384452 -0.12753085 -0.54360098  0.73015091]
 [-0.61336825  0.34571339  0.67191199  0.22977362]]
奇异值 S：
 [1.66621826 0.76637738 0.3830737  0.15219379]
矩阵 V^T：
 [[-0.27306812 -0.18042741 -0.41128904 -0.85071798]
 [-0.90925967  0.07890203  0.40047095  0.08151283]
 [ 0.31213328 -0.03911799  0.8153355  -0.48607677]
 [-0.0354044  -0.97963779  0.07544779  0.18265804]]


**练习 1.3：矩阵的逆与伪逆
题目：创建一个 5×5 的随机矩阵，并计算其逆矩阵和伪逆矩阵。**

In [ ]:
# 创建一个 5×5 的随机矩阵
matrix = np.random.rand(5, 5)

# 计算逆矩阵
inverse_matrix = np.linalg.inv(matrix)

# 计算伪逆矩阵
pinv_matrix = np.linalg.pinv(matrix)

print("原矩阵：\n", matrix)
print("逆矩阵：\n", inverse_matrix)
print("伪逆矩阵：\n", pinv_matrix)

原矩阵：
 [[0.36621122 0.85525691 0.62084391 0.20996974 0.51208281]
 [0.59303756 0.44670265 0.11135147 0.76817313 0.45444432]
 [0.88054519 0.386644   0.40561647 0.39228732 0.78942153]
 [0.96638982 0.56754776 0.52932911 0.45180814 0.2129374 ]
 [0.99236779 0.33774359 0.91173698 0.39104497 0.15577898]]
逆矩阵：
 [[-0.93342251 -0.97247197  0.74734107  2.15707171 -0.8304356 ]
 [ 0.9417903  -0.30709621 -0.66227955  1.86342302 -1.39101709]
 [ 0.65768191  0.23253918 -0.38973338 -2.11010205  2.01901358]
 [-0.09282166  2.17757127 -0.99422353 -1.58789173  1.16145642]
 [ 0.28809611  0.03355256  1.45182559 -1.44546163 -0.00697382]]
伪逆矩阵：
 [[-0.93342251 -0.97247197  0.74734107  2.15707171 -0.8304356 ]
 [ 0.9417903  -0.30709621 -0.66227955  1.86342302 -1.39101709]
 [ 0.65768191  0.23253918 -0.38973338 -2.11010205  2.01901358]
 [-0.09282166  2.17757127 -0.99422353 -1.58789173  1.16145642]
 [ 0.28809611  0.03355256  1.45182559 -1.44546163 -0.00697382]]


**练习 2.1：多维数组的切片与索引
题目：创建一个 3×4×5 的随机多维数组。提取其中第 2 行、第 3 列的所有元素，并将其值设置为 -1。**

In [ ]:
# 创建一个 3×4×5 的随机多维数组
array = np.random.rand(3, 4, 5)

# 提取第 2 行、第 3 列的所有元素，并设置为 -1
array[1, 2, :] = -1  # 第 2 行和第 3 列（索引从 0 开始）

print("修改后的数组：\n", array)

修改后的数组：
 [[[ 0.10079887  0.29813483  0.57698459  0.11066888  0.18791347]
  [ 0.41264096  0.93847569  0.54652773  0.22245645  0.69658256]
  [ 0.40988775  0.61758788  0.26475949  0.09155232  0.8632349 ]
  [ 0.83739953  0.09273224  0.55463366  0.1365873   0.67785624]]

 [[ 0.40146553  0.04858202  0.74857279  0.64554309  0.52581716]
  [ 0.82153162  0.09885012  0.30499013  0.7772186   0.35630398]
  [-1.         -1.         -1.         -1.         -1.        ]
  [ 0.69687345  0.85334931  0.96899227  0.82566279  0.06628087]]

 [[ 0.09858662  0.47500222  0.56413333  0.58329063  0.11978352]
  [ 0.23330615  0.46537836  0.68031827  0.18662762  0.5500308 ]
  [ 0.10217651  0.75932004  0.39964847  0.69959963  0.3417323 ]
  [ 0.96203185  0.77487631  0.64462209  0.9651079   0.27541367]]]


**练习 2.2：布尔索引与条件筛选
题目：创建一个 10×10 的随机数组，值在 [0, 1) 范围内。提取所有大于 0.5 的元素，并将其替换为 -1。**

In [ ]:
# 创建一个 10×10 的随机数组
array = np.random.rand(10, 10)

# 提取所有大于 0.5 的元素，并将其替换为 -1
array[array > 0.5] = -1

print("修改后的数组：\n", array)

修改后的数组：
 [[ 0.32869672 -1.          0.34595746  0.12418815 -1.         -1.
   0.47210857  0.26973162 -1.          0.44900034]
 [-1.         -1.          0.06813529 -1.          0.09234744 -1.
   0.42924171  0.36773215 -1.          0.04757293]
 [-1.          0.02696801 -1.          0.49061745 -1.          0.36448317
  -1.          0.01550313 -1.          0.20059714]
 [ 0.0854446   0.48936298 -1.          0.10878461 -1.         -1.
  -1.         -1.          0.46541817 -1.        ]
 [-1.          0.26295231 -1.          0.48744161  0.10765034  0.43562461
   0.33907285 -1.          0.46134824 -1.        ]
 [-1.         -1.          0.20621618  0.09796066 -1.         -1.
  -1.          0.01608813  0.17238208  0.33676971]
 [ 0.11223791  0.06783657  0.29483364 -1.          0.02414556  0.42295465
  -1.         -1.         -1.          0.30166365]
 [-1.         -1.          0.18979343 -1.         -1.          0.01410748
   0.18308396 -1.          0.01945923 -1.        ]
 [ 0.32050594  0.086101

**练习 2.3：数组的广播与运算
题目：创建两个数组：A 是一个 3×4 的随机数组，B 是一个长度为 4 的随机数组。计算 A 中每一行与 B 的点积。**

In [ ]:
# 创建两个数组
A = np.random.rand(3, 4)
B = np.random.rand(4)

# 计算 A 中每一行与 B 的点积
result = A @ B  # 或者使用 np.dot(A, B)

print("A：\n", A)
print("B：\n", B)
print("点积结果：\n", result)

A：
 [[0.18297155 0.81839466 0.23688411 0.67868471]
 [0.19432903 0.74543067 0.77271749 0.78210912]
 [0.1045489  0.73985376 0.12565807 0.43719972]]
B：
 [0.21606556 0.97882423 0.18470592 0.88668929]
点积结果：
 [1.48613473 1.6078467  1.15764631]


**练习 3.1：随机数生成与统计
题目：创建一个 100×100 的随机数组，值服从标准正态分布。计算每行的均值和标准差，并将结果存储到一个新的数组中。**

In [ ]:
# 创建一个 100×100 的随机数组，服从标准正态分布
array = np.random.normal(size=(100, 100))

# 计算每行的均值和标准差
means = np.mean(array, axis=1)
stds = np.std(array, axis=1)

# 将结果存储到一个新的数组中
result = np.vstack((means, stds)).T

print("每行的均值和标准差：\n", result)

每行的均值和标准差：
 [[-0.00818407  1.00048041]
 [ 0.00905545  1.071941  ]
 [ 0.15911637  1.03415624]
 [ 0.04837493  0.94226503]
 [ 0.09273964  1.02592182]
 [ 0.01219982  1.0282976 ]
 [-0.16716991  0.99222619]
 [ 0.02935051  1.07836836]
 [-0.10943271  0.92659554]
 [-0.07688783  0.92652886]
 [ 0.23920069  1.0601238 ]
 [ 0.02334554  0.94775205]
 [-0.00406625  0.937411  ]
 [-0.15084226  0.88124511]
 [-0.03193642  0.88673569]
 [-0.19430883  0.95393806]
 [ 0.13786293  1.06403744]
 [-0.04807341  0.80588813]
 [ 0.02226144  1.00625893]
 [-0.03984794  0.88497857]
 [ 0.11897899  0.90995986]
 [ 0.13361624  1.01685422]
 [ 0.10482886  0.88028008]
 [-0.1091583   0.98805937]
 [ 0.12183663  0.92943337]
 [ 0.1821306   0.9991502 ]
 [-0.00421595  0.93463479]
 [-0.04022859  0.91420221]
 [-0.00766473  0.95637838]
 [ 0.14992135  1.03095481]
 [ 0.00221183  1.01983107]
 [-0.12040496  1.07071735]
 [-0.07744226  1.02552725]
 [-0.00763463  0.97729454]
 [ 0.04287289  1.04937219]
 [ 0.09715118  1.05583358]
 [ 0.09999199  1

**题目：创建一个 10×10 的随机整数数组，范围为 [1, 100]。从数组中随机抽取 10 个元素，允许重复。**

In [ ]:
# 创建一个 10×10 的随机整数数组
array = np.random.randint(1, 101, size=(10, 10))

# 随机抽取 10 个元素，允许重复
sample = np.random.choice(array.flatten(), size=10, replace=True)

print("原始数组：\n", array)
print("随机抽样结果：\n", sample)

原始数组：
 [[ 47  52  81  57   6  85  92  62  31  13]
 [ 69  11  50  42  44   8  82  49  61  43]
 [ 34  61  75  30  12 100  31  40  30  96]
 [ 84  26  61  41  21  52  26  98  29  23]
 [ 33  98  16  49  56  50  28  42  68  25]
 [ 83  11  63  87  97  67  90  25  21  60]
 [ 41  96  57  23  45  87  64  20  70  77]
 [ 65 100  75  32  83  17  10  88  63  38]
 [ 76  99  24  12  91  71  70  69  19  98]
 [  5  94  73  34  48  97  46  22  30  16]]
随机抽样结果：
 [20 65 52 77 12 22 22 83 25 98]


**练习 3.3：直方图与统计
题目：创建一个 1000×1 的随机数组，值服从均匀分布 [0, 10]。计算其直方图，将范围分为 10 个区间，并返回每个区间的计数。**

In [ ]:
# 创建一个 1000×1 的随机数组，服从均匀分布 [0, 10]
array = np.random.uniform(0, 10, size=1000)

# 计算直方图，将范围分为 10 个区间
hist, bins = np.histogram(array, bins=10, range=(0, 10))

print("直方图计数：\n", hist)
print("区间划分：\n", bins)

直方图计数：
 [140 105 101  98  99  87  88  97 100  85]
区间划分：
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


**练习 4.1：数组的堆叠
题目：创建两个 3×3 的随机数组 A 和 B。将它们沿行方向堆叠成一个 6×3 的数组，再沿列方向堆叠成一个 3×6 的数组。**

In [ ]:
# 创建两个 3×3 的随机数组
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# 沿行方向堆叠
row_stack = np.vstack((A, B))

# 沿列方向堆叠
col_stack = np.hstack((A, B))

print("沿行方向堆叠：\n", row_stack)
print("沿列方向堆叠：\n", col_stack)

沿行方向堆叠：
 [[0.17041223 0.73264358 0.50226309]
 [0.84833343 0.08780218 0.06942786]
 [0.87582434 0.2628689  0.61479676]
 [0.93449386 0.14044956 0.0597752 ]
 [0.21141261 0.8230412  0.84731361]
 [0.67600283 0.53707674 0.07413411]]
沿列方向堆叠：
 [[0.17041223 0.73264358 0.50226309 0.93449386 0.14044956 0.0597752 ]
 [0.84833343 0.08780218 0.06942786 0.21141261 0.8230412  0.84731361]
 [0.87582434 0.2628689  0.61479676 0.67600283 0.53707674 0.07413411]]


**练习 4.2：数组的拆分
题目：创建一个 6×6 的随机数组。将其沿行方向拆分为 3 个 2×6 的数组，再沿列方向拆分为 3 个 6×2 的数组。**

In [ ]:
# 创建一个 6×6 的随机数组
array = np.random.rand(6, 6)

# 沿行方向拆分
row_split = np.split(array, 3, axis=0)

# 沿列方向拆分
col_split = np.split(array, 3, axis=1)

print("沿行方向拆分：\n", row_split)
print("沿列方向拆分：\n", col_split)

沿行方向拆分：
 [array([[0.93807855, 0.5121059 , 0.9585033 , 0.66740027, 0.72852062,
        0.93841085],
       [0.13268213, 0.49834978, 0.40667712, 0.93289021, 0.0894141 ,
        0.46833997]]), array([[0.93555777, 0.57434688, 0.2265648 , 0.22695887, 0.66246911,
        0.04055954],
       [0.103774  , 0.11736627, 0.06512668, 0.9399776 , 0.94364672,
        0.54570452]]), array([[0.74565528, 0.50286066, 0.77844835, 0.49504334, 0.10614232,
        0.88633123],
       [0.79476621, 0.90014485, 0.70648025, 0.93487934, 0.97222133,
        0.65925353]])]
沿列方向拆分：
 [array([[0.93807855, 0.5121059 ],
       [0.13268213, 0.49834978],
       [0.93555777, 0.57434688],
       [0.103774  , 0.11736627],
       [0.74565528, 0.50286066],
       [0.79476621, 0.90014485]]), array([[0.9585033 , 0.66740027],
       [0.40667712, 0.93289021],
       [0.2265648 , 0.22695887],
       [0.06512668, 0.9399776 ],
       [0.77844835, 0.49504334],
       [0.70648025, 0.93487934]]), array([[0.72852062, 0.93841085],
       

In [ ]:
import numpy as np

In [ ]:
# 创建ndarray数组
arr = np.array([1,2,3,4,5], float)
arr

array([1., 2., 3., 4., 5.])

In [ ]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a1 = np.zeros((2,3), dtype=np.float32)
a1

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [ ]:
a2 = np.arange(1,6, 0.3)
a2

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8])

In [ ]:
a3 = np.eye(3)
a3  # one-hot编码

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a4 = np.random.random(5)  # 模型运算参数初始值
a4

array([0.85197818, 0.53542747, 0.69376428, 0.35640313, 0.62931527])

In [ ]:
a5 = np.random.normal(0, 0.1, 5)  # 模型运算参数初始值
a5

array([ 0.09843588,  0.22422758,  0.02775411, -0.03748287,  0.20932644])

In [ ]:
a6 = np.array([(1,2), (3,4), (5,6)])
# print(a6)
print(a6[:,1])

[2 4 6]


In [ ]:
a7 = np.array([(1,2), (3,4), (5,6)])
# i,j = a7[0]
for i,j in a7:
    print(i,j)

1 2
3 4
5 6


In [ ]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int64


In [ ]:
print(3 in a)

True


In [ ]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,3,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [ ]:
print(a)
a = a.T
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
a = a.flatten()
print(a)

[1 4 7 2 5 8 3 6 9]


In [ ]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,:,np.newaxis]  # [3,1,2]
a8.shape

(3, 2, 1)

In [ ]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]


In [ ]:
a.sum()

4.0

In [ ]:
a.prod()

1.0

In [ ]:
# 数组，矩阵、维度

# 数组、矩阵  ： 数据组织结构形式

# 维度： 通讯地址

In [ ]:
a = np.array([5,3,1])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

mean: 3.0
var: 2.6666666666666665
std: 1.632993161855452


In [ ]:
a = np.array([1.02, 3.8, 4.9])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [ ]:
a = np.array([16,31,12,28,22,31,48])
a.sort()  # 排序
a

array([12, 16, 22, 28, 31, 31, 48])

In [ ]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [ ]:
a9 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[4,5,6],[7,8,9]])

a9 * b9

array([[ 4, 10, 18],
       [28, 40, 54]])

In [ ]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [ ]:
np.save('result.npy',manual_result)

In [ ]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [ ]:
a = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
b = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])

In [1]:
import numpy as np

# 创建一个随机的 3×3 矩阵
matrix = np.random.rand(3, 3)

# 计算特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("矩阵：\n", matrix)
print("特征值：\n", eigenvalues)
print("特征向量：\n", eigenvectors)

矩阵：
 [[0.09163492 0.63017795 0.67635724]
 [0.28184355 0.91578172 0.38013454]
 [0.52808837 0.50590738 0.82545079]]
特征值：
 [ 1.64471852 -0.26635918  0.45450809]
特征向量：
 [[-0.51069553 -0.91218186  0.15030869]
 [-0.54445976  0.08884209 -0.68182061]
 [-0.66539736  0.40003917  0.71591058]]
