In [3]:
import numpy as np
# 创建ndarray数组
arr = np.array([1,2,3,4,5,6], int)
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(a)
print(a.T)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)


In [8]:
a1 = np.zeros((3,4), dtype=np.int64)
a1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [18]:
a2 = np.arange(1,7, 0.5)
a2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [19]:
a3 = np.eye(4)
a3  # one-hot编码

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
a4 = np.random.random(7)  # 模型运算参数初始值
a4

array([0.19039299, 0.36309417, 0.97666328, 0.61508596, 0.51404943,
       0.15603949, 0.22036667])

In [22]:
a5 = np.random.normal(0, 0.1, 5)  # 模型运算参数初始值
a5

array([ 0.18569408, -0.01458741, -0.11511322,  0.00740185, -0.16238187])

In [27]:
a6 = np.array([(1,2), (3,4), (5,6)])
print(a6.T)
print(a6.T[:,1])

[[1 3 5]
 [2 4 6]]
[3 4]


In [28]:
a7 = np.array([(1,2), (3,4), (5,6),(7,8)])
# i,j = a7[0]
for i,j in a7:
    print(i,j)

1 2
3 4
5 6
7 8


In [16]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int64


In [22]:
print(3 in a)

True


In [32]:
a7 = np.arange(1,16)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,5,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(15,)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]
(3, 5, 1)


In [33]:
print(a)
a = a.T
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [30]:
a = a.flatten()
print(a)

[1 4 7 2 5 8 3 6 9]


In [39]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,:,np.newaxis]  # [3,1,2]
a8.shape

(3, 2, 1)

In [44]:
a = np.ones((3,2))
b = np.array([(-1,1),(-1,1),(-1,1)])
print(a)
print(b)
print('---------')
print(a+b)
print('---------')
print(a-b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]
 [-1  1]]
---------
[[0. 2.]
 [0. 2.]
 [0. 2.]]
---------
[[2. 0.]
 [2. 0.]
 [2. 0.]]


In [45]:
a.sum()

6.0

In [46]:
a.prod()

1.0

In [51]:
a = np.array([5,3,2,1,4])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

mean: 3.0
var: 2.0
std: 1.4142135623730951


In [53]:
a = np.array([1.021,1.02, 3.8, 4.9, 4.91])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 4
argmin: 1
ceil: [2. 2. 4. 5. 5.]
floor: [1. 1. 3. 4. 4.]
rint: [1. 1. 4. 5. 5.]


In [58]:
# a = np.array([16,31,12,28,22,31,48])
a = np.random.randint(0, 100, size=10)
print(a)
a.sort()
print(a)

[22  6 52 59 81 91 47 25 54 13]
[ 6 13 22 25 47 52 54 59 81 91]


In [59]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [64]:
a9 = torch.arange(1,7,dtype=torch.float64).reshape(2,3)
b9 = torch.arange(4,10,dtype=torch.float64).reshape(2,3)
a9 * b9

tensor([[ 4., 10., 18.],
        [28., 40., 54.]], dtype=torch.float64)

In [70]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[1, 5], [3, 7]], dtype=np.float32)
m2 = np.array([[5, 4], [2, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 5.]
 [3. 7.]]
矩阵 2:
[[5. 4.]
 [2. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[15. 44.]
 [29. 68.]]
使用 @ 运算符得到的矩阵乘法结果:
[[15. 44.]
 [29. 68.]]
1.0 * 5.0 = 5.0
5.0 * 2.0 = 10.0
结果矩阵[1,1]:15.0

1.0 * 4.0 = 4.0
5.0 * 8.0 = 40.0
结果矩阵[1,2]:44.0

3.0 * 5.0 = 15.0
7.0 * 2.0 = 14.0
结果矩阵[2,1]:29.0

3.0 * 4.0 = 12.0
7.0 * 8.0 = 56.0
结果矩阵[2,2]:68.0

手动推演结果:
[[15. 44.]
 [29. 68.]]


In [67]:
np.save('result.npy',manual_result)

In [68]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [71]:
a = np.array([2,3,4])
b = np.array([5,6,7])
a + b

array([ 7,  9, 11])

In [ ]:
a = np.array([(1,2), (2,2), (3,3), (4,4), (5,5)])  # shape(4,2)
b = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])