In [1]:
import torch

data = torch.tensor([[1,2],[3,4],[4,5]], dtype=torch.int32)
data

tensor([[1, 2],
        [3, 4],
        [4, 5]], dtype=torch.int32)

In [2]:
import numpy as np

np_array = np.array([[1,2],[3,4],[4,5]],dtype=np.float32)
data2 = torch.from_numpy(np_array)
data2

tensor([[1., 2.],
        [3., 4.],
        [4., 5.]])

In [3]:
data2.dtype

torch.float32

In [4]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float64)
data3

tensor([[0.4123, 0.6231],
        [0.2076, 0.2535],
        [0.4982, 0.0623]], dtype=torch.float64)

In [5]:
# 2个三行4列的参数
shape = (2,3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.0662, 0.0067, 0.6312, 0.5907],
         [0.4616, 0.8467, 0.5428, 0.8261],
         [0.8183, 0.8634, 0.9227, 0.2083]],

        [[0.7713, 0.9050, 0.6667, 0.6637],
         [0.8805, 0.6170, 0.1169, 0.6897],
         [0.5278, 0.5765, 0.3197, 0.8057]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [6]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,5, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([5, 5])
tensor([[0.2601, 0.2126, 0.6723],
        [0.3587, 0.1666, 0.6208],
        [0.0773, 0.0409, 0.4837],
        [0.4084, 0.2131, 0.3841],
        [0.8383, 0.8902, 0.0966]])
tensor([[-0.2596,  1.0519,  0.2797],
        [-1.3586,  1.6241, -1.6107],
        [-0.7226,  0.7714,  0.3573],
        [-1.0961,  0.3451, -0.4850],
        [-1.0017,  0.6777,  0.2602]])
tensor([[-0.3666, -1.7452, -2.0497],
        [ 0.0412, -0.4497, -1.1072],
        [-1.4811,  0.5105,  3.8835],
        [ 0.7603,  1.1126, -1.2170],
        [ 0.1127,  0.8509,  0.0128]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [7]:
tensor = torch.rand(3,4).reshape(12)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Device tensor is stored on: {tensor}")

Shape of tensor: torch.Size([12])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Device tensor is stored on: tensor([0.1207, 0.8266, 0.1334, 0.6238, 0.5499, 0.4386, 0.3097, 0.0608, 0.8531,
        0.0354, 0.4885, 0.7356])


In [17]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
cpu
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
cpu


In [20]:
tensor = torch.rand(5, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([0.6785, 0.2388, 0.6358, 0.7522])
First column:  tensor([0.6785, 0.4499, 0.9160, 0.0974, 0.8553])
Last column: tensor([0.7522, 0.6352, 0.0047, 0.6747, 0.6365])
tensor([[0.6785, 0.0000, 0.6358, 0.7522],
        [0.4499, 0.0000, 0.6434, 0.6352],
        [0.9160, 0.0000, 0.4326, 0.0047],
        [0.0974, 0.0000, 0.9139, 0.6747],
        [0.8553, 0.0000, 0.5196, 0.6365]])


In [26]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[2.0354, 0.0000, 1.9074, 2.2567, 2.0354, 0.0000, 1.9074, 2.2567, 2.0354,
         0.0000, 1.9074, 2.2567],
        [1.3497, 0.0000, 1.9301, 1.9057, 1.3497, 0.0000, 1.9301, 1.9057, 1.3497,
         0.0000, 1.9301, 1.9057],
        [2.7480, 0.0000, 1.2977, 0.0142, 2.7480, 0.0000, 1.2977, 0.0142, 2.7480,
         0.0000, 1.2977, 0.0142],
        [0.2923, 0.0000, 2.7417, 2.0242, 0.2923, 0.0000, 2.7417, 2.0242, 0.2923,
         0.0000, 2.7417, 2.0242],
        [2.5659, 0.0000, 1.5589, 1.9094, 2.5659, 0.0000, 1.5589, 1.9094, 2.5659,
         0.0000, 1.5589, 1.9094]])
torch.Size([5, 12])


In [8]:
import torch
tensor = torch.arange(1,13, dtype=torch.float32).reshape(3, 4)
print(tensor)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 30.,  70., 110.],
        [ 70., 174., 278.],
        [110., 278., 446.]])
tensor([[ 30.,  70., 110.],
        [ 70., 174., 278.],
        [110., 278., 446.]])
tensor([[ 30.,  70., 110.],
        [ 70., 174., 278.],
        [110., 278., 446.]])
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])


C:\Users\windows\AppData\Local\Temp\ipykernel_5524\3364241750.py:13: UserWarning: An output with one or more elements was resized since it had shape [3, 4], which does not match the required output shape [3, 3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:35.)
  torch.matmul(tensor, tensor.T, out=y3)


In [9]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

78.0 <class 'float'>


In [10]:
np_arr = z1.numpy()
np_arr

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.],
       [ 81., 100., 121., 144.]], dtype=float32)

In [11]:
print(tensor, "\n")
tensor.add_(5)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]]) 

tensor([[ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.]])


In [2]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\windows\AppData\Local\Temp\ipykernel_20544\604160287.py:12: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3687.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression.png'

In [1]:
import graphviz
dot = graphviz.Digraph(comment='Test Graph')
dot.node('A', 'Node A')
dot.node('B', 'Node B')
dot.edge('A', 'B')
dot.render('test.gv', view=True)  

'test.gv.pdf'