## numpy基础练习

In [71]:
%load_ext autoreload
%autoreload 2
import numpy as np

In [4]:
arr = np.array([2,3,7,8])
arr
brr = np.array([2,3,7,8],float)
brr

array([2., 3., 7., 8.])

In [5]:
a = np.array([(1, 2, 3),(4,5,6),(7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a1 = np.zeros((4,6), dtype=np.float32)
a1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)

In [8]:
# 生成等差数列
a2 = np.arange(1,8, 0.5) 
a2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

In [9]:
# 生成单位矩阵
a3 = np.eye(3)
a3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
a4 = np.random.random(3)  # 模型运算参数初始值
a4

array([0.47205081, 0.19003876, 0.05467443])

In [13]:
# 正态分布的随机值
a5 = np.random.normal(0, 0.2, 5)
a5

array([-0.33299428,  0.27168729, -0.06387473, -0.05242816, -0.16083272])

In [14]:
a6 = np.array([(1,2), (3,4), (5,6)])
print(a6[:,1])

[2 4 6]


In [15]:
a7 = np.array([(1,2), (3,4), (5,6)])
# i,j = a7[0]
for i,j in a7:
    print(i,j)

1 2
3 4
5 6


In [20]:
# 创建一个二维数组
a = np.array([(1,2,3), (4,5,6), (7,8,9)])

# 打印数组的维度信息
print("ndim:", a.ndim)
# 打印数组的形状信息
print("shape:", a.shape)
# 打印数组的元素总数
print("size", a.size)
# 打印数组元素的数据类型
print("dtype", a.dtype)
print((1,2,3) in a)

ndim: 2
shape: (3, 3)
size 9
dtype int32
True


In [21]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,3,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义


[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [22]:
# 数组的转置（行转列）
print(a)
a = a.T
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
# 展平
a = a.flatten()
print(a)

[1 4 7 2 5 8 3 6 9]


In [24]:
# 新增维度
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,:,np.newaxis]
a8.shape

(3, 2, 1)

In [25]:
# 数组运算
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]


In [26]:
a.sum() # 所有元素之和

4.0

In [27]:
# 所有元素之积
a.prod() 

1.0

In [28]:
# 均值、方差、标准差
a = np.array([1, 2, 3, 4, 5])
print(np.mean(a))
print(np.var(a))
print(np.std(a))

3.0
2.0
1.4142135623730951


In [29]:
a = np.array([1.5, 2.8, 5.9])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 2
argmin: 0
ceil: [2. 3. 6.]
floor: [1. 2. 5.]
rint: [2. 3. 6.]


In [30]:
a = np.array([16,31,12,28,22,31,48])
a.sort()  # 排序
a

array([12, 16, 22, 28, 31, 31, 48])

In [37]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [42]:
# 文件操作
np.save('result.npy',a)
np.savetxt('rt.txt',a)

In [43]:
# 读取
print(np.loadtxt('rt.txt'))
print(np.load('result.npy'))

[12. 16. 22. 28. 31. 31. 48.]
[12 16 22 28 31 31 48]


In [44]:
# numpy广播机制
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [49]:
a = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
b = np.array([-1,1]) # shape(2,)
# b = b.reshape((1,2))
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])

## pytorch基础
https://pytorch.org/


In [50]:
import torch

data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
data

tensor([[1., 2.],
        [3., 4.]])

In [51]:
import numpy as np

np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [53]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.2031, 0.3945],
        [0.8128, 0.0370]])

In [55]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3257, 0.0502, 0.1339],
        [0.0546, 0.8730, 0.6689]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [57]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=10))

torch.Size([5, 3])
tensor([[0.5632, 0.2424, 0.3779],
        [0.7391, 0.8392, 0.3213],
        [0.5462, 0.1749, 0.9052],
        [0.0591, 0.5994, 0.9861],
        [0.2490, 0.4822, 0.8544]])
tensor([[-2.3712,  0.0187,  1.5363],
        [-0.6087,  1.2279,  0.8016],
        [ 0.2634,  0.3633,  0.9317],
        [-0.5238,  1.4638, -1.3183],
        [-0.2456,  1.9411,  1.6753]])
tensor([[-0.7125, -0.0407, -0.0273],
        [ 1.3431,  0.0566,  2.0050],
        [-1.0421,  0.2504,  0.4675],
        [ 0.5320, -0.9218,  0.6438],
        [-0.0193,  1.1104,  2.8057]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [58]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [59]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.9090, 0.9235, 0.8127, 0.1726],
        [0.5807, 0.2368, 0.9741, 0.8804],
        [0.1892, 0.3420, 0.2204, 0.0870]])
cpu
tensor([[0.9090, 0.9235, 0.8127, 0.1726],
        [0.5807, 0.2368, 0.9741, 0.8804],
        [0.1892, 0.3420, 0.2204, 0.0870]])
cpu


In [60]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [61]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.]])
torch.Size([4, 12])


In [62]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [64]:
print(tensor)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
45.0 <class 'float'>


In [65]:
np_arr = z1.numpy()
np_arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [66]:
print(tensor, "\n")
tensor.add_(5)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [1]:
# 机器上需要安装https://graphviz.org/download/ 否则报错
# pytorch计算图可视化
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\juncheng\AppData\Local\Temp\ipykernel_31208\995729796.py:14: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\Users\dev-admin\Desktop\build42\libtorch_1738271764196\work\aten\src\ATen\native\TensorShape.cpp:3687.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression.png'