In [3]:
import torch

data = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float32)
data

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [4]:
import numpy as np

np_array = np.array([[1,2],[3,4],[5,6]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)

In [5]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.7155, 0.9700],
        [0.2650, 0.8021],
        [0.6850, 0.9806]])

In [6]:
shape = (3,4,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4945, 0.7965, 0.4149, 0.2291],
        [0.0233, 0.1812, 0.8640, 0.2184],
        [0.4333, 0.9115, 0.0268, 0.8606]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(4,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(4,3))
# 标准正态分布
print(torch.randn(4,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(4,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=19))

torch.Size([4, 3])
tensor([[0.4212, 0.6498, 0.3090],
        [0.9347, 0.9408, 0.3211],
        [0.2659, 0.0338, 0.8419],
        [0.6903, 0.6303, 0.7436]])
tensor([[-2.1944, -1.3300, -2.0376],
        [-1.0932,  0.7177,  0.5099],
        [ 0.3257, -0.1610,  0.8593],
        [ 1.6450,  0.2749, -1.4559]])
tensor([[-0.2692,  0.2100,  0.7357],
        [ 1.0687, -0.2699,  0.5674],
        [ 0.1341, -1.3857,  1.1401],
        [-0.4845,  0.9696,  0.6011]])
tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000])


In [9]:
tensor = torch.rand(5,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([5, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.4802, 0.2264, 0.5424, 0.7858],
        [0.7251, 0.0223, 0.2603, 0.9930],
        [0.6685, 0.7546, 0.5854, 0.7522],
        [0.8931, 0.2227, 0.3276, 0.7843],
        [0.7392, 0.3403, 0.4590, 0.9100]], device='cuda:0')
cuda:0
tensor([[0.4802, 0.2264, 0.5424, 0.7858],
        [0.7251, 0.0223, 0.2603, 0.9930],
        [0.6685, 0.7546, 0.5854, 0.7522],
        [0.8931, 0.2227, 0.3276, 0.7843],
        [0.7392, 0.3403, 0.4590, 0.9100]], device='cuda:0')
cuda:0


In [13]:
tensor = torch.ones(5, 5)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,2] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])


In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1 * 3)
print(t1.shape)

tensor([[3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.],
        [3., 3., 0., 3., 3.]])
torch.Size([15, 5])


In [18]:
import torch
tensor = torch.arange(1,17, dtype=torch.float32).reshape(4, 4)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])


In [19]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

136.0 <class 'float'>


In [20]:
np_arr = z1.numpy()
np_arr

array([[  1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.],
       [ 81., 100., 121., 144.],
       [169., 196., 225., 256.]], dtype=float32)

In [21]:
print(tensor, "\n")
tensor.add_(5)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]) 

tensor([[ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])


In [22]:
tensor

tensor([[ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])

In [25]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(3, 3, requires_grad=True)  # 3x3 的随机矩阵
b = torch.randn(3, requires_grad=True)     # 3 维的随机向量
c = torch.randn(1, requires_grad=True)     # 常数值
x = torch.randn(3, requires_grad=True)     # 3 维的随机向量

# 计算 x^T * A + b * x + c
result = torch.matmul(A, x) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})

# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

'expression.png'

In [26]:
import torch
#from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(3, 3,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(3,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(3, requires_grad=True)

result = torch.matmul(A, x.T)
print(result)

tensor([ 0.8113,  0.2139, -0.1990], grad_fn=<MvBackward0>)


In [28]:
print(x)
print(x.T)

tensor([-0.5765, -0.7762,  0.5546], requires_grad=True)
tensor([-0.5765, -0.7762,  0.5546], grad_fn=<PermuteBackward0>)
