In [2]:
import numpy as np
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [3]:
a=np.array([1,2,3],float)
a

array([1., 2., 3.])

In [4]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a=np.zeros((5,7),dtype=float)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [16]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a=np.arange(10,0,-1)
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [21]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.random(3)

array([0.81144316, 0.89721584, 0.06735134])

In [ ]:
#均值为mu,标准差为sigma 
mu,sigma=10,100
np.random.normal(mu,sigma,10)

array([ 187.34739302,   -5.481507  , -203.91442413, -180.24790991,
         16.52277416,  145.03943642, -189.92745137,  -78.07507856,
        -23.74551422,   51.68017936])

In [30]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
a[2]

array([7, 8, 9])

In [34]:
a[2:]

array([[7, 8, 9]])

In [33]:
a[:,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
a[2][2]

np.int64(9)

In [36]:
a=np.arange(1,10,2)
for i in a:
    print(i)

1
3
5
7
9


In [38]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
for i,j,k in a :
    print(i*j*k)

6
120
504


In [44]:
a=np.arange(1,10,1)
a=a.reshape(3,3)
print(f"ndim:{a.ndim}")
print(f"shape:{a.shape}")
print(f"size:{a.size}")
print(f"dtype:{a.dtype}")

ndim:2
shape:(3, 3)
size:9
dtype:int64


In [48]:
a=np.arange(1,5,1)
print(a)
a=a.reshape(2,2)
print(a)
print(3 in a )
print(5 in a )

[1 2 3 4]
[[1 2]
 [3 4]]
True
False


In [52]:
a=np.zeros([5,6])
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
a.reshape(3,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
a=np.array([(1,2,3),(4,5,6)])
a.transpose()


array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
a=np.array([(1,2),(3,4),[3,3]])
a.shape

(3, 2)

In [67]:
b=np.array([1,2,3,4])
b.shape
b

array([1, 2, 3, 4])

In [70]:
a=a[:,np.newaxis]
a

array([[[1, 2]],

       [[3, 4]],

       [[3, 3]]])

In [71]:
a.shape

(3, 1, 2)

In [74]:
a=np.ones((2,3))
b=np.array([(1,2,3),(4,5,6)])
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]]


In [75]:
a+b

array([[2., 3., 4.],
       [5., 6., 7.]])

In [76]:
a-b

array([[ 0., -1., -2.],
       [-3., -4., -5.]])

In [77]:
a*b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [78]:
a/b

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [79]:
a=np.array([(1,2),(3,4)])
a.sum()


np.int64(10)

In [80]:
a.prod()

np.int64(24)

In [83]:
a=np.array([2,5,7,9])
print(f"mean:{a.mean()}")
print(f"var:{a.var()}")
print(f"std:{a.std()}")
print(f"max:{a.max()}")
print(f"min:{a.min()}")


mean:5.75
var:6.6875
std:2.5860201081971503
max:9
min:2


In [89]:
a=np.array([0.1,2.9,5.7,9.9,7.2])
print(f"argmax:{a.argmax()}")
print(f"argmin:{a.argmin()}")
print(f"ceil:{np.ceil(a)}")
print(f"floor:{np.floor(a)}")
print(f"rint:{np.rint(a)}")


argmax:3
argmin:0
ceil:[ 1.  3.  6. 10.  8.]
floor:[0. 2. 5. 9. 7.]
rint:[ 0.  3.  6. 10.  7.]


In [90]:
a=np.array([21,10,8,2,31,56])
a.sort()
a

array([ 2,  8, 10, 21, 31, 56])

In [97]:
import numpy as np
m1=np.array([(1,1),(2,3)],dtype=np.float32)
m2=np.array([(5,6),(7,8)],dtype=np.float32)

result_dot=np.dot(m1,m2)

result_at=m1@m2

print(f"矩阵1：m1\n{m1}")
print(f"矩阵2：\n{m2}")
print("使用np.dot得到的矩阵乘法结果：")
print(result_dot)
print("使用@运算符得到的矩阵乘法结果")
print(result_at)

矩阵1：m1
[[1. 1.]
 [2. 3.]]
矩阵2：
[[5. 6.]
 [7. 8.]]
使用np.dot得到的矩阵乘法结果：
[[12. 14.]
 [31. 36.]]
使用@运算符得到的矩阵乘法结果
[[12. 14.]
 [31. 36.]]


In [101]:
#手动推演
manul_result=np.zeros((m1.shape[0],m2.shape[1]),dtype=np.float32)

for i in range(m1.shape[0]):
    for j in range(m2.shape[0]):
        manul_result[i,j]=0
        for k in range(m1.shape[1]):
            print(f"{m1[i,k]*m2[k,j]}={m1[i,k]*m2[k,j]}")
            manul_result[i,j]+=m1[i,k]*m2[k,j]
        print(f"结果矩阵[{i+1},{j+1}]:{manul_result[i,j]}\n")
print("手动推演结果")
print(manul_result)

5.0=5.0
7.0=7.0
结果矩阵[1,1]:12.0

6.0=6.0
8.0=8.0
结果矩阵[1,2]:14.0

10.0=10.0
21.0=21.0
结果矩阵[2,1]:31.0

12.0=12.0
24.0=24.0
结果矩阵[2,2]:36.0

手动推演结果
[[12. 14.]
 [31. 36.]]


In [102]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [104]:
##广播，reshape 
a=np.array([(1,2),(2,2)])
b=np.array([5,6])
a+b

array([[6, 8],
       [7, 8]])