In [2]:
import torch 
data=[[1,2,3],[4,5,6]]
x_data=torch.tensor(data)
x_data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
import numpy as np 
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
x_np

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
x_ones=torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones}\n")

Ones Tensor:
 tensor([[1, 1, 1],
        [1, 1, 1]])



In [9]:
x_rand=torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor:\n{x_rand}\n")

Random Tensor:
tensor([[0.3941, 0.5622, 0.3820],
        [0.0541, 0.2071, 0.9383]])



In [11]:
shape=(5,6)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor} \n")
print(f"Ones Tensor:\n{ones_tensor} \n")
print(f"Zeros Tensor:\n{zeros_tensor} \n")

Random Tensor:
tensor([[0.7211, 0.7147, 0.1383, 0.6694, 0.9593, 0.5605],
        [0.7386, 0.9275, 0.4288, 0.7691, 0.0265, 0.4312],
        [0.8716, 0.9518, 0.5379, 0.0114, 0.4760, 0.0187],
        [0.8058, 0.5327, 0.6799, 0.9324, 0.5375, 0.0089],
        [0.8105, 0.4873, 0.4658, 0.4373, 0.1021, 0.5473]]) 

Ones Tensor:
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]) 

Zeros Tensor:
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]) 



In [ ]:
##基于现有tensor构建，但是使用新值填充
m=torch.ones(10,9,dtype=torch.double)
n=torch.rand_like(m,dtype=torch.float)

print(m.size())

##均匀分布
torch.rand(10,9)
##标准正态分布
torch.randn(5,3)
##离散
torch.normal(mean=1,std=2,size=(5,6))
##线性间隔向量
torch.linspace(start=10,end=100,steps=20)

torch.Size([10, 9])


tensor([ 10.0000,  14.7368,  19.4737,  24.2105,  28.9474,  33.6842,  38.4211,
         43.1579,  47.8947,  52.6316,  57.3684,  62.1053,  66.8421,  71.5789,
         76.3158,  81.0526,  85.7895,  90.5263,  95.2632, 100.0000])

In [24]:
tensor=torch.rand(2,5)
print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype of tensor :{tensor.dtype}")
print(f"Device tensor is stored on :{tensor.device}")

Shape of tensor:torch.Size([2, 5])
Datatype of tensor :torch.float32
Device tensor is stored on :cpu


In [ ]:
##设置在gpu运行
if torch.cuda.is_available():
    tensor=tensor.to('cuda')
    print("y")
print("n")


n


In [78]:
##张量的索引和切片
# tensor=torch.ones(5,6)
aa=np.array([[1,2,3],[6,7,8]])
print(aa.shape)
tensor=torch.tensor(aa,dtype=float)
print(f"First row:{tensor[0]}")
print(f"First column:{tensor[:,0]}")
print(f"Last column:{tensor[...,-1]}")
tensor[:,1]=0
print(tensor)

(2, 3)
First row:tensor([1., 2., 3.], dtype=torch.float64)
First column:tensor([1., 6.], dtype=torch.float64)
Last column:tensor([3., 8.], dtype=torch.float64)
tensor([[1., 0., 3.],
        [6., 0., 8.]], dtype=torch.float64)


In [79]:
##张量的拼接
t1=torch.cat([tensor,tensor,tensor],dim=0)
print(t1)

print()
t2=torch.cat([tensor,tensor,tensor],dim=1)
print(t2)

tensor([[1., 0., 3.],
        [6., 0., 8.],
        [1., 0., 3.],
        [6., 0., 8.],
        [1., 0., 3.],
        [6., 0., 8.]], dtype=torch.float64)

tensor([[1., 0., 3., 1., 0., 3., 1., 0., 3.],
        [6., 0., 8., 6., 0., 8., 6., 0., 8.]], dtype=torch.float64)


In [80]:
#算术运算
y1=tensor@tensor.T
y2=tensor.matmul(tensor.T)

y3=torch.rand_like(tensor)

torch.matmul(tensor,tensor.T,out=y3)

z1=tensor*tensor
z2=tensor.mul(tensor)

z3=torch.rand_like(tensor)

torch.mul(tensor,tensor,out=z3)

print(f"tensor:{tensor}")
print(f"y3 {y3}")
 
print(z1)
print()
print(z2)
print()
print(f"z3:{z3}")
print()




tensor:tensor([[1., 0., 3.],
        [6., 0., 8.]], dtype=torch.float64)
y3 tensor([[ 10.,  30.],
        [ 30., 100.]], dtype=torch.float64)
tensor([[ 1.,  0.,  9.],
        [36.,  0., 64.]], dtype=torch.float64)

tensor([[ 1.,  0.,  9.],
        [36.,  0., 64.]], dtype=torch.float64)

z3:tensor([[ 1.,  0.,  9.],
        [36.,  0., 64.]], dtype=torch.float64)



C:\Users\ZXD\AppData\Local\Temp\ipykernel_12128\793515796.py:7: UserWarning: An output with one or more elements was resized since it had shape [2, 3], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:35.)
  torch.matmul(tensor,tensor.T,out=y3)


In [81]:
agg=tensor.sum()
agg_item=agg.item()
print(agg_item,type(agg_item))

18.0 <class 'float'>


In [82]:
print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 3.],
        [6., 0., 8.]], dtype=torch.float64) 

tensor([[ 6.,  5.,  8.],
        [11.,  5., 13.]], dtype=torch.float64)


In [83]:
t=torch.ones(5)
print(f"t:{t}")
n=t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


In [84]:
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


In [85]:
n=np.ones(5)
t=torch.from_numpy(n)

In [86]:
np.add(n,1,out=n)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n:[2. 2. 2. 2. 2.]


In [102]:
import torch
from torchviz import make_dot

A=torch.randn(7,9,requires_grad=True)
b=torch.randn(9,requires_grad=True)
c=torch.randn(1,requires_grad=True)
x=torch.randn(9,requires_grad=True)

result=torch.matmul(A,x.T)+torch.matmul(b,x)+c
print(f"result:{result}")

dot=make_dot(result,params={'A':A,'b':b,'c':c,'x':x})
dot.render('expression001',format='png',cleanup=True,view=False)


result:tensor([ 1.4138,  5.8278, -0.2165,  1.2927, -0.7357,  2.2571,  5.6715],
       grad_fn=<AddBackward0>)


'expression001.png'