In [1]:
#初步实现
import torch
import torch.nn as nn  # 神经网络模块

#隐藏层

#线性层
linear1 = nn.Linear(784, 64, bias=True)  # 输入层，输出层，偏置
#激活层
# relu = nn.ReLU()  # 激活函数
act = nn.Sigmoid()  # 激活函数
#输出层
linear2 = nn.Linear(64, 10, bias=True)  # 输入层，输出层，偏置

#模拟输入
x = torch.randn(10, 784)
#前向传播
y = linear1(x)
print(y)
y = act(y)
print(y)
y = linear2(y)
print(y)
print(y.shape)

softmax = nn.Softmax(dim=1)  # 激活函数
final = softmax(y)  # 激活函数
print(final)

tensor([[ 0.4136, -0.0628,  1.1827,  0.1750, -0.6683, -1.3056, -0.2969,  0.8713,
         -0.1008, -0.5162,  0.5188, -0.1401, -0.2248, -0.6465,  0.1609, -0.0787,
          0.8236,  0.1788, -0.0614, -0.5464,  0.0271, -0.3060, -0.3624,  0.3365,
          0.0838, -0.2563,  0.5331, -0.2956,  0.0355, -0.1228, -0.9544, -0.0118,
          0.1606,  0.0952, -0.8931,  0.3993, -0.3682,  0.4910,  0.9280,  0.3702,
         -0.9988, -0.1009, -0.6129,  0.6124, -0.2254, -0.9078, -0.3138, -0.2307,
          0.0959,  0.3262,  0.2701,  0.4587,  1.1093, -0.0529,  0.5868, -0.2865,
          0.4867, -0.4911,  0.4757, -0.3317, -0.0545, -0.9095,  0.1863,  1.3674],
        [ 0.4054, -0.6503,  0.0757,  0.8748,  0.9158,  0.3395,  0.6988,  0.2723,
          1.3180,  0.1190, -0.5115, -0.3042, -1.0918,  0.0176,  1.0286,  0.4093,
         -0.2184,  0.4145, -0.2821, -0.2368,  0.1884, -0.3552,  0.4426,  0.3942,
          0.0550, -0.1717, -0.2401,  0.4309, -0.3672, -0.2401, -0.9265, -0.3679,
         -0.2627,  0.2386, 

In [4]:
#结构串联
model = nn.Sequential(
    nn.Linear(784, 64),
    nn.Sigmoid(),
    nn.Linear(64, 10)
)


loss_fn = nn.CrossEntropyLoss()  # 交叉熵损失函数
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)  # SGD优化器

[param for param in model.parameters()]

[Parameter containing:
 tensor([[-0.0126, -0.0266,  0.0290,  ...,  0.0174,  0.0216, -0.0312],
         [ 0.0271,  0.0183,  0.0115,  ...,  0.0097,  0.0148, -0.0065],
         [-0.0049,  0.0100, -0.0080,  ..., -0.0005,  0.0266, -0.0264],
         ...,
         [-0.0136, -0.0337,  0.0147,  ...,  0.0020,  0.0331, -0.0208],
         [ 0.0146,  0.0268, -0.0124,  ...,  0.0092,  0.0262,  0.0341],
         [ 0.0087, -0.0043,  0.0215,  ...,  0.0163,  0.0047,  0.0319]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0332,  0.0204,  0.0169,  0.0353,  0.0045, -0.0084,  0.0309, -0.0125,
         -0.0318,  0.0025,  0.0252, -0.0083,  0.0007, -0.0303,  0.0027, -0.0127,
          0.0303,  0.0135,  0.0096,  0.0284,  0.0142,  0.0040, -0.0078, -0.0156,
          0.0124,  0.0161, -0.0304, -0.0327,  0.0099, -0.0008, -0.0223,  0.0146,
         -0.0137, -0.0335,  0.0135,  0.0038, -0.0352,  0.0047, -0.0168, -0.0313,
         -0.0206, -0.0212, -0.0039, -0.0074, -0.0290, -0.0163,  0.0271, -0.0160