In [3]:
import numpy as np


In [4]:
#创建ndarray数组
arr = np.array([1,2,3,4], float)
arr

array([1., 2., 3., 4.])

In [5]:
# 创建多维数组
a = np.array([[1,2,3],[4,5,6]])
b = np.array([(4,2,3),(4,5,6)])

a
b


array([[4, 2, 3],
       [4, 5, 6]])

In [6]:
#创建占位符为0/1的2行3列数组
a1 = np.zeros((2,3),dtype=np.float64)
a2 = np.ones((2,3),dtype=np.float64)

a1
# a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#创建等差数列，[1.6,5),步长0.3
a2 = np.arange(1.6, 5, 0.3)
a2

array([1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6, 4.9])

In [8]:
# numpy.eye() 用于生成一个二维单位矩阵（identity matrix）。单位矩阵是一个方阵，在主对角线上（从左上到右下）全是 1，其余元素全是 0。
# 这个函数非常有用，尤其是在线性代数计算和矩阵操作中。
a3 = np.eye(3)
a3  # one-hot编码

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# 用于生成一个位于半开区间 [0.0, 1.0) 内的随机浮点数
a4 = np.random.random(5)
a4

array([0.40465077, 0.71837959, 0.19038928, 0.97612562, 0.25834512])

In [ ]:
#用于从正态分布（高斯分布）中生成随机数。正态分布由两个参数定义：均值（平均值）和标准差。函数的基本用法如下：
# numpy.random.normal(loc=0.0, scale=1.0, size=None)
# loc：这是正态分布的均值（平均值），默认为 0。
# scale：这是正态分布的标准差，默认为 1。
# size：这是输出的形状。如果提供整数，则返回该数量的样本；如果提供元组，则返回该形状的数组。
a5 = np.random.normal(0, 0.1, 5)
a5

array([ 0.05174661,  0.13246365,  0.1526548 , -0.00583591,  0.108788  ])

In [32]:
a6 = np.array([(1,2), (3,4), (5,6)])
print(a6)
print(a6[:,1])

[[1 2]
 [3 4]
 [5 6]]
[2 4 6]


In [ ]:
a7 = np.array([(1,2), (3,4), (5,6)])
# i,j = a7[0]
# for i,j in a7:
#     print(i,j)
# print(a7[0])
# print(a7[0:3])
print(a7[ : , :1])
print(a7[1][1])

1 2
3 4
5 6


In [39]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim) #维度
print("shape:", a.shape) #数组大小
print("size", a.size) #元素总数
print("dtype", a.dtype) #元素类型

ndim: 2
shape: (3, 3)
size 9
dtype int64


In [ ]:
#检查数值是否存在
a = np.array([(1,2),(3,4)])
print(1 in a)
print(5 in a)

True
False


In [47]:
#数组重排 reshape
a = np.zeros([2,3,4])
a
a = a.reshape(24)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#数组转置
a = np.array([(1,2,3),(4,5,6)])

# print(a.T)
print(a.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)

a7 = a7.reshape(3, 3, 1)  # 维度大小乘积 == 元素个数
print(a7)
print(a7.shape) # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽


[1 2 3 4 5 6 7 8 9]
(9,)
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
(3, 1, 3)


In [ ]:
#多维数组转成1维数组
a = a.flatten()
print(a)

[1 2 3 4 5 6]


In [64]:
# 增加维度
a = np.array([1,2,3])
print(a.shape)
a = a[:,np.newaxis]
print(a.shape)
print(a)


(3,)
(3, 1)
[[1]
 [2]
 [3]]


In [70]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,:,np.newaxis]  # [3,2,1]
print(a8.shape)
print(a8)

(3, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [86]:
# 数学操作
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
b = np.array([[-1,1],[-1,1]])

b.shape

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a.sum()) #数组内求和
print(a.prod()) #数组内求积


[[0. 2.]
 [0. 2.]]
[[2. 0.]
 [2. 0.]]
[[-1.  1.]
 [-1.  1.]]
[[-1.  1.]
 [-1.  1.]]
4.0
1.0


In [ ]:
#平均数、方差、标准差、最大值、最小值
a = np.array([5,3,1])
print(a.mean()) #平均数
print(a.var()) #方差
print(a.std()) #标准差
print(a.max()) #最大值
print(a.min()) #最小值

3.0
2.6666666666666665
1.632993161855452
5
1


In [ ]:
# 最大最小值对应的索引 argmax, argmin
# 取元素值上限、下限、四舍五入
# 还有很多数据运算操作，它们的使⽤⽅式基本都类似，例如：abs,sign, sqrt, log,log10, exp, sin, cos, tan, arcsin, arccos, arctan, 
# sinh, cosh, tanh, arcsinh, arccosh,arctanh 等等

a = np.array([1.2, 4.9, 3.8])
print(a.argmax())
print(a.argmin())
print(np.ceil(a))
print(np.floor(a))
print(np.rint(a))
a.sort()
print(a)

1
0
[2. 5. 4.]
[1. 4. 3.]
[1. 5. 4.]
[1.2 3.8 4.9]


In [11]:
#矩阵乘法：内积运算

# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2) 
result_dot = np.dot(m1,m2) #使用np.dot进行矩阵乘法
result_at = m1 @ m2  #使用运算法@进行矩阵乘法，看个人习惯

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
print(manual_result)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    for j in range(m2.shape[1]):
        manual_result[i, j] = 0
        for k in range(m1.shape[1]):
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            manual_result[i, j] += m1[i, k] * m2[k, j]
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)      


矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
[[0. 0.]
 [0. 0.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [12]:
# 还有其他函数
# eig：特征值、特征向量
# inv: 逆
# qr: QR分解
# svd: 奇异值分解
# solve: 解线性方程 Ax=b
# lstsq: 计算Ax=b的最小二乘解

# 文件操作
# 二进制文件： np.save、np.load, 二进制文件会存储为.npy格式
# 文本文件： np.savetxt、np.loadtxt

np.save('result.npy',manual_result)

result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [114]:
# 广播机制：若运算中的2个数组形状不同时，numpy将自动触发广播机制
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b


a = np.array([(1, 2),(2, 3), (3, 3), (4, 4)]) #shape(4,2)
b = np.array([-1, 1]) # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
np.shape(a)
print(a)
print(b)
a + b
# np.shape(b)

[[1 2]
 [2 3]
 [3 3]
 [4 4]]
[-1  1]


array([[0, 3],
       [1, 4],
       [2, 4],
       [3, 5]])

In [116]:
# 张量
import torch

tensor = torch.arange(1, 10, dtype=torch.float32).reshape(3, 3)
print(tensor)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
# print(y1)
print(y2)

y3 = torch.rand_like(tensor) #创建与tensor相同shape的矩阵
torch.matmul(tensor, tensor.T, out=y3) # out输出赋值


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.float32
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])


tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])