# Numpy section


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
arr = arr.reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr = np.zeros(10, dtype=int)
arr = arr.reshape(2,5)
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
arr = np.ones([5,5], dtype=int)
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
var = np.random.random(5)
var = np.random.normal(10, .10, 15)
var

array([ 9.98648996,  9.94873822,  9.9239071 , 10.10084347, 10.19764845,
        9.90322374, 10.01967571, 10.16229774,  9.89797194, 10.10937162,
       10.00014213, 10.09194692,  9.96076728, 10.09843734,  9.99403389])

In [27]:
print(var.ndim)
print(var.shape)
print(var.size)
print(var.dtype)
print(var.itemsize)
print(var.data)

1
(15,)
15
float64
8


In [66]:
a = np.array([1,2,3,4,5,6])
print(a)
b = np.array([2,2,2,2,2,2])
a*b
a+b
a/b
a@b
np.dot(a, b)


[1 2 3 4 5 6]


42

In [58]:
a.sum()
a.prod()
a.min()
a.max()
a.mean()
a.std()
a.var()

2.9166666666666665

In [60]:
a.argmax()
a.argmin()
a.sort()
a

array([1, 2, 3, 4, 5, 6])

In [65]:
a = np.array([(1,2,3),(4,5,6)])
a = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
a
a.transpose()

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [85]:
b = np.arange(12).reshape(3,4,1)
c = np.arange(4, 10).reshape(3,1,2)
print(b)
print(c)
np.matmul(b,c)
np.matmul(b,c).shape

# np.dot(b,c)
# np.dot(b,c).shape

b[:,1]

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
[[[4 5]]

 [[6 7]]

 [[8 9]]]


array([[1],
       [5],
       [9]])

# Torch section

In [88]:
import torch
data = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float64)
data

d = torch.from_numpy(b)
d

tensor([[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]])

In [91]:
data = torch.rand_like(d, dtype=torch.float64)
data

tensor([[[0.4359],
         [0.8714],
         [0.8330],
         [0.8668]],

        [[0.7647],
         [0.5841],
         [0.1786],
         [0.6918]],

        [[0.5953],
         [0.0677],
         [0.2444],
         [0.1685]]], dtype=torch.float64)

In [96]:
m = torch.ones(4, 2, dtype=torch.float32)
m = torch.rand(5, 20, dtype=torch.float32)
m = torch.randn(5, 20, dtype=torch.float32)
m

tensor([[ 0.3490,  0.5632, -0.9741, -1.5875,  0.4334,  0.0290,  3.3796,  0.8706,
          0.8180, -1.3591,  0.9928, -0.3612, -1.5762,  0.5541, -0.2257, -1.3303,
         -0.9462, -1.1127, -0.5815,  0.2833],
        [ 2.1711,  0.9710,  0.6430,  0.7215, -0.6669, -0.3016,  0.3158, -1.5467,
          1.7384,  0.6924, -0.4850,  0.9734,  0.9139,  1.1350, -0.1684,  0.7427,
         -0.5061, -1.4259, -0.2062,  0.4130],
        [ 0.6030, -0.4947,  0.6664,  0.5638, -1.3042, -1.4027, -2.8305,  0.3032,
          0.8427,  0.7815, -1.3563,  0.4239,  0.2805, -0.0790, -0.5993,  2.2812,
          0.2432, -0.9404,  1.9652, -0.5728],
        [-0.6452,  0.2649, -1.9054,  0.7070, -0.4436,  1.0785,  1.2956,  1.5670,
         -0.0072, -2.9445, -1.2375,  0.5856, -0.2971, -0.3160, -0.5126,  0.8199,
          0.2683,  0.9971,  1.8101,  0.4586],
        [-1.9392,  2.3334,  3.2484,  0.1328, -0.4193, -0.3087, -1.1570, -0.7338,
          0.8340,  1.7096, -0.2323,  0.4561,  1.6425,  0.2234,  0.1921, -0.8299,
      

In [100]:
m.device
n = m.to("mps")
n
n.device

device(type='mps', index=0)

In [108]:
agg = n.sum()
agg
agg.item()


10.834550857543945

In [112]:
a = torch.ones_like(agg)
a
b = torch.zeros_like(n)
b
b.size()

torch.Size([5, 20])

In [120]:
c = torch.linspace(0, 9, 10)
c = c.reshape(2,5)
c

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [130]:
d = torch.normal(mean=1, std=1, size=(2,2))
d
e = torch.rand(3,4)
print(e)
print(e[0])
print(e[:, 0])
print(e[..., -1])


tensor([[0.9970, 0.1494, 0.5850, 0.3594],
        [0.3801, 0.5138, 0.8945, 0.3670],
        [0.9490, 0.5628, 0.6240, 0.3953]])
tensor([0.9970, 0.1494, 0.5850, 0.3594])
tensor([0.9970, 0.3801, 0.9490])
tensor([0.3594, 0.3670, 0.3953])


In [139]:
print(d)
print(d.T)
print(d.transpose(0,1))
print(d @ d.T)
print(d * d.T)
print(torch.matmul(d, d.T))
print(torch.mul(d, d.T))
print(d * d.T)

tensor([[ 0.3821, -1.7828],
        [ 0.3975,  0.1213]])
tensor([[ 0.3821,  0.3975],
        [-1.7828,  0.1213]])
tensor([[ 0.3821,  0.3975],
        [-1.7828,  0.1213]])
tensor([[ 3.3243, -0.0644],
        [-0.0644,  0.1728]])
tensor([[ 0.1460, -0.7087],
        [-0.7087,  0.0147]])
tensor([[ 3.3243, -0.0644],
        [-0.0644,  0.1728]])
tensor([[ 0.1460, -0.7087],
        [-0.7087,  0.0147]])
tensor([[ 0.1460, -0.7087],
        [-0.7087,  0.0147]])


In [141]:
d.add_(100)
d

tensor([[200.3821, 198.2172],
        [200.3975, 200.1213]])

In [146]:
k = torch.cat([d, d.T])
s = torch.stack([d, d.T])
print(k)
print(s)

tensor([[200.3821, 198.2172],
        [200.3975, 200.1213],
        [200.3821, 200.3975],
        [198.2172, 200.1213]])
tensor([[[200.3821, 198.2172],
         [200.3975, 200.1213]],

        [[200.3821, 200.3975],
         [198.2172, 200.1213]]])
