In [12]:
import numpy as np
import torch

## Numpy 功能测试

In [43]:
# 基本数组创建和属性
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("基础数组属性:")
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)
print("dtype:", a.dtype)

# 不同数据类型的数组
print("\n不同数据类型的数组:")
a_float32 = np.array([(1,2,3), (4,5,6)], dtype=np.float32)
a_float64 = np.array([(1,2,3), (4,5,6)], dtype=np.float64)
a_int32 = np.array([(1,2,3), (4,5,6)], dtype=np.int32)
print("float32:", a_float32)
print("float64:", a_float64)
print("int32:", a_int32)

# 特殊数组创建
print("\n特殊数组创建:")
zeros = np.zeros((3,4))  # 3行4列的零矩阵
ones = np.ones((2,3,2))  # 2x3x2的1矩阵
identity = np.eye(4)     # 4x4单位矩阵
diagonal = np.diag([1,2,3,4])  # 对角矩阵
print("zeros:\n", zeros)
print("ones:\n", ones)
print("identity:\n", identity)
print("diagonal:\n", diagonal)

# 序列数组
print("\n序列数组:")
seq1 = np.arange(0, 10, 0.5)    # 步长0.5
seq2 = np.linspace(0, 1, 5)     # 5个等间距点
seq3 = np.logspace(0, 2, 5)     # 对数等间距
print("arange:", seq1)
print("linspace:", seq2)
print("logspace:", seq3)

# 随机数组
print("\n随机数组:")
np.random.seed(42)  # 设置随机种子
rand_uniform = np.random.rand(3,3)        # 均匀分布
rand_normal = np.random.randn(3,3)        # 标准正态分布
rand_int = np.random.randint(1,10,(3,3))  # 随机整数
print("uniform:\n", rand_uniform)
print("normal:\n", rand_normal)
print("random int:\n", rand_int)

# 形状操作
print("\n形状操作:")
b = np.arange(12)
b1 = b.reshape(3,4)        # 重塑为3x4
b2 = b.reshape(2,2,3)      # 重塑为2x2x3
b3 = b.reshape(3,-1)       # 自动计算列数
print("原始:", b)
print("reshape(3,4):\n", b1)
print("reshape(2,2,3):\n", b2)
print("reshape(3,-1):\n", b3)

# 数组组合
print("\n数组组合:")
c1 = np.array([1,2,3])
c2 = np.array([4,5,6])
v_stack = np.vstack((c1,c2))    # 垂直堆叠
h_stack = np.hstack((c1,c2))    # 水平堆叠
tile_arr = np.tile(c1, (2,2))   # 重复数组
print("vstack:\n", v_stack)
print("hstack:", h_stack)
print("tile:\n", tile_arr)

# 条件索引和布尔索引
print("\n条件索引:")
d = np.array([1.2, -3.4, 5.6, -7.8, 9.0])
print("正数:", d[d > 0])
print("负数:", d[d < 0])
print("绝对值大于5的元素:", d[np.abs(d) > 5])

# 统计运算
print("\n统计运算:")
e = np.array([[1,2,3], [4,5,6]])
print("总和:", e.sum())
print("按行求和:", e.sum(axis=0))
print("按列求和:", e.sum(axis=1))
print("累积和:", e.cumsum())
print("最大值:", e.max())
print("最小值:", e.min())
print("平均值:", e.mean())
print("标准差:", e.std())

基础数组属性:
ndim: 2
shape: (3, 3)
size: 9
dtype: int32

不同数据类型的数组:
float32: [[1. 2. 3.]
 [4. 5. 6.]]
float64: [[1. 2. 3.]
 [4. 5. 6.]]
int32: [[1 2 3]
 [4 5 6]]

特殊数组创建:
zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
diagonal:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

序列数组:
arange: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
linspace: [0.   0.25 0.5  0.75 1.  ]
logspace: [  1.           3.16227766  10.          31.6227766  100.        ]

随机数组:
uniform:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
normal:
 [[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]
random int:
 [[3 7 4]
 [9 3 5]
 [3 7 5]]

形状操作:
原始: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape(3,4):
 [[ 0  1  2 

## Pytorch 功能测试

In [44]:
# 基本张量创建和属性
data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
print("基础张量属性:")
print("维度数:", data.dim())
print("形状:", data.shape)
print("数据类型:", data.dtype)
print("设备:", data.device)

# 不同数据类型的张量
print("\n不同数据类型的张量:")
data_float16 = torch.tensor([[1,2],[3,4]], dtype=torch.float16)
data_float64 = torch.tensor([[1,2],[3,4]], dtype=torch.float64)
data_int32 = torch.tensor([[1,2],[3,4]], dtype=torch.int32)
print("float16:", data_float16)
print("float64:", data_float64)
print("int32:", data_int32)

# 特殊张量创建
print("\n特殊张量创建:")
zeros = torch.zeros(3,4)
ones = torch.ones(2,3,2)
eye = torch.eye(4)
diag = torch.diag(torch.tensor([1,2,3,4]))
print("zeros:\n", zeros)
print("ones:\n", ones)
print("eye:\n", eye)
print("diagonal:\n", diag)

# 序列张量
print("\n序列张量:")
arange = torch.arange(0, 10, 0.5)
linspace = torch.linspace(0, 1, 5)
logspace = torch.logspace(0, 2, 5)
print("arange:", arange)
print("linspace:", linspace)
print("logspace:", logspace)

# 随机张量
print("\n随机张量:")
torch.manual_seed(42)
rand_uniform = torch.rand(3,3)
rand_normal = torch.randn(3,3)
rand_int = torch.randint(1,10,(3,3))
print("uniform:\n", rand_uniform)
print("normal:\n", rand_normal)
print("random int:\n", rand_int)

# 形状操作
print("\n形状操作:")
b = torch.arange(12)
b1 = b.reshape(3,4)
b2 = b.view(2,2,3)
b3 = b.reshape(3,-1)
print("原始:", b)
print("reshape(3,4):\n", b1)
print("view(2,2,3):\n", b2)
print("reshape(3,-1):\n", b3)

# 张量组合
print("\n张量组合:")
c1 = torch.tensor([1,2,3])
c2 = torch.tensor([4,5,6])
v_stack = torch.vstack((c1,c2))
h_stack = torch.hstack((c1,c2))
repeat = c1.repeat(2,2)
print("vstack:\n", v_stack)
print("hstack:", h_stack)
print("repeat:\n", repeat)

# 条件索引和布尔索引
print("\n条件索引:")
d = torch.tensor([1.2, -3.4, 5.6, -7.8, 9.0])
print("正数:", d[d > 0])
print("负数:", d[d < 0])
print("绝对值大于5的元素:", d[torch.abs(d) > 5])

# 数学运算
print("\n数学运算:")
e = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
print("总和:", e.sum())
print("按行求和:", e.sum(dim=0))
print("按列求和:", e.sum(dim=1))
print("累积和:", e.cumsum(dim=0))
print("最大值:", e.max())
print("最小值:", e.min())
print("平均值:", e.mean())
print("标准差:", e.std())

# GPU支持
if torch.cuda.is_available():
    print("\nGPU操作:")
    cuda_tensor = e.cuda()
    print("GPU设备:", cuda_tensor.device)
    print("GPU上的计算:", cuda_tensor + cuda_tensor)
    cpu_tensor = cuda_tensor.cpu()
    print("转回CPU:", cpu_tensor)

# 梯度计算
print("\n自动求导:")
x = torch.tensor([2.0], requires_grad=True)
y = x ** 2 + 2*x + 1
y.backward()
print("x:", x)
print("y:", y)
print("dy/dx:", x.grad)

# 与NumPy互操作
print("\n与NumPy互操作:")
numpy_array = e.numpy()
back_to_tensor = torch.from_numpy(numpy_array)
print("转为NumPy:", numpy_array)
print("转回PyTorch:", back_to_tensor)

基础张量属性:
维度数: 2
形状: torch.Size([2, 2])
数据类型: torch.float32
设备: cpu

不同数据类型的张量:
float16: tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)
float64: tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
int32: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

特殊张量创建:
zeros:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones:
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
eye:
 tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
diagonal:
 tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])

序列张量:
arange: tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])
linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
logspace: tensor([  1.0000,   3.1623, 

In [45]:
# 导入可视化工具
from torchviz import make_dot

# 创建计算图示例
print("\n计算图示例:")

# 简单的线性计算图
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
z = x * y + torch.pow(x, 2)
print("计算结果:", z)
print("计算图节点:")
print("- x:", x)
print("- y:", y)
print("- z:", z)
make_dot(z, params={"x": x, "y": y}).render("simple_graph", format="png")

# 复杂的多层计算图
def create_complex_graph():
    a = torch.randn(3, requires_grad=True)
    b = torch.randn(3, requires_grad=True)
    c = a + b
    d = a * b
    e = torch.sum(c)
    f = torch.sum(d)
    g = e + f
    return g, {"a": a, "b": b}

result, params = create_complex_graph()
print("\n复杂计算图结果:", result)
make_dot(result, params=params).render("complex_graph", format="png")

# 神经网络计算图
class SimpleNet(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = torch.nn.Linear(2, 3)
        self.fc2 = torch.nn.Linear(3, 1)
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

net = SimpleNet()
sample_input = torch.randn(1, 2, requires_grad=True)
output = net(sample_input)
print("\n神经网络输出:", output)
make_dot(output, params=dict(list(net.named_parameters()) + [('input', sample_input)])).render("neural_net_graph", format="png")

# 带有分支的计算图
def create_branched_graph():
    x = torch.tensor(2.0, requires_grad=True)
    y = x * 2
    z = x ** 2
    w = y + z
    v = y * z
    return w + v, {"x": x}

branch_result, branch_params = create_branched_graph()
print("\n分支计算图结果:", branch_result)
make_dot(branch_result, params=branch_params).render("branched_graph", format="png")

# 查看梯度流
print("\n梯度流分析:")
branch_result.backward()
for name, param in branch_params.items():
    print(f"{name} 的梯度:", param.grad)


计算图示例:
计算结果: tensor(10., grad_fn=<AddBackward0>)
计算图节点:
- x: tensor(2., requires_grad=True)
- y: tensor(3., requires_grad=True)
- z: tensor(10., grad_fn=<AddBackward0>)

复杂计算图结果: tensor(-0.4482, grad_fn=<AddBackward0>)

神经网络输出: tensor([[-0.0817]], grad_fn=<AddmmBackward0>)

分支计算图结果: tensor(24., grad_fn=<AddBackward0>)

梯度流分析:
x 的梯度: tensor(30.)
