In [43]:
##1、使用sklearn数据集训练逻辑回归模型；
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [61]:
#1.获取训练数据
# x,y = make_classification(n_features=10,n_samples=200)
#鸢尾花数据
data=load_iris()
x,y=data.data[:100],data.target[:100]

#分割数据
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7)

#权重参数
theta = np.random.randn(1,4)
bias = 0
#超参数
eta = 1e-3

In [45]:
#2.前向运算，计算y_hat
def cacl_y_hat(x,theta,bias):
    z = np.dot(theta,x.T) + bias
    y_hat = 1/(1+np.exp(-z))
    return y_hat

In [46]:
#3.loss函数
def cacl_loss(y,y_hat):
    e = 1e-8
    return np.mean(-y*np.log(y_hat+e)-(1-y)*np.log(1-y_hat+e))

In [47]:
#4.求偏导
def calc_derivate(x,y,y_hat):
    m = x.shape[0]
    delta_theta = (1/m)*np.dot(y_hat-y,x)
    delta_bias = np.mean(y_hat-y)
    return delta_theta,delta_bias

In [48]:
#5.梯度下降函数
def gradient_decent(x,y,theta,bias,eta,epoch=5000):
    #更新斜率直到loss<某值or达到循环上限
    i = 0
    while True:
        i += 1
        #求y_hat
        y_hat = cacl_y_hat(x,theta,bias)
        #计算loss
        loss = cacl_loss(y,y_hat)
        delta_theta,delta_bias = calc_derivate(x,y,y_hat)
        theta = theta - eta*delta_theta
        bias = bias - eta*delta_bias
        # if i%100==0:
        #     print(f'loss:{loss},bias:{bias}')
        if loss < 0.1  or i > epoch:
            print(i)
            return theta,bias

In [49]:
theta_after,bias_after = gradient_decent(x=x_train,y=y_train,theta=theta,bias=bias,eta=eta)
print(theta_after,bias_after)

5001
[[-0.44914292 -0.5633189   1.57172908 -0.05235427]] -0.20671589115831088


In [ ]:
#验证梯度下降后参数的准确率
def correct_rate(theta,bias,x_test,y_test):
    i=0
    correct_num=0
    all = y_test.shape[0]
    y_hat = cacl_y_hat(theta=theta,bias=bias,x=x_test)
    while i<all:
        if y_hat[0][i]>0.5:
            temp=1
        else:
            temp=0
        if temp==y_test[i]:
            correct_num+=1
        i+=1
    return correct_num/all

# correct_rate(theta_after,bias_after,x_test,y_test)

1.0

In [67]:
##2、调整学习率，样本数据拆分比率，观察训练结果；
#学习率eta=0.1、0.01、0.001，可见学习率越大所需循环次数越少
theta_after_1,bias_after_1 = gradient_decent(x=x_train,y=y_train,theta=theta,bias=bias,eta=0.1)
theta_after_2,bias_after_2 = gradient_decent(x=x_train,y=y_train,theta=theta,bias=bias,eta=0.01)
theta_after_3,bias_after_3 = gradient_decent(x=x_train,y=y_train,theta=theta,bias=bias,eta=0.001)
print(theta_after_1,bias_after_1)
print(theta_after_2,bias_after_2)
print(theta_after_3,bias_after_3)

65
640
5001
[[ 0.42287989 -1.68550084  0.89519747  0.7370891 ]] -0.1326535457909936
[[ 0.42579166 -1.67479371  0.87910043  0.73032731]] -0.13075216760759895
[[ 0.45419146 -1.58263449  0.7352123   0.66801181]] -0.113280419325434


In [52]:
#样本数据拆分比,，0.9、0.6、0.3、0.1
#通常增加数据有助于提高准确率，但不是绝对的，和学习率、数据质量、训练轮次、数据分布等等有关
data=load_iris()
x,y=data.data[:100],data.target[:100]

In [70]:
x_train_7,x_test_7,y_train_7,y_test_7 = train_test_split(x,y,train_size=0.9,shuffle=False) #分割数据
theta_after_7,bias_after_7 = gradient_decent(x=x_train_7,y=y_train_7,theta=theta,bias=bias,eta=0.001) #计算参数
rate_7 = correct_rate(theta_after_7,bias_after_7,x_test_7,y_test_7) #计算准确率

x_train_6,x_test_6,y_train_6,y_test_6 = train_test_split(x,y,train_size=0.6,shuffle=False)
theta_after_6,bias_after_6 = gradient_decent(x=x_train_6,y=y_train_6,theta=theta,bias=bias,eta=0.001)
rate_6 = correct_rate(theta_after_6,bias_after_6,x_test_6,y_test_6)

x_train_5,x_test_5,y_train_5,y_test_5 = train_test_split(x,y,train_size=0.3,shuffle=False)
theta_after_5,bias_after_5 = gradient_decent(x=x_train_5,y=y_train_5,theta=theta,bias=bias,eta=0.001)
rate_5 = correct_rate(theta_after_5,bias_after_5,x_test_5,y_test_5)

x_train_4,x_test_4,y_train_4,y_test_4 = train_test_split(x,y,train_size=0.1,shuffle=False)
theta_after_4,bias_after_4 = gradient_decent(x=x_train_4,y=y_train_4,theta=theta,bias=bias,eta=0.001)
rate_4 = correct_rate(theta_after_4,bias_after_4,x_test_4,y_test_4)

print(f'0.9准确率{rate_7}\n0.6准确率{rate_6}\n0.3准确率{rate_5}\n0.1准确率{rate_4}\n')

5001
5001
192
209
0.9准确率1.0
0.6准确率1.0
0.3准确率0.2857142857142857
0.1准确率0.4444444444444444



In [72]:
##3、训练后模型参数保存到文件，在另一个代码中加载参数实现预测功能；
np.save('theta',theta_after_7)
np.save('bias',bias_after_7)

theta_after_7,bias_after_7

(array([[ 0.43399691, -1.57993285,  0.73128132,  0.67716976]]),
 -0.1180061047028804)

In [54]:
#pytorch写法
import torch
#1.生成数据，转成张量
x,y = make_classification(n_features=10)
tensor_x = torch.tensor(x,dtype=torch.float)
tensor_y = torch.tensor(y,dtype=torch.float)

theta=torch.randn(1,10,requires_grad=True)
bias=torch.randn(1,requires_grad=True)
for i in range(5000):
    #2.前向运算
    y_hat = torch.nn.functional.linear(tensor_x,theta,bias)
    y_hat = torch.sigmoid(y_hat)
    #3.计算损失
    loss = torch.nn.functional.binary_cross_entropy(
        y_hat.squeeze(1),#去除维度为1的维度
        tensor_y,
        reduction='mean'
    )

    #4.计算梯度，梯度值保存在theta.grad、bias.grad中
    loss.backward()

    #5.参数更新
    with torch.autograd.no_grad(): #关闭梯度计算跟踪
        #梯度更新
        theta -= eta*theta.grad
        bias -= eta*bias.grad
        #清空梯度
        theta.grad.zero_()
        bias.grad.zero_()
    print(f'train loss:{loss.item():.4f}')

train loss:1.0997
train loss:1.0995
train loss:1.0992
train loss:1.0989
train loss:1.0986
train loss:1.0983
train loss:1.0981
train loss:1.0978
train loss:1.0975
train loss:1.0972
train loss:1.0969
train loss:1.0967
train loss:1.0964
train loss:1.0961
train loss:1.0958
train loss:1.0956
train loss:1.0953
train loss:1.0950
train loss:1.0947
train loss:1.0945
train loss:1.0942
train loss:1.0939
train loss:1.0936
train loss:1.0933
train loss:1.0931
train loss:1.0928
train loss:1.0925
train loss:1.0923
train loss:1.0920
train loss:1.0917
train loss:1.0914
train loss:1.0912
train loss:1.0909
train loss:1.0906
train loss:1.0903
train loss:1.0900
train loss:1.0898
train loss:1.0895
train loss:1.0892
train loss:1.0889
train loss:1.0887
train loss:1.0884
train loss:1.0881
train loss:1.0879
train loss:1.0876
train loss:1.0873
train loss:1.0870
train loss:1.0868
train loss:1.0865
train loss:1.0862
train loss:1.0859
train loss:1.0857
train loss:1.0854
train loss:1.0851
train loss:1.0848
train loss