In [ ]:
import numpy as np

# 1.Numpy基础数组创建-------
# 1.1 将list转化为np.array
a = [1,2,3]
b=np.array(a)
b

a = np.array([1,2,3],float)
a

# 1.2 创建多维数组
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 2.NumPy 特殊数组创建-------
# 2.1 通过占位符创建

#创建为0的矩阵
a=np.zeros((2,3),dtype=float)
a

# 创建为1的矩阵
a = np.ones((3,3))
a

#等差数列
a=np.arange(1,5,0.5)
a

#单位矩阵
a = np.eye(3)
a

#指定长度
np.random.random(5)

array([0.55413906, 0.3298561 , 0.867313  , 0.13433579, 0.02591641])

In [ ]:
# 3. NumPy 数组的访问-------
a=np.array([(1,2,3),(4,5,6), (7,8,9)])
a[0]

a[1:]

a[:,:1]

a[1][1]

5

In [ ]:
# 4. NumPy 数组的遍历-------

#一维
a=np.array([1,2,3])

for i in a:
    print(i)

#多维
a=np.array([(1,2),(3,4),(5,6)])
for i,j in a:
    print(i*j)


1
2
3
2
12
30


In [ ]:
# 5. NumPy 数组的常用属性-------

#ndarray.ndim : 数组的维度（数组轴的个数），等于秩
#ndarray.shape : 数组的⼤⼩。为⼀个表⽰数组在每个维度上⼤⼩的整数元组。例如⼆维
#数组中，表⽰数组的ʼʼ ⾏数ʼʼ 和ʼʼ 列数ˮ
#ndarray.size : 数组元素的总个数，等于 shape 属性中元组元素的乘积
#ndarray.dtype : 表⽰数组中元素类型的对象

a = np.array([(1,2,3, 4,5,6, 7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)


ndim: 2
shape: (1, 9)
size 9
dtype int32


In [ ]:
# 6. NumPy 数组的基本操作-------
# in :检测数值是否在数组中
a = np.array([(1,2),(3,4)])
print(3 in a)
print(5 in a)

# reshape : 数组的重排列，例如将⼀个 3 维数组转变为 1 维（元素数⼀定要保持不变）
a=np.zeros([2,3,4])
a

a=a.reshape(24)
a

#tanspose ：转置 (可以直接.T
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a
a.transpose() #a.T

#flatten : 把多维数组转换为⼀维数组，注意每个元组的⻓度是相同的
a=np.array([(1,2),(3,4),(5,6)])
a
a.flatten()

#newaxis : 增加维度
a=np.array([1,2,3])
a.shape

a=a[:,np.newaxis]
a
a.shape

True
False


(3, 1)

In [ ]:
# 7.NumPy 数组的数学操作-------

# 7.1 加减乘除
#* 星乘表⽰矩阵内各对应位置相乘，点乘表⽰求矩阵内积，⼆维数组称为矩阵积（mastrix product）：
a=np.ones((2,2))
b=np.array([(-1,1),(-1,1)])
print(a,a.shape,a.dtype)
print(b,b.shape,b.dtype)

a+b
a-b
a*b
a/b

# 7.2 求和、求积
a = np.array([1,2,1])
a.sum()

a.prod()

# 7.2 平均数，⽅差，标准差，最⼤值，最⼩值
a = np.array([5,3,1])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())
print("max:", a.max())
print("min:", a.min())

# 7.3 最⼤与最⼩值对应的索引值
a = np.array([5,3,1])
print(a.argmax(),a.argmin())

# 7.4 取元素值上限，下限，四舍五⼊
a = np.array([1.2, 3.8, 4.9])
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("rint:", np.rint(a))

# 7.4 排序
a = np.array([16,31,12,28,22,31,48])
a.sort()
a

a = np.array([(5,2),(2,4)])
print(a.shape)
a.sort()
print(a)

[[1. 1.]
 [1. 1.]] (2, 2) float64
[[-1  1]
 [-1  1]] (2, 2) int32
mean: 3.0
var: 2.6666666666666665
std: 1.632993161855452
max: 5
min: 1
0 2
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]
(2, 2)
[[2 5]
 [2 4]]


In [ ]:
# 8.NumPy 线性代数-------
# 有关线性代数的运算均在 numpy.linalg 中
# dot : 矩阵乘法，
# 对于两个⼀维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；
a=np.array([1,2,3])
b=np.array([2,3,4])

np.dot(a,b)

# 对于⼆维数组，计算的是两个数组的矩阵乘积；
# 对于多维数组，它的通⽤计算公式如下，即结果数组中的每个元素都是：数组 a 
# 的最后⼀维上的所有元素与数组 b 的倒数第⼆位上的所有元素的乘积和：
# dot(a, b)[i,j,k,m]= sum(a[i,j,:] * b[k,:,m])

m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
print("m1-----")
print(m1)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
print("m2-----")
print(m2)

result_dot = np.dot(m1, m2)
result_dot
print(result_dot)

result_at = m1 @ m2
result_at
print(result_at)

print("开始手动推演")

# 创建⼀个全零矩阵，⽤于存储⼿动推演的结果
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环: 遍历 matrix1的每一行
# i:表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环: 遍历matrix2的每一列
    # j: 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为0
        manual_result[i,j]=0
        
        #内层循环:计算matrix1的第i行与matrix2的第j列对应元素的乘积之和
        #k:当前参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i,k]} * {m2[k,j]} = {m1[i,k] * m2[k,j]}")
            # 将matrix1的第i行第k列元素与matrix2的第k行第j列元素相乘,并累计加
            manual_result[i,j] += m1[i,k] * m2[k,j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i,j]}\n")

print("手动推演结果:")
print(manual_result)


# eig : 特征值、特征向量
# inv : 逆
# qr : QR 分解
# svd : 奇异值分解
# solve : 解线性⽅程 Ax=b
# lstsq : 计算Ax=b 的最⼩⼆乘解

m1-----
[[1. 2.]
 [3. 4.]]
m2-----
[[5. 6.]
 [7. 8.]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
开始手动推演
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [ ]:
# 9.文件操作-------

# ⼆进制⽂件： np.save 、 np.load
# ⽂本⽂件： np.loadtxt 、 np.savetxt
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
np.save("result.npy",m1)

In [ ]:

# 10.NumPy ⼴播机制-------
# ⼴播 (Broadcast) 是 numpy 对不同形状 (shape) 的数组进⾏数值计算的⽅式，对数
# 组的算术运算通常在相应的元素上进⾏。如果两个数组 a 和 b 形状相同，即满⾜
# a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相
# 同，且各维度的⻓度相同。

#当运算中的 2 个数组的形状不同时，numpy 将⾃动触发⼴播机制
a = np.array([(1,2), (2,2), (3,3), (4,4)]) # shape(4,2)
b = np.array([-1,1]) # shape(2)→ shape(1,2) → shape(4,2) [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

# 注意: 广播机制要求两个数组最后一维的维度要对其
