In [1]:
# pytorch基础-------
import torch
import numpy as np

# 1. 张量(Tensor)的概念
# -装载数据的容器

# 2.张量的创建

# 直接从数据
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

# 从numpy数组
np_array = np.array(data)
np_array
# x_np = torch.from_numpy(np_array)
# x_np
# 报错:
#RuntimeError                              Traceback (most recent call last)
#Cell In[11], line 18
#     16 np_array = np.array(data)
#     17 np_array
#---> 18 x_np = torch.from_numpy(np_array)
#     19 x_np
#
#RuntimeError: Numpy is not available

# 从另外一个张量
x_ones = torch.ones_like(x_data) # 保留of x_data的属性
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # 覆盖 x_data的数据类型
print(f"Random Tensor: \n {x_rand} \n")

# 使⽤随机值或常量值：
# shape 是张量维度的元组。在下⾯的函数中，它决定了输出张量的维度
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

# 其他方法
# # 基于现有tensor构建，但使⽤新值填充
m = torch.ones(5,3, dtype=torch.double)
m

n = torch.rand_like(m, dtype=torch.float)
n
# 获取tensor的⼤⼩
print("-------")
print(m.size()) # torch.Size([5,3])
# 均匀分布
print("-------")
torch.rand(5,3)
# 标准正态分布
torch.randn(5,3)
# 离散正态分布
torch.normal(mean=.0,std=1.0,size=(5,3))
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
torch.linspace(start=1,end=10,steps=20)


G:\Hmsoft\Anaconda\package\envs\py312\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: DLL load failed while importing _multiarray_umath: 找不到指定的模块。 (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7800, 0.5296],
        [0.2925, 0.3348]]) 

Random Tensor: 
 tensor([[0.6180, 0.7931, 0.4454],
        [0.4105, 0.1959, 0.0935]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
-------
torch.Size([5, 3])
-------


tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [26]:
# 2. 张量的属性
# 张量的属性描述了张量的形状、数据类型和存储它们的设备。以对象的⻆度来判断，
# 张量可以看做是具有特征和⽅法的对象

tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [37]:
# 3. 张量的运算
# 算术,线性代数,矩阵操作(转置,索引,切片),采样

# 3.1 
# 默认情况下，张量是在 CPU 上创建的。我们可以使⽤使⽤ .to() ⽅法明确地将张量移动
#到 GPU可⽤的情况下)。请注意！跨设备复制内容量较⼤的张量，在时间和内存⽅⾯可能成本很⾼！
# 设置张量在GPU上运算
zhichi=torch.cuda.is_available()
print(zhichi)
if torch.cuda.is_available():
   tensor = tensor.to('cuda')
else:
   print("Not available") 
   
# 3.2 张量的索引和切⽚：
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[...,-1])
tensor[:,1] = 0
print(tensor)

# 3.3 张量的拼接
#可以使⽤ torch.cat ⽤来连接指定维度的⼀系列张量。
#另⼀个和 torch.cat 功能类似的函数是torch.stack
print("-----------------------")
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

# 3.4 算术运算
# 计算两个张量之间矩阵乘法的⼏种⽅式。 y1, y2, y3 最后的值是⼀样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# 计算张量逐元素相乘的⼏种⽅法。 z1, z2, z3 最后的值是⼀样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

# 3.5 单元素张量
# 如果⼀个单元素张量，例如将张量的值聚合计算，可以使⽤ item() ⽅法将其转换为Python 数值
agg = tensor.sum()
agg_item = agg.item()
print(agg, agg_item, type(agg_item))

# 3.6 In-place操作
# 把计算结果存储到当前操作数中的操作就称为就地操作。含义和pandas中inPlace参
# 数的含义⼀样。pytorch中，这些操作是由带有下划线 _ 后缀的函数表⽰。例如：
# x.copy_(y) , x.t_() , 将改变 x ⾃⾝的值。
print(tensor, "\n")
tensor.add_(5)
print(tensor)

False
Not available
First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
-----------------------
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor(12.) 12.0 <class 'float'>
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [43]:
# 5. 张量与numpy之间的转换
# CPU 和 NumPy 数组上的张量共享底层内存位置，所以改变⼀个另⼀个也会变

# 5.1 张量到numpy数组
print("----------------")
t = torch.ones(5)
print(f"t: {t}")
#n = t.numpy()
#print(f"n: {n}")
#ERROR 张量和numpy之间的转换会报错
#---------------------------------------------------------------------------
#RuntimeError                              Traceback (most recent call last)
#Cell In[43], line 8
#      6 t = torch.ones(5)
#      7 print(f"t: {t}")
#----> 8 n = t.numpy()
#      9 print(f"n: {n}")
#     11 # 5.2 Numpy数组到张量

# 5.2 Numpy数组到张量
print("----------------")
n = np.ones(5)
t = torch.from_numpy(n)


----------------
t: tensor([1., 1., 1., 1., 1.])


RuntimeError: Numpy is not available

In [2]:
# 6. 计算图
#
# 计算图( Computation graph)
#所有的深度学习框架都依赖于计算图来完成梯度下降、优化梯度值等计算。
# ⽽计算图的创建和应⽤，通常包含如下两个部分：
#1. ⽤⼾构建前向传播图
#2. 框架处理后向传播(梯度更新)
#模型从简单到复杂，pytorch和tensorflow都使⽤计算图来完成⼯作。
#但是，这两个框架所使⽤的计算图也却有所不同：
# tensorflow1.x 使⽤的是静态计算图，tensorflow2.x和pytorch使⽤的是动态计算图

# 6.1静态计算图
# 通常包括以下两个阶段。
#阶段1：定义⼀个架构(可以使⽤⼀些基本的流控制⽅法，⽐如循环和条件指令)
#阶段2：运⾏⼀组数据来训练模型，进⾏推理。
#优点：允许对图进⾏强⼤的离线优化/调度，所以速度相对较快。
#缺点：难以调试，对代码中处理结构化或者可变⼤⼩的数据处理⽐较复杂

# 6.2动态计算图
# 在执⾏正向计算时，隐式地定义图(动态构建)。
# 优点：灵活，侵⼊性⼩，允许动态构建和评估。
# 缺点：难以优化。

# 6.3pytorch计算图可视化
import torch
from torchviz import make_dot
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
print("----------------")
# 计算 x^T * A  b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)


----------------


ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH