# Numpy

## 基础用法

In [2]:
import numpy as np

In [3]:
# 创建一个3x3的二维数组
arr = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(arr)
# 指定类型创建
arr2 = np.array([(1,2,3), (4,5,6), (7,8,9)], float)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [4]:
# 创建都是0的数组
arr3 = np.zeros((3,3), dtype=np.float32)
print(arr3)
# 根据 start end step 创建数组
arr4 = np.arange(1, 10, 1)
print(arr4)
# 创建对角矩阵
arr5 = np.eye(4)
print(arr5)
# 创建随机数组
arr6 = np.random.random(5) 
print(arr6)
# 创建正态分布的随机数组
arr7 = np.random.normal(0, 1, 10)
print(arr7)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 2 3 4 5 6 7 8 9]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0.74578759 0.65006546 0.09357573 0.74688478 0.80706604]
[-0.98437785 -1.43146219 -0.63437583 -1.07282624 -0.8655184   1.14521827
 -0.95052033  0.30392552 -2.1848777   0.60668895]


In [5]:
# 基础属性
arr8 = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=np.float32)
print("ndim:", arr8.ndim)
print("shape:", arr8.shape)
print("size", arr8.size)
print("dtype", arr8.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype float32


In [6]:
arr9 = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=np.float32)
print(arr9)
# 转置
print(arr9.T)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


## 计算

In [7]:
arr10 = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=np.float32)
print(arr10)
print(arr10.sum())
print(arr10.prod())
print(arr10.mean())
print(arr10.var())
print(arr10.std())
print(arr10.min())
print(arr10.max())
print(arr10.argmin())
print(arr10.argmax())
print(np.ceil(arr10))
print(np.floor(arr10))
print(np.rint(arr10))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
45.0
362880.0
5.0
6.6666665
2.5819888
1.0
9.0
0
8
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [9]:
# 矩阵运算
arr11 = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=np.float32)
arr12 = np.array([(1,2,3), (4,5,6), (7,8,9)], dtype=np.float32)
print(arr11 + arr12)
print(arr11 - arr12)
print(arr11 @ arr12)
print(np.dot(arr11, arr12))

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
