# Pytorch基础

In [8]:
import torch
import numpy as np

In [9]:
# 创建一个张量
data1 = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
data1

tensor([[1., 2.],
        [3., 4.]])

In [10]:
# 从numpy数组创建张量
np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4]])

In [11]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.9252, 0.2815],
        [0.3670, 0.9314]])

In [12]:
shape = (3,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2136, 0.2072, 0.2871],
        [0.8560, 0.9568, 0.4280],
        [0.8340, 0.8338, 0.0628]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# 均匀分布
print(torch.rand(5,5))
# 标准正态分布
print(torch.randn(5,5))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,5)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

tensor([[0.0352, 0.3934, 0.3923, 0.5550, 0.2124],
        [0.9065, 0.7071, 0.5158, 0.9739, 0.5010],
        [0.0853, 0.4120, 0.4001, 0.6752, 0.3649],
        [0.9802, 0.8112, 0.3816, 0.6474, 0.1025],
        [0.8980, 0.9765, 0.4340, 0.2368, 0.0879]])
tensor([[-0.2335,  0.1012, -1.3499, -0.8471,  0.8577],
        [ 1.6731,  0.3031,  1.5962, -0.5222,  1.2655],
        [ 1.2836,  0.5488, -0.2060,  0.1947,  0.4861],
        [ 1.8964, -0.7889,  0.0843,  1.0398,  1.9656],
        [-0.4985, -0.5802, -0.5190, -0.7904, -0.7036]])
tensor([[ 0.3579, -1.2843,  0.4581,  1.2185, -0.3994],
        [ 0.6997, -0.1102,  1.9063, -0.5577,  0.7814],
        [-0.5750, -1.2827, -0.7207,  0.3613, -0.5178],
        [-0.7206,  0.7436, -1.5946, -1.0283,  1.1820],
        [ 0.1963,  0.9606, -1.1715,  1.1568,  1.1359]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9

## 基础属性

In [14]:
data4 = torch.rand(3,4)

print(f"Shape of tensor: {data4.shape}")
print(f"Datatype of tensor: {data4.dtype}")
print(f"Device tensor is stored on: {data4.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [16]:
data5 = torch.rand(4,4)
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = data5.to(device)

print(data5)
print(data5.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    data5 = data5.to(device)

print(data5)
print(data5.device)

tensor([[0.5697, 0.6192, 0.1862, 0.1846],
        [0.5973, 0.0060, 0.1910, 0.9932],
        [0.6179, 0.8712, 0.1394, 0.4435],
        [0.8921, 0.9741, 0.9179, 0.7546]])
cpu
tensor([[0.5697, 0.6192, 0.1862, 0.1846],
        [0.5973, 0.0060, 0.1910, 0.9932],
        [0.6179, 0.8712, 0.1394, 0.4435],
        [0.8921, 0.9741, 0.9179, 0.7546]], device='mps:0')
mps:0


In [17]:
# 切片
data6 = torch.ones(4, 4)
print('First row: ', data6[0])
print('First column: ', data6[:, 0])
print('Last column:', data6[..., -1])
data6[:,1] = 0
print(data6)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [18]:
# 拼接
data7 = torch.ones(2, 2)
data8 = torch.cat([data7, data7], dim=1)
data8

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
# 矩阵乘法
data9 = torch.ones(2, 2) * 5
data10 = torch.ones(2, 2) * 4

y1 = data9 @ data9.T
y2 = data9.matmul(data9.T)

y3 = torch.rand_like(data9)
torch.matmul(data9, data10.T, out=y3)

print(y1, y2, y3, sep='\n')

z1 = data9 * data9
z2 = data9.mul(data9)

z3 = torch.rand_like(data9)
torch.mul(data9, data10, out=z3)

print(z1, z2, z3, sep='\n')

tensor([[50., 50.],
        [50., 50.]])
tensor([[50., 50.],
        [50., 50.]])
tensor([[40., 40.],
        [40., 40.]])
tensor([[25., 25.],
        [25., 25.]])
tensor([[25., 25.],
        [25., 25.]])
tensor([[20., 20.],
        [20., 20.]])
