In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from transformers import AutoModelForTokenClassification, AutoTokenizer,DataCollatorForTokenClassification,TrainingArguments, Trainer
from datasets import load_dataset
import torch

MODEL_NAME = 'google-bert/bert-base-chinese'
# DATASET_NAME = 'nlhappy/CLUE-NER'
DATASET_NAME = 'doushabao4766/msra_ner_k_V3'

def get_model_and_tokenizer(num_labels, model_name = MODEL_NAME):
    model = AutoModelForTokenClassification.from_pretrained(model_name, num_labels=num_labels)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return model,tokenizer

model,tokenizer = get_model_and_tokenizer(7)
out = tokenizer('床前明月光', return_tensors='pt')
for i in out:
    print(i,'=>', out[i])
print()
out = model(**out, labels = torch.tensor([0,1,0,2,5,4,5]))
for i in out:
    print(i,'=>', out[i])
print()

ds = load_dataset(DATASET_NAME)
ds['train'] = ds['train'].shard(num_shards=4, index=2)
ds['test'] = ds['test'].shard(num_shards=4, index=2)
print(ds)

for row in ds['test']:
    for i in row:
        print(i,'=>', row[i])
    # out = tokenizer([''.join(row['tokens'])], return_tensors='pt')
    # print(out)
    # out = model(**out)
    # print(out)
    break

2025-05-30 12:49:35.471743: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748609375.882631      19 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748609375.996595      19 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


config.json:   0%|          | 0.00/624 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/412M [00:00<?, ?B/s]

Some weights of BertForTokenClassification were not initialized from the model checkpoint at google-bert/bert-base-chinese and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/110k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/269k [00:00<?, ?B/s]

input_ids => tensor([[ 101, 2414, 1184, 3209, 3299, 1045,  102]])
token_type_ids => tensor([[0, 0, 0, 0, 0, 0, 0]])
attention_mask => tensor([[1, 1, 1, 1, 1, 1, 1]])

loss => tensor(2.0277, grad_fn=<NllLossBackward0>)
logits => tensor([[[-1.3062e-01,  2.7423e-01, -7.2892e-01, -1.4593e-01,  9.0201e-03,
           5.9231e-01, -2.5089e-01],
         [-3.0666e-01,  1.0125e-02, -2.4537e-01,  6.6411e-02, -2.2912e-01,
          -2.7657e-01,  3.2932e-01],
         [-2.1197e-01, -7.3096e-04, -7.5714e-01,  5.5561e-01, -3.8275e-01,
          -3.3191e-01,  6.7459e-01],
         [-2.7895e-01,  4.1240e-01, -3.9410e-01,  3.8463e-01, -4.1043e-01,
           5.8132e-01,  8.4107e-01],
         [ 1.3884e-01,  1.9171e-01, -5.6250e-01,  2.7086e-01,  3.0940e-02,
           7.2413e-01,  3.2944e-01],
         [-5.5538e-01, -1.1317e-01, -1.2075e-01, -1.9966e-01, -4.4493e-01,
           6.7300e-01,  2.1346e-01],
         [ 1.6461e-01,  8.1280e-02, -2.5310e-01,  3.6034e-01, -2.3462e-01,
           4.5436e-01, -2

README.md:   0%|          | 0.00/697 [00:00<?, ?B/s]

(…)-00000-of-00001-42717a92413393f9.parquet:   0%|          | 0.00/13.9M [00:00<?, ?B/s]

(…)-00000-of-00001-8899cab5fdab45bc.parquet:   0%|          | 0.00/946k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/45001 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3443 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'knowledge'],
        num_rows: 11250
    })
    test: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'knowledge'],
        num_rows: 861
    })
})
id => 1722
tokens => ['环', '保', '时', '装', '还', '主', '张', '废', '弃', '物', '的', '再', '生', '，', '如', '将', '废', '弃', '的', '牛', '仔', '布', '作', '为', '原', '料', '，', '捣', '碎', '为', '纤', '维', '状', '，', '再', '梳', '理', '、', '织', '制', '成', '新', '的', '牛', '仔', '布', '，', '既', '节', '省', '了', '资', '源', '，', '又', '减', '少', '了', '污', '染', '。']
ner_tags => [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
knowledge => 时装：时装（英文：Fashion），一般指某时期流行的时尚服装，包配服装配饰在内，配饰一般包括例如伞、眼镜、手袋、首饰等等所有佩戴在个人身上的东西，令时装不再局限于衣服，开阔了其广度。纽约、巴黎、伦敦、米兰等获视为时装之都。


In [3]:

def mapper(item):
    # if len(item['tokens']) == 0:
        # print(item)
        # return
    input = tokenizer([''.join(it) for it in item['tokens']],truncation=True,padding=True,max_length=512,add_special_tokens=False,return_tensors="pt")
    # print(input)
    len_limit = input["input_ids"].shape[1]
    input['labels'] = [arr[:len_limit] for arr in item['ner_tags']]
    return input

ds2 = ds.map(mapper, batched=True)

ds2.set_format('torch', columns=['input_ids', 'token_type_ids', 'attention_mask', 'labels'])
print(ds2)

for row in ds2['test']:
    for i in row:
        print(i,'=>', row[i])
    break

Map:   0%|          | 0/11250 [00:00<?, ? examples/s]

Map:   0%|          | 0/861 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'knowledge', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 11250
    })
    test: Dataset({
        features: ['id', 'tokens', 'ner_tags', 'knowledge', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 861
    })
})
input_ids => tensor([4384,  924, 3198, 6163, 6820,  712, 2476, 2426, 2461, 4289, 4638, 1086,
        4495, 8024, 1963, 2199, 2426, 2461, 4638, 4281,  798, 2357,  868,  711,
        1333, 3160, 8024, 2941, 4810,  711, 5275, 5335, 4307, 8024, 1086, 3463,
        4415,  510, 5302, 1169, 2768, 3173, 4638, 4281,  798, 2357, 8024, 3188,
        5688, 4689,  749, 6598, 3975, 8024, 1348, 1121, 2208,  749, 3738, 3381,
         511,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  

In [4]:
!pip install evaluate seqeval

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 7.2 MB/s eta 0:00:00
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16162 sha256=483708b5364190b5f6217fc5f932fd8b205b867f187772f2b83a5caae7aa0808
  Stored in directory: /root/.cache/pip/wheels/bc/92/f0/243288f899c2eacdfa8c5f9aede4c71a9bad0ee26a01dc5ead
Successfully built seqeval
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cesium 0.12.4 requires numpy<3.0,>=2.0, but you have numpy 1.26.4 which is incompatible.
bigframes 

In [5]:
args = TrainingArguments(
    output_dir="ner_train",  # 模型训练工作目录（tensorboard，临时模型存盘文件，日志）
    num_train_epochs = 3,    # 训练 epoch
    save_safetensors=False,  # 设置False保存文件可以通过torch.load加载
    per_device_train_batch_size=32,  # 训练批次
    per_device_eval_batch_size=32,
    report_to='tensorboard',  # 训练输出记录
    eval_strategy="epoch",
)

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer,padding=True)

import evaluate

entites = ['O', 'PER', 'ORG', 'LOC']
tags = ['O']
for entity in entites[1:]:
    tags.append('B-' + entity.upper())
    tags.append('I-' + entity.upper())
print(tags)
# metric 方法
def compute_metrics(result):
    # result 是一个tuple (predicts, labels)
    # 获取评估对象
    seqeval = evaluate.load('seqeval')
    predicts,labels = result
    predicts = np.argmax(predicts, axis=2)
    # 准备评估数据
    predicts = [[tags[p] for p,l in zip(ps,ls) if l != -100]
                 for ps,ls in zip(predicts,labels)]
    labels = [[tags[l] for p,l in zip(ps,ls) if l != -100]
                 for ps,ls in zip(predicts,labels)]
    results = seqeval.compute(predictions=predicts, references=labels)
    return results


trainer = Trainer(model, args, train_dataset=ds2['train'], eval_dataset=ds2['test'],data_collator=data_collator,compute_metrics=compute_metrics)

trainer.train()

['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC']


/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/_functions.py:70: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn(


Trainer is attempting to log a value of "{'precision': 0.7068607068607069, 'recall': 0.74235807860262, 'f1': 0.7241746538871139, 'number': 458}" of type <class 'dict'> for key "eval/LOC" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'precision': 0.7104072398190046, 'recall': 0.8010204081632653, 'f1': 0.7529976019184651, 'number': 196}" of type <class 'dict'> for key "eval/ORG" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'precision': 0.832807570977918, 'recall': 0.8024316109422492, 'f1': 0.8173374613003096, 'number': 329}" of type <class 'dict'> for key "eval/PER" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.
Trainer is attempting to log a value of "{'precision': 0.8333333333333334, 'recall': 0.7532751091703057, 'f1'

TrainOutput(global_step=528, training_loss=0.07377877436352498, metrics={'train_runtime': 1083.7516, 'train_samples_per_second': 31.142, 'train_steps_per_second': 0.487, 'total_flos': 5509821822709248.0, 'train_loss': 0.07377877436352498, 'epoch': 3.0})

In [6]:

def predict(text):
    out = tokenizer(text, return_tensors='pt',add_special_tokens=False).to('cuda')
    word_ids = out.word_ids(0)
    # print(word_ids)
    out = model(**out)
    predicts = np.argmax(out['logits'].cpu().detach().numpy(), axis=2)[0]
    print(predicts)
    tmp_tag = None
    tmp = []
    result = []
    for i in range(len(predicts)):
        predict_label = predicts[i]
        if predict_label - 1 == tmp_tag:
            tmp.append(text[word_ids[i]])
        else:
            if tmp_tag:
                result.append({'entity': tags[tmp_tag][2:], 'content': ''.join(tmp)})
                # print(tags[tmp_tag][2:], tmp)
            tmp_tag = None
            tmp = []
            if predict_label % 2:
                tmp_tag = predict_label
                tmp.append(text[word_ids[i]])
            elif predict_label > 0:
                tmp_tag = predict_label - 1
                tmp.append(text[word_ids[i]])
    print(result)

predict('澳大利亚和日本进行了友好交流。')
predict('全佛山谁最能打？')
predict('双方确定了今后发展中美关系的指导方针。')

[5 6 6 6 0 5 6 0 0 0 0 0 0 0 0]
[{'entity': 'LOC', 'content': '澳大利亚'}, {'entity': 'LOC', 'content': '日本'}]
[0 6 6 0 0 0 0 0]
[{'entity': 'LOC', 'content': '佛山'}]
[0 0 0 0 0 0 0 0 0 5 5 0 0 0 0 0 0 0 0]
[{'entity': 'LOC', 'content': '中'}, {'entity': 'LOC', 'content': '美'}]


In [7]:
# !tar -cf output.tar output