In [2]:
import numpy as np

In [ ]:
# 创建nparray数组
arr = np.array([1,3,5,7], int)
arr

array([1, 3, 5, 7])

In [ ]:
# 创建nparray数组
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 创建行列都为3，内容为0的数组
a1 = np.zeros((3,3), dtype=np.float64)
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#创建从1开始，间隔0.5，到10结束的数组，不包含10
a2 = np.arange(1,10, 0.5)
a2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [11]:
a3 = np.eye(5)
a3  # one-hot编码

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
a4 = np.random.random(10)  # 模型运算参数初始值
a4

array([0.71468462, 0.8565597 , 0.02282409, 0.22912097, 0.67285582,
       0.47717487, 0.25878862, 0.222486  , 0.17745106, 0.41689853])

In [19]:
a5 = np.random.normal(-1, 10, 6)  # 模型运算参数初始值
a5

array([-14.49546338,  -2.56088282, -13.36506215,  -2.55106224,
        -6.34494221,  17.25338211])

In [ ]:
#创建从1到6的数组，重塑为3行2列矩阵
a6 = np.arange(1,7).reshape(3,2)
print(a6)
print(a6[:,1]) #取所有行第二列

[[1 2]
 [3 4]
 [5 6]]
[2 4 6]


In [ ]:
a7 = np.array([(1,2,3), (3,4,5), (4,5,6)])
#按矩阵列数提取每行数字
for i,j,k in a7:
    print(i,j,k)

1 2 3
3 4 5
4 5 6


In [ ]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])  #打印矩阵的各项属性
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int32


In [37]:
print((1,3,2) in a)

True


In [ ]:
a7 = np.arange(1,21)
print(a7)
print(a7.shape)
# 2*2*5 = 20
a7 = a7.reshape(2,2,5)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
(2, 2, 5)


In [ ]:
print(a)
a = a.T #转置
print(a)

[1 4 7 2 5 8 3 6 9]
[1 4 7 2 5 8 3 6 9]


In [ ]:
a = a.flatten() #降维
print(a)

[1 4 7 2 5 8 3 6 9]


In [54]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,np.newaxis,:]  # [3,1,2]  增加新的维度
print(a8)
a8.shape

[[[1 2]]

 [[3 4]]

 [[5 6]]]


(3, 1, 2)

In [ ]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
#相同维度的矩阵加减运算
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]


In [ ]:
a.sum() #和

4.0

In [ ]:
a.prod() #乘积

1.0

In [ ]:
a = np.array([5,3,7])
#依次为平均值、方差、标准差
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

mean: 5.0
var: 2.6666666666666665
std: 1.632993161855452


In [13]:
a = np.array([10.02, 13.8, 14.9])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 2
argmin: 0
ceil: [11. 14. 15.]
floor: [10. 13. 14.]
rint: [10. 14. 15.]


In [59]:
a = np.random.rand(10)
a.sort()  # 排序
a

array([0.05832334, 0.07983702, 0.11578463, 0.23644443, 0.37951187,
       0.7252622 , 0.79088788, 0.79841723, 0.92020648, 0.95083322])

In [ ]:
a9 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[4,5,6],[7,8,9]])

a9 * b9  #两个矩阵相同位置的数字相乘

array([[ 4, 10, 18],
       [28, 40, 54]])

In [62]:


# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [ ]:
np.save('result.npy',manual_result) #保存本地

In [ ]:
result_np = np.load('result.npy')  #本地读取
result_np

array([[12., 14.],
       [24., 28.]], dtype=float32)

In [64]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [ ]:
a = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
b = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b  #b数组自动变为与a同维度后进行计算

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])

In [68]:
import torch

data = torch.tensor([[1,1,2],[1,3,4]], dtype=torch.int)
data

tensor([[1, 1, 2],
        [1, 3, 4]], dtype=torch.int32)

In [74]:
import numpy as np

np_array = np.arange(1,9).reshape(4,2)
data2 = torch.from_numpy(np_array)
data2


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=torch.int32)

In [75]:
data2.dtype

torch.int32

In [76]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.8873, 0.3679],
        [0.8003, 0.4462],
        [0.2887, 0.8644],
        [0.3447, 0.7320]])

In [ ]:
shape = (2,2,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
#随机、全1、全0
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4146, 0.1938],
        [0.5606, 0.9692]]) 

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0.],
        [0., 0.]])


In [82]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([5, 3])
tensor([[0.0191, 0.7668, 0.7224],
        [0.6603, 0.1889, 0.1936],
        [0.1712, 0.8810, 0.9979],
        [0.8527, 0.3861, 0.0294],
        [0.5129, 0.8659, 0.9842]])
tensor([[-0.3056, -1.3283, -1.6019],
        [ 1.0936,  1.6409, -0.1677],
        [-1.0093,  1.5272,  0.7494],
        [-0.1826, -1.2648, -1.0349],
        [-1.1323,  0.0474, -1.0881]])
tensor([[ 0.8380,  0.2951, -0.7092],
        [-0.4809,  0.6285, -2.5855],
        [-0.3824, -0.7055, -0.4338],
        [ 0.2372, -0.3643, -0.2142],
        [ 0.6087, -0.7763,  0.4080]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [ ]:
tensor = torch.rand(3,3)
#打印torch的属性
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [87]:
# 检查pytorch是否支持GPU
print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

False
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
cpu
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
cpu


In [ ]:
tensor = torch.rand(3, 4)
print(tensor)
print('First row: ', tensor[0])             #打印首行
print('First column: ', tensor[:, 0])       #打印首列
print('Last column:', tensor[..., -1])      #打印最后一个维度（末列）
tensor[:,1] = 0   #第二列的值改为0
print(tensor)

tensor([[0.7680, 0.0462, 0.6809, 0.6879],
        [0.4532, 0.0363, 0.0602, 0.7579],
        [0.2822, 0.6558, 0.0465, 0.3388]])
First row:  tensor([0.7680, 0.0462, 0.6809, 0.6879])
First column:  tensor([0.7680, 0.4532, 0.2822])
Last column: tensor([0.6879, 0.7579, 0.3388])
tensor([[0.7680, 0.0000, 0.6809, 0.6879],
        [0.4532, 0.0000, 0.0602, 0.7579],
        [0.2822, 0.0000, 0.0465, 0.3388]])


In [ ]:
tensor = torch.ones(3,3)
tensor[:,1] = 0
#横向合成
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[3., 0., 3., 3., 0., 3., 3., 0., 3.],
        [3., 0., 3., 3., 0., 3., 3., 0., 3.],
        [3., 0., 3., 3., 0., 3., 3., 0., 3.]])
torch.Size([3, 9])


In [ ]:
#竖向合成
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2 * 3)
print(t2.shape)

tensor([[[3., 0., 3.],
         [3., 0., 3.],
         [3., 0., 3.]],

        [[3., 0., 3.],
         [3., 0., 3.],
         [3., 0., 3.]],

        [[3., 0., 3.],
         [3., 0., 3.],
         [3., 0., 3.]]])
torch.Size([3, 3, 3])


In [99]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)

torch.matmul(tensor, tensor.T, out=y3)  #out=y3直接覆盖了y3本来的值
# print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3) #out=z3直接覆盖了z3本来的值

print(z1)
print(z3)

tensor([[0.4058, 0.8738, 0.4680],
        [0.0530, 0.7397, 0.6866],
        [0.9811, 0.3696, 0.7255]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [101]:
#获取python中对应值
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

45.0 <class 'float'>


In [ ]:
#torch转numpy
np_arr = z1.numpy()
np_arr

In [ ]:
print(tensor, "\n")
tensor.mul_(5)  #危险用法，会直接修改内存中的值，不建议在模型中使用
# tensor = tensor * 5
# tensor *= 5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 5., 10., 15.],
        [20., 25., 30.],
        [35., 40., 45.]])


In [103]:
tensor

tensor([[ 5., 10., 15.],
        [20., 25., 30.],
        [35., 40., 45.]])

In [104]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) ** 2 + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_21676\2487162076.py:12: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) ** 2 + c


ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH