# ipynb后缀文件，是Juypter Notebook使用的文件格式，Juypter Nodebook是一个交互式笔记本，支持40多种编程语言，这种文件格式，非常适合用于数据分析、机器学习和可视化

# Numpy：是python语言中用于科学计算的一个非常重要的库，它提供了高性能的多维数组对象，以及用于处理这些数组的工具和函数。

# Numpy数组
 - Numpy数组是一个多维数组对象，称为 Ndarray。

# Numpy基础数组创建

In [4]:
import numpy as np
arr = [7,8,9,10]
nparray = np.array(arr)
nparray

array([ 7,  8,  9, 10])

In [13]:
import numpy as numpy
a = ['a','b']
z = numpy.array(a)
z

y = numpy.array([1,2,3,4,5,6],float)
y

array([1., 2., 3., 4., 5., 6.])

In [15]:
# 创建多维数组
narr = np.array([(9,8,7),(1,2,3),(4,5,6)])
narr

array([[9, 8, 7],
       [1, 2, 3],
       [4, 5, 6]])

In [18]:
# numpy创建特殊数组
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# 创建指定类型的numpy数组
b = np.zeros((3,4),dtype=np.int16)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [23]:
# 创建一个全为1的数组
x = np.ones((3,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
# 创建一个等差数列，从2开始，10结束，步长为1.5
x = np.arange(2,10,1.5)
x

array([2. , 3.5, 5. , 6.5, 8. , 9.5])

In [25]:
# 创建单位矩阵，单位举证：是一个方阵，从左上角到右下角的对角线（称为主对角线）上的元素均为1，除此以外全都为0。
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# 生成指定长度，在[0,1)之间的随机数
x = np.random.rand(4)
x

array([0.05715407, 0.501101  , 0.08293154, 0.64351458])

In [28]:
# 生成指定长度，符合标准差的数组
x = np.random.normal(0,1,10)
x

array([-0.82033034, -0.88027949,  0.18515153, -3.26631052, -0.18068345,
        0.61314475,  0.58275371, -1.55154132, -0.56724278,  0.49926296])

# Numpy数组的访问
和列表一样，Numpy数组也可以通过索引访问。也可以切片

In [45]:
# 创建一个3行2列的数组
x = np.array([[1,2],[3,4],[5,6]])
x[2]
x[:]
x[::2]
x[::-1]
x[:,0]

array([1, 3, 5])

In [46]:
# Numpy数组的遍历
x = np.array([1,2,3,4,5,6])
for i in x:
    print(i)

1
2
3
4
5
6


In [49]:
x = np.array([(1,2,3),(4,5,6),(7,8,9)])
for i in x:
  print(i)

[1 2 3]
[4 5 6]
[7 8 9]


# Numpy 数组的常用属性
ndarray.ndim:数组的维度
ndarray.shape:数组的大小。表示数组在每个维度上的大小。例如，一个n行m列的数组的shape为(n,m)。
ndarray.size:数组的元素总数。
ndarray.dtype:数组中元素的类型。

In [51]:
x = np.array([(1,2,3),(4,5,6),(7,8,9)])
print('x', x)
print('ndim', x.ndim)
print('shape', x.shape)
print('size', x.size)
print('dtype',x.dtype)

x [[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape (3, 3)
size 9
dtype int32


In [52]:
# Numpy 数组的基本操作
# in:检测数值是否在数组中
x = np.array([[1,2],[3,4]])
print(2 in x)
print(5 in x)

True
False


In [62]:
# 数组的重排列
x = np.zeros((3,3,4),dtype=int)
print(x)
print("-------------------")
x = x.reshape(36)
print(x)
print("-------------------")
x = x.reshape(2,3,6)
print(x)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
-------------------
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
-------------------
[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]


In [63]:
# tanspose: 转置
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
x = x.transpose()
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [66]:
# flatten:把多维数组转换为一维数组，每个元组的长度是相同的
x = np.array([[1,2],[3,4],[5,6]])
y = x.flatten()
y

array([1, 2, 3, 4, 5, 6])

In [69]:
# newaxis:增加维度
x = np.array([1,2,3])
y = x.shape
print(y)
z = x[:,np.newaxis]
print(z)
print(z.shape)
zz = z[:,np.newaxis]
print(zz)

(3,)
[[1]
 [2]
 [3]]
(3, 1)
[[[1]]

 [[2]]

 [[3]]]


In [78]:
# Numpy 数组的数学操作
# *：星乘表示矩阵内各对应位置相乘，点乘表示矩阵内积，二维数组称为矩阵积
x = np.ones((2,2))
print(x)
y = np.array([[-1,1],[-1,1]])
print(y)
z = x + y
print(z)
z1 = x - y
print(z1)
z2 = x * y
print(z2)
z3 = x / y 
print(z3)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]
[[0. 2.]
 [0. 2.]]
[[2. 0.]
 [2. 0.]]
[[-1.  1.]
 [-1.  1.]]
[[-1.  1.]
 [-1.  1.]]


In [86]:
x = np.array([1,2,3])
print(x)
y = x.sum()
print('y',y)
yy = x.prod()
print('yy',yy)
x1 = np.array([[1,2],[3,4]])
print(x1)
y1 = x1.sum()
print('y1',y1)
z = y1.prod()
print('z', z)

[1 2 3]
y 6
yy 6
[[1 2]
 [3 4]]
y1 10
z 10


In [87]:
# 平均数，方差，标准差，最大值，最小值
x = np.array([1,2,3,4,5])
print('mean:', np.mean(x))
print('var:', np.var(x))
print('std:', np.std(x))
print('max:', np.max(x))
print('min:', np.min(x))

mean: 3.0
var: 2.0
std: 1.4142135623730951
max: 5
min: 1


In [88]:
# 最大元素与最小元素的索引值：argmax，argmin
# 取元素值的上限，下限，四舍五入：ceil,floor,round
x = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print(np.argmax(x))
print(np.argmin(x))
print(np.ceil(x))
print(np.floor(x))
print(np.round(x))

8
0
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [92]:
# 排序 sort
x = np.array([3, 1, 2, 5, 4])
print(x,end='\n\n')
y = np.sort(x)
print(y,end='\n\n')
z = np.sort(x)[::-1]
print(z,end='\n\n')

[3 1 2 5 4]

[1 2 3 4 5]

[5 4 3 2 1]



In [97]:
# Numpy 线性代数
# 有关线性代数的运算均在numpy.linalg包中实现。
# dot:矩阵乘法：对于两个一维数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；
# 对于二维数组，计算的是两个数组的矩阵乘积；对于多维数组，它的通用计算公式如下，即结果数组中的每个元素都是：数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和。
m1 = np.array([[1,2],[3,4]],dtype=np.int32)
m2 = np.array([[5,6],[7,8]],dtype=np.int32)
print("===========================")
print('m1', m1, sep='\n')
print('m2', m2, sep='\n')
print("===========================")
print(m1 @ m2)
print("===========================")
print(m1.dot(m2))


m1
[[1 2]
 [3 4]]
m2
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
