# Pytorch基础
Pytorch是一个开源的深度学习框架，由Facebook人工智能研究院（FAIR）开发。它是基于Python语言的，提供了丰富的工具和库，用于构建和训练深度学习模型。

# 张量（Tensor)
张量是Pytorch中的基本数据结构，类似于NumPy中的数组。它可以表示标量、向量、矩阵和更高维的数据。张量可以在GPU上进行加速计算，因此在深度学习中被广泛使用。

In [2]:
import torch
# 直接从数据
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [3]:
# 从numpy数组
import numpy as np
np_array = np.array([[1,2],[3,4]])
data = torch.from_numpy(np_array)
print(data)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
data.dtype

torch.int32

In [6]:
# 从另一个张量
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_one = torch.ones_like(x_data) # 保留x_data的属性
print(f"Ones Tensor: \n {x_one} \n")
# 覆盖x_data的数据类型
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2610, 0.2720],
        [0.1192, 0.2043]]) 



In [10]:
# 使用随机值或者常量值
# shap：是张量维度的元组。
shape = (3,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5451, 0.8391, 0.1885],
        [0.4484, 0.4894, 0.6320],
        [0.4599, 0.3978, 0.6165]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [22]:
# 基于现有的tensor构建，但使用新值填充
m = torch.ones(3,3,dtype=torch.double)
print(m)
n = torch.rand_like(m,dtype=torch.float)
print(n)
# 获取tensor的大小
print(m.size())
# 均匀分布
print(torch.rand(3,3))
# 标准正态分布
print(torch.randn(3,3))
# 离散正态分布
print(torch.normal(mean=.1, std=1.0,size=(3,3)))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.5911, 0.3129, 0.9298],
        [0.4209, 0.6880, 0.4891],
        [0.7492, 0.0379, 0.8435]])
torch.Size([3, 3])
tensor([[0.7231, 0.6424, 0.7277],
        [0.7017, 0.2829, 0.0495],
        [0.5032, 0.5720, 0.8877]])
tensor([[-0.7736, -1.5465,  0.6998],
        [-0.2717, -1.7299,  1.4661],
        [-0.5432,  1.0709,  0.8985]])
tensor([[-1.1930,  0.0582,  0.1646],
        [-0.2606,  0.0927,  0.1349],
        [ 0.2950, -0.8724, -0.2026]])


In [24]:
# 张量的属性
# 张量的属性描述了张量的形状、数据类型和存储它们的设备。以对象的角度来判断，张量可以看作是具有特征和方法的对象。
tensor = torch.rand(4,5)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.7252, 0.8593, 0.5948, 0.7472, 0.6886],
        [0.5026, 0.2360, 0.8548, 0.2300, 0.6790],
        [0.7746, 0.3303, 0.9144, 0.8687, 0.7464],
        [0.7275, 0.9464, 0.1500, 0.7834, 0.0898]])
torch.Size([4, 5])
torch.float32
cpu


In [25]:
# 判断是否支持gpu
print(torch.cuda.is_available())

False


In [34]:
# 张量的切片和索引
tensor = torch.rand(5, 5)
print(tensor)
print("第一行%s" % tensor[0])
print("第一列{}".format(tensor[:,0]))
print("最后已列", tensor[...,-1])
print(f"最后一列{tensor[:,-1]}")

tensor[:,2] = 1
print(tensor)


tensor([[0.4057, 0.0889, 0.4281, 0.8296, 0.8342],
        [0.3447, 0.1277, 0.6114, 0.3122, 0.6062],
        [0.1132, 0.3991, 0.3863, 0.3336, 0.2873],
        [0.5786, 0.2719, 0.0670, 0.8815, 0.1948],
        [0.7571, 0.3181, 0.2030, 0.2541, 0.3470]])
第一行tensor([0.4057, 0.0889, 0.4281, 0.8296, 0.8342])
第一列tensor([0.4057, 0.3447, 0.1132, 0.5786, 0.7571])
最后已列 tensor([0.8342, 0.6062, 0.2873, 0.1948, 0.3470])
最后一列tensor([0.8342, 0.6062, 0.2873, 0.1948, 0.3470])
tensor([[0.4057, 0.0889, 1.0000, 0.8296, 0.8342],
        [0.3447, 0.1277, 1.0000, 0.3122, 0.6062],
        [0.1132, 0.3991, 1.0000, 0.3336, 0.2873],
        [0.5786, 0.2719, 1.0000, 0.8815, 0.1948],
        [0.7571, 0.3181, 1.0000, 0.2541, 0.3470]])


In [41]:
# 张量的拼接
x1 = torch.cat([tensor,tensor,tensor],dim=1)
print(x1)
print(x1 * 2)
print(x1.shape)

tensor([[0.4057, 0.0889, 1.0000, 0.8296, 0.8342, 0.4057, 0.0889, 1.0000, 0.8296,
         0.8342, 0.4057, 0.0889, 1.0000, 0.8296, 0.8342],
        [0.3447, 0.1277, 1.0000, 0.3122, 0.6062, 0.3447, 0.1277, 1.0000, 0.3122,
         0.6062, 0.3447, 0.1277, 1.0000, 0.3122, 0.6062],
        [0.1132, 0.3991, 1.0000, 0.3336, 0.2873, 0.1132, 0.3991, 1.0000, 0.3336,
         0.2873, 0.1132, 0.3991, 1.0000, 0.3336, 0.2873],
        [0.5786, 0.2719, 1.0000, 0.8815, 0.1948, 0.5786, 0.2719, 1.0000, 0.8815,
         0.1948, 0.5786, 0.2719, 1.0000, 0.8815, 0.1948],
        [0.7571, 0.3181, 1.0000, 0.2541, 0.3470, 0.7571, 0.3181, 1.0000, 0.2541,
         0.3470, 0.7571, 0.3181, 1.0000, 0.2541, 0.3470]])
tensor([[0.8113, 0.1777, 2.0000, 1.6591, 1.6684, 0.8113, 0.1777, 2.0000, 1.6591,
         1.6684, 0.8113, 0.1777, 2.0000, 1.6591, 1.6684],
        [0.6893, 0.2553, 2.0000, 0.6243, 1.2125, 0.6893, 0.2553, 2.0000, 0.6243,
         1.2125, 0.6893, 0.2553, 2.0000, 0.6243, 1.2125],
        [0.2264, 0.7983, 2

In [48]:
# 算术运算
tensor = torch.arange(1, 10, dtype=torch.float32)
print(tensor)
tensor = tensor.reshape(3, 3)
print(tensor)
# 计算张量之间矩阵乘法的几种方式。
x1 = tensor@tensor.T
x2 = tensor.matmul(tensor.T)
x3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=x3)
print(x1)
print(x2)
print(x3)


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])


In [49]:
# 计算张量逐元素相乘的几种方法。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
print(z1)
print(z2)
print(z3)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[0.4406, 0.2065, 0.2424],
        [0.1905, 0.9320, 0.5387],
        [0.5773, 0.0014, 0.7411]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [52]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item)
print(type(agg_item))

tensor(45.)
45.0
<class 'float'>


In [55]:
# In-place操作
print("tensor: ", tensor)
tensor.add_(3)
print("tensor: ", tensor)
tenson = tensor - 2
print("tenson: ", tenson)

tensor:  tensor([[ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor:  tensor([[ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])
tenson:  tensor([[ 5.,  6.,  7.],
        [ 8.,  9., 10.],
        [11., 12., 13.]])


In [57]:
# 与numpy之间的转换
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
print(type(n))

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [59]:
# Numpy数组到张量
n = np.ones(5)
print(type(n))
t = torch.from_numpy(n)
print(t)
print(type(t))

<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [1]:
# pythorch计算图可视化
import torch 
from torchviz import make_dot
# 定义矩阵x,向量y,和常数z
x = torch.randn(10,10,requires_grad=True)
y = torch.randn(10,requires_grad=True)
z = torch.randn(1,requires_grad=True)
m = torch.randn(10,requires_grad=True)
print(x)
print(y)
print(z)
print(m)
# 计算 m^T * x + y * m + z
result = torch.matmul(x, m.T) + torch.matmul(y,m) + z

# 生成计算图节点
dot = make_dot(result, params={'x': x, 'y': y, 'z': z, 'm':m})
# 绘制计算
dot.render('expression', format='png', cleanup=True, view=False)

tensor([[ 0.7001, -0.6774,  0.5869, -0.8031, -1.7564, -1.2646, -2.2095, -0.2889,
         -1.7938, -0.8510],
        [-0.5056,  1.8471, -1.8398,  1.7961,  0.9302, -0.3732, -1.4352, -0.5111,
         -2.1559, -0.7353],
        [ 0.0473,  0.5934,  0.9535, -1.3326,  0.1812, -0.1191,  0.5387,  1.4252,
          0.8257,  0.0101],
        [-0.5305, -0.1641, -0.1918,  0.2336, -0.2381, -0.7834, -1.1396, -0.3506,
         -0.7392,  1.2957],
        [-0.1974, -0.8036, -0.0988, -1.5215, -0.9537,  1.0805, -1.0337, -0.2532,
          0.9586,  0.0350],
        [-0.6232, -1.1874,  1.0203,  0.0596, -2.3049, -0.7731, -0.1611,  0.4482,
          1.0059, -1.2191],
        [-0.3399, -1.2490,  1.0138, -1.2708,  0.2763,  1.0642,  0.6759, -2.1069,
          1.5509, -0.4469],
        [ 1.0258,  0.1294, -0.7182, -0.2828, -0.9816, -1.1595, -1.4077, -0.0624,
         -0.6119,  0.4205],
        [ 0.0709,  1.0023,  0.7420,  0.0270,  0.8310,  1.2163, -1.9146,  0.6482,
         -1.2403,  0.6824],
        [-0.6901, -

C:\Users\xiong\AppData\Local\Temp\ipykernel_18388\2826643257.py:14: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  result = torch.matmul(x, m.T) + torch.matmul(y,m) + z


'expression.png'