In [2]:
import numpy as np

In [3]:
#创建ndarray数组
arr = np.array([1,2,3,4,5,6],float)
arr

array([1., 2., 3., 4., 5., 6.])

In [4]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a1 = np.zeros((3,3),dtype=np.float32)
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [6]:
a2 = np.arange(1,10,0.5)
a2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [7]:
#创建单位矩阵,可用于one-hot编码
a3 = np.eye(3)
a3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#创建随机数组，范围[0,1)，可用于模型参数初始值
a4 = np.random.random(6)
a4

array([0.85483852, 0.33793429, 0.54296314, 0.04190963, 0.79761626,
       0.58793977])

In [9]:
#创建随机数组，服从正态分布,也可用于模型参数初始值
a5 = np.random.normal(0,1,6)
a5

array([ 1.81487529, -0.3185515 ,  1.3752987 ,  0.6300502 , -0.26661127,
        0.39531429])

In [10]:
a6 = np.array([(1,2),(3,4),(5,6)])
print(a6)
print(a6[:,0])
# print(a6[1:])
# print(a6[1,:])
# print(a6[1,1])

[[1 2]
 [3 4]
 [5 6]]
[1 3 5]


In [11]:
a7 = np.array([(1,2),(3,4),(5,6)])

# i,j = a7[0]
# print(i,j)

for i,j in a7:
    print(i,j)

1 2
3 4
5 6


In [12]:
a8 = np.array([(1,2,3),(4,5,6),(6,7,8)])
print("ndim:",a8.ndim)          #维度
print("shape:",a8.shape)        #形状
print("size:",a8.size)          #元素个数
print("dtype:",a8.dtype)        #元素类型
print("itemsize:",a8.itemsize)  #元素字节大小


ndim: 2
shape: (3, 3)
size: 9
dtype: int32
itemsize: 4


In [13]:
print((1,2,3) in a8)
print(1 in a8)
# print((1,2) in a8)    #报错

True
True


In [14]:
a9 = np.arange(1,10,1)
print(a9)
print(a9.shape)

a9 = a9.reshape(3,3)  #改变形状,数据元素个数要一致
print(a9)
print(a9.shape)


# 高维矩阵，每个维度有具体含义
# 加载图片数据  img.shape [1,3,120,120] 1表示图片数量，3表示RGB通道，120表示宽，120表示高

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [15]:
print(a)
a = a.T    #转置，也可以使用a.transpose()
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
a = a.flatten()  #降维
print(a)

[1 4 7 2 5 8 3 6 9]


In [17]:
a6 = np.array([(1,2),(3,4),(5,6)])
a6 = a6[:,:,np.newaxis]  #增加维度
print(a6)
print(a6.shape)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
(3, 2, 1)


In [18]:
a10 = np.ones((2,3))
b = np.array([(1,2,3),(4,5,6)])
print(a10)
print(b)
print()

print(a10+b)  #对应元素相加
print()

# print(a10-b)
# print()

# print(a10*b)
# print()

# print(a10/b)
# print()


[[1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]]

[[2. 3. 4.]
 [5. 6. 7.]]



In [19]:
print(a10.sum())   #所有元素求和
print(a10.sum(axis=0))   #列求和
print(a10.sum(axis=1))   #行求和
print("-----------------")

print(a10.max())   #所有元素最大值  
print(a10.max(axis=0))   #列最大值
print(a10.max(axis=1))   #行最大值
print("-----------------")

print(a10.prod())  #所有元素乘积
print("-----------------")



6.0
[2. 2. 2.]
[3. 3.]
-----------------
1.0
[1. 1. 1.]
[1. 1.]
-----------------
1.0
-----------------


In [20]:
a11 = np.array([1.2,2.3,3.4,4.5,5.6,6.7])
print("mean:",a11.mean())  #平均值
print("var:",a11.var())    #方差
print("std:",a11.std())    #标准差
print("median:",np.median(a11))  #中位数

print("argmax:",a11.argmax())  #最大值索引
print("argmin:",a11.argmin())  #最小值索引

print("ceil:",np.ceil(a11))    #向上取整
print("floor:",np.floor(a11))  #向下取整
print("rint:",np.rint(a11))    #四舍五入,round,around,rint等价

mean: 3.9499999999999997
var: 3.5291666666666672
std: 1.8786076404259264
median: 3.95
argmax: 5
argmin: 0
ceil: [2. 3. 4. 5. 6. 7.]
floor: [1. 2. 3. 4. 5. 6.]
rint: [1. 2. 3. 4. 6. 7.]


In [21]:
a12 =  np.array([16,32,55,7,2,62,40])
a12.sort()  #排序,默认升序,默认是快速排序
print(a12)

a12.sort(kind='heapsort')  #堆排序
print(a12)

a12[::-1].sort()   #降序
print(a12)

[ 2  7 16 32 40 55 62]
[ 2  7 16 32 40 55 62]
[62 55 40 32 16  7  2]


In [22]:
a1 = np.array([[1,2,3],[4,5,6]])
b1 = np.array([[7,8,9],[10,11,12]])

a1 * b1

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
# 定义两个矩阵
from numpy import dtype


m = np.array([[1,2],[3,4]],dtype = np.float32)
n = np.array([[5,6],[7,8]],dtype = np.float32)

'''--- A (..., m, n)的最后一个维度（倒数第一维 n）必须等于 B(..., n, p) 的倒数第二维（n）---'''
# 使用dot函数计算两个矩阵的乘积
result_dot = np.dot(m,n)            

# 使用@符号计算两个矩阵的乘积
result_at = m @ n

print("矩阵1：\n",m)
print("矩阵2：\n",n)
print("使用dot函数计算的结果：\n",result_dot)
print("使用@符号计算的结果：\n",result_at)

# 创建一个全零矩阵，用于存放结果
# 结果矩阵的行数等于矩阵m的行数，列数等于矩阵n的列数
manual_result = np.zeros((m.shape[0],n.shape[1]),dtype = np.float32)

# 外层循环遍历m的行
# i表示结果矩阵的行索引
for i in range(m.shape[0]):
    # 中层循环遍历n的列
    # j表示结果矩阵的列索引
    for j in range(n.shape[1]):
        # 初始化结果矩阵的元素为0
        manual_result[i,j] = 0
        # 内层循环：计算矩阵m的第i行和矩阵n的第j列对应元素的乘积之和
        # k表示矩阵m的列索引，也是矩阵n的行索引
        for k in range(m.shape[1]):
            manual_result[i,j] += m[i,k] * n[k,j]
        # 打印每次计算的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i,j]}\n")

print("手动计算的结果：\n",manual_result)



矩阵1：
 [[1. 2.]
 [3. 4.]]
矩阵2：
 [[5. 6.]
 [7. 8.]]
使用dot函数计算的结果：
 [[19. 22.]
 [43. 50.]]
使用@符号计算的结果：
 [[19. 22.]
 [43. 50.]]
结果矩阵[1,1]:19.0

结果矩阵[1,2]:22.0

结果矩阵[2,1]:43.0

结果矩阵[2,2]:50.0

手动计算的结果：
 [[19. 22.]
 [43. 50.]]


In [28]:
a = np.array([[1,2],[3,4]])

# 特征值和特征向量
eigvl,eigvt = np.linalg.eig(a)
print("特征值：",eigvl)
print("特征向量：",eigvt)
print("--------------------")

# 逆矩阵
inverse_a = np.linalg.inv(a)
print("逆矩阵：\n",inverse_a)
print("--------------------")

# QR分解,是将一个矩阵分解为一个正交矩阵Q和一个上三角矩阵R的乘积
q,r = np.linalg.qr(a)
print("Q矩阵：\n",q)
print("R矩阵：\n",r)
print("--------------------")

# SVD分解(奇异值分解)，
u,s,v = np.linalg.svd(a)
print("U矩阵：\n",u)
print("S矩阵：\n",s)
print("V矩阵：\n",v)
print("--------------------")

# 解线性方程组
b = np.array([5,7])
x = np.linalg.solve(a,b)
print("方程组的解：",x)
print("--------------------")

# 计算最小二乘解
x = np.linalg.lstsq(a, b, rcond=None)  
print("最小二乘解：",x)
print("--------------------")


特征值： [-0.37228132  5.37228132]
特征向量： [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
--------------------
逆矩阵：
 [[-2.   1. ]
 [ 1.5 -0.5]]
--------------------
Q矩阵：
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R矩阵：
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]
--------------------
U矩阵：
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S矩阵：
 [5.4649857  0.36596619]
V矩阵：
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
--------------------
方程组的解： [-3.  4.]
--------------------
最小二乘解： (array([-3.,  4.]), array([], dtype=float64), 2, array([5.4649857 , 0.36596619]))
--------------------


In [25]:
np.save('result.npy',manual_result)  

In [26]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [27]:
a = np.array([(1,2),(3,4),(5,6),(7,8)])  #sahpe(4,2)
b = np.array([-1,1])  #shape(2,) --> shape(1,2) --> shape(4,2)  广播机制  [(-1,1),(-1,1),(-1,1),(-1,1)]
a + b

array([[0, 3],
       [2, 5],
       [4, 7],
       [6, 9]])