In [2]:
import torch
print(torch.__version__)          # PyTorch 版本
print(torch.cuda.is_available())  # 输出 True 才表示 GPU 可用
print(torch.version.cuda)         # 查看 PyTorch 关联的 CUDA 版本

2.6.0+cu126
True
12.6


In [3]:
import torch

date1 = torch.tensor([[1,2],[3,4]])
date1

tensor([[1, 2],
        [3, 4]])

In [4]:
import numpy as np

np_arry = np.array([[1,2],[3,4]])

date2 = torch.from_numpy(np_arry)
date2

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [5]:
# 通过已知张量维度创建新张量
date3 = torch.rand_like(date2,dtype=torch.float)                
date3

tensor([[0.3096, 0.9067],
        [0.3248, 0.2996]])

In [6]:
from torch import rand


shape = (2,3,)
rand_tensor = torch.rand(shape)        # 随机张量
ones_tensor = torch.ones(shape)        # 全1张量
zeros_tensor = torch.zeros(shape)      # 全0张量

print(f"Random Tensor: \n {rand_tensor} \n")     
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6162, 0.4772, 0.9226],
        [0.6612, 0.3033, 0.0458]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# 基于现有tensor构建，使用新的数值填充
from traceback import print_list


m = torch.ones(5,3,dtype=torch.double)
n = torch.rand_like(m,dtype=torch.float)

# 获取tensor的大小
print(m.size())     # torch.Size([5, 3])

# 均匀分布(0,1)
u = torch.rand(2,3)
print(u)
print("------------------")

# 正态分布
n = torch.randn(2,3)
print(n)
print("------------------")

# 离散正态分布
d = torch.normal(mean=.0,std=1.0,size=(2,3))
print(d)
print("------------------")

# 线性间隔向量（返回的是一个1维张量，包含在区间start和end上均匀间隔的steps个点）
l = torch.linspace(start=0,end=100,steps=5)
print(l)
print("------------------")

torch.Size([5, 3])
tensor([[0.5273, 0.9480, 0.9029],
        [0.0018, 0.3779, 0.6514]])
------------------
tensor([[ 0.1786, -0.6784,  0.8847],
        [-1.1851,  0.1136,  0.6099]])
------------------
tensor([[ 2.0954,  0.9864,  0.5260],
        [-2.9542, -1.0217,  1.0707]])
------------------
tensor([  0.,  25.,  50.,  75., 100.])
------------------


In [8]:
tensor  = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")        
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")     

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# 检查 GPU 数量
print("GPU count:", torch.cuda.device_count())  

# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda:0")          # a CUDA device object
    tensor = tensor.to(device)             

print(tensor)
print(tensor.device)



# mac上没有GPU，使用M系列芯片
# if torch.backends.mps.is_available():




GPU count: 1
tensor([[0.1924, 0.9186, 0.4298, 0.2169],
        [0.1631, 0.5299, 0.1965, 0.6310],
        [0.0666, 0.3281, 0.4804, 0.2398]], device='cuda:0')
cuda:0


In [ ]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])             
print('Last column:', tensor[..., -1])     
tensor[:,1] = 0         # 将第二列都置为0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
# torch.cat功能类似torch.stack，一个是拼接（左右），一个是堆叠（上下）
t1 = torch.cat([tensor, tensor, tensor], dim=1)      # 按列拼接张量，dim=1表示按列拼接
print(t1)
print(t1.shape)
t2 = torch.cat([tensor, tensor, tensor], dim=0)      # 按行拼接张量，dim=0表示按行拼接
print(t2)
print(t2.shape)

t3 = torch.stack([tensor, tensor, tensor], dim=1)    # 按列堆叠张量，dim=1表示按列堆叠
print(t3)
print(t3.shape)

t4 = torch.stack([tensor, tensor, tensor], dim=0)    # 按行堆叠张量，dim=0表示按行堆叠
print(t4)
print(t4.shape)


tensor([[ 6.,  7.,  8.,  6.,  7.,  8.,  6.,  7.,  8.],
        [ 9., 10., 11.,  9., 10., 11.,  9., 10., 11.],
        [12., 13., 14., 12., 13., 14., 12., 13., 14.]])
torch.Size([3, 9])
tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
torch.Size([9, 3])
tensor([[[ 6.,  7.,  8.],
         [ 6.,  7.,  8.],
         [ 6.,  7.,  8.]],

        [[ 9., 10., 11.],
         [ 9., 10., 11.],
         [ 9., 10., 11.]],

        [[12., 13., 14.],
         [12., 13., 14.],
         [12., 13., 14.]]])
torch.Size([3, 3, 3])
tensor([[[ 6.,  7.,  8.],
         [ 9., 10., 11.],
         [12., 13., 14.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.],
         [12., 13., 14.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.],
         [12., 13., 14.]]])
torch.Size([3, 3, 3])


In [15]:
import torch 
tensor = torch.arange(1, 10,dtype=torch.float32).reshape(3,3)

# 计算两个张量之间矩阵乘法的几种方法，结果都是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


# 计算张量逐元素相乘的几种方法，结果都是一样的 
z1 = tensor * tensor
z2 = tensor.mul(tensor)
# print(z1)
# print(z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
# print(z3)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [27]:
agg = tensor.sum()         
agg_item = agg.item()           # 将张量中的元素转换为Python数值
print(agg_item, type(agg_item))

90.0 <class 'float'>


In [ ]:
np_arr = z1.numpy()           # 将张量转换为numpy数组
np_arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [ ]:
# inplace操作
print(tensor,"\n")
tensor.add_(5)
# tensor = tensor + 5
# tensor+=5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [1]:
# 张量转换为numpy数组
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

NameError: name 'torch' is not defined

In [20]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [21]:
# numpy数组转换为张量
n = np.ones(5)
t = torch.from_numpy(n)

In [22]:
import torch
from torchviz import make_dot

# 定义矩阵A，向量b和常数c
A = torch.randn(10,10,requires_grad=True)       # requires_grad=True表示需要计算梯度
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10,requires_grad=True)

# 计算x^T A x + b^T x + c
result = torch.matmul(A,x.T) + torch.dot(b,x) + c

# 生成计算图节点
dot = make_dot(result, params={"A":A, "b":b, "c":c, "x":x})

# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\sgp\AppData\Local\Temp\ipykernel_17332\253383709.py:11: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:3729.)
  result = torch.matmul(A,x.T) + torch.dot(b,x) + c


'expression.png'