In [5]:
import numpy as np # 引入numpy包

In [6]:
# 创建一个float类型的nparray
arrFloat = np.array([1.2,2.3,3.6,4.65,5.98], float)
print(arrFloat)
print(arrFloat.dtype)
# 创建一个int类型的nparray
arrInt = np.array([1,2,3,4,5], int)
print(arrInt)
print(arrInt.dtype)

[1.2  2.3  3.6  4.65 5.98]
float64
[1 2 3 4 5]
int32


In [9]:
# 创建多维数组
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# 使用zeros初始化一个2行3列的array
a = np.zeros((2,3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
# 使用noes创建一个全部为1的数组 dtype指定类型
# a = np.ones((3,3), dtype=int)
a = np.ones((3,3), dtype=float)
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# 使用arange创建间隔相同的等差数组
a = np.arange(1,6,0.33) # arange从左到右三个参数 第一个参数表示开始数字，等差数组中的最大值不能大于等于第二个参数，第三个参数为差值
a

array([1.  , 1.33, 1.66, 1.99, 2.32, 2.65, 2.98, 3.31, 3.64, 3.97, 4.3 ,
       4.63, 4.96, 5.29, 5.62, 5.95])

In [28]:
# 创建单位矩阵
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# 生成平均分布的随机数组
a = np.random.random(9)
a

array([0.06666646, 0.36963094, 0.78123824, 0.84610622, 0.63861437,
       0.55201124, 0.87399262, 0.49462543, 0.87813169])

In [33]:
# 生成符合正态分布的随机数组
num,sigma=0,0.1 # num为均值 sigma为标准差
a = np.random.normal(num,sigma,8)
a

array([-0.02187904, -0.04036978,  0.11503233, -0.04529666, -0.02472513,
        0.02429918,  0.09806004,  0.09761164])

In [45]:
a = np.array([[1,2], [3,4], [5,6]])
# 通过索引访问数组
print(a[2])
# 通过符号 : 访问索引前或者后的所有数组项
print(a[1:])
print(a[:2])
# 还可以指定二维数组中的每一项
print(a[:,:1])
print(a[1,1])
print(a[1][1])

[5 6]
[[3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1]
 [3]
 [5]]
4
4


In [49]:
# 使用for in 遍历numpy
a = np.array([1,2,3,4,5])
for i in a:
    print(i)
# 遍历多维数组
a = np.array([[1,2],[3,4],[5,6]])
for i in a:
    print(i)
    for j in i:
        print(j)

1
2
3
4
5
[1 2]
1
2
[3 4]
3
4
[5 6]
5
6


In [ ]:
print('ndim', a.ndim) # ndim 维度 矩阵的秩
print('shape', a.shape) # shape 数组大小
print('size', a.size) # size 数组元素总个数
print('dtype', a.dtype) # dtype 数组中元素类型

ndim 2
shape (3, 2)
size 6
dtype int32


In [ ]:
a = np.arange(1,11, 1)
print(a)
a = a.reshape((2,5)) # reshap中的参数成绩应该为数组的size值，既数组用元素个数
print(a)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# 使用T或者transpose()将数组转秩
# print(a.T)
print(a.transpose())

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
# flatten() 将多维数组转为一维
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10]


In [66]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b) # 数组详见
print()
print(a-b) # 数组相减
# 相乘 相除 同理 都是每个对应位置间的元素互相运算
print(a.sum()) # 求和 数组内每个元素互相相加
a = np.array([[1,2],[2,3]])
print(a.prod()) # 求积 数组内每个元素互相相乘

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]
4.0
12


In [ ]:
a = np.array([1,2,3,4,5])
print("mean:",a.mean()) # mean() 求平均数
print("var:", a.var()) # var 求方差
print("std:", a.std()) # std 求标准差

mean: 3.0
var: 2.0
std: 1.4142135623730951


In [76]:
a = np.array([1.2,5.4,1.5,2.3])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 1
argmin: 0
ceil: [2. 6. 2. 3.]
floor: [1. 5. 1. 2.]
rint: [1. 5. 2. 2.]


In [ ]:
a = np.array([12,44,2,54,5,24])
a.sort() # sort 对数组进行升序排序
a

array([ 2,  5, 12, 24, 44, 54])

In [7]:
# 使用 np.dot 或者 @ 来进行矩阵乘法运算
#对于⼆维数组，计算的是两个数组的矩阵乘积；
#对于多维数组，它的通⽤计算公式如下，即结果数组中的每个元素都是：数组 a 的最后⼀维上的所有元素与数组 b 的倒数第⼆位上的所有元素的乘积和：dot(a, b)[i,j,k,m]= sum(a[i,j,:] * b[k,:,m]) 
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8], [9,10]])
result_dot = np.dot(a,b)
result_at = a @ b
print(result_dot)
print(result_at)

[[ 25  28]
 [ 57  64]
 [ 89 100]]
[[ 25  28]
 [ 57  64]
 [ 89 100]]


In [ ]:
np.save('result.npy', result_at) # np.save 存储文件 

In [ ]:
np.load('result.npy') # np.load 打开文件

array([[ 25,  28],
       [ 57,  64],
       [ 89, 100]])