In [2]:
import torch
import numpy as np

# 创建一个张量
data = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float)
data


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [3]:
# 通过numpy创建一个张量
np_array = np.array([[1,2],[3,4],[5,6]])
print(np_array)
print(torch.__version__)
print(np.__version__)
data = torch.from_numpy(np_array)
print(data)
# 数据类型
print(data.dtype)

[[1 2]
 [3 4]
 [5 6]]
2.6.0+cpu
2.2.0
tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.int64


In [11]:
# torch.rand_like 通过已知张量来创建新的张量 注意指定张量内部数据类型
data2 = torch.rand_like(data, dtype=torch.float16)
data2

tensor([[0.7759, 0.0649],
        [0.0947, 0.1582],
        [0.3745, 0.1646]], dtype=torch.float16)

In [13]:
shape = (3,3) # shape 张量维度
rand_tensor = torch.rand(shape) # 指定维度下随机一个张量
ones_tensor = torch.ones(shape) # 指定维度下初始化一个全部为1的张量
zeros_tensor = torch.zeros(shape) # 指定维度下初始化一个全部为0的张量
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.9667, 0.0901, 0.1856],
        [0.8368, 0.2179, 0.1342],
        [0.7433, 0.8042, 0.6795]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(3,5, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)
# 获取tensor的⼤⼩
print(m.size()) # torch.Size([3,5])
# 均匀分布
print(torch.rand(3,5))
# 标准正态分布
print(torch.randn(3,5))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(3,5)))
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=20))

torch.Size([3, 5])
tensor([[0.8712, 0.1311, 0.1182, 0.1941, 0.9303],
        [0.6861, 0.4497, 0.7107, 0.2813, 0.2676],
        [0.3276, 0.3615, 0.6664, 0.7961, 0.4990]])
tensor([[-0.7588, -1.3232,  0.6431,  0.0964,  0.8541],
        [ 0.0840, -1.1206, -0.2369,  1.2832,  0.0087],
        [-0.9147,  0.8657, -0.3849, -1.5592,  0.2866]])
tensor([[ 0.7207, -0.4677, -0.9454,  0.7172,  1.1158],
        [ 0.8505,  0.5364, -0.1640, -0.7723, -0.4060],
        [ 0.2089,  0.3053, -0.3013,  1.3968,  1.2452]])
tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])


In [17]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}") # shape 张量的维度大小
print(f"Datatype of tensor: {tensor.dtype}") # dtype 张量的数据类型
print(f"Device tensor is stored on: {tensor.device}") # 张量在哪个设备上存储

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [18]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.7064, 0.7501, 0.3071, 0.7946],
        [0.5073, 0.4343, 0.2472, 0.0408],
        [0.8393, 0.1950, 0.8128, 0.4901]])
cpu
tensor([[0.7064, 0.7501, 0.3071, 0.7946],
        [0.5073, 0.4343, 0.2472, 0.0408],
        [0.8393, 0.1950, 0.8128, 0.4901]])
cpu


In [ ]:
tensor = torch.zeros(4, 3)
print('First row: ', tensor[0]) 
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1]) # -1表示倒数第一个  ... 用来表示前置所有
tensor[:,1] = 1
print(tensor)


First row:  tensor([0., 0., 0.])
First column:  tensor([0., 0., 0., 0.])
Last column: tensor([0., 0., 0., 0.])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim=-2) #cat 拼接张量 dim指定维度
print(t1)
print(t1 * 3)
print(t1.shape)

tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
tensor([[0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.],
        [0., 3., 0.]])
torch.Size([12, 3])


In [30]:
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)
print(tensor)
# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3) # out指定输出到y3
print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [33]:
agg = tensor.sum() # sum 将张量中的所有元素相加
print(agg)
agg_item = agg.item() # item 将一个单元素的张量转化为python数值
print(agg_item, type(agg_item))

tensor(45.)
45.0 <class 'float'>


In [ ]:
np_arr = z1.numpy() # numpy() 将张量转化为numpy数组
np_arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [ ]:
print(tensor, "\n")
tensor.add_(5) # 等同于如下两个方法 会改变tensor原张量的值，称之为in-place操作
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [3]:
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
print(result)
# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\83668\AppData\Local\Temp\ipykernel_19700\125038839.py:11: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:3729.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


tensor([ 1.8969,  3.4667,  0.9040,  6.8076, -0.7734, -0.2501,  4.1617, -3.3890,
        -4.1655, -1.7984], grad_fn=<AddBackward0>)


'expression.png'