#### pytorch搭建神经网络模型

In [3]:
#简单实现
import torch.nn as nn
import torch
# X输入shape(,784)
# 隐藏层 shape(784, 64) #参数矩阵，64个神经元
# 隐藏层 shape(64,) #偏置bias，等于神经元的数量
# 输出层 shape(64,10) #每个神经元有10个对应类别
# 输出层 shape(10,) #偏置bias
# Y输出shape(,10) 10个类别

In [ ]:
###隐藏层
#线性层
linear = nn.Linear(in_features=784, out_features=64, bias=True)
#激活层
act = nn.Sigmoid()

###输出层
linear2 = nn.Linear(in_features=64, out_features=10, bias=True)


###模拟输入
x = torch.randn(10, 784)
out1 = linear(x)
# print(out1)
out2 = act(out1)
# print(out2)
out3 = linear2(out2)
# print(out3)  #实数，可用softmax转换成概率的方式

softmax = nn.Softmax(dim=1)
final = softmax(out3)
print(final)

tensor([[0.0622, 0.0733, 0.0898, 0.2311, 0.0779, 0.0911, 0.1092, 0.0515, 0.1033,
         0.1106],
        [0.0752, 0.0775, 0.0862, 0.1964, 0.0906, 0.1079, 0.1047, 0.0534, 0.0965,
         0.1116],
        [0.0769, 0.0719, 0.0840, 0.1763, 0.0812, 0.1119, 0.1046, 0.0568, 0.1181,
         0.1182],
        [0.0774, 0.0744, 0.0807, 0.1972, 0.0857, 0.1141, 0.1272, 0.0520, 0.0951,
         0.0962],
        [0.0831, 0.0752, 0.0854, 0.1927, 0.0833, 0.1072, 0.1071, 0.0514, 0.0909,
         0.1237],
        [0.0811, 0.0670, 0.0870, 0.2055, 0.0800, 0.1263, 0.1012, 0.0457, 0.1043,
         0.1017],
        [0.0822, 0.0728, 0.0864, 0.1950, 0.0708, 0.1172, 0.1050, 0.0665, 0.0977,
         0.1064],
        [0.0787, 0.0793, 0.0799, 0.2064, 0.0735, 0.1135, 0.1050, 0.0553, 0.0982,
         0.1102],
        [0.0759, 0.0610, 0.0922, 0.1876, 0.0834, 0.1242, 0.0948, 0.0482, 0.1004,
         0.1325],
        [0.0740, 0.0633, 0.0970, 0.2034, 0.0835, 0.1086, 0.1054, 0.0503, 0.0981,
         0.1165]], grad_fn=<

In [ ]:
# 所有的结构串联
model = nn.Sequential(
    nn.Linear(784, 64),  #输入层
    nn.Sigmoid(),     #隐藏层
    nn.Linear(64, 10)  #输出层
)

#### 损失函数

In [ ]:
loss_fn = nn.CrossEntropyLoss() #交叉熵损失函数，计算梯度

#优化器（模型参数更新）
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) #SGD优化器， 梯度下降


In [19]:
[param for param in model.parameters()]

[Parameter containing:
 tensor([[-0.0092, -0.0283, -0.0126,  ...,  0.0012, -0.0318,  0.0205],
         [-0.0164, -0.0304, -0.0160,  ..., -0.0092, -0.0307, -0.0223],
         [-0.0211, -0.0102, -0.0347,  ...,  0.0018,  0.0094, -0.0293],
         ...,
         [ 0.0208, -0.0042,  0.0221,  ..., -0.0259, -0.0257,  0.0072],
         [-0.0297, -0.0104,  0.0178,  ...,  0.0073,  0.0063, -0.0156],
         [-0.0002,  0.0104, -0.0133,  ...,  0.0285,  0.0315, -0.0185]],
        requires_grad=True),
 Parameter containing:
 tensor([ 0.0200, -0.0335,  0.0104, -0.0352,  0.0314,  0.0218,  0.0062,  0.0235,
         -0.0140,  0.0110, -0.0346,  0.0050,  0.0160, -0.0225, -0.0213, -0.0148,
         -0.0333, -0.0164, -0.0300, -0.0301,  0.0163,  0.0201, -0.0135,  0.0210,
          0.0032, -0.0176, -0.0317,  0.0118,  0.0279, -0.0269, -0.0296,  0.0138,
          0.0117, -0.0130, -0.0053, -0.0080,  0.0138,  0.0179, -0.0060,  0.0273,
         -0.0011, -0.0030, -0.0322,  0.0091, -0.0163, -0.0190, -0.0288,  0.0042