In [11]:
import numpy as np

In [15]:
a = [1,2,3]
b = np.array(a)
b

array([1, 2, 3])

In [16]:
a = np.array([1,2,3],float)
a

array([1., 2., 3.])

In [17]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a = np.zeros((2,3),dtype = np.float32)
a

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [24]:
a = np.zeros((4,5),dtype = np.int32)
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
c = np.arange(1,6,0.4)
c

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. , 5.4, 5.8])

In [32]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.random.random(5) # 模型参数初始值
a

array([0.416416  , 0.81865075, 0.23267112, 0.81082704, 0.05331576])

In [ ]:
a = np.random.normal(0,0.1,5) # 模型参数初始值
a

array([ 0.02392954,  0.03929318, -0.09394022, -0.01118848, -0.19098619])

In [43]:
a = np.array([(1,2),(3,4),(5,6)])
#a[0]
#print(a[:,1])
#a[1:]
a[0][1]

2

In [ ]:
a = np.array([(1,2), (3,4), (5,6)])  #循环取数
#i,j = a[0]
for i,j in a:
    print(i,j)

1 2
3 4
5 6


In [47]:
a = np.array([1,2,3]) 
for i in a:
    print(i)

1
2
3


In [54]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int32


In [49]:
a = np.array([(1,2), (3,4)])
print(3 in a)
print(5 in a)

True
False


In [ ]:
a = np.arange(1,10)
print(a)
print(a.shape)

a1 = a.reshape(3,3)
print(a1)
print(a1.shape)  #高维矩阵  每个维度都有含义

#加载图像数据
#img.shap [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽


[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [13]:
a = np.array([1.2,3.8,4.9])
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("rint:", np.rint(a))

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [19]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
a = a.T
print(a)
b = a.flatten()
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 4 7 2 5 8 3 6 9]


In [20]:
a8 = np.array([(1,2),(3,4),(5,6)])
a8 = a8[:,np.newaxis,:]
a8.shape



(3, 1, 2)

In [23]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]


In [27]:
a = np.array([1,2,1])
#a.sum()
print(a.sum())
print()
a.prod()

4



2

In [28]:
a = np.array([5,3,1])
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())
print("max:", a.max())
print("min:", a.min())

mean: 3.0
var: 2.6666666666666665
std: 1.632993161855452
max: 5
min: 1


In [ ]:
#数组，矩阵，维度
#数组，矩阵 ： 数据组织结构形式
#维度 ： 通讯地址

In [ ]:
a = np.array([1.2, 3.8, 4.9])
print("argmax:", a.argmax()) #最大值索引
print("argmin:", a.argmin()) #最小值索引
print("ceil:", np.ceil(a))   #向上取整
print("floor:", np.floor(a)) #向下取整
print("rint:", np.rint(a))   #四舍五入

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [ ]:
a = np.array([16,31,12,28,22,31,48])
a.sort() #只排序  不返回任何数据
a

array([12, 16, 22, 28, 31, 31, 48])

In [39]:
# 定义两个简单的矩阵 
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# 使⽤ np.dot 进⾏矩阵乘法 
result_dot = np.dot(m1, m2)
# 使⽤ @ 运算符进⾏矩阵乘法 
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使⽤ np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使⽤ @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建⼀个全零矩阵，⽤于存储⼿动推演的结果
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
# 外层循环：遍历 matrix1 的每⼀⾏
# i 表⽰结果矩阵的⾏索引 
for i in range(m1.shape[0]):
 # 中层循环：遍历 matrix2 的每⼀列
 # j 表⽰结果矩阵的列索引
 for j in range(m2.shape[1]):
 # 初始化当前位置的结果为 0
  manual_result[i, j] = 0
 # 内层循环：计算 matrix1 的第 i ⾏与 matrix2 的第 j 列对应元素的乘积之和
 # k 表⽰参与乘法运算的元素索引
 for k in range(m1.shape[1]):
 # 打印当前正在计算的元素
  print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
 # 将 matrix1 的第 i ⾏第 k 列元素与 matrix2 的第 k ⾏第 j 列元素相乘，并累
 manual_result[i, j] += m1[i, k] * m2[k, j]
 # 打印当前位置计算完成后的结果
 print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")
print("⼿动推演结果:")
print(manual_result)


矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使⽤ np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使⽤ @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:16.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:32.0

⼿动推演结果:
[[ 0. 16.]
 [ 0. 32.]]


In [40]:
np.save('result.npy',manual_result)

In [41]:
result_np = np.load('result.npy')
result_np

array([[ 0., 16.],
       [ 0., 32.]], dtype=float32)

In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [47]:
a = np.array([(1,2), (2,2), (3,3), (4,4)]) # shape(4,2)
b = np.array([-1,1]) # shape(2)-> shape(1,2) -> shape(4,2) [-1,1],[-1,1],[-1,1],[-1,1]
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])