In [70]:
import numpy as np
import torch
from torchviz import make_dot
# 创建ndarray数组
ndarry = np.array([1,2,3,4], float)
ndarry


ModuleNotFoundError: No module named 'torchviz'

In [2]:
#创建多维数组
arr = np.array([(1,2,3), (2,3,4), (3,4,5)])
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [3]:
#创建0数组
arr_zero = np.zeros((3,3), dtype=float)
arr_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
#创建1数组
arr_one = np.ones((3,3), dtype=np.float32)
arr_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [5]:
#创建等差序列
arr_arange = np.arange(0,3, 0.9)
arr_arange

array([0. , 0.9, 1.8, 2.7])

In [6]:
#创建单位矩阵
arr_eye = np.eye(4)
arr_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
# 创建[0,1) 随机数
np.random.random(3)
# 创建均值m，标准差sigma的正态分布随机数
m,sigma = 1, 0.5
np.random.normal(m, sigma, 10)

array([1.27589729, 1.47806508, 0.87743632, 0.64207862, 1.07446925,
       1.21128044, 1.36518984, 1.81712723, 0.5311751 , 0.87623786])

In [8]:
# 访问多维数组
a = arr[0]
b = arr[1:]
c = arr[:, 1:]
d = arr[1][2]
print(d)

4


In [9]:
# 遍历一维数组
for i in arr_arange:
    print(i)
# 遍历多维数组
for i,j,*k in arr:
    print(i,j,k)

0.0
0.9
1.8
2.7
1 2 [3]
2 3 [4]
3 4 [5]


In [10]:
# np数组常用属性
print("ndim(维度-秩): ", arr.ndim ,
      "\nshape(大小): ", arr.shape,
      "\nsize(元素个数): ", arr.size,
      "\ndtype(元素类型): ", arr.dtype)

ndim(维度-秩):  2 
shape(大小):  (3, 3) 
size(元素个数):  9 
dtype(元素类型):  int32


In [11]:
# 检测数值是否在数组中
print(3 in arr, "\n", 6 in arr)
# 将多维数组转成一维
print(arr.reshape(arr.size), "\n", arr.flatten())
# 转置
print(arr.T, "\n", arr.transpose())

True 
 False
[1 2 3 2 3 4 3 4 5] 
 [1 2 3 2 3 4 3 4 5]
[[1 2 3]
 [2 3 4]
 [3 4 5]] 
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


In [12]:
# 增加维度
arr = arr[:, np.newaxis]
arr

array([[[1, 2, 3]],

       [[2, 3, 4]],

       [[3, 4, 5]]])

In [13]:
# np数学运算
a = np.ones((2,2))
b = np.array([(1,2), (3,4)])
print("a+b=", a + b)
print("a-b=", a - b)
print("a*b=", a * b)
print("a/b", a / b)

a+b= [[2. 3.]
 [4. 5.]]
a-b= [[ 0. -1.]
 [-2. -3.]]
a*b= [[1. 2.]
 [3. 4.]]
a/b [[1.         0.5       ]
 [0.33333333 0.25      ]]


In [14]:
print("求和sum=", b.sum())
print("求积prod=", b.prod())

求和sum= 10
求积prod= 24


In [15]:
print("平均数mean:", b.mean())
print("方差var:", b.var())
print("标准差std:", b.std())
print("最大最小值:", b.max(), "|", b.min())

平均数mean: 2.5
方差var: 1.25
标准差std: 1.118033988749895
最大最小值: 4 | 1


In [16]:
a = np.array([1.2, 3.8, 4.9, 3.5])
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil(向上取整):", np.ceil(a))
print("floor(向下取整):", np.floor(a))
print("rint:(四舍五入)", np.rint(a))

argmax: 2
argmin: 0
ceil(向上取整): [2. 4. 5. 4.]
floor(向下取整): [1. 3. 4. 3.]
rint:(四舍五入) [1. 4. 5. 4.]


In [17]:
a.sort()
a

array([1.2, 3.5, 3.8, 4.9])

In [18]:
# 矩阵乘法（内积）
a = np.array([(1,2),(3,4)])
b = np.array([(-1, -2),(-3, -4)])
print(np.dot(a, b))
print(a @ b)

[[ -7 -10]
 [-15 -22]]
[[ -7 -10]
 [-15 -22]]


In [19]:
# 广播机制，自动补全计算时的元素，使shape相同
c = np.array([(1,2)])
d = np.array([[1],[2]])
print(a + c)
print(a + d)

[[2 4]
 [4 6]]
[[2 3]
 [5 6]]


In [ ]:
# 张量初始化
data = [(1,2),(3,4)]
xdata = torch.tensor(data)
print(xdata)

# ndarr = np.array([(1,2)])
# xdata2 = torch.from_numpy(ndarr)

tensor([[1, 2],
        [3, 4]])


In [31]:
x_ones = torch.ones_like(xdata)
print(x_ones)
x_rands = torch.rand_like(xdata, dtype=torch.float)
print(x_rands)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1236, 0.5554],
        [0.5623, 0.0404]])


In [32]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0148, 0.2390, 0.8751],
        [0.7530, 0.5366, 0.6136]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [48]:
# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(3,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)
# 获取tensor的⼤⼩
print(m.size()) # torch.Size([3,3])
# 均匀分布
torch.rand(3,3)
# 标准正态分布
torch.randn(3,3)
# 离散正态分布
torch.normal(mean=.0,std=1.0,size=(3,3))
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
torch.linspace(start=1,end=10,steps=20)

torch.Size([3, 3])


tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [35]:
# 张量的属性
print("形状:",xdata.shape)
print("类型:", xdata.dtype)
print("存储设备:", xdata.device)

形状: torch.Size([2, 2])
类型: torch.int64
存储设备: cpu


In [46]:
# 设置张量在GPU上运算
if torch.cuda.is_available():
    tensor = xdata.to('cuda')
print(tensor)

tensor([[1, 2],
        [3, 4]], device='cuda:0')


In [38]:
print('First row: ', xdata[0])
print('First column: ', xdata[:, 0])
print('Last column:', xdata[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1, 2])
First column:  tensor([1, 3])
Last column: tensor([2, 4])
tensor([[1, 0],
        [3, 0]], device='cuda:0')


In [ ]:
t1 = torch.cat([xdata, xdata], dim=1) #默认dim = 0
t1

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

In [62]:
# 计算两个张量之间矩阵乘法的⼏种⽅式。 y1, y2, y3 最后的值是⼀样的 dot
tensor = torch.tensor([(1,2), (3,4)], dtype=torch.float)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

# 计算张量逐元素相乘的⼏种⽅法。 z1, z2, z3 最后的值是⼀样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[ 5., 11.],
        [11., 25.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


In [64]:
agg = tensor.sum()
print(agg)
agg_item = agg.item() # 将单元素张量转化为python值
print(agg_item, type(agg_item))

tensor(10.)
10.0 <class 'float'>


In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)
# In-place操作虽然节省了⼀部分内存，但在计算导数时可能会出现问题，因为它会⽴即丢失历史记录。因此，不⿎励使⽤它们。

tensor([[1., 2.],
        [3., 4.]]) 

tensor([[6., 7.],
        [8., 9.]])


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])


RuntimeError: Numpy is not available

In [ ]:
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

ModuleNotFoundError: No module named 'torchviz'