In [2]:
import torch

data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
data

tensor([[1., 2.],
        [3., 4.]])

In [7]:
import torch
import numpy as np

data2 = torch.from_numpy(np.array([(1, 2), (3, 4)]))
print(data2)
data2.dtype

# NumPy（Numerical Python）是 Python 中⼀个基础且强⼤的开源数值计算库，
# 它为 Python 提供了⾼效的多维数组对象以及处理这些数组的各种⼯具，
# ⼴泛应⽤于数据科学、机器学习、科学计算等众多领域。

tensor([[1, 2],
        [3, 4]])


torch.int64

In [5]:
# 从另⼀个张量：除⾮明确覆盖，否则新张量保留参数张量的属性（形状、数据类型）。
x_ones = torch.ones_like(data2)  # 保留of data2的属性
print(f"ones tensor\n {x_ones} \n")

x_rand = torch.rand_like(data2, dtype=torch.float) #覆盖data的数据类型
print(f"random tensor \n {x_rand} \n")


ones tensor
 tensor([[1, 1],
        [1, 1]]) 

random tensor 
 tensor([[0.5630, 0.7480],
        [0.8971, 0.8171]]) 



In [6]:
#使用随机值或者常量值，shape 是张量维度的元组。在下⾯的函数中，它决定了输出张量的维度。
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"rand_tensor\n {rand_tensor} \n")
print(f"ones_tensor\n {ones_tensor} \n")
print(f"zeros_tensor\n {zeros_tensor} \n")

# 其它⼀些创建⽅法

rand_tensor
 tensor([[0.8913, 0.9885, 0.3334],
        [0.2340, 0.2721, 0.3548]]) 

ones_tensor
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zeros_tensor
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [ ]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)
# n 的返回结果是一个大小为 (5, 3) 的张量，其中的元素是从均匀分布 [0, 1) 中随机采样的浮点数，
# 数据类型为 torch.float（32 位浮点数）。由于随机性，每次运行代码时 n 的具体数值会有所不同，但它们总是位于 0 和 1 之间。

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))


In [25]:
# 张量的属性描述了张量的形状、数据类型和存储它们的设备。以对象的⻆度来判断，
# 张量可以看做是具有特征和⽅法的对象。
# https://pytorch.org/docs/stable/torch.html 
# 这个链接⾥ 全⾯介绍100 多种张量运算，包括算术、线性代数、矩阵操作（转置、索引、切⽚）、采样等等。

tensor = torch.rand(3,4)
tensor.shape
tensor.dtype
tensor.device
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [28]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)
print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)


tensor([[0.2207, 0.9895, 0.0580, 0.3381],
        [0.9759, 0.5539, 0.8441, 0.5568],
        [0.5912, 0.4033, 0.8426, 0.7234]])
cpu
tensor([[0.2207, 0.9895, 0.0580, 0.3381],
        [0.9759, 0.5539, 0.8441, 0.5568],
        [0.5912, 0.4033, 0.8426, 0.7234]], device='mps:0')
mps:0


In [31]:
# 张量的索引和切⽚：
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0  #对张量中所有行的第1列操作
print(tensor)


First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [32]:
# 可以使⽤ torch.cat ⽤来连接指定维度的⼀系列张量。另⼀个和 torch.cat 功能类似的函数
# 是torch.stack
# 参数 dim 指定了沿哪个维度进行拼接。对于 dim=1：
# 如果 tensor 是一个二维张量（矩阵），dim=0 表示沿着行的方向（垂直方向）拼接，而 dim=1 表示沿着列的方向（水平方向）拼接。
# 具体而言，dim=1 意味着将多个张量在列方向上拼接在一起。这会增加列的数量，而行数保持不变。
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.]])
torch.Size([4, 12])


In [35]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)
#reshape重新定义形状

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

y3 = torch.rand_like(tensor) #初始化
torch.matmul(tensor, tensor.T, out=y3)
print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[0.7851, 0.9353, 0.2647],
        [0.8768, 0.1896, 0.3515],
        [0.0615, 0.9086, 0.5943]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [37]:
# 如果⼀个单元素张量，例如将张量的值聚合计算，可以使⽤ item() ⽅法将其转换为Python 数值
agg = tensor.sum()  #所有元素相加
agg_item = agg.item() 
print(agg_item, type(agg_item))

45.0 <class 'float'>


In [38]:
# In-place操作
# 把计算结果存储到当前操作数中的操作就称为就地操作。含义和pandas中inPlace参数的含义⼀样。
# pytorch中，这些操作是由带有下划线 _ 后缀的函数表⽰。例如：
# x.copy_(y) ,  x.t_() , 将改变 x ⾃⾝的值。
print(tensor, "\n")
tensor.add_(5)

# tensor = tensor + 5
# tensor += 5

print(tensor)

##############特别注意##############
# In-place操作虽然节省了⼀部分内存，但在计算导数时可能会出现问题，
# 因为它会⽴即丢失历史记录。因此，不⿎励使⽤它们

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) 

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])


In [39]:
tensor

# 与numpy之间的转换
# CPU 和 NumPy 数组上的张量共享底层内存位置，所以改变⼀个另⼀个也会变。


tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])

In [47]:
import numpy
# 张量到numpy数组,
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# 与numpy之间的转换,CPU 和 NumPy 数组上的张量共享底层内存位置，所以改变⼀个另⼀个也会变。
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

# Numpy数组到张量
n = numpy.ones(6)
t = torch.from_numpy(n)

numpy.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2. 2.]


计算图
在进⼀步学习pytorch之前，先要了解⼀个概念 —— 计算图( Computation graph)
所有的深度学习框架都依赖于计算图来完成梯度下降、优化梯度值等计算。
⽽计算图的创建和应⽤，通常包含如下两个部分：
1. ⽤⼾构建前向传播图
2. 框架处理后向传播(梯度更新)
模型从简单到复杂，pytorch和tensorflow都使⽤计算图来完成⼯作。
但是，这两个框架所使⽤的计算图也却有所不同：
tensorflow1.x 使⽤的是静态计算图，tensorflow2.x和pytorch使⽤的是动态计算图。

静态计算图
通常包括以下两个阶段。
阶段1：定义⼀个架构(可以使⽤⼀些基本的流控制⽅法，⽐如循环和条件指令)
阶段2：运⾏⼀组数据来训练模型，进⾏推理。
优点：允许对图进⾏强⼤的离线优化/调度，所以速度相对较快。
缺点：难以调试，对代码中处理结构化或者可变⼤⼩的数据处理⽐较复杂。

动态计算图
在执⾏正向计算时，隐式地定义图(动态构建)。
优点：灵活，侵⼊性⼩，允许动态构建和评估。
缺点：难以优化。

两种计算图⽐较起来，可以看出：动态图是对调试友好的(对程序员友好)。它允许逐
⾏执⾏代码，并可以访问所有张量。这样更便于发现和找到我们计算或逻辑中的问
题。当然，前提是你必须熟练掌握程序的调试(debug)技能 😄 ~~

In [10]:
# pytorch计算图可视化
# 通过torchviz可以实现

import torch
import torchviz
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)

result1 = torch.matmul(A, x.T)
result2 = torch.matmul(b, x)
# print(b)
# print(x)
print(result1)

print(result2)
print(c)

result = result1 + result2 + c
print(result)
# x.T
# result1
# # 计算 x^T * A + b * x + c
# result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# # 生成计算图节点
# dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# # 绘制计算图
# dot.render('expression', format='png', cleanup=True, view=False)


tensor([ 0.4354, -7.9705, -1.9479,  0.9520,  3.5812, -0.8248,  0.4581, -0.7154,
         0.6195, -4.3332], grad_fn=<MvBackward0>)
tensor(-2.5183, grad_fn=<DotBackward0>)
tensor([-1.0274], requires_grad=True)
tensor([ -3.1103, -11.5161,  -5.4935,  -2.5937,   0.0355,  -4.3705,  -3.0876,
         -4.2611,  -2.9262,  -7.8788], grad_fn=<AddBackward0>)
