In [1]:
import numpy as np

In [2]:
# 创建ndarray数组
arr = np.array([2,4,6,8,10], float)
arr

array([ 2.,  4.,  6.,  8., 10.])

In [7]:
a = np.array([(2,4,6), (8,10,12), (14,18,20)],dtype=float)
a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 18., 20.]])

In [9]:
a1 = np.zeros((10,10), dtype=np.float32)
a1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [10]:
a2 = np.arange(1,8, 0.5)
a2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

In [11]:
a3 = np.eye(6)
a3  # one-hot编码

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [12]:
a4 = np.random.random(10)  # 模型运算参数初始值
a4

array([0.23566858, 0.14889801, 0.79197235, 0.93630471, 0.481181  ,
       0.29104515, 0.28874878, 0.9702382 , 0.62116254, 0.76970855])

In [14]:
a5 = np.random.normal(0, 1, 6)  # 模型运算参数初始值
a5

array([-0.35787342, -0.24194079,  0.75533816, -1.1228455 , -0.688104  ,
        0.64953225])

In [16]:
a6 = np.array([(1,12), (3,100), (5,0.6)])
# print(a6)
print(a6[:,0])

[1. 3. 5.]


In [17]:
a7 = np.array([(11,22), (13,24), (15,26)])
# i,j = a7[0]
for i,j in a7:
    print(i,j)

11 22
13 24
15 26


In [23]:
a = np.array([[(1,2,3), (4,5,6), (7,8,9)]])
a1 = np.array([1,2,3])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)
a

ndim: 3
shape: (1, 3, 3)
size 9
dtype int32


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
print(3 in a)

True


In [25]:
a7 = np.arange(2,16)
print(a7)
print(a7.shape)

a7 = a7.reshape(2,7,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(14,)
[[[ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]]]
(2, 7, 1)


In [28]:
print(a7)
a = a7.T
print(a)

[[[ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]]]
[[[ 2  9]
  [ 3 10]
  [ 4 11]
  [ 5 12]
  [ 6 13]
  [ 7 14]
  [ 8 15]]]


In [29]:
a = a.flatten()
print(a)


[ 2  9  3 10  4 11  5 12  6 13  7 14  8 15]


In [35]:
a8 = np.array([(12,21), (23,43), (56,76)])
a8 = a8[:,:,np.newaxis]  # [3,1,2]
a8 = a8[:,np.newaxis,:,]
a8.shape

(3, 1, 2, 1)

In [36]:
a = np.zeros((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)

[[0. 0.]
 [0. 0.]]
[[-1  1]
 [-1  1]]

[[-1.  1.]
 [-1.  1.]]

[[ 1. -1.]
 [ 1. -1.]]


In [37]:
a.sum()

0.0

In [38]:
a.prod()

0.0

In [ ]:
# 数组，矩阵、维度

# 数组、矩阵  ： 数据组织结构形式

# 维度： 通讯地址

In [43]:
a = np.array([2,64,128])
print("取整_mean:",int(a.mean()))
print("mean:",a.mean())
print("var:", a.var())
print("std:", a.std())

取整_mean: 64
mean: 64.66666666666667
var: 2646.222222222222
std: 51.44144459696114


In [46]:
a = np.array([0, 2.8,2,5 ,4.9])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 3
argmin: 0
ceil: [0. 3. 2. 5. 5.]
floor: [0. 2. 2. 5. 4.]
rint: [0. 3. 2. 5. 5.]


In [47]:
a = np.array([16,31,1.2,2.8,22,31,48])
a.sort()  # 排序
a

array([ 1.2,  2.8, 16. , 22. , 31. , 31. , 48. ])

In [48]:
import torch
tensor = torch.arange(2,20, dtype=torch.float32).reshape(3, 6)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


C:\Users\liyang\AppData\Local\Temp\ipykernel_18428\1034466771.py:11: UserWarning: An output with one or more elements was resized since it had shape [3, 6], which does not match the required output shape [3, 3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:35.)
  torch.matmul(tensor, tensor.T, out=y3)


tensor([[  4.,   9.,  16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121., 144., 169.],
        [196., 225., 256., 289., 324., 361.]])

In [55]:
a9 = np.array([[6,2,7],[4,51,6]])
# a9= a9.transpose(1,0)  
b9 = np.array([[4,7,6],[10,8,9]])

a9 * b9

array([[ 24,  14,  42],
       [ 40, 408,  54]])

In [56]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[24, 56], [36, 47]], dtype=np.float32)
m2 = np.array([[50, 68], [79, 18]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[24. 56.]
 [36. 47.]]
矩阵 2:
[[50. 68.]
 [79. 18.]]
使用 np.dot 得到的矩阵乘法结果:
[[5624. 2640.]
 [5513. 3294.]]
使用 @ 运算符得到的矩阵乘法结果:
[[5624. 2640.]
 [5513. 3294.]]
24.0 * 50.0 = 1200.0
56.0 * 79.0 = 4424.0
结果矩阵[1,1]:5624.0

24.0 * 68.0 = 1632.0
56.0 * 18.0 = 1008.0
结果矩阵[1,2]:2640.0

36.0 * 50.0 = 1800.0
47.0 * 79.0 = 3713.0
结果矩阵[2,1]:5513.0

36.0 * 68.0 = 2448.0
47.0 * 18.0 = 846.0
结果矩阵[2,2]:3294.0

手动推演结果:
[[5624. 2640.]
 [5513. 3294.]]


In [57]:
np.save('result.npy',manual_result)

In [58]:
result_np = np.load('result.npy')
result_np

array([[5624., 2640.],
       [5513., 3294.]], dtype=float32)

In [60]:
a = np.array([2,3,4])
b = np.array([4,7,6])
a + b

array([ 6, 10, 10])

In [63]:
a = np.array([(1,12), (21,12), (23,3), (41,4)])  # shape(4,2)
b = np.array([0,-np.inf])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

array([[  1., -inf],
       [ 21., -inf],
       [ 23., -inf],
       [ 41., -inf]])