In [1]:
import torch

data = torch.tensor([[11,21],[31,14]], dtype=torch.float32)
data

tensor([[11., 21.],
        [31., 14.]])

In [2]:
import numpy as np

np_array = np.array([[11,21],[31,14]])
data2 = torch.from_numpy(np_array)
data2

tensor([[11, 21],
        [31, 14]], dtype=torch.int32)

In [3]:
data2.dtype

torch.int32

In [4]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float32)
data3

tensor([[0.7716, 0.4052],
        [0.2497, 0.8192]])

In [7]:
shape = (1,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5792, 0.1618, 0.3977]]) 

Ones Tensor: 
 tensor([[1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.]])


In [8]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(3,1, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([3, 1])
tensor([[0.2318, 0.7361, 0.2657],
        [0.2027, 0.9578, 0.9842],
        [0.2479, 0.5188, 0.2394],
        [0.3634, 0.8613, 0.9626],
        [0.2771, 0.6528, 0.5105]])
tensor([[-0.7517, -0.5316, -0.5412],
        [ 0.4323,  0.4509,  1.3405],
        [ 0.2337,  1.5365,  0.7179],
        [-0.9683,  0.4040,  0.5504],
        [ 0.5759,  0.5571,  0.1157]])
tensor([[ 0.8864, -0.2509,  1.3995],
        [-1.7784,  1.1668,  1.0366],
        [ 0.0869, -0.6527, -0.9683],
        [-0.4097,  0.7753,  0.6146],
        [-0.5043, -0.0422,  0.3553]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [9]:
tensor = torch.rand(1,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([1, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [10]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.3758, 0.6466, 0.7110, 0.1101]])
cpu
tensor([[0.3758, 0.6466, 0.7110, 0.1101]])
cpu


In [12]:
tensor = torch.ones(3, 2)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1.])
First column:  tensor([1., 1., 1.])
Last column: tensor([1., 1., 1.])
tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])


In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 2)
print(t1.shape)

tensor([[2., 0., 2., 0., 2., 0.],
        [2., 0., 2., 0., 2., 0.],
        [2., 0., 2., 0., 2., 0.]])
torch.Size([3, 6])


In [30]:
import torch
tensor = torch.arange(1,26, dtype=torch.float32).reshape(5, 5)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[  1.,   4.,   9.,  16.,  25.],
        [ 36.,  49.,  64.,  81., 100.],
        [121., 144., 169., 196., 225.],
        [256., 289., 324., 361., 400.],
        [441., 484., 529., 576., 625.]])
tensor([[  1.,   4.,   9.,  16.,  25.],
        [ 36.,  49.,  64.,  81., 100.],
        [121., 144., 169., 196., 225.],
        [256., 289., 324., 361., 400.],
        [441., 484., 529., 576., 625.]])


In [31]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

325.0 <class 'float'>


In [32]:
np_arr = z1.numpy()
np_arr

array([[  1.,   4.,   9.,  16.,  25.],
       [ 36.,  49.,  64.,  81., 100.],
       [121., 144., 169., 196., 225.],
       [256., 289., 324., 361., 400.],
       [441., 484., 529., 576., 625.]], dtype=float32)

In [34]:
print(tensor, "\n")
tensor.add_(2)
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]]) 

tensor([[ 8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22.],
        [23., 24., 25., 26., 27.],
        [28., 29., 30., 31., 32.]])


In [35]:
tensor

tensor([[ 8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22.],
        [23., 24., 25., 26., 27.],
        [28., 29., 30., 31., 32.]])

In [7]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
a = torch.randn(12, 12,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(12,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(12, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(a, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'a': a, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression_work', format='png', cleanup=True, view=False)

'expression_work.png'

In [9]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
a = torch.randn(12, 6,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(6,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(6, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(a, x) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'a': a, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression_work1', format='png', cleanup=True, view=False)

'expression_work1.png'