In [3]:
#1. numpy 多维数组运算库
#数据类型：bool_  int_  uint_  float_  complex_
#numpy的数据类型实际上是dtype对象的实例，对应唯一的字符
# ndarray  numpy数组  由数组实际数据与描述这些数据的元数据组成
#1.1 numpy数组创建
#用列表转换
import numpy as np
a = [1,2,3]
b = np.array(a)
b

array([1, 2, 3])

In [4]:
arr1 = np.array([1,2,3], float)
arr2 = np.array((3,4,5),int)
arr3 = np.array([4,5,6],dtype = float)
print(arr1, arr1.dtype)  #打印时省略了array修饰
print(arr2, arr2.dtype)  #Jupyter Notebook默认会显示最后赋值的变量结果  因此用print
arr3  

[1. 2. 3.] float64
[3 4 5] int32


array([4., 5., 6.])

In [5]:
#多维数组创建
a = np.array(([1,2,3],[4,5,6],[7,8,9]))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#特殊数组创建
a = np.zeros((3,4), float)  #全0数组
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b = np.ones((3,2))  #全1数组
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
c = np.arange(100,10,-10)  #等差数组
c

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [9]:
d = np.eye(3)  #单位矩阵1
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
e = np.identity(3)  #单位矩阵2
e 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
f = np.random.rand(4)  #随机数数组
f

array([0.52842422, 0.01466973, 0.91258917, 0.7065939 ])

In [12]:
g = np.zeros_like([[1,2,3],[4,5,6]])  #0矩阵
g

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
h = np.full((2,3),5)  #按形状填充特定值
h

array([[5, 5, 5],
       [5, 5, 5]])

In [14]:
i = np.diag([3,4,5])  #对角矩阵
i

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [15]:
mu,sigma = 1,0.2  #正太分布数组
np.random.normal(mu,sigma,5)

array([1.29340767, 0.98747885, 1.02385605, 1.07321461, 0.90437547])

In [16]:
#1.2 np数组访问
a = np.array(([1,2],[3,4]))
print(a[0])
print(a[1:])
print(a[:1])
print(a[:,:1])
print(a[1][1])

[1 2]
[[3 4]]
[[1 2]]
[[1]
 [3]]
4


In [17]:
# 数组的遍历
a = np.array([1,2,3])
for i in a:
    print(i)
b = np.array(([1,2],[4,5],[6,7]))
for j,k in b:
    print(j*k)

1
2
3
2
20
42


In [18]:
#数组的属性
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim)  #维度、秩
print("shape:", a.shape)  #大小
print("size", a.size)  #元素个数
print("dtype", a.dtype)  #元素类型

ndim: 2
shape: (3, 3)
size 9
dtype int32


In [19]:
# 1.3数组的基本操作
# 检测数值是否在组中
a = np.array([(1,2,3),(4,5,6)])
print(4 in a)
print(7 in a)

True
False


In [20]:
# 数组的重排列
a = np.zeros([2,3])
a
a.reshape(6)  #array([0.,0.,0.,0.,0.,0.])
a.reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
# 数组的转置
a = np.array(([1,2,3,4],[5,6,7,8]))
a.T  #a.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
# 多维数组转换一维
a = np.array([(1,2,3),(4,5,6)])
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [23]:
#增加维度
a = np.array((1,2,3,4))
print(a.shape)
a = a[:, np.newaxis]
a

(4,)


array([[1],
       [2],
       [3],
       [4]])

In [24]:
# 1.4 数组的数学操作
a = np.array(((1,2),(2,1)))
b = np.ones((2,2))
print(a)
print(b)
print(a+b)
print(a*b)
print(a.sum())
print(a.prod())  #积

[[1 2]
 [2 1]]
[[1. 1.]
 [1. 1.]]
[[2. 3.]
 [3. 2.]]
[[1. 2.]
 [2. 1.]]
6
4


In [25]:
a = np.array((2,4,6))
print("mean:",a.mean())  #平均值
print("var:", a.var())  #方差
print("std:", a.std())  #标准差
print("max:", a.max())  
print("min:", a.min())

mean: 4.0
var: 2.6666666666666665
std: 1.632993161855452
max: 6
min: 2


In [26]:
a = np.array([1.2, 3.8, 4.9])
print("argmax:", a.argmax())  #返回元素最大值位置
print("argmin:", a.argmin())  #返回元素最小值位置
print("ceil:", np.ceil(a))  #向上取整
print("floor:", np.floor(a))  #向下取整
print("rint:", np.rint(a))  #四舍五入

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [27]:
#排序
a = np.array([16,31,12,28,22,31,48])
a.sort()
a

array([12, 16, 22, 28, 31, 31, 48])

In [28]:
#numpy线性代数
a = np.array(((1,2),(3,4)))
b = np.array(((2,2),(3,3)))
result_dot = np.dot(a,b)  #矩阵乘法
result_at = a @ b  #矩阵乘法
print(result_dot)
print(result_at)

[[ 8  8]
 [18 18]]
[[ 8  8]
 [18 18]]


In [6]:
m1 = np.array([[1, 2], [3, 4]] , dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]] , dtype=np.float32)
#结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32) 
for i in range(m1.shape[0]):
    for j in range(m1.shape[0]):
        manual_result[i, j] = 0
    for k in range(m1.shape[1]):
        print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
        manual_result[i, j] += m1[i, k] * m2[k, j]
    print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")
print("⼿动推演结果:")
print(manual_result)

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

⼿动推演结果:
[[ 0. 22.]
 [ 0. 50.]]


In [13]:
#文件操作
#二进制文件 np.save  np.load  .npy格式
#文本文件 np.loadtxt  np.savetext
np.save('result.npy',manual_result)

In [14]:
result_np = np.load('result.npy')
result_np

array([[ 0., 22.],
       [ 0., 50.]], dtype=float32)

In [17]:
#numpy广播机制
#不同形状数组数值运算
a = np.array(((1,2,3),(4,5,6)))  #(3,2)
b = np.array((1,2,3))  #(1,3)
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
#2. pytorch基础