In [1]:
'''Numpy线性代数
1. 简单的相乘
'''
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[3, 4, 5], [6, 7, 8]])
# 俩个类型一样的矩阵相乘， 相应元素相乘
print(arr1 * arr2)

[[ 3  8 15]
 [24 35 48]]


In [2]:
'''
2.矩阵(向量) 乘积
对于二维数组乘积，要求 X1 的列 与 X2的行保持一致
'''
arr3 = np.array([[2, 3], [4, 5], [6, 7]])
# resp = np.dot(arr1, arr2)   # arr1, arr2 都是 2x3矩阵，不满足条件
resp = np.dot(arr1, arr3)
print(resp)

[[28 34]
 [64 79]]


In [3]:
'''尝试其它维度数据运算
@ 一维向量 & 一维向量
@ 二维矩阵 & 一维向量
@ 多维运算：要求第一个数组的最后一维的长度跟 第二个数组倒数第二维的长度相同
'''
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 0])
print(np.dot(a, b))

c = np.random.randint(0, 10, size=(5, 5))
print(a.shape, c.shape)
print(np.dot(c, a))

d = np.random.randint(1, 8, (1, 2, 3, 4))
e = np.random.randint(2, 9, (6, 5, 4, 7))
print(np.dot(d, e).shape)

80
(5,) (5, 5)
[87 94 71 42 49]
(1, 2, 3, 6, 5, 7)
