In [1]:
import numpy as np #先引入包

#定义一个一维数组，规定数据类型
arr = np.array([12,2, 34,43], dtype=np.float32)
arr

array([12.,  2., 34., 43.], dtype=float32)

In [8]:
'''
定义 3*3 数组
'''
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
arr2
'''
或者初始化一个多维的空数组
'''
arr_empty = np.zeros((4, 4), dtype=int)
arr_empty[0] = [255, 255, 255, 255]
arr_empty

array([[255, 255, 255, 255],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0]])

In [ ]:
'''
使用np.eye()来创建特殊矩阵，实现矩阵对角线上的数值相同
'''
arr_eye = np.eye(4)
arr_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
'''
等差序列的创建
np.arange(起，止， 步长)
'''
# arr_dx = np.arange(1, 7)
arr_dx = np.arange(1, 7, 0.3)
arr_dx

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7])

In [ ]:
'''
随机数生成, 生成一个0~1之间的随机数
'''
# randx = np.random.random()    #一个就够了
# randx
arr_dx = np.random.random(size=6)   #如果需要多个
arr_dx

array([0.42650095, 0.68556823, 0.11062446, 0.12843361, 0.51204839,
       0.62398769])

In [3]:
'''
正态分布规律的随机数
loc: float = 正态分布的均值
scale: float = 标准差
size: None = 生成的随机个数
'''
arr_nx = np.random.normal(1, 0.1, 33)
arr_nx

array([1.04726394, 1.01143902, 0.98795866, 0.97771469, 0.83045975,
       1.21748462, 0.98593393, 1.0297252 , 1.07547164, 0.96187654,
       1.01121297, 0.90037408, 0.88483329, 1.04404072, 0.94581853,
       1.02634437, 0.90334849, 1.01739006, 0.95543958, 0.89634045,
       0.99319838, 1.06205596, 1.10631076, 1.02217482, 0.83828147,
       0.85997785, 1.02855133, 1.08242996, 1.11702978, 1.19601381,
       0.8391306 , 0.97880457, 0.97687712])