In [33]:
'''
numpy数组对象访问
1. 切片
'''
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float64)
print("原始数组：\n",np_arr)
# 切片访问
print("只要前两个：\n", np_arr[:2], type(np_arr[:2]))
# 获取具体的元素
np_item = np_arr[1, -1] + 15
print("第二行，最后一列:", np_item, type(np_item))
# 判断元素是否在数组里
if 21 in np_arr:
    print("是的， 它在这个数组中")
else:
    print("这个该死的小混蛋，它没在这里面")
# 另外可以查询
print((4, 5, 6) in np_arr)
print((3, 4, 5) in np_arr)

原始数组：
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
只要前两个：
 [[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'>
第二行，最后一列: 21.0 <class 'numpy.float64'>
这个该死的小混蛋，它没在这里面
True
False


In [16]:
'''np.arr遍历'''
# 多维数组遍历1：
for a1, a2, a3 in np_arr:
    print(a1, a2, a3)

1.0 2.0 3.0
4.0 5.0 6.0
7.0 8.0 9.0


In [30]:
'''获取数组属性'''
print(f"数组np_arr的维度：{np_arr.ndim}")
print(f"数组np_arr的大小：{np_arr.shape}")
print(f"数组np_arr一共 {np_arr.size} 个元素")
print(f"数组np_arr里元素的类型： {np_arr.dtype}")
# 创建一个多维数组
np_arr2 = np.zeros((2, 3, 4))
print(np_arr2)
print(f"数组np_arr2的维度：{np_arr2.ndim}")
print(f"数组np_arr2的大小：{np_arr2.shape}")
print(f"数组np_arr2一共 {np_arr2.size} 个元素")
print(f"数组np_arr2里元素的类型： {np_arr2.dtype}")

数组np_arr的维度：2
数组np_arr的大小：(3, 3)
数组np_arr一共 9 个元素
数组np_arr里元素的类型： float64
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
数组np_arr2的维度：3
数组np_arr2的大小：(2, 3, 4)
数组np_arr2一共 24 个元素
数组np_arr2里元素的类型： float64


In [ ]:
np_arr3 = np.arange(1, 10)
np_arr3
np_arr4 = np_arr3.reshape(1, 3, 3)
np_arr5 = np_arr3.reshape(3, 3)
print(np_arr4.ndim, np_arr5.ndim)

3 2


In [44]:
'''
转置(T)
行列互换
'''
print("原始数组：\n", np_arr)
print("转置后的数组：\n", np_arr.T)
np_arr6 = np.array([(1, 2), (3, 4), (5, 6)])
print(np_arr6.T)

原始数组：
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
转置后的数组：
 [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
[[1 3 5]
 [2 4 6]]


In [51]:
'''将多维数组拉伸成一维数组'''
print(np_arr6.T.flatten())
print(np_arr.T.flatten())

[1 3 5 2 4 6]
[1. 4. 7. 2. 5. 8. 3. 6. 9.]


In [57]:
'''np.arr 数学运算
1. 两个数组相加首先两个数组 shape要相同;
2. 数组自身运算： 求 数组元素相加，相乘；
'''
arr_n1 = np.ones((2, 2))
arr_n2 = np.array([[1, 2], [4, 6]])
arr_n3 = arr_n1 + arr_n2
print("arr_n1: \n", arr_n1, "\n arr_n2: \n", arr_n2, "\n arr_n3: \n", arr_n3)
print(f"数组 arr_n3 元素相加= {arr_n3.sum()}; 元素相乘= {arr_n3.prod()}")
print("数组相乘: \n", arr_n2 * arr_n3)

arr_n1: 
 [[1. 1.]
 [1. 1.]] 
 arr_n2: 
 [[1 2]
 [4 6]] 
 arr_n3: 
 [[2. 3.]
 [5. 7.]]
数组 arr_n3 元素相加= 17.0; 元素相乘= 210.0
数组相乘: 
 [[ 2.  6.]
 [20. 42.]]


In [63]:
'''平均数，极值， 方差，标准差'''
print("arr_n3 的平均值：", arr_n3.mean(), "最大值：", arr_n3.max(), "最小值：", arr_n3.min(), "标准差：", arr_n3.std(), "方差：", arr_n3.var())

arr_n3 的平均值： 4.25 最大值： 7.0 最小值： 2.0 标准差： 1.920286436967152 方差： 3.6875


In [76]:
'''极值索引， 数组元素向上取整， 向下取整，四舍五入'''
arr_n7 = np.array([(3.134, 2.768), (0.22, 1.96)])
print("arr_n7最大值索引：", arr_n7.argmax())
print("arr_n7最小值索引：", arr_n7.argmin())
print("arr_n7 元素向上取整:\n", np.ceil(arr_n7))
print("arr_n7 元素向下取整:\n", np.floor(arr_n7))
print("arr_n7 元素四舍五入:\n", np.rint(arr_n7))


arr_n7最大值索引： 0
arr_n7最小值索引： 2
arr_n7 元素向上取整:
 [[4. 3.]
 [1. 2.]]
arr_n7 元素向下取整:
 [[3. 2.]
 [0. 1.]]
arr_n7 元素四舍五入:
 [[3. 3.]
 [0. 2.]]


In [ ]:
'''当你执行 arr_n7.sort() 对数组进行排序时，需要注意 NumPy 中的 sort 方法默认是按数组的最后一个轴（即最内层轴）进行排序'''
arr_n7.sort()
print(arr_n7)

[[2.768 3.134]
 [0.22  1.96 ]]
