In [5]:
'''tensor 的索引和切片'''
import torch

tsr_arr = torch.randn((4, 4))
print("原始张量: \n", tsr_arr)
print("第一行数据：", tsr_arr[0])
print("第一列数据：", tsr_arr[:, 0])
print("最后一列:", tsr_arr[..., -1])

原始张量: 
 tensor([[ 0.2767, -0.6826, -0.3169,  1.3604],
        [-0.2712, -1.2449, -0.1660,  0.7241],
        [ 1.4916,  0.9854, -0.7983,  0.3595],
        [-1.3402, -0.3410, -0.1998, -0.6995]])
第一行数据： tensor([ 0.2767, -0.6826, -0.3169,  1.3604])
第一列数据： tensor([ 0.2767, -0.2712,  1.4916, -1.3402])
最后一列: tensor([ 1.3604,  0.7241,  0.3595, -0.6995])


In [10]:
'''张量拼接
@function-torch.cat(inputs, dim) -> Tensor
@params-inputs: 待拼接的张量序列，可以是任意相同Tensor类型的序列(shape相同)
@params-dim: 选择的维度，不能超过待拼接的第一个序列的维度 
'''
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
tensor3 = torch.cat((tensor1, tensor2), dim=0)
print(tensor3)
tensor4 = torch.cat((tensor1, tensor2), dim=1)
print(tensor4)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
