In [2]:
'''
pytorch-张量
Tensor
'''
import torch

print(torch.__version__)

tsr_arr = torch.tensor([[1, 2], [3, 4]], dtype=torch.float64)
tsr_arr

2.5.1


tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [10]:
'''使用np.array生成, 会将 np定义的数据类型转换为torch的数据类型'''
import numpy as np

np_arr = np.array([[1, 2], [3, 4]], dtype=np.float64)
tsr_arr = torch.from_numpy(np_arr)
tsr_arr

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [11]:
'''使用现有张量作为模板，创建结构相同的新张量
@注意：当使用 rand_like()生成随机数张量时，如果模板是int类型时，要在使用时 需要指定数据类型
'''
tsr_arr2 = torch.ones_like(tsr_arr) # 以 tsr_arr为模板，创建元素全都是1的新张量(同样的还有zeros_like:创建全部为0的张量)
tsr_arr2    # 如果tsr_arr是float的，新的张量也是float
# tsr_arr3 = torch.rand_like(tsr_arr, dtype=torch.float64)
tsr_arr3 = torch.rand_like(tsr_arr)
tsr_arr3

tensor([[0.6775, 0.4067],
        [0.5247, 0.7241]], dtype=torch.float64)

In [ ]:
'''使用shape自定义张量'''
size = (3, 4)
tsr_rand = torch.rand(size=(2, 3, 4))
tsr_ones = torch.ones(size)
tsr_zero = torch.zeros(size)
print(f"Random Tensor: \n {tsr_rand}")
print(f"Ones Tensor: \n {tsr_ones}")
print(f"Zeros Tensor: \n {tsr_zero}")

Random Tensor: 
 tensor([[[0.9251, 0.5246, 0.3799, 0.4356],
         [0.3967, 0.4015, 0.1455, 0.9895],
         [0.4735, 0.1042, 0.9410, 0.5648]],

        [[0.3801, 0.0555, 0.9222, 0.0790],
         [0.2793, 0.5313, 0.7522, 0.7536],
         [0.4518, 0.5462, 0.9305, 0.7687]]])
Ones Tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), type: <built-in method type of Tensor object at 0x0000028D342DCEB0>
Zeros Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), type: <built-in method type of Tensor object at 0x0000028D342DCEB0>


In [18]:
'''张量属性'''

tsr_prope = torch.rand(3, 4)
print("Tensor'Shape:",tsr_prope.shape)  #obj.shape & obj.size()
print("Tensor'DataType:", tsr_prope.dtype)
print("Tensor'Stored Device:", tsr_prope.device)

Tensor'Shape: torch.Size([3, 4])
Tensor'DataType: torch.float32
Tensor'Stored Device: cpu


In [ ]:
'''GPU&CPU
@：检查一下本地服务器是否支持GPU加速
'''
print(f"torch 支持GPU加速吗：{torch.cuda.is_available()}")
# mac上
print(f"torch 支持GPU加速吗：{torch.backends.mps.is_available()}")

torch 支持GPU加速吗：False
torch 支持GPU加速吗：False
