In [2]:
'''张量运算
1. 对照np.array的点积
'''
import torch

tensor1 = torch.arange(1, 5).reshape(2, 2)
tensor2 = torch.arange(4, 8).reshape(2, 2)
print(tensor1 @ tensor2)
print(tensor1 * tensor2)

a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([6, 7, 8, 9, 0])
print(a, b)
print(a @ b)
c = torch.randint(0, 10, size=(5, 5))
print(a @ c)

'''
# 对于更高维度的点积运算，还有一些没搞明白
d = torch.randint(1, 8, (3, 2, 3, 4))
e = torch.randint(2, 9, (2, 3, 4, 7))
print(d @ e)
'''

tensor([[16, 19],
        [36, 43]])
tensor([[ 4, 10],
        [18, 28]])
tensor([1, 2, 3, 4, 5]) tensor([6, 7, 8, 9, 0])
tensor(80)
tensor([65, 90, 31, 46, 67])


'\n# 对于更高维度的点积运算，还有一些没搞明白\nd = torch.randint(1, 8, (3, 2, 3, 4))\ne = torch.randint(2, 9, (2, 3, 4, 7))\nprint(d @ e)\n'

In [3]:
'''求和运算'''
tensor3 = torch.ones(size=(3, 3))
agg = tensor3.sum() #返回的结果是用tensor包裹的元素之和
print(agg)
print(agg.item())   #实际应用中，可能需要用到求和后的python数据类型

tensor(9.)
9.0


In [4]:
'''function_()
torch定义了一种类型的方法：以_作为后缀，
表示该方法没有返回值，而是在张量本身进行修改
慎用！！！
'''
tensor4 = torch.ones(size=(3, 3))
np4 = tensor4.numpy()
tensor4.add_(3) #每个元素+3
print(np4, tensor4) # tenso4的变化，引起了 np4的变化

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]] tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])
