In [1]:
import numpy as np

In [ ]:

a1 = [9.22,-9.22]
# a1 = [1,2]
b1 = np.array(a1,dtype = float)
b1

array([ 9.22, -9.22])

In [64]:
print(b1, type(b1), type(b1[0]))

[ 9.22 -9.22] <class 'numpy.ndarray'> <class 'numpy.float64'>


In [75]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [116]:
# c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(c)
# print(c.shape)
# print(c.dtype)
print(c.sum())
print(sum(c))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
378
[[30 33 36]
 [39 42 45]
 [48 51 54]]


In [108]:
c2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
# c3 = c2
# print(c2)
# print(c2.shape)
print(c2*2)
print(c2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
c3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(sum(c3))

[12 15 18]


In [120]:
#创建特殊数组
n1 = np.zeros((2,2),dtype=int)
print(n1)
n2 = np.ones((3,3),dtype=float)
print(n2)

[[0 0]
 [0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [128]:
#创建等差数列
n3 = np.arange(1,5,1)
# print(n3)
n3

array([1, 2, 3, 4])

In [137]:
#创建单位矩阵
n4 = np.eye(3,dtype=int)
n4
print(n4.shape)
print(n4.size)

(3, 3)
9


In [158]:
#生成指定长度，在[0,1)之间平均分布的随机数组：
n5 = np.random.random(5)
n5

array([0.21113652, 0.22349857, 0.84087494, 0.18336266, 0.89622706])

In [167]:
#⽣成指定⻓度，符合正态分布的随机数组，指定其均值为 10，标准差为 2：
ave,sigma = 10, 2
n6 = np.random.normal(ave,sigma,5)
n6

array([13.11540856,  9.25264392,  8.02180736,  5.88599483,  7.80652141])

In [214]:
#Numpy数组的访问
nu = np.array([((1,2),(4,5),(6,7)),((8,9),(10,11),(12,13)),((14,15),(16,17),(18,19)),((20,21),(22,23),(24,25))])
nu[0]


array([[1, 2],
       [4, 5],
       [6, 7]])

In [215]:
# nu = np.array([((1,2),(4,5),(6,7)),((8,9),(10,11),(12,13)),((14,15),(16,17),(18,19)),((20,21),(22,23),(24,25))])
nu[:1]

array([[[1, 2],
        [4, 5],
        [6, 7]]])

In [216]:
# nu = np.array([((1,2),(4,5),(6,7)),((8,9),(10,11),(12,13)),((14,15),(16,17),(18,19)),((20,21),(22,23),(24,25))])
nu[1:]

array([[[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25]]])

In [224]:
# nu = np.array([((1,2),(4,5),(6,7)),((8,9),(10,11),(12,13)),((14,15),(16,17),(18,19)),((20,21),(22,23),(24,25))])
nu[:,:1]

array([[[ 1,  2]],

       [[ 8,  9]],

       [[14, 15]],

       [[20, 21]]])

In [259]:
a2 = np.array([(1,2),(3,4),(5,6)])
a2[:,:1]

array([[1],
       [3],
       [5]])

In [266]:
#Numpy数组的遍历
a3 = np.array([1,2,30])
for i in a3:
    print(i)

1
2
30


In [272]:
# NumPy 数组的常⽤属性
# nu = np.array([((1,2),(4,5),(6,7)),((8,9),(10,11),(12,13)),((14,15),(16,17),(18,19)),((20,21),(22,23),(24,25))])
print("ndarray.ndim : 数组的维度（数组轴的个数），等于秩 ")
print("ndim:",nu.ndim)
print()
print("ndarray.shape : 数组的⼤⼩。为⼀个表⽰数组在每个维度上⼤⼩的整数元组。例如⼆维数组中，表⽰数组的ʼ ⾏数ʼ 和ʼ 列数ˮ")
print("shape:",nu.shape)
print()
print("ndarray.size : 数组元素的总个数，等于 shape 属性中元组元素的乘积")
print("size:",nu.size)
print()
print("ndarray.dtype : 表⽰数组中元素类型的对象")
print("dtype",nu.dtype)

ndarray.ndim : 数组的维度（数组轴的个数），等于秩 
ndim: 3

ndarray.shape : 数组的⼤⼩。为⼀个表⽰数组在每个维度上⼤⼩的整数元组。例如⼆维数组中，表⽰数组的ʼ ⾏数ʼ 和ʼ 列数ˮ
shape: (4, 3, 2)

ndarray.size : 数组元素的总个数，等于 shape 属性中元组元素的乘积
size: 24

ndarray.dtype : 表⽰数组中元素类型的对象
dtype int32


In [296]:
nu3 = np.array([(1,2,3),(1,2,3)])
nu3

array([[1, 2, 3],
       [1, 2, 3]])

In [305]:
# in :检测数值是否在数组中
# nu3 = np.array([(1,2,3),(1,2,3)])
print(4 in nu3)

False


In [316]:
#reshape : 数组的重排列，例如将⼀个 3 维数组转变为 1 维（元素数⼀定要保持不变）
nu3.reshape(6)

array([1, 2, 3, 1, 2, 3])

In [320]:
# tanspose ：转置 (可以直接.T）
nu3.T

array([[1, 1],
       [2, 2],
       [3, 3]])

In [322]:
nu

array([[[ 1,  2],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25]]])

In [321]:
nu.T

array([[[ 1,  8, 14, 20],
        [ 4, 10, 16, 22],
        [ 6, 12, 18, 24]],

       [[ 2,  9, 15, 21],
        [ 5, 11, 17, 23],
        [ 7, 13, 19, 25]]])

In [327]:
q = np.array([(1,2,3),(4,5,6),(7,8,9)])
q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [328]:
q.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [329]:
q.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [345]:
# flatten : 把多维数组转换为⼀维数组，注意每个元组的⻓度是相同的
#q = np.array([(1,2,3),(4,5,6),(7,8,9)])
q1 = np.array([((1,2,3),(4,5,6),(7,8,9)),((1,2,3),(4,5,6),(7,8,9))])
q1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [401]:
#newaxis : 增加维度
q2 = np.array([1,2,3])
q2

array([1, 2, 3])

In [402]:
q2.shape

(3,)

In [403]:
q2 = q2[:,np.newaxis]
q2

array([[1],
       [2],
       [3]])

In [404]:
q2.shape

(3, 1)

In [410]:
#* 星乘表⽰矩阵内各对应位置相乘，点乘表⽰求矩阵内积，⼆维数组称为矩阵积（mastrix product）：
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print()
print(b)

[[1. 1.]
 [1. 1.]]

[[-1  1]
 [-1  1]]


In [411]:
a + b

array([[0., 2.],
       [0., 2.]])

In [412]:
a * b

array([[-1.,  1.],
       [-1.,  1.]])

In [413]:
a - b

array([[2., 0.],
       [2., 0.]])

In [416]:
a / b

array([[-1.,  1.],
       [-1.,  1.]])

In [ ]:
w = np.array([1,2,3,4])
w.sum()

24

In [419]:
w.prod()

24

In [426]:
# 平均数，⽅差，标准差，最⼤值，最⼩值
a = np.array([5,3,1])
print("平均数","mean:",a.mean())
print("方差","var",a.var())
print("标准差","std",a.std())
print("最大值","max",a.max())
print("最小值","min",a.min())

平均数 mean: 3.0
方差 var 2.6666666666666665
标准差 std 1.632993161855452
最大值 max 5
最小值 min 1


In [434]:
#最⼤与最⼩值对应的索引值：argmax,argmin:
# 取元素值上限，下限，四舍五⼊：ceil, floor, rint
a = np.array([1.2,3.4,5.6])
print("最大值索引","argmax",np.argmax(a))
print("最小值索引","argmin",np.argmin(a))
print("元素取上限","ceil",np.ceil(a))
print("元素取下限","floor",np.floor(a))
print("元素四舍五入","rint",np.rint(a))

最大值索引 argmax 2
最小值索引 argmin 0
元素取上限 ceil [2. 4. 6.]
元素取下限 floor [1. 3. 5.]
元素四舍五入 rint [1. 3. 6.]


In [458]:
# 排序
a = np.array([(10,9,8),(25,3,4)])
a.sort()
print(a)

[[ 8  9 10]
 [ 3  4 25]]


In [6]:
a = np.array([(1,9,8),(25,3,4)])
a.sort()
# print(a)
# np.flip(a)
# reversed_arr = a[::-1,:]    # 在第0轴上倒序
# print(reversed_arr)

reversed_arr = a[:,::-1]    # 在第1轴上倒序
print(reversed_arr)

[[ 9  8  1]
 [25  4  3]]


In [24]:
n = np.array([1,2,3,4,-121,45])
np.tan(n)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, 20.52488998,
        1.61977519])

In [28]:
#两个一维数组，计算的是两个数组对应下标元素的乘积和（数学上称之为内积）
#对于二位数组计算的是两个数组的矩阵乘积

#定义两个简单的矩阵
#一维数组
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])
# result_dot = np.dot(m1,m2)
result_dot = m1 @ m2
result_dot

32

In [43]:
#二位数组
m3 = np.array([(1,2),(3,4)])
m4 = np.array([(5,6),(7,8)])
result_dot2 = np.dot(m3,m4)
print(m3)
print()
print(m4)
print()
print(result_dot2)
print()
result_at = m3 @ m4
print(result_at)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [59]:
m5 = np.array([(1,2),(3,4)])
m6 = np.array([((5,6),(7,8))])
print(m5)
print()
print(m6)
print()
result_dot3 = np.dot(m5,m6)
print("result_dot:")
print(result_dot3)
result_at3 = m5 @ m6
print("result_at:")
print(result_at3)

[[1 2]
 [3 4]]

[[[5 6]
  [7 8]]]

result_dot:
[[[19 22]]

 [[43 50]]]
result_at:
[[[19 22]
  [43 50]]]


In [65]:
m1 = np.array([(1,2),(3,4)],dtype=np.float32)
m2 = np.array([(5,6),(7,8)])
#创建一个全零矩阵,用存储手动推演结果
#结果矩阵的行数等于matrix1的行数，列数等于matrix2的列数
manual_result = np.zeros((m1.shape[0],m2.shape[1]),dtype=np.float32)

#外层循环：遍历matrix1的每一行
#i表示结果矩阵的索引
for i in range(m1.shape[0]):
    #中层循环：遍历matrix2的每一列
    #j表示结果矩阵的索引
    for j in range(m2.shape[1]):
        #初始化当前位置的结果位0
        manual_result[i,j] = 0
        #内层循环：计算matrix1的第i行与matrix2的第j列对应元素的乘积之和
        #k表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            #打印当前正在计算的元素
            print(f"{m1[i,j]} * {m2[k,j]} = {m1[i,j]} * {m2[k,j]}")
            #将matrix1的第i行第k列元素与matrix2的第k行第j列元素相乘，并累加
            manual_result[i,j] += m1[i,k] * m2[k,j]
        #打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i,j]}\n")
print("手动推演结果")
print(manual_result)


1.0 * 5 = 1.0 * 5
1.0 * 7 = 1.0 * 7
结果矩阵[1,1]:19.0

2.0 * 6 = 2.0 * 6
2.0 * 8 = 2.0 * 8
结果矩阵[1,2]:22.0

3.0 * 5 = 3.0 * 5
3.0 * 7 = 3.0 * 7
结果矩阵[2,1]:43.0

4.0 * 6 = 4.0 * 6
4.0 * 8 = 4.0 * 8
结果矩阵[2,2]:50.0

手动推演结果
[[19. 22.]
 [43. 50.]]


In [11]:
data = np.array([1,2,3])
np.save("data.npy",data)

In [12]:
file = np.load("data.npy")
file

array([1, 2, 3])

In [13]:
test = np.array([(1,2,3),(4,5,6)])
np.savetxt("test.txt",test)

In [14]:
test_file = np.loadtxt("test.txt")
test_file

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
#广播机制
a = np.array([(1,2),(2,2),(3,3),(4,4)])
b = np.array([5,6])
a + b

array([[ 6,  8],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]])