In [6]:
import torch
import numpy as np


In [4]:
#张量

#从Numpy数组中创建
a = np.array([(1,2,3),(4,5,6)])
x_np = torch.from_numpy(a)
x_np

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [20]:
#直接从数据中创建
data = [[10,20,30],[40,50,60]]
# data = [[10,20,30]]
x_data = torch.tensor(data)
print(x_data)

tensor([[10, 20, 30],
        [40, 50, 60]])


In [21]:
#从另一张量中创建
x_ones= torch.ones_like(x_np)
print(f"Ones Tensor:\n{x_ones}\n",x_ones.dtype)

Ones Tensor:
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
 torch.int32


In [22]:
#从另一张量中创建
x_rand = torch.rand_like(x_data,dtype=torch.float)      #覆盖原有x_data的数据类型
x_rand

tensor([[0.0181, 0.0667, 0.5319],
        [0.9455, 0.1500, 0.0742]])

In [23]:
print("x_ones.shape:",x_ones.shape)
print("x_data.shape:",x_data.shape)
print("x_rand.shape:",x_rand.shape)

x_ones.shape: torch.Size([2, 3])
x_data.shape: torch.Size([2, 3])
x_rand.shape: torch.Size([2, 3])


In [28]:
# 使⽤随机值或常量值：
#shape 是张量维度的元组。在下⾯的函数中，它决定了输出张量的维度。
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor\n{ones_tensor}\n")
print(f"Zeros Tensor\n{zeros_tensor}\n")

Random Tensor:
tensor([[0.8533, 0.1975, 0.8439],
        [0.6573, 0.0848, 0.9115]])

Ones Tensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [48]:
#其他一些创建方法
#基于现有tensor构建，但使用新值填充
m = torch.ones(5,3,dtype=torch.double)
n = torch.rand_like(m,dtype=torch.float)

#获取tensor的大小
print(m.size())
n

torch.Size([5, 3])


tensor([[0.5596, 0.7206, 0.2840],
        [0.7208, 0.2587, 0.1193],
        [0.6035, 0.1569, 0.5012],
        [0.5108, 0.9487, 0.3274],
        [0.7491, 0.1271, 0.8043]])

In [58]:
#均匀分布
torch.rand(5,3)

tensor([[0.0724, 0.5631, 0.6668],
        [0.4579, 0.4147, 0.8994],
        [0.7902, 0.8423, 0.9427],
        [0.2016, 0.2564, 0.8735],
        [0.6420, 0.3355, 0.8014]])

In [68]:
#标准正态分布
torch.randn(5,3)


tensor([[ 2.4674, -0.9658, -0.5749],
        [-0.8805,  0.2326,  3.1471],
        [-0.1655, -1.3269,  0.5015],
        [-2.0211,  1.3892, -0.8160],
        [ 0.2059, -0.4951,  1.3306]])

In [118]:
#离散正态分布
torch.normal(mean=.0,std=1.0,size=(5,3))

tensor([[-0.5155,  1.2276,  2.2863],
        [-0.7181, -1.1068,  0.2950],
        [ 0.0577, -0.4889,  0.1441],
        [ 0.5195, -0.4705, -0.0938],
        [ 0.5296,  0.3952, -0.9055]])

In [9]:
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
torch.linspace(start=0.5,end=10,steps=20)

tensor([ 0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,
         4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,
         8.5000,  9.0000,  9.5000, 10.0000])

In [13]:
#张量的属性
tensor = torch.rand(5,6)
print(f"Shaoe of tensor:\t{tensor.shape}")
print(f"Datatype of tensor:\t{tensor.dtype}")
print(f"Device of tensor:\t{tensor.device}")
print(tensor)

Shaoe of tensor:	torch.Size([5, 6])
Datatype of tensor:	torch.float32
Device of tensor:	cpu
tensor([[0.8761, 0.5700, 0.7347, 0.9524, 0.8829, 0.0802],
        [0.6776, 0.2437, 0.8173, 0.7736, 0.3970, 0.7755],
        [0.6735, 0.7870, 0.0069, 0.8403, 0.1179, 0.7385],
        [0.2520, 0.9926, 0.0391, 0.1035, 0.7234, 0.7513],
        [0.0259, 0.4594, 0.7978, 0.2533, 0.7868, 0.4389]])


In [14]:
#张量的运算
#默认情况张量在CPU上运算
#判断是否支持在GPU上运算
torch.cuda.is_available()

False

In [8]:
tensor = torch.randn(5,5)
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[-0.5370, -0.9013, -1.6874, -1.2567, -0.3504],
        [-2.1047,  0.3546,  0.3100, -1.1826, -0.0795],
        [-1.9480, -0.9064, -0.5035, -0.9696,  0.0187],
        [ 1.9089, -1.7725,  0.7393, -0.8591, -1.7596],
        [ 0.5382,  1.9071,  0.7776, -0.3306,  0.5056]])
cpu
tensor([[-0.5370, -0.9013, -1.6874, -1.2567, -0.3504],
        [-2.1047,  0.3546,  0.3100, -1.1826, -0.0795],
        [-1.9480, -0.9064, -0.5035, -0.9696,  0.0187],
        [ 1.9089, -1.7725,  0.7393, -0.8591, -1.7596],
        [ 0.5382,  1.9071,  0.7776, -0.3306,  0.5056]])
cpu


In [36]:
#张量的索引和切片
nd = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])
tensor = torch.from_numpy(nd)
print(f"First row:\t{tensor[0]}")
print(f"First Column:\t{tensor[:,0]}")
print(f"Last Column:\t{tensor[:,-1]}")
print(f"Last Column:\t{tensor[...,-1]}")    #通用写法
print(tensor)
tensor[:1] = 0
print(tensor)
tensor[:,1] = 2
print(tensor)

First row:	tensor([1, 2, 3, 4], dtype=torch.int32)
First Column:	tensor([ 1,  5,  9, 13], dtype=torch.int32)
Last Column:	tensor([ 4,  8, 12, 16], dtype=torch.int32)
Last Column:	tensor([ 4,  8, 12, 16], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)
tensor([[ 0,  0,  0,  0],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)
tensor([[ 0,  2,  0,  0],
        [ 5,  2,  7,  8],
        [ 9,  2, 11, 12],
        [13,  2, 15, 16]], dtype=torch.int32)


In [41]:
#张量的拼接
t1 = torch.from_numpy(np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)]))
t2 = torch.from_numpy(np.array([(10,20,30),(40,50,60),(70,80,90),(100,110,120)]))
t3 = torch.cat([t1,t2,t1,t2],dim = 1)
t3

tensor([[  1,   2,   3,  10,  20,  30,   1,   2,   3,  10,  20,  30],
        [  4,   5,   6,  40,  50,  60,   4,   5,   6,  40,  50,  60],
        [  7,   8,   9,  70,  80,  90,   7,   8,   9,  70,  80,  90],
        [ 10,  11,  12, 100, 110, 120,  10,  11,  12, 100, 110, 120]],
       dtype=torch.int32)

In [46]:
t1 = torch.from_numpy(np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)]))
t2 = torch.from_numpy(np.array([(10,20,30),(40,50,60),(70,80,90),(100,110,120)]))
t3 = torch.cat([t1,t2,t1,t2],dim = 0)
t3

tensor([[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [ 10,  11,  12],
        [ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120],
        [  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [ 10,  11,  12],
        [ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]], dtype=torch.int32)

In [4]:
#算数运算
#计算两个张量之间矩阵乘法
y1 = torch.from_numpy(np.array([(1,2),(3,4)]))
y2 = torch.from_numpy(np.array([(5,6),(7,8)]))
print(y1)
print(y2)
print()
print(y2.T)
print()
result1 = y1 @ y2.T     #.的优先级高于@
print(result1)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[5, 6],
        [7, 8]], dtype=torch.int32)

tensor([[5, 7],
        [6, 8]], dtype=torch.int32)

tensor([[17, 23],
        [39, 53]], dtype=torch.int32)


In [98]:
tensor = torch.arange(1,17,dtype=torch.float32).reshape(4,4)
print(tensor)
print()
print(tensor.T)
print()
# #计算两个张量之间矩阵乘法的几种方式，y1、y2、y3最后的值是一样的dot
# y1 = tensor @ tensor.T
# y2 = tensor.matmul(tensor.T)      #matmul和numpy中的dot是一样的
# y3 = torch.rand_like(tensor)
# torch.matmul(tensor,tensor.T,out=y3)    #out=yy3覆盖y3原先的值

# print("tensor @ tensor.T:")
# print(y1)
# print("tensor.matmul(tensor.T):")
# print(y2) 
# print("torch.matmul(tensor,tensor.T,out=y3):")
# print(y3)

#计算张量元素相乘的几种方法。z1、z2、z3最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)     #out=z3覆盖z3原先的值

#每一位乘以4
z4 = torch.rand_like(tensor)
torch.mul(tensor,4,out=z4)

print("tensor * tensor:")
print(z1)
print("tensor.mul(tensor):")
print(z2)
print("torch.mul(tensor,tensor,out=z3):")
print(z3)
print("torch.mul(tensor,3,out=z4):")
print(z4)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

tensor([[ 1.,  5.,  9., 13.],
        [ 2.,  6., 10., 14.],
        [ 3.,  7., 11., 15.],
        [ 4.,  8., 12., 16.]])

tensor * tensor:
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])
tensor.mul(tensor):
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])
torch.mul(tensor,tensor,out=z3):
tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.],
        [169., 196., 225., 256.]])
torch.mul(tensor,3,out=z4):
tensor([[ 4.,  8., 12., 16.],
        [20., 24., 28., 32.],
        [36., 40., 44., 48.],
        [52., 56., 60., 64.]])


In [99]:
#单元素张量
#如果一个单元素张量，例如张量的值聚合计算，可以使用item()方法将其转换为Python数值
print(tensor)
agg = tensor.sum()
agg_item = agg.item()   #返回python的中原生的基本类型
print(agg)
print(agg_item,type(agg_item))

#对于更高纬的数据不能用Python的类型来接收，可以将它转换为Numpy的ndarray数组再来进行本地化的操作或运算
np_arr = tensor.numpy()
np_arr

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor(136.)
136.0 <class 'float'>


array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]], dtype=float32)

In [100]:
# In-place操作      谨慎使用！！！
#把计结果存储到当前操作数中的操作就称为就地操作。含义和pandas中的inPlace参数的含义一样。pytorch中，这些操作是由带有下划线_后缀的函数表示。
#例如：x.copy_(y),x.t_(),将改变x自身的值。
print(tensor,"\n")
tensor.add_(10)     #没有返回的结果值，将计算的结果直接更新到张量，张量内部的值直接就被更新了
# 和tensor = tensor + 5或tensor += 5效果相同，In-place操作会节省一部分内存空间，效率更高，但在计算导数时可能会出现问题，因为他会立即丢失历史记录。因此，不鼓励使用他们。

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]) 



In [107]:
#与numpy之间的转换
#张量到numpy数组
t = torch.ones(5,5)
print(t)
n = t.numpy()
n

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [113]:
#张量值的变更也反应在关联的Numpy数组中
# t.add_(3)
print(t)
n

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]], dtype=float32)

In [126]:
#numpy数组到张量
n1 = np.eye(4)
t1 = torch.from_numpy(n1)
t1

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]], dtype=torch.float64)

In [127]:
#numpy数组的变化也反应在张量中
np.add(n1,1,out=n1)
print(f"t1:{t1}")
print(f"n1:{n1}")

t1:tensor([[2., 1., 1., 1.],
        [1., 2., 1., 1.],
        [1., 1., 2., 1.],
        [1., 1., 1., 2.]], dtype=torch.float64)
n1:[[2. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 2. 1.]
 [1. 1. 1. 2.]]


In [ ]:
#计算图
import torch
from torchviz import make_dot

#定义矩阵A,向量b和常数c
A = torch.randn(5,5,requires_grad=True)     #requires_grad=True表示对A求导
b = torch.randn(5,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(5,requires_grad=True)

#计算x^T * A + b * x +c
result = torch.matmul(A, x.T) + torch.matmul(b,x) + c
#生成计算图节点
dot = make_dot(result,params={"A":A,"b":b,"c":c,"x":x})
#绘制计算图
dot.render("expression",format="png",cleanup=True,view=False)


'expression.png'