In [2]:
import numpy as np
# 1、numpy数组: Ndarray
# 1.1、基础数组创建
a1 = [1 ,2 ,3, 4]
b1 = np.array(a1)
b1

array([1, 2, 3, 4])

In [8]:
b2 = np.array(a1, float)
b2
b3 = np.array([1, 3, 4])
b3

array([1, 3, 4])

In [10]:
b4 = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(b4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# 1.2、特殊数组创建
b5 = np.zeros((2,4), dtype=float)
print(b5)
b6 = np.zeros((3,3))
print(b6)
print(b6.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [17]:
b7 = np.ones((3,3))
print(b7)
b8 = np.ones((3,4,5))
print(b8)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [21]:
b9 = np.arange(1, 7, 0.2)
print(b9)
print(b9.dtype)
b10 = np.arange(1, 7, 1)
print(b10)
print(b10.dtype)
b11 = np.arange(1, 7, -1)
print(b11)
print(b11.dtype)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8]
float64
[1 2 3 4 5 6]
int64
[]
int64


In [24]:
b12 = np.eye(2)
print(b12)
b13 = np.eye(3)
print(b13)
b14 = np.eye(6)
print(b14)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [28]:
b15 = np.random.random(7)
print(b15)
# ⽣成指定⻓度，符合正态分布的随机数组，指定其均值为 0，标准差为 0.1
b16 = np.random.normal(0, 0.1, 7)
print(b16)
b17 = np.random.normal(10, 2, 7)
print(b17)

[0.53434827 0.47005096 0.24632449 0.75564545 0.88290284 0.81010416
 0.76732191]
[-0.01034373  0.04421758  0.01502351 -0.02592748  0.23805934  0.09061323
  0.16693391]
[ 8.2767358   9.42386307 10.02974344 13.58000322 10.16374639 11.25147729
 10.30361126]


In [33]:
# 1.3、数组访问
b18 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b18[0])
print(b18[0][1])
print(b18[1:])
print(b18[1:, :1])
print(b18[1:, 1:])

[1 2 3]
2
[[4 5 6]
 [7 8 9]]
[[4]
 [7]]
[[5 6]
 [8 9]]


In [37]:
# 1.4、数据遍历
b19 = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i,j,k in b19:
    print(i,"-",j,"-",k)

1 - 2 - 3
4 - 5 - 6
7 - 8 - 9


In [39]:
# 1.5、数组常用属性
b20 = np.ones((2,4,5))
print(b20)
print("数组的维度（数组轴的个数），等于秩：", b20.ndim)
print("数组的⼤⼩：", b20.shape)
print("数组元素的总个数，等于 shape 属性中元组元素的乘积：", b20.size)
print("元素类型：", b20.dtype)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
数组的维度（数组轴的个数），等于秩： 3
数组的⼤⼩： (2, 4, 5)
数组元素的总个数，等于 shape 属性中元组元素的乘积： 40
元素类型： float64


In [59]:
# 1.6、数组的基本操作
b21 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b21)
print(1 in b21)
# print((1,2) in b21) # 报错：operands could not be broadcast together with shapes (3,3) (2,)
print((11,22,3) in b21)
print((11,22,33) in b21)
print([1,2,3] in b21)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
True
True
False
True


In [ ]:
b22 = np.ones((3,4,5))
print(b22)
# 元素数需保持一致
b23 = b22.reshape(3,20)
print("b23=", b23)
b24 = b22.reshape(5, 4, 3)
print("b24=", b24)
b25 = b22.reshape(3*4*5)
print("b25=", b25)


In [66]:
b26 = np.ones((2,3))
print(b26)
b26.transpose()
print(b26)
b27 = b26.transpose()
print(b27)
b28 = np.ones((2,3,4))
print("b28=", b28)
print(b28.shape)
b29 = b28.T
print("b28.T=", b29)
print(b29.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
b28= [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)
b28.T= [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(4, 3, 2)


In [68]:
b30 = np.ones((3,4))
print(b30)
b30.flatten()
print(b30)
b31 = b30.flatten()
print(b31)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# 增加维度
b32 = np.ones((2,3))
print(b32)
print(b32.shape)
b33 = b32[:,np.newaxis]
print(b33)
print(b33.shape)
b34 = b32[:,:,np.newaxis]
print(b34)
print(b34.shape)
b35 = b32[np.newaxis]
print(b35)
print(b35.shape)
print(b35[0][1][2])

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
[[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
(2, 3, 1)
[[[1. 1. 1.]
  [1. 1. 1.]]]
(1, 2, 3)
1.0


In [85]:
# 1.7、数组的数学操作
b36 = np.array([(1,2),(3,4)])
b37 = np.array([(-1,1),(-1,1)])
print(b36)
print(b37)
print(b36 + b37)
print(b36 - b37)
print(b36 * b37)
print(b36 / b37)
print()
b38 = np.array([(1,2,5),(3,4,7)])
b39 = np.array([(-1,1),(-1,1)])
print(b38)
print(b39)
# print(b38 + b39) # 报错：operands could not be broadcast together with shapes (2,3) (2,2)
print("元素求和", b38.sum())
print("元素求积", b38.prod())

[[1 2]
 [3 4]]
[[-1  1]
 [-1  1]]
[[0 3]
 [2 5]]
[[2 1]
 [4 3]]
[[-1  2]
 [-3  4]]
[[-1.  2.]
 [-3.  4.]]

[[1 2 5]
 [3 4 7]]
[[-1  1]
 [-1  1]]
元素求和 22
元素求积 840


In [93]:
b40 = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])
print(b40)
print("平均数：", b40.mean())
print("方差：", b40.var())
print("标准差：", b40.std())
print("最大值：", b40.max())
print("最小值：", b40.min())
print("最大值索引：", b40.argmax())
print("最小值索引：", b40.argmin())
b41 = np.ceil(b40)
print("元素值上限", b41)
b42 = np.floor(b40)
print("元素值下限", b42)
b43 = np.rint(b40)
print("元素值四舍五入", b43)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
平均数： 3.85
方差： 3.5291666666666663
标准差： 1.8786076404259262
最大值： 6.6
最小值： 1.1
最大值索引： 5
最小值索引： 0
元素值上限 [[2. 3. 4.]
 [5. 6. 7.]]
元素值下限 [[1. 2. 3.]
 [4. 5. 6.]]
元素值四舍五入 [[1. 2. 3.]
 [4. 6. 7.]]


In [97]:
b44 = np.array([[7.2, 3.3, 1.1], [6.6, 4.4, 5.5]])
print(b44)
b44.sort()
print(b44) # 原数组发生变化
b44.sort(axis=0)
print(b44)

[[7.2 3.3 1.1]
 [6.6 4.4 5.5]]
[[1.1 3.3 7.2]
 [4.4 5.5 6.6]]
[[1.1 3.3 6.6]
 [4.4 5.5 7.2]]


In [ ]:
# 1.8、线性代数：numpy.linalg
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
r1 = np.dot(m1, m2)
r2 = m1 @ m2
print(r1)
print(r2)
print("点乘：数组 a 的最后⼀维上的所有元素与数组 b 的倒数第⼆位上的所有元素的乘积和")
m1 = np.array([[1, 2, 5], [3, 4, 5]])
m2 = np.array([[5, 6], [7, 8], [9, 10]])
print(m1.shape)
print(m2.shape)
r1 = np.dot(m1, m2)
r2 = m1 @ m2
print(r1)
print(r2)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
点乘：数组 a 的最后⼀维上的所有元素与数组 b 的倒数第⼆位上的所有元素的乘积和
(2, 3)
(3, 2)
[[ 64  72]
 [ 88 100]]
[[ 64  72]
 [ 88 100]]


In [106]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8], [9, 10]])
# 特征值
r1 = np.linalg.eig(m1)
print(r1)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [5]:
# 2、文件操作
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
r = m @ m
print(r)
np.save('test.npy', r)
r1 = np.load('test.npy')
print(r1)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
# 3、Numpy数组的广播机制
m1 = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
m2 = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
r = m1 + m2
print(r)
m1 = np.array([(1,2,3), (2,2,3)])  # shape(2,3)
m2 = np.array([-1,-1,-1])  # shape(3)-> shape(1,3) -> shape(2,3)  [[-1,-1,-1],[-1,-1,-1]]
print(m1.shape)
print(m2.shape)
r = m1 + m2
print(r)

[[0 3]
 [1 3]
 [2 4]
 [3 5]]
(2, 3)
(3,)
[[0 1 2]
 [1 1 2]]
