In [2]:
import torch
import numpy as np
# 1、张量创建
a1 = [[1,2], [3,4]]
a2 = torch.tensor(a1)
print(a1)
print(a2)
a3 = np.array(a1)
a4 = torch.from_numpy(a3)
print(a3)
print(a4)
a5 = torch.tensor(a3)
print(a5)


[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [10]:
a6 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
a7 = torch.ones_like(a6)
print(a6)
print(a7)
a8 = torch.zeros_like(a6)
a9 = torch.rand_like(a6) # 如果a6中不指定元素类型dtype=torch.float32，会提示异常："check_uniform_bounds" not implemented for 'Long'
print(a8)
print(a9)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8376, 0.2956, 0.5259],
        [0.3100, 0.8980, 0.1396],
        [0.5937, 0.5577, 0.1904]])


In [11]:
# 使⽤随机值或常量值创建张量
shape1 = (3, 3)
a10 = torch.rand(shape1)
a11 = torch.ones(shape1)
a12 = torch.zeros(shape1)
print(a10)
print(a11)
print(a12)

tensor([[0.5363, 0.8547, 0.6221],
        [0.4980, 0.8079, 0.9235],
        [0.6420, 0.0363, 0.9245]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [16]:
# 其他创建方法
a13 = torch.rand(5,3) # 均匀分布
a14 = torch.rand((5,3))
print(a13)
print(a14)
a15 = torch.randn(5,3) # 标准正态分布
a16 = torch.randn((5,3))
print(a15)
print(a16)
a17 = torch.normal(mean=0, std=1, size=(5,3))
print(a17)
a18 = torch.linspace(0, 10, steps=22) # 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(a18)

tensor([[0.3423, 0.8027, 0.6159],
        [0.1695, 0.2874, 0.0209],
        [0.4353, 0.8694, 0.3767],
        [0.3369, 0.2818, 0.1074],
        [0.5890, 0.6797, 0.4615]])
tensor([[0.3611, 0.7151, 0.1436],
        [0.8452, 0.9552, 0.0947],
        [0.8486, 0.7029, 0.6817],
        [0.4086, 0.3377, 0.3649],
        [0.0487, 0.2333, 0.6606]])
tensor([[-2.1703,  0.4440, -1.5605],
        [ 1.1872, -0.2284,  0.0931],
        [ 0.5562, -1.2871,  0.0130],
        [ 0.1680, -0.9407, -0.1366],
        [ 0.6455, -1.8513, -1.1154]])
tensor([[-0.7406,  0.9654,  0.8645],
        [-0.2863,  0.2678,  2.1574],
        [-0.3779,  0.8856, -1.7784],
        [ 0.1886,  0.0744,  1.5943],
        [-1.6880,  0.9600,  0.5375]])
tensor([[-0.5836, -1.0123, -0.7555],
        [-1.7100,  1.5276, -0.5966],
        [ 0.6149,  0.1347,  0.7784],
        [-0.2301, -0.7709,  1.5764],
        [-1.4163, -0.5135,  0.1054]])
tensor([ 0.0000,  0.4762,  0.9524,  1.4286,  1.9048,  2.3810,  2.8571,  3.3333,
         3.8095,  4.

In [19]:
# 2、张量的属性
a19 = torch.ones((3,4,5))
print(a19)
print("维度：", a19.shape)
print("维度：", a19.size())
print("元素类型：", a19.dtype)
print("存储位置：", a19.device)
print(torch.cuda.is_available())

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
维度： torch.Size([3, 4, 5])
维度： torch.Size([3, 4, 5])
元素类型： torch.float32
存储位置： cpu
False


In [ ]:
# 3、张量拼接，dim 参数指定了沿着哪个维度进行拼接
a20 = torch.ones(2, 3)
print(a20)
print(a20.shape)
a21 = torch.cat([a20, a20], dim=0)
print(a21)
print(a21.shape)
a22 = torch.cat([a20, a20], dim=1)
print(a22)
print(a22.shape)
a23 = torch.cat([a20, a20, a20], dim=0)
print(a23)
print(a23.shape)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([4, 3])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.Size([2, 6])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([6, 3])


In [23]:
a20 = torch.ones(2, 3, 4)
print(a20)
print(a20.shape)
a21 = torch.cat([a20, a20], dim=0)
print(a21)
print(a21.shape)
a22 = torch.cat([a20, a20], dim=1)
print(a22)
print(a22.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([4, 3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 6, 4])


In [32]:
# 4、张量算数运算
# 点乘
a23 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
print(a23)
a24 = torch.ones(3,3)
print(a24)
r1 = a23 @ a24
r2 = a23.matmul(a24)
r3 = torch.matmul(a23, a24)
r4 = torch.ones(3,3)
torch.matmul(a23, a24, out=r4)
print(r1)
print(r2)
print(r3)
print(r4)
print(a23.T)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 6.,  6.,  6.],
        [15., 15., 15.],
        [24., 24., 24.]])
tensor([[ 6.,  6.,  6.],
        [15., 15., 15.],
        [24., 24., 24.]])
tensor([[ 6.,  6.,  6.],
        [15., 15., 15.],
        [24., 24., 24.]])
tensor([[ 6.,  6.,  6.],
        [15., 15., 15.],
        [24., 24., 24.]])
tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])


In [30]:
# 叉乘
a23 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
print(a23)
a24 = torch.eye(3,3)
print(a24)
r1 = a23 * a24
r2 = a23.mul(a24)
r3 = torch.mul(a23, a24)
print(r1)
print(r2)
print(r3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])
tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])
tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])


In [33]:
# 转换为python数值
a25 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
s = a25.sum()
i = s.item()
print(s, type(s))
print(i, type(i))

tensor(45.) <class 'torch.Tensor'>
45.0 <class 'float'>


In [34]:
# in-place操作
a26 = torch.ones(3,3)
print(a26)
a26.add(3)
print(a26)
a26.add_(3)
print(a26) # in-place操作，直接在原对象上修改

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [ ]:
# 5、计算图，先安装torchviz：pip install torchviz
from torchviz import make_dot
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
print(A)
print(b)
print(c)
print(x)

result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
print(result)
# ⽣成计算图节点
dot = make_dot(result, params={'数据A': A, '数据b': b, '数据c': c, 'x': x})
# 绘制计算图
# 报错：ExecutableNotFound: failed to execute WindowsPath('dot')。解决：conda install graphviz
dot.render('expression', format='png', cleanup=True, view=False)

tensor([[-1.3643,  0.6178, -0.2687, -1.0982,  0.7881,  1.3200, -0.7000, -1.2041,
          0.0354, -1.8176],
        [ 1.5282, -1.3045, -0.9800, -3.0414, -1.0705,  1.2879, -1.4402,  0.2408,
          0.5597, -0.4214],
        [ 1.4928, -0.0136,  0.1205,  0.3898, -1.2655,  0.8170, -1.7315, -1.8967,
         -1.2994, -0.1273],
        [ 2.3637,  1.4442, -1.0803,  0.2539,  1.0767,  0.3993, -0.2864,  1.0144,
          0.7471,  0.1619],
        [ 0.9635,  2.1311,  0.0893,  1.4448,  0.6213,  0.1077,  0.7644,  0.3736,
         -0.4169,  0.1178],
        [-1.2069, -0.0853,  0.0492,  0.0757, -1.3383, -1.4889, -2.6017, -1.4635,
         -1.0001,  0.9490],
        [-0.0874, -1.4874,  0.3384, -0.0111, -0.6986, -0.2471,  1.1679, -1.7987,
          1.3660,  0.2930],
        [-0.5454, -0.1600, -0.1981, -1.4923,  2.0955, -2.0320, -2.5412,  1.0250,
          0.2086, -0.6704],
        [ 0.1630,  0.1002,  1.4615,  0.9642, -1.8208,  0.5563,  0.3433,  0.7701,
         -1.1473, -1.1008],
        [-0.3824, -

'expression.png'