In [14]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [3]:
result = make_classification()
result

(array([[-2.08789674e-01,  7.72840290e-01,  6.43597464e-01, ...,
         -3.67977801e-01, -1.18565462e+00, -6.88296093e-01],
        [ 4.33327160e-01,  8.78734885e-01, -6.32676233e-01, ...,
         -1.41514759e+00,  5.77140067e-01, -2.99128342e-01],
        [-1.92194268e-01, -3.87143482e-01, -1.55763274e+00, ...,
          1.28278285e-01, -1.05865072e+00,  7.00951970e-01],
        ...,
        [-1.08862660e+00,  4.51765399e-01, -4.06120684e-01, ...,
         -8.86560989e-01,  2.53306133e-01,  4.39582680e-01],
        [-3.09101965e-04,  5.69993006e-01,  9.53164395e-02, ...,
         -1.03818709e-02,  8.44991588e-01,  1.49227088e+00],
        [ 5.39402713e-01, -1.38915975e-01,  3.87870555e-02, ...,
          2.34091795e-01, -2.51231704e-02,  6.84240566e-01]]),
 array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       

In [5]:
x,y = make_classification()
print (x)
print (y)
print (x.shape)
print (y.shape)

[[ 0.75319068  1.36933065  1.3477372  ... -0.38685853 -0.09373776
  -1.55400581]
 [ 0.33931386  0.16587132 -1.98069876 ... -1.08211266 -0.56530259
  -0.48703529]
 [-0.3564442  -2.23817714  0.80937502 ...  1.4200677  -0.9267845
   0.59001968]
 ...
 [ 0.03044534 -0.48727203 -0.70366553 ... -0.19689172  1.95378211
  -0.31772788]
 [ 0.49882697 -0.50643587 -0.68781201 ... -0.32827763  0.08817942
  -2.25666737]
 [ 1.0758991   1.41612801 -1.01951141 ... -0.62563058  0.07515954
   0.40680242]]
[1 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 0 1
 0 1 1 0 1 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 1
 1 1 0 1 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0]
(100, 20)
(100,)


In [6]:
x[0]

array([ 0.75319068,  1.36933065,  1.3477372 , -1.29997182,  1.17240697,
       -1.69659363,  0.32548646,  0.89545602, -0.00857879,  0.35158154,
        1.06320113,  2.30197906,  0.60103636, -0.9662018 , -0.40559159,
       -0.15734401,  1.32592765, -0.38685853, -0.09373776, -1.55400581])

In [7]:
y[0]

1

In [9]:
x,y = make_classification(n_samples=150)
print (x)
print (y)
print (x.shape)
print (y.shape)

[[-1.34813864  0.5469736  -0.23973207 ... -0.73665865  2.34947035
   0.19256291]
 [ 1.88494564  0.94549233  0.04730195 ...  1.8690573  -1.56512016
   0.95048909]
 [ 0.35561322 -0.32121167 -0.36854164 ... -1.56269179  0.34702842
  -1.41120588]
 ...
 [ 0.45984639 -0.18641963  0.52569552 ... -0.16361818  0.44168925
   1.69897653]
 [-1.04282538 -0.6175952   0.80595678 ...  0.49519244  0.74636201
   0.2420045 ]
 [ 1.11489282 -0.43287294  0.11849391 ...  1.9358528  -1.18788222
  -0.86599473]]
[0 1 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 1 1 1
 1 1 0 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 0 1
 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 1
 0 0 0 1 0 0 0 0 1 0 1 1 1 0 0 1 1 0 1 1 1 0 1 1 0 1 1 0 1 0 1 0 1 1 1 0 1
 0 1]
(150, 20)
(150,)


In [15]:
x,y = make_classification(n_samples=150, n_features=20)
print (x)
print (y)
print (x.shape)
print (y.shape)

[[-1.43700843 -1.00941324 -0.14062439 ...  1.59537996  0.40682279
   0.99104636]
 [ 1.6601185  -0.1765334  -1.03986927 ...  0.15585863 -1.78190944
  -0.39835637]
 [-0.21718753  0.58697782 -0.35425006 ...  0.10719736  0.17330042
  -0.1570463 ]
 ...
 [ 0.66041534  0.87875545 -1.86317775 ...  1.15977171 -1.8440235
   0.66404742]
 [ 1.48416511 -1.4193692  -1.12327151 ... -0.38664212 -1.33668143
  -2.5398549 ]
 [-1.00027615 -0.32869176  1.13961963 ...  1.03472172 -0.38099626
  -0.38530789]]
[1 0 1 0 1 1 1 0 1 1 0 1 1 1 0 0 1 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 1 1
 1 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1
 1 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0
 1 0 0 1 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 1 0 1 0 0 0
 0 0]
(150, 20)
(150,)


In [ ]:
# 生成训练数据
x,y = make_classification(n_samples=150, n_features=20)

# 数据拆分
# 局部样本训练模型（过拟合模型）测试预测不好 训练数据和测试数据差距大
# 新样本数据模型表现不好（泛化能力差）故意不告诉一些数据
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [18]:
print (X_train.shape)
print (X_test.shape)

(105, 20)
(45, 20)


In [28]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import numpy as np

In [41]:
# 1.生成训练数据
x, y = make_classification(n_samples=150, n_features=20)

# 数据拆分
# 局部样本训练模型（过拟合模型）测试预测不好 训练数据和测试数据差距大
# 新样本数据模型表现不好（泛化能力差）故意不告诉一些数据
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [ ]:
# 权重参数
theta = np.random.randn(20,1) # shape (1,10)??
bias = 0

# 超参数
lr = 0.1 # 学习率
epochs = 3000 # 训练次数

In [ ]:
# 假设 X 是 shape (3, 3)
# [[x1,x2,x3],
#  [x4,x5,x6],
#  [x7,x8,x9]]
# X.T 是 shape (3, 3) 
# [[x1,x4,x7],
#  [x2,x5,x8],
#  [x3,x6,x9]]

# 假设 theta 模型参数 shape (1, 3)
# [[w1, w2, w3]]
# theta * X.T shape (1, 3)
#  y1 = w1 * x1 + w2 * x2 + w3 * x3 
#  y2 = w1 * x4 + w2 * x5 + w3 * x6
#  y3 = w1 * x7 + w2 * x8 + w3 * x9
#  [[y1, y2, y3]]

# 2.模型计算函数
def forward (x, theta, bias):
    # 线性运算
    z = np.dot(x, theta) + bias # shape (105,10)
    # sigmoid
    y_hat = 1 / (1 + np.exp(-z))   # shape (105,10)
    return y_hat

# 3.计算损失函数
def loss(y, y_hat):
    e = 1e-8
    return - y * np.log(y_hat + e) - (1 - y) * np.log(1 - y_hat + e)

# 4.计算梯度
def calc_gradient(x,y,y_hat):
    # 计算梯度
    m = x.shape[0] # ??[-1]
    # theta梯度计算
    delta_theta = np.dot(x.T, (y_hat - y)) / m
    # bias梯度计算
    delta_bias = np.mean(y_hat - y)
    # 返回梯度
    return delta_theta, delta_bias

# 5. 模型训练
for i in range(epochs):
    # 前向计算
    y_hat = forward(X_train, theta, bias)
    # 计算损失
    loss_val = loss(y_train, y_hat)
    # 计算梯度
    delta_theta, delta_bias = calc_gradient(X_train, y_train, y_hat)
    # 更新参数
    theta = theta - lr * delta_theta
    bias = bias - lr * delta_bias

    if i % 100 == 0:
        # 计算准确率
        acc = np.mean(np.round(y_hat) == y_train)  # [False,True,...,False] -> [0,1,...,0]
        print(f"epoch: {i}, loss: {np.mean(loss_val)}, acc: {acc}")

epoch: 0, loss: 1.5577539064461832, acc: 0.5000453514739229
epoch: 100, loss: 0.7535725388320061, acc: 0.6239455782312925
epoch: 200, loss: 0.6245643106076021, acc: 0.6858049886621315
epoch: 300, loss: 0.6095839129114565, acc: 0.690702947845805
epoch: 400, loss: 0.6078404756059572, acc: 0.6955102040816327
epoch: 500, loss: 0.6075991032349671, acc: 0.6858956916099773
epoch: 600, loss: 0.6075604057074662, acc: 0.6810884353741496
epoch: 700, loss: 0.6075536672863693, acc: 0.6810884353741496
epoch: 800, loss: 0.6075524458228826, acc: 0.6810884353741496
epoch: 900, loss: 0.6075522202295992, acc: 0.6810884353741496
epoch: 1000, loss: 0.6075521782005113, acc: 0.6810884353741496
epoch: 1100, loss: 0.6075521703381462, acc: 0.6810884353741496
epoch: 1200, loss: 0.6075521688644571, acc: 0.6810884353741496
epoch: 1300, loss: 0.6075521685879764, acc: 0.6810884353741496
epoch: 1400, loss: 0.6075521685360835, acc: 0.6810884353741496
epoch: 1500, loss: 0.6075521685263425, acc: 0.6810884353741496
epoch

In [56]:
# 模型推理
idx = np.random.randint(len(X_test)) # 随机选择一个测试样本索引
x = X_test[idx]
y = y_test[idx]

predict = np.round(forward(x.reshape(1, -1), theta, bias))  # 将 x 变为 (1, 20)
print(f"y: {y}, predict: {predict[0][0]}") 

y: 1, predict: 1.0


In [57]:
import joblib
import numpy as np

In [58]:
theta = joblib.load('theta.pkl')  # 加载 theta
bias = joblib.load('bias.pkl')    # 加载 bias

In [59]:
X_test = np.array([[5.1, 3.5, 1.4, 0.2],  
                   [6.2, 2.9, 4.3, 1.3]])
y_hat = forward(X_test, theta, bias)

In [60]:
print("预测结果 (类别概率)：", y_hat)
print("预测类别：", np.argmax(y_hat, axis=1))

预测结果 (类别概率)： [[0.99917476 0.97216441 0.00860482]
 [0.17068458 0.8501093  0.52404475]]
预测类别： [0 1]
