In [37]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

#生成数据集
X,y = load_iris(return_X_y=True)
X = X[:100]  # 取前100个数据
y = y[:100]  # 取前100个标签(0,1)
print(X)
print(y)

#拆分数据集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

#初始化模型参数
thetas = np.random.randn(1,4)
bias = 0
lr = 1e-4
epochs = 5000

#前向计算
def forward(X, thetas, bias):
    z =  np.dot(thetas, X.T) + bias
    y_hat = 1 / (1 + np.exp(-z)) #sigmoid函数
    return y_hat
#计算损失函数
def loss(y, y_hat):
    return -np.mean(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))
#反向传播 计算梯度
def backward(X, y, y_hat):
    m = X.shape[0]
    d_theta = 1 / m * np.dot(y_hat - y, X)
    d_bias = np.mean(y_hat - y)
    return d_theta, d_bias
#梯度下降
def gradient_descent(X, y, thetas, bias, lr, epochs):
    for i in range(epochs):
        y_hat = forward(X, thetas, bias)
        d_theta, d_bias = backward(X, y, y_hat)
        thetas -= lr * d_theta
        bias -= lr * d_bias
        if i % 1000 == 0:
            print('epoch %d loss %f' % (i, loss(y, y_hat)))
    return thetas, bias




[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [42]:
#训练模型
thetas, bias = gradient_descent(X_train, y_train, thetas, bias, lr, epochs)
print(thetas)
print(bias)
np.save('thetas.npy', thetas)
np.save('bias.npy', bias)

epoch 0 loss 0.271075
epoch 1000 loss 0.261620
epoch 2000 loss 0.252758
epoch 3000 loss 0.244438
epoch 4000 loss 0.236615
[[-0.50333587 -0.01787508  0.77726458  0.98801286]]
-0.05414030266659471


In [48]:
#模型测试
idx = np.random.randint(len(X_test))
x = X_test[idx]
y = y_test[idx]
thetas = np.load('thetas.npy')
bias = np.load('bias.npy')
def predict(x):
    pred = forward(x, thetas, bias)[0]
    if pred >= 0.5:
        return 1
    else:
        return 0
    
print("预测结果:", predict(x))
print("实际结果:", y)

预测结果: 1
实际结果: 1
