## NumPy 数组

In [3]:
import numpy as np
import math

In [3]:
# 创建ndarray数组
arr = np.array([1,2,3,4])
print(arr,type(arr))
arr = np.array([1,2,3,4,5], float)
print(arr,type(arr))

[1 2 3 4] <class 'numpy.ndarray'>
[1. 2. 3. 4. 5.] <class 'numpy.ndarray'>


In [4]:
# 创建多维数组
arr = np.array([(1,2,3),(1,2,3),(1,2,3)])
print(arr,type(arr))

[[1 2 3]
 [1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [5]:
# 创建特殊数组
# 0 
arr = np.zeros((3,3),dtype=int)
print(arr,type(arr))
arr

[[0 0 0]
 [0 0 0]
 [0 0 0]] <class 'numpy.ndarray'>


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
# 全为1的数组
arr = np.ones((3,3),dtype=float)
print(arr,type(arr))


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>


In [7]:
# 创建等差数列，
arr_arange = np.arange(1,3,0.5)
arr_arange

array([1. , 1.5, 2. , 2.5])

In [8]:
# 创建单位矩阵
arr_eye = np.eye(3,3,dtype=np.int8)
arr_eye  # one-hot编码

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [9]:
# 生成指定长度的在 [0,1) 之间平均分布的随机数组
a4 = np.random.random(4)  # 模型运算参数初始值
a4

array([0.41603183, 0.27329667, 0.48104696, 0.74845229])

In [10]:
# 生成指定长度的在 符合正态分布的随机数组
mu, sigma = 0, 1  # mu, sigma = 0, 1-->标准正态分布
a5 = np.random.normal(mu, sigma, 10)  # 模型运算参数初始值
a5

array([ 0.49919792, -1.19688631,  0.60425046, -2.24024984,  0.08601566,
       -0.86689292,  0.67714879,  0.64772878,  0.81741495,  1.87242107])

## NumPy 数组访问

In [71]:
a6 = np.array([(1,2,3), (3,4,5), (5,6,7)])
print(a6,'\n')      # 整个数组
print(a6[0],'\n')   # 索引第一行
print(a6[1:3],'\n') # 切片，取第二行到第三行
print(a6[:,1:3],'\n')    # 切片，取第二列到第三列
print(a6[0,0])      # 索引数组里的第一个内容

[[1 2 3]
 [3 4 5]
 [5 6 7]] 

[1 2 3] 

[[3 4 5]
 [5 6 7]] 

[[2 3]
 [4 5]
 [6 7]] 

1


## NumPy 数组的遍历

In [74]:
''' 一维数组的遍历'''
a_1 = np.array([1,2,3])

for i in a_1:
    print(i)
print()

''' 二维数组的遍历'''
# 创建一个二维数组a7
a7 = np.array([(1,2), (3,4), (5,6)])
# 将数组a7的第一个元素赋值给i和j
i,j = a7[0]     # 元组的知识
# 打印i和j
print(i,j,'\n')
# 遍历数组a7，将每个元素的第一个元素赋值给i，第二个元素赋值给j
for i,j in a7:
    # 打印i和j，使用format函数将i和j放入方括号中
    print('[{},{}]'.format(i,j))


1
2
3

1 2 

[1,2]
[3,4]
[5,6]


## NumPy数组的常用属性

⽐较常⽤的属性有：
- ndarray.ndim : 数组的维度（数组轴的个数），等于秩
- ndarray.shape : 数组的⼤⼩。为⼀个表⽰数组在每个维度上⼤⼩的整元组。例如⼆维数组中，表⽰数组的’ ⾏数’ 和’ 列数”
- ndarray.size : 数组元素的总个数，等于 shape 属性中元组元素的乘积
- ndarray.dtype : 表⽰数组中元素类型的对象

@property装饰器将一个方法转换为一个属性,这几个属性都是装饰器转换得到

In [ ]:
# 导入numpy库
import numpy as np
# 创建一个二维数组
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(a,'\n')
# 打印数组的维度
print('ndim:',a.ndim)   # 数组的维度
# 打印数组的形状
print('shape:',a.shape)  # 
# 打印数组元素的总个数
print('size:',a.size)   # 数组元素的总个数
# 打印数组元素类型的对象
print('dtype:',a.dtype)  # 数组元素类型的对象
# 打印数组第一个元素的类型
print(type(a[0,0]))


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

ndim: 2
shape: (3, 3)
size: 9
dtype: int32
<class 'numpy.int32'>
None


## NumPy 的基本操作

In [107]:
'''检测数值是否在数组中'''
# 生成一个3行3列的随机整数矩阵，范围在0到10之间
a = np.random.randint(low=0, high=10, size=(3,3))
# 打印矩阵
print(a,end='\n'*2)
# 判断5是否在矩阵中
print(5 in a)
# 判断1是否在矩阵中
print(1 in a)


[[7 2 8]
 [3 4 0]
 [2 5 5]]

True
False


In [ ]:
'''数组的重排列，例如将⼀个 3 维数组转变为 1 维（元素数⼀定要保持不变）'''
# 创建一个3x3x3的零矩阵
a = np.zeros(shape=[3,3,3])
# 打印矩阵
print(a,end='\n'*2)
# 将a重新塑形为1维数组
a = a.reshape(-1)
# 打印a，并输出a的长度，然后换行两次
print(a,'len:',len(a),end='\n'*2)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.] len: 27



In [123]:
'''数组的转置 (可以直接.T)'''
# 创建一个1行3列的全零数组
a = np.zeros([1,3])
# 打印数组a
print(a,end='\n'*2)
# 打印数组a的转置
print(a.transpose(),end='\n'*2)

print(a.T,end='\n'*2)

[[0. 0. 0.]]

[[0.]
 [0.]
 [0.]]

[[0.]
 [0.]
 [0.]]



In [131]:
'''flatten : 把多维数组转换为⼀维数组，注意每个元组的⻓度是相同的'''
a = np.array([(1,2),(1,2),(1,2)])
print(a,end='\n'*2)
print(a.flatten(),end='\n'*2)

[[1 2]
 [1 2]
 [1 2]]

[1 2 1 2 1 2]



In [138]:
'''newaxis : 增加维度'''
a = np.array([1,2,3])
print(a, end='\n'*2)
print(a.shape, end='\n'*2)
a = a[:,np.newaxis]
print(a, end='\n'*2)
print(a.shape, end='\n'*2)


[1 2 3]

(3,)

[[1]
 [2]
 [3]]

(3, 1)



## NumPy 数组的数学操作

- 加减乘除
- 求和、求积
- 平均数，⽅差，标准差，最⼤值，最⼩值
- 最⼤与最⼩值对应的索引值：argmax,argmin:
- 取元素值上限，下限，四舍五⼊：ceil, floor, rint
- 排序：sort

除了上述函数外，还有很多数据运算操作，它们的使⽤⽅式基本都类似，例如：abs,
sign, sqrt, log,log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh,
arcsinh, arccosh,arctanh 等等。



In [ ]:
'''* 星乘表⽰矩阵内各对应位置相乘，点乘表⽰求矩阵内积，⼆维数组称为矩阵积
（mastrix product）：
'''
# 数组，矩阵、维度

# 数组、矩阵  ： 数据组织结构形式

# 维度： 通讯地址
a = np.array([(-2,2),(-2,2)])
b = np.ones((2,2))

print(a, end='\n'*2)
print(b, end='\n'*2)
# 加减乘除
print(a+b, end='\n'*2)
print(a*b, end='\n'*2)
print(a/b, end='\n'*2)
# 求和、求积
print(a.sum(), end='\n'*2)
print(b.sum(), end='\n'*2)
print(a.prod(), end='\n'*2)
print(b.prod(), end='\n'*2)




[[-2  2]
 [-2  2]]

[[1. 1.]
 [1. 1.]]

[[-1.  3.]
 [-1.  3.]]

[[-2.  2.]
 [-2.  2.]]

[[-2.  2.]
 [-2.  2.]]

0

4.0

16

1.0


[[1 2]
 [2 2]
 [3 3]
 [4 4]] (4, 2)
[-1  1] (2,)


array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])

In [162]:
'''平均数，⽅差，标准差，最⼤值，最⼩值'''
# 创建一个包含三个元素的数组
a = np.array([5,3,1])
# 计算数组的平均值
print("mean:",a.mean(),a.sum()/3)
# 计算数组的方差
print("var:", a.var(),((5-3)**2+(3-3)**2+(1-3)**2)/3)
# 计算数组的标准差
print("std:", a.std(),math.sqrt(((5-3)**2+(3-3)**2+(1-3)**2)/3))
print("max:",a.max())
print("min:",a.min())
3^2 # 异或操作

mean: 3.0 3.0
var: 2.6666666666666665 2.6666666666666665
std: 1.632993161855452 1.632993161855452
max: 5
min: 1


1

In [164]:
'''最⼤与最⼩值对应的索引值：argmax,argmin:
取元素值上限，下限，四舍五⼊：ceil, floor, rint'''
a = np.array([1.2, 3.8, 4.9])
print("argmax:", a.argmax())
print("argmin:", a.argmin())
print("ceil:", np.ceil(a))
print("floor:", np.floor(a))
print("rint:", np.rint(a))

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [167]:
'''排序'''
a = np.array([16,31,12,28,22,31,48])
a.sort()
print(a)

[12 16 22 28 31 31 48]


## NumPy 线性代数

In [11]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,3,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [4]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [ ]:
a9 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[4,5,6],[7,8,9]])

a9 * b9

In [5]:
# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1,m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


## NumPy 文件操作

In [6]:
np.save('result.npy',manual_result)

In [7]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

## NumPy的广播机制

只能由低维向高维兼容

在NumPy中，形状兼容（Shape Compatibility）是指两个数组在进行算术运算时，它们的形状可以匹配，从而可以进行逐元素运算。形状兼容的规则如下：

1. **形状完全相同**：如果两个数组的形状完全相同，那么它们是形状兼容的。例如，形状为`(2, 3)`和形状为`(2, 3)`的两个数组是形状兼容的。

2. **广播机制**：如果两个数组的形状不完全相同，NumPy会尝试通过广播机制使它们兼容。广播机制遵循以下规则：
   - 如果两个数组的维度数不同，那么维度较小的数组会在前面添加一个或多个长度为1的维度，直到两个数组的维度数相同。
   - 如果两个数组的维度数相同，但某一维度的大小不同，那么长度为1的维度会被扩展到与另一个数组对应维度的大小相同。

   例如，形状为`(2, 3)`和形状为`(3,)`的两个数组是形状兼容的，因为`b`可以通过广播机制扩展为形状`(2, 3)`，然后与`a`进行逐元素运算。

3. **标量广播**：标量（即单个数值）可以广播为任何形状的数组。例如，形状为`(2, 3)`的数组与标量`10`是形状兼容的，因为标量`10`可以广播为形状`(2, 3)`的数组，然后与`a`进行逐元素运算。

广播机制的注意事项
形状不匹配的处理：如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度等于1，那么会引发异常2。

In [31]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b
print(a + b)

print('======',end='\n'*2)

a = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
a = a[:,:,np.newaxis]
print(a,'shape:',a.shape,end='\n'*2)
b = np.array([-1,-1])                       # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
print(b,'shape:',b.shape,end='\n'*2)
print(a + b)
b = np.array([1,-1,1,-1])                          # 只能由低维向高维兼容
print('b.shape',b.shape)
print(a + b)

[5 7 9]

[[[1]
  [2]]

 [[2]
  [2]]

 [[3]
  [3]]

 [[4]
  [4]]] shape: (4, 2, 1)

[-1 -1] shape: (2,)

[[[0 0]
  [1 1]]

 [[1 1]
  [1 1]]

 [[2 2]
  [2 2]]

 [[3 3]
  [3 3]]]
b.shape (4,)
[[[2 0 2 0]
  [3 1 3 1]]

 [[3 1 3 1]
  [3 1 3 1]]

 [[4 2 4 2]
  [4 2 4 2]]

 [[5 3 5 3]
  [5 3 5 3]]]


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

c = a + b
print(c)

[[11 22 33]
 [14 25 36]]
