## pytorch基础-张量

张量（Tensor）

张量（Tensor）是pytorch中的基本单位，也是深度学习框架构成的重要组成。

我们可以先把张量看做是⼀个容器，⾥⾯承载了需要运算的数据。

张量可以通过多种⽅式初始化。看看下⾯的例⼦：
直接从数据

张量可以直接从数据中创建。数据类型是⾃动推断的。

In [ ]:
import torch
# 创建一个二维列表
data = [[1,2],[2,3],[3,4]]
# 将二维列表转换为张量
data_tensor = torch.tensor(data=data)
# 打印二维列表
print(data)
# 打印张量
print(data_tensor)
# 创建一个二维列表，并指定数据类型为float32
data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
# 打印数据类型
print(data.dtype)
# 打印张量
data

[[1, 2], [2, 3], [3, 4]]
tensor([[1, 2],
        [2, 3],
        [3, 4]])
torch.float32


tensor([[1., 2.],
        [3., 4.]])

## tensor（张量）和numpy_array(数组)转换

In [ ]:
import numpy as np

import torch
# 创建一个numpy数组
np_array = np.array([[1,2],[3,4]])
print(type(np_array))
# 将numpy数组转换为tensor
data_tensor = torch.from_numpy(np_array)
print(data_tensor,type(data_tensor))
# 将tensor转换为numpy数组
np_array = data_tensor.numpy()
np_array

<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


array([[1, 2],
       [3, 4]])

## tensor的属性和方法


In [ ]:
# 打印data_tensor的数据类型
print(data_tensor.dtype)
# 打印data_tensor的形状
print(data_tensor.shape)
# 打印data_tensor的维度
print(data_tensor.ndim)
# 打印data_tensor所在的设备
print(data_tensor.device)
# print(data_tensor.)


torch.int32
torch.Size([2, 2])
2
cpu


In [ ]:
# 打印data_tensor的形状
print('data_tensor.shape: ',data_tensor.shape)
# 创建一个与data_tensor形状相同，数据类型为float的随机张量-->torch.tensor_like(data_tensor,dtype=float) x 应该为torch.rand_like(data_tensor,dtype=float)
data3 = torch.rand_like(data_tensor, dtype=torch.float)
# 打印data3的形状
print('data3.shape: ',data3.shape)
# 返回data3
data3

data_tensor.shaped:  torch.Size([3, 2])
data3.shape:  torch.Size([3, 2])


tensor([[0.8982, 0.2162],
        [0.4869, 0.5964],
        [0.8275, 0.0211]])

In [ ]:
# 定义一个形状为(2,3,)的张量
shape = (2,3,) #  定义一个形状为(2,3)的元组
rand_tensor = torch.rand(shape) #  生成一个指定形状的随机张量 torch.tensor(shape:tuple)
ones_tensor = torch.ones(shape) #  生成一个形状为(2,3)的全1张量 torch.ones((2,3))
zeros_tensor = torch.zeros(shape) #  生成一个形状为(2,3)的全0张量torch.zeros((2,3))

print(f"Random Tensor: \n {rand_tensor} \n") #  打印随机张量
print(f"Ones Tensor: \n {ones_tensor} \n") #  打印全1张量
print(f"Zeros Tensor: \n {zeros_tensor}") #  打印全0张量

Random Tensor: 
 tensor([[0.1617, 0.4225, 0.0395],
        [0.1011, 0.6725, 0.4511]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# 创建一个5行3列的全1矩阵，数据类型为双精度浮点数
m = torch.ones(5,3, dtype=torch.double)
# 创建一个与m形状相同的随机矩阵，数据类型为单精度浮点数
n = torch.rand_like(m, dtype=torch.float)
# 打印m的形状
print(m.size(),'\n',m) # torch.Size([5,3])

print('======================')

# 打印一个5行3列的随机矩阵
print(torch.rand(5,3))
# 打印一个5行3列的正态分布随机矩阵
print(torch.randn(5,3))
# 打印一个5行3列的正态分布随机矩阵，均值为0，标准差为1
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 打印一个从1到10的等间隔的21个数的张量
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([5, 3]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.5648, 0.7737, 0.0239],
        [0.8702, 0.9839, 0.3671],
        [0.8697, 0.3623, 0.4183],
        [0.4954, 0.4076, 0.5233],
        [0.4497, 0.6551, 0.2449]])
tensor([[ 1.7889, -0.7664, -1.4013],
        [-0.5463, -0.1856, -0.2040],
        [ 1.0264, -1.7208,  0.6240],
        [-1.0375, -0.5275, -1.1950],
        [ 1.0389,  0.7380,  0.1551]])
tensor([[ 0.8706,  0.2942,  1.9502],
        [ 0.2671, -0.1697, -0.7264],
        [ 0.2316,  1.6486, -0.5303],
        [-0.8716, -0.0133, -0.2651],
        [-1.9328, -1.3316, -0.1177]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [ ]:
# 创建一个3行4列的随机张量
tensor = torch.rand(3,4)

# 打印张量的形状
print(f"Shape of tensor: {tensor.shape}")
# 打印张量的数据类型
print(f"Datatype of tensor: {tensor.dtype}")
# 打印张量存储的设备
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    # 如果支持GPU，则将设备设置为GPU
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

# mac上没有GPU，使用M系列芯片
if torch.backends.mps.is_available():
    device = torch.device("mps")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.4028, 0.9439, 0.1505, 0.3773],
        [0.0966, 0.0682, 0.3893, 0.9114],
        [0.9544, 0.5207, 0.9319, 0.7016]])
cpu
tensor([[0.4028, 0.9439, 0.1505, 0.3773],
        [0.0966, 0.0682, 0.3893, 0.9114],
        [0.9544, 0.5207, 0.9319, 0.7016]])
cpu


## 张量运算

In [ ]:
# 创建一个4x4的全1张量
tensor = torch.ones(4, 4)
# 打印第一行
print('First row: ', tensor[0])
# 打印第一列
print('First column: ', tensor[:, 0])
# 打印最后一列
print('Last column:', tensor[..., -1])
# 将第二列的值全部设为0
tensor[:,1] = 0
# 打印修改后的张量
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 将tensor与自身拼接三次，沿着第0维拼接
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)  # 打印拼接后的tensor
print(t1.shape)  # 打印拼接后的tensor的形状
# 将tensor与自身拼接三次，沿着第1维拼接
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)  # 将拼接后的tensor乘以3
print(t1.shape)  # 打印拼接后的tensor的形状

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([12, 4])
tensor([[3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.]])
torch.Size([4, 12])


In [ ]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

y3 = torch.rand_like(tensor)
print('y3:\n',y3)
# 计算tensor和tensor的转置的矩阵乘法，并将结果存储在y3中
torch.matmul(tensor, tensor.T, out=y3)
print('torch.matmul(tensor, tensor.T, out=y3)   y3:\n',y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print("tensor * tensor:", z1)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print("tensor * tensor:", z1)
print("torch.mul(tensor, tensor, out=z3) z3:", z3)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
y3:
 tensor([[0.1259, 0.5341, 0.5635],
        [0.1361, 0.6661, 0.6179],
        [0.2140, 0.2239, 0.3957]])
torch.matmul(tensor, tensor.T, out=y3)   y3:
 tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor * tensor: tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
torch.mul(tensor, tensor, out=z3) z3: tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [12]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))
agg = torch.tensor(agg_item)
print(agg)

tensor(45.)
45.0 <class 'float'>
tensor(45.)


In [13]:
np_arr = z1.numpy()
print(np_arr,type(np_arr))
tensor = torch.from_numpy(np_arr)
print(tensor)

[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]] <class 'numpy.ndarray'>
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


### In-place操作

In [ ]:
# 打印tensor
# 打印tensor
print(tensor, "\n")
# 将tensor的值增加5
tensor.add_(5)
# tensor = tensor + 5
# tensor += 5
# 打印增加后的tensor
print(tensor)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]]) 

tensor([[ 6.,  9., 14.],
        [21., 30., 41.],
        [54., 69., 86.]])


In [15]:
tensor

tensor([[ 6.,  9., 14.],
        [21., 30., 41.],
        [54., 69., 86.]])

## 计算图

计算图
在进⼀步学习pytorch之前，先要了解⼀个概念 —— 计算图( Computation graph)所有的深度学习框架都依赖于计算图来完成梯度下降、优化梯度值等计算。⽽计算图的创建和应⽤，通常包含如下两个部分：

1. ⽤⼾构建前向传播图
2. 框架处理后向传播(梯度更新)

模型从简单到复杂，pytorch和tensorflow都使⽤计算图来完成⼯作。但是，这两个框架所使⽤的计算图也却有所不同：tensorflow1.x 使⽤的是静态计算图，tensorflow2.x和pytorch使⽤的是动态计算图。

In [3]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)

# # 不设置 requires_grad=True 这个参数
# A = torch.randn(10, 10)  # requires_grad=True 表示我们要对 A 求导
# b = torch.randn(10)
# c = torch.randn(1)
# x = torch.randn(10)

print(A)
print(b)
print(c)
print(x)

# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

tensor([[-0.7056, -1.1294,  1.3409, -0.7608, -0.5293, -0.1568, -0.2279,  0.2818,
          0.0207, -0.7942],
        [ 0.7274, -1.2783,  0.2343, -0.1232,  0.1612,  1.1243,  0.5018,  1.5124,
         -1.3377,  0.9328],
        [-1.1371,  1.4808, -0.6457,  1.6646, -1.2049,  0.8178, -0.6517, -1.1324,
         -1.3577,  0.4634],
        [-0.1495,  1.0262, -1.2738,  0.0795,  2.0065,  1.0519, -0.4876, -1.3043,
         -1.8095,  1.2450],
        [-0.4401, -0.3208, -1.3851,  0.5539,  0.0972, -0.4738,  1.3937, -0.2813,
          1.5669, -0.2977],
        [-0.7179, -1.5290,  1.2114, -0.2846,  0.1133,  0.3436,  0.1981,  0.6191,
         -0.4928,  0.9062],
        [ 1.1626,  0.0691,  0.3070,  0.6794, -0.3059, -0.3886,  0.1550, -1.9580,
          0.8805, -1.6631],
        [ 0.3296, -0.9578, -0.0962,  1.0546, -0.9969, -0.6307, -0.4276, -1.4007,
          0.8332, -0.8394],
        [-0.3763, -1.0011, -0.6376,  1.1612, -0.8291, -0.4670,  0.5048,  2.6009,
          0.1233,  0.2711],
        [-0.1989, -

'expression.png'