
# 一、Numpy 
## 1. Numpy 数组的创建

In [19]:
import numpy as np
np_array_1d = np.array([1, 2, 3])             # 一维数组
np_array_2d = np.array([[1, 2], [3, 4]])      # 二维数组
np_zeros = np.zeros((2, 3))                   # 全零矩阵
np_rand = np.random.rand(2, 2)                # 随机矩阵

print(np_array_1d)
print(np_array_2d)
print(np_zeros)
print(np_rand)

# 保存和加载
np.save("result.npy",np_zeros)
result = np.load("result.npy")
result

[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.55716409 0.7811256 ]
 [0.98380374 0.03004612]]


array([[0., 0., 0.],
       [0., 0., 0.]])

## 2. Nmupy 运算

In [20]:
# 加减乘除
a1 = np.array([[2,3],[5,6],[4,6]])
a2 = np.array([[1,-1]])
a3 = a1 + a2   # 广播机制
print(a3)

a4 = a3 - a1
print(a4)

a5 = a4 * 3
print(a5)

a6 = a5 / 2
print(a6)

[[3 2]
 [6 5]
 [5 5]]
[[ 1 -1]
 [ 1 -1]
 [ 1 -1]]
[[ 3 -3]
 [ 3 -3]
 [ 3 -3]]
[[ 1.5 -1.5]
 [ 1.5 -1.5]
 [ 1.5 -1.5]]


In [21]:
# 点积
np_dot = np.dot(np_array_1d, np_array_1d)
print(np_dot)

14


In [22]:

# 矩阵乘法
mat_a = np.array([[1, 2], [3, 4]])
mat_b = np.array([[5, 6], [7, 8]])
np_matmul = np.matmul(mat_a, mat_b)
print(np_matmul)

result = mat_a @ mat_b
print(result)


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [23]:
# 转置
np_transpose = mat_a.T
print(mat_a)
print(np_transpose)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [24]:
# 求和、均值、标准差
print("Sum:", np.sum(mat_a))
print("Mean:", np.mean(mat_a))
print("Std:", np.std(mat_a))

Sum: 10
Mean: 2.5
Std: 1.118033988749895


## 3. 形状操作

In [25]:
# 重塑
mat_a.reshape(4, 1)
print(mat_a)
# 切片
print(mat_b[:, 1]) 

[[1 2]
 [3 4]]
[6 8]


# 二、PyTorch 基础
## 1. tensor操作

In [26]:
import torch

torch_tensor_1d = torch.tensor([1., 2., 3.])  # 一维张量（注意默认类型为float32）
torch_tensor_2d = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
torch_zeros = torch.zeros(2, 3)
torch_rand = torch.rand(2, 2)

print(torch_tensor_1d)
print(torch_tensor_2d)
print(torch_zeros)
print(torch_rand)

# 矩阵乘法
tensor_a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
tensor_b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
torch_matmul = torch.matmul(tensor_a, tensor_b)
print("矩阵乘法",torch_matmul)

result = tensor_a @ tensor_b
print("矩阵乘法",result)

# 点积
torch_dot = torch.dot(torch_tensor_1d, torch_tensor_1d)
print(torch_dot)
print(torch_dot.item())

# 求和、均值、标准差
print("Sum:", torch.sum(tensor_a).item())
print("Mean:", torch.mean(tensor_a).item())
print("Std:", torch.std(tensor_a).item())

# 重塑
torch_reshaped = tensor_a.view(4, 1)  # 或 reshape()
print("\nPyTorch重塑形状:")
print(torch_reshaped)

# 张量拼接
tensor = torch.tensor([[0,1,0],[1,1,1],[1,1,1]])
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print("拼接后结果：",t1)


tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9569, 0.1907],
        [0.4186, 0.0084]])
矩阵乘法 tensor([[19., 22.],
        [43., 50.]])
矩阵乘法 tensor([[19., 22.],
        [43., 50.]])
tensor(14.)
14.0
Sum: 10.0
Mean: 2.5
Std: 1.29099440574646

PyTorch重塑形状:
tensor([[1.],
        [2.],
        [3.],
        [4.]])
拼接后结果： tensor([[0, 1, 0, 0, 1, 0, 0, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])


## 2. Pytorch 使用

In [27]:

# 查看显卡可用性
torch.cuda.is_available()

False

In [28]:
# 梯度更新

# 计算图可视化

from torchviz import make_dot
A = torch.randn(10,10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10,requires_grad=True)

result = torch.matmul(A,x.T) + torch.matmul(b,x) + c

# 生成计算节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x':x})

# 绘制计算图
dot.render('expression',format='png',cleanup=True,view=False)



'expression.png'

In [29]:
# add_() 就地操作慎用
torch_tensor_1d = torch.tensor([1., 2., 3.])
print(torch_tensor_1d)
result = torch_tensor_1d.add(5)
print("torch_tensor_1d",torch_tensor_1d)
print("result",result)

result = torch_tensor_1d.add_(5)
print("torch_tensor_1d",torch_tensor_1d)
print("result",result)


tensor([1., 2., 3.])
torch_tensor_1d tensor([1., 2., 3.])
result tensor([6., 7., 8.])
torch_tensor_1d tensor([6., 7., 8.])
result tensor([6., 7., 8.])
