In [1]:
import numpy as np
# 1、numpy数组: Ndarray
# 1.1、基础数组创建
a1 = [1 ,2 ,3, 4]
matrix = np.array(a1)
matrix

array([1, 2, 3, 4])

In [2]:
matrix = np.array(a1, float)
matrix
matrix = np.array([1, 5, 6])
matrix

array([1, 5, 6])

In [3]:
matrix = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# 1.2、特殊数组创建
matrix = np.zeros((2,4), dtype=float)
print("matrix:",matrix)
matrix = np.zeros((3,3))
print("matrix:",matrix)
print(matrix.dtype)

matrix: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
matrix: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [5]:
matrix = np.ones((3,3))
print(matrix)
matrix = np.ones((3,4,5))
print(matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [6]:
matrix = np.arange(1, 3, 0.3)
print(matrix)
print(matrix.dtype)
matrix = np.arange(1, 8, 2)
print(matrix)
print(matrix.dtype)

[1.  1.3 1.6 1.9 2.2 2.5 2.8]
float64
[1 3 5 7]
int64


In [7]:
# 创建单位矩阵
matrix = np.eye(2)
print(matrix)
matrix = np.eye(3)
print(matrix)
# 创建一个 3×5 的矩阵，对角线偏移量为 1
matrix = np.eye(3, 5, k=1)
print(matrix)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [8]:
matrix = np.random.random(7)
print(matrix)
# ⽣成指定⻓度，符合正态分布的随机数组，指定其均值为 0，标准差为 0.1
matrix = np.random.normal(0, 0.1, 7)
print(matrix)
matrix = np.random.normal(10, 2, 7)
print(matrix)

[0.48187832 0.86806287 0.59371934 0.90413937 0.72751069 0.01372851
 0.12033351]
[-0.0077943  -0.03422957 -0.03381059 -0.1075318  -0.09025589 -0.10664199
 -0.06219685]
[10.78495356  8.23121864 11.2959726   9.10654054  9.81174985 11.36104465
 12.2355545 ]


In [9]:
# 1.3、数组访问
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[0])
print(matrix[0][1])
print(matrix[1:])
print(matrix[1:, :1])
print(matrix[1:, 1:])

[1 2 3]
2
[[4 5 6]
 [7 8 9]]
[[4]
 [7]]
[[5 6]
 [8 9]]


In [10]:
# 1.4、数据遍历
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i,j,k in matrix:
    print(i,"-",j,"-",k)

1 - 2 - 3
4 - 5 - 6
7 - 8 - 9


In [11]:
# 1.5、数组常用属性
matrix = np.ones((2,4,5))
print(matrix)
print("数组的维度（数组轴的个数），等于秩：", matrix.ndim)
print("数组的⼤⼩：", matrix.shape)
print("数组元素的总个数，等于 shape 属性中元组元素的乘积：", matrix.size)
print("元素类型：", matrix.dtype)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
数组的维度（数组轴的个数），等于秩： 3
数组的⼤⼩： (2, 4, 5)
数组元素的总个数，等于 shape 属性中元组元素的乘积： 40
元素类型： float64


In [12]:
# 1.6、数组的基本操作
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(1 in matrix)
# print((1,2) in matrix) # 报错：operands could not be broadcast together with shapes (3,3) (2,)
print((11,22,3) in matrix)
print((11,22,33) in matrix)
print([1,2,3] in matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
True
True
False
True


In [13]:
matrix = np.ones((3,4,5))
print(matrix)
# 元素数需保持一致
matrix = matrix.reshape(3,20)
print("matrix=", matrix)
matrix = matrix.reshape(5, 4, 3)
print("matrix=", matrix)
matrix = matrix.reshape(3*4*5)
print("matrix=", matrix)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
matrix= [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
matrix= [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
matrix= [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
matrix = np.ones((2,3))
print(matrix)
matrix.transpose()
print(matrix)
matrix = matrix.transpose()
print(matrix)
matrix = np.ones((2,3,4))
print("matrix=", matrix)
print(matrix.shape)
matrix = matrix.T
print("matrix.T=", matrix)
print(matrix.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
matrix= [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 3, 4)
matrix.T= [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(4, 3, 2)


In [15]:
matrix = np.ones((3,4))
print(matrix)
matrix.flatten()
print(matrix)
matrix = matrix.flatten()
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
# 增加维度
# 在开头添加新轴
arr = np.array([1, 2, 3, 4])
print(arr)
arr_2d = arr[np.newaxis, :]
print("在开头添加新轴:\n", arr_2d)
print("新形状:", arr_2d.shape)
matrix = np.ones((2,3))
print(matrix)
print(matrix.shape)
matrix = matrix[:,np.newaxis]
print("新形状:\n",matrix)
print(matrix.shape)
matrix = matrix[:,:,np.newaxis]
print("新形状:\n",matrix)
print(matrix.shape)
matrix = matrix[np.newaxis]
print(matrix)
print(matrix.shape)
print(matrix[0][0][0])

[1 2 3 4]
在开头添加新轴:
 [[1 2 3 4]]
新形状: (1, 4)
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
新形状:
 [[[1. 1. 1.]]

 [[1. 1. 1.]]]
(2, 1, 3)
新形状:
 [[[[1. 1. 1.]]]


 [[[1. 1. 1.]]]]
(2, 1, 1, 3)
[[[[[1. 1. 1.]]]


  [[[1. 1. 1.]]]]]
(1, 2, 1, 1, 3)
[[1. 1. 1.]]


In [17]:
# 1.7、数组的数学操作
matrix = np.array([(1,2),(3,4)])
matrix = np.array([(-1,1),(-1,1)])
print(matrix)
print(matrix)
print(matrix + matrix)
print(matrix - matrix)
print(matrix * matrix)
print(matrix / matrix)
print()
matrix = np.array([(1,2,5),(3,4,7)])
matrix = np.array([(-1,1),(-1,1)])
print(matrix)
print(matrix)
# print(matrix + matrix) # 报错：operands could not be broadcast together with shapes (2,3) (2,2)
print("元素求和", matrix.sum())
print("元素求积", matrix.prod())

[[-1  1]
 [-1  1]]
[[-1  1]
 [-1  1]]
[[-2  2]
 [-2  2]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[1. 1.]
 [1. 1.]]

[[-1  1]
 [-1  1]]
[[-1  1]
 [-1  1]]
元素求和 0
元素求积 1


In [18]:
matrix = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])
print(matrix)
print("平均数：", matrix.mean())
print("方差：", matrix.var())
print("标准差：", matrix.std())
print("最大值：", matrix.max())
print("最小值：", matrix.min())
print("最大值索引：", matrix.argmax())
print("最小值索引：", matrix.argmin())
matrix = np.ceil(matrix)
print("元素值上限", matrix)
matrix = np.floor(matrix)
print("元素值下限", matrix)
matrix = np.rint(matrix)
print("元素值四舍五入", matrix)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
平均数： 3.85
方差： 3.5291666666666663
标准差： 1.8786076404259262
最大值： 6.6
最小值： 1.1
最大值索引： 5
最小值索引： 0
元素值上限 [[2. 3. 4.]
 [5. 6. 7.]]
元素值下限 [[2. 3. 4.]
 [5. 6. 7.]]
元素值四舍五入 [[2. 3. 4.]
 [5. 6. 7.]]


In [19]:
matrix = np.array([[7.2, 3.3, 1.1], [6.6, 4.4, 5.5]])
print(matrix)
matrix.sort()
print(matrix) # 原数组发生变化
matrix.sort(axis=0)
print(matrix)

[[7.2 3.3 1.1]
 [6.6 4.4 5.5]]
[[1.1 3.3 7.2]
 [4.4 5.5 6.6]]
[[1.1 3.3 6.6]
 [4.4 5.5 7.2]]


In [20]:
# 1.8、线性代数：numpy.linalg
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
r1 = np.dot(m1, m2)
r2 = m1 @ m2
print(r1)
print(r2)
print("点乘：数组 a 的最后⼀维上的所有元素与数组 b 的倒数第⼆位上的所有元素的乘积和")
m1 = np.array([[1, 2, 5], [3, 4, 5]])
m2 = np.array([[5, 6], [7, 8], [9, 10]])
print(m1.shape)
print(m2.shape)
r1 = np.dot(m1, m2)
r2 = m1 @ m2
print(r1)
print(r2)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
点乘：数组 a 的最后⼀维上的所有元素与数组 b 的倒数第⼆位上的所有元素的乘积和
(2, 3)
(3, 2)
[[ 64  72]
 [ 88 100]]
[[ 64  72]
 [ 88 100]]


In [21]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8], [9, 10]])
# 特征值
r1 = np.linalg.eig(m1)
print(r1)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [22]:
# 2、文件操作
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
r = m @ m
print(r)
np.save('test.npy', r)
r1 = np.load('test.npy')
print(r1)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [23]:
# 3、Numpy数组的广播机制
m1 = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
m2 = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
r = m1 + m2
print(r)
m1 = np.array([(1,2,3), (2,2,3)])  # shape(2,3)
m2 = np.array([-1,-1,-1])  # shape(3)-> shape(1,3) -> shape(2,3)  [[-1,-1,-1],[-1,-1,-1]]
print(m1.shape)
print(m2.shape)
r = m1 + m2
print(r)

[[0 3]
 [1 3]
 [2 4]
 [3 5]]
(2, 3)
(3,)
[[0 1 2]
 [1 1 2]]
