In [13]:
import torch; # type: ignore
import numpy as np

# 1、张量创建
tensorTest = [[1,2], [3,4]]
print(tensorTest)
tensorTest = torch.tensor(tensorTest)
print(tensorTest)
tensorTest = np.array(tensorTest)
print(tensorTest)
tensorTest = torch.from_numpy(tensorTest)
print(tensorTest)
tensorTest = torch.tensor(tensorTest)
print(tensorTest)


[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


C:\Users\29760\AppData\Local\Temp\ipykernel_22448\1316924808.py:9: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  tensorTest = np.array(tensorTest)
C:\Users\29760\AppData\Local\Temp\ipykernel_22448\1316924808.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensorTest = torch.tensor(tensorTest)


In [14]:
tensorTest = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
tensorTest = torch.ones_like(tensorTest)
print(tensorTest)
print(tensorTest)
tensorTest = torch.zeros_like(tensorTest)
tensorTest = torch.rand_like(tensorTest) # 如果tensorTest中不指定元素类型dtype=torch.float32，会提示异常："check_uniform_bounds" not implemented for 'Long'
print(tensorTest)
print(tensorTest)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3305, 0.6762, 0.4242],
        [0.2223, 0.1028, 0.7142],
        [0.9060, 0.0895, 0.2812]])
tensor([[0.3305, 0.6762, 0.4242],
        [0.2223, 0.1028, 0.7142],
        [0.9060, 0.0895, 0.2812]])


In [15]:
# 使⽤随机值或常量值创建张量
shape1 = (3, 3)
tensorTest = torch.rand(shape1)
tensorTest = torch.ones(shape1)
tensorTest = torch.zeros(shape1)
print(tensorTest)
print(tensorTest)
print(tensorTest)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [16]:
# 其他创建方法
tensorTest = torch.rand(5,3) # 均匀分布
tensorTest = torch.rand((5,3))
print(tensorTest)
print(tensorTest)
tensorTest = torch.randn(5,3) # 标准正态分布
tensorTest = torch.randn((5,3))
print(tensorTest)
print(tensorTest)
tensorTest = torch.normal(mean=0, std=1, size=(5,3))
print(tensorTest)
tensorTest = torch.linspace(0, 10, steps=22) # 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(tensorTest)

tensor([[0.7939, 0.1668, 0.3537],
        [0.8758, 0.2170, 0.4810],
        [0.1829, 0.5889, 0.1512],
        [0.8198, 0.9878, 0.3339],
        [0.0846, 0.8824, 0.7013]])
tensor([[0.7939, 0.1668, 0.3537],
        [0.8758, 0.2170, 0.4810],
        [0.1829, 0.5889, 0.1512],
        [0.8198, 0.9878, 0.3339],
        [0.0846, 0.8824, 0.7013]])
tensor([[ 1.1059, -1.2167,  0.0485],
        [ 1.1039,  0.4125, -1.2176],
        [ 1.6356, -0.8966, -0.0927],
        [-0.4016,  0.2126, -0.8706],
        [ 0.2255,  0.0947, -2.2724]])
tensor([[ 1.1059, -1.2167,  0.0485],
        [ 1.1039,  0.4125, -1.2176],
        [ 1.6356, -0.8966, -0.0927],
        [-0.4016,  0.2126, -0.8706],
        [ 0.2255,  0.0947, -2.2724]])
tensor([[-1.6274,  0.4158, -0.6932],
        [-0.1416, -0.7481,  0.0848],
        [ 0.6383, -0.1605, -1.8543],
        [ 1.4544,  0.4875,  1.0943],
        [-2.5213,  0.6767,  1.5254]])
tensor([ 0.0000,  0.4762,  0.9524,  1.4286,  1.9048,  2.3810,  2.8571,  3.3333,
         3.8095,  4.

In [17]:
# 2、张量的属性
tensorTest = torch.ones((3,4,5))
print(tensorTest)
print("维度：", tensorTest.shape)
print("维度：", tensorTest.size())
print("元素类型：", tensorTest.dtype)
print("存储位置：", tensorTest.device)
print(torch.cuda.is_available())

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
维度： torch.Size([3, 4, 5])
维度： torch.Size([3, 4, 5])
元素类型： torch.float32
存储位置： cpu
False


In [18]:
# 3、张量拼接，dim 参数指定了沿着哪个维度进行拼接
tensorTest = torch.ones(2, 3)
print(tensorTest)
print(tensorTest.shape)
tensorTest = torch.cat([tensorTest, tensorTest], dim=0)
print(tensorTest)
print(tensorTest.shape)
tensorTest = torch.cat([tensorTest, tensorTest], dim=1)
print(tensorTest)
print(tensorTest.shape)
tensorTest = torch.cat([tensorTest, tensorTest, tensorTest], dim=0)
print(tensorTest)
print(tensorTest.shape)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([4, 3])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.Size([4, 6])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.Size([12, 6])


In [19]:
tensorTest = torch.ones(2, 3, 4)
print(tensorTest)
print(tensorTest.shape)
tensorTest = torch.cat([tensorTest, tensorTest], dim=0)
print(tensorTest)
print(tensorTest.shape)
tensorTest = torch.cat([tensorTest, tensorTest], dim=1)
print(tensorTest)
print(tensorTest.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([4, 3, 4])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 

In [20]:
# 4、张量算数运算
# 点乘
tensorTest = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
print(tensorTest)
tensorTest = torch.ones(3,3)
print(tensorTest)
r1 = tensorTest @ tensorTest
r2 = tensorTest.matmul(tensorTest)
r3 = torch.matmul(tensorTest, tensorTest)
r4 = torch.ones(3,3)
torch.matmul(tensorTest, tensorTest, out=r4)
print(r1)
print(r2)
print(r3)
print(r4)
print(tensorTest.T)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [21]:
# 叉乘
tensorTest1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
print(tensorTest1)
tensorTest2 = torch.eye(3,3)
print(tensorTest2)
r1 = tensorTest1 * tensorTest2
r2 = tensorTest1.mul(tensorTest2)
r3 = torch.mul(tensorTest1, tensorTest2)
print(r1)
print(r2)
print(r3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])
tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])
tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])


In [22]:
# 转换为python数值
tensorTest = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
s = tensorTest.sum()
i = s.item()
print(s, type(s))
print(i, type(i))

tensor(45.) <class 'torch.Tensor'>
45.0 <class 'float'>


In [23]:
# in-place操作
tensorTest = torch.ones(3,3)
print(tensorTest)
tensorTest.add(3)
print(tensorTest)
tensorTest.add_(3)
print(tensorTest) # in-place操作，直接在原对象上修改

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [24]:
# 5、计算图，先安装torchviz：pip install torchviz
from torchviz import make_dot
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
print(A)
print(b)
print(c)
print(x)

result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
print(result)
# ⽣成计算图节点
dot = make_dot(result, params={'数据A': A, '数据b': b, '数据c': c, 'x': x})
# 绘制计算图
# 报错：ExecutableNotFound: failed to execute WindowsPath('dot')。解决：conda install graphviz
dot.render('expression', format='png', cleanup=True, view=False)

tensor([[ 0.6419,  0.4156, -1.1987,  1.3588, -0.7087, -0.1228,  0.2634,  1.3743,
          1.2352,  1.1777],
        [ 1.8671,  1.0672, -0.2352,  1.2464, -0.4567,  1.5838, -2.8774,  1.5527,
         -0.7481, -0.5145],
        [-0.9668, -1.1937,  1.0413,  1.1937,  0.6765,  0.9360, -0.2362,  0.7363,
          0.0455, -0.7008],
        [ 0.4648,  1.3149,  0.8614, -0.9764,  1.4870,  1.9549, -0.5637,  0.2848,
         -0.4398,  0.0719],
        [-0.5819,  0.8575,  0.0514,  1.7167, -0.1593, -1.9993,  0.2463,  0.2509,
          0.4617, -0.6696],
        [ 1.0920, -0.7440,  0.3390,  0.1093, -0.9507,  0.9897,  0.6069,  1.5570,
          0.6824, -0.1009],
        [-2.2575, -0.4461, -0.5536, -1.1595, -0.0620, -0.6834,  0.1444,  0.8909,
         -0.2175,  0.5755],
        [ 0.8596, -2.1230, -0.9950, -0.6791,  0.2569,  0.5144,  1.7620,  0.9004,
          1.2510, -2.4118],
        [ 0.7537, -1.0866, -0.5311, -0.6070, -0.0639, -1.4760,  0.3211,  0.7172,
          0.7402,  0.7873],
        [ 1.6821, -

'expression.png'