In [4]:
import numpy as np

In [5]:
#创建数组
arr=np.array([1,2,3,4,5],float)
arr

array([1., 2., 3., 4., 5.])

In [6]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)],float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
#创建全0的数组
a1 = np.zeros((2,3),dtype=np.float32)
print(a1)
#创建全1的数组
a2 = np.ones((3,3),dtype=np.int32)
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#创建等差数列
a3 = np.arange(1,10,0.4,dtype=np.float32)
print(a3)

[1.        1.4       1.8       2.1999998 2.6       3.        3.3999999
 3.7999997 4.2       4.6       5.        5.3999996 5.7999997 6.2
 6.5999994 6.9999995 7.3999996 7.7999997 8.2       8.599999  9.
 9.4       9.799999 ]


In [30]:
#为什么会产生2.1999998的误差是因为0.4在二进制中是一个无限循环的小数，默认显示6位就会导致这样的情况
#要改的话用更高精度的float类型
a4 = np.arange(1,10,0.4,dtype=np.float64)
print(a4)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5.  5.4 5.8 6.2 6.6 7.  7.4 7.8
 8.2 8.6 9.  9.4 9.8]


In [ ]:
#创建单位矩阵5×5
a5 = np.eye(5)
a5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
#生成了一个2行3列的随机数矩阵，服从正态分布,均值为0，标准差为1
a6 = np.random.randn(2, 3)
print(a6)

print()
# 生成[0.0, 1.0)区间内的均匀分布随机数
a7 =np.random.rand(2, 3)
print(a7)

print()
# 生成[low, high)区间内的随机整数,均匀分布
a8 = np.random.randint(1, 10, size=(2, 3))
print(a8)

print()
# 生成指数分布随机数
a9 = np.random.exponential(scale=1.0, size=(2, 3))
print(a9)

print()
# 生成泊松分布随机数lam = 5.0，意味着在这个时间间隔或空间内事件发生的平均数量是 5。
a10 = np.random.poisson(lam=5.0, size=(2, 3))
print(a10)

print()
# 生成二项分布随机数
a11 = np.random.binomial(n=10, p=0.5, size=(2, 3))
print(a11)


[[-1.7991056  -0.93343675 -0.19062938]
 [-0.69971935 -1.06713996 -0.82174403]]

[[0.50720816 0.68373687 0.30805833]
 [0.84777427 0.66830075 0.19575716]]

[[9 4 4]
 [5 3 5]]

[[0.05754087 0.62183965 0.00880163]
 [0.376534   2.68269705 3.57414145]]

[[ 3  7 10]
 [ 3  5  5]]

[[6 7 7]
 [4 5 6]]


In [ ]:
#numpy数组和list的访问基本一致，支持切片操作
aa1 = np.array([[1,2],[3,4],[5,6]])
aa1[0:2,0:1]
#0:2 表示选择行的范围，从第0行开始（包含）到第2行结束（不包含），也就是选择第0行和第1行。
#0:1 表示选择列的范围，从第0列开始（包含）到第1列结束（不包含），也就是选择第0列。

array([[1],
       [3]])

In [55]:
a6 = np.array([(1,2), (3,4), (5,6)])
# print(a6)
print(a6[:,1])

[2 4 6]


In [56]:
a7 = np.array([(1,2), (3,4), (5,6)])
# i,j = a7[0]
for i,j in a7:
    print(i,j)

1 2
3 4
5 6


In [57]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size", a.size)
print("dtype", a.dtype)

ndim: 2
shape: (3, 3)
size 9
dtype int32


In [59]:
print(10 in a)

False


In [60]:
a7 = np.arange(1,10)
print(a7)
print(a7.shape)

a7 = a7.reshape(3,3,1)  # 维度大小乘积 == 元素个数
print(a7)

print(a7.shape)  # 高维矩阵，每个维度都有含义

# 加载图像数据
# img.shape [1,3,120,120] 1个样本，3颜色特征通道，120高，120宽

[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [61]:
print(a)
a = a.T#矩阵转置
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
a = a.flatten()#拉成一维数组
print(a)

[1 4 7 2 5 8 3 6 9]


In [65]:
a8 = np.array([(1,2), (3,4), (5,6)])
a8 = a8[:,np.newaxis,:]  # [3,1,2]
a8.shape
#np.newaxis 是一个特殊的对象，用于在数组的指定位置插入一个新的维度。
print(a8)

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [76]:
a = np.ones((2,2))
b = np.array([(-1,1),(-1,1)])
print(a)
print(b)
print()
print(a+b)
print()
print(a-b)
print(a.sum())

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]
4.0


In [ ]:
#product”（乘积）
a = np.array([[1, 2], [3, 4]])
print(a.prod())

24


In [ ]:
a = np.array([5,3,1])
print("mean:",a.mean())#算术平均值
print("var:", a.var())#方差
print("std:", a.std())#标准差

mean: 3.0
var: 2.6666666666666665
std: 1.632993161855452


In [78]:
a = np.array([1.02, 3.8, 4.9])
print("argmax:", a.argmax()) # 最大值的索引
print("argmin:", a.argmin()) # 最小值的索引

print("ceil:", np.ceil(a))  # 向上取整
print("floor:", np.floor(a)) # 向下取整
print("rint:", np.rint(a))  # 四舍五入

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [79]:
a = np.array([16,31,12,28,22,31,48])
a.sort()  # 排序
a

array([12, 16, 22, 28, 31, 31, 48])

In [80]:
import torch
tensor = torch.arange(1,10, dtype=torch.float32).reshape(3, 3)

print(tensor.dtype)

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

torch.float32


tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [81]:
a9 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[4,5,6],[7,8,9]])

a9 * b9

array([[ 4, 10, 18],
       [28, 40, 54]])

In [82]:
import numpy as np

# 定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]], dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]], dtype=np.float32)
# m1 = m1.reshape(2,2)  # 矩阵1最后1个维度 == 矩阵2倒数第2个维度
# m2 = m2.reshape(2,2)

# 使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1, m2)

# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使用 np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使用 @ 运算符得到的矩阵乘法结果:")
print(result_at)

# 创建一个全零矩阵，用于存储手动推演的结果
# 结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)

# 外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
            # 将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")

print("手动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使用 np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使用 @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果:
[[19. 22.]
 [43. 50.]]


In [83]:
np.save('result.npy',manual_result)

In [84]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [85]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [86]:
a = np.array([(1,2), (2,2), (3,3), (4,4)])  # shape(4,2)
b = np.array([-1,1])  # shape(2)-> shape(1,2) -> shape(4,2)  [[-1,1],[-1,1],[-1,1],[-1,1]]
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])

In [87]:
data = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
data

tensor([[1., 2.],
        [3., 4.]])

In [88]:
np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [89]:
# 通过已知张量维度，创建新张量
data3 = torch.rand_like(data2, dtype=torch.float)
data3

tensor([[0.8173, 0.4312],
        [0.8604, 0.9843]])

In [90]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2857, 0.9891, 0.1805],
        [0.3574, 0.5032, 0.1546]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [91]:
# 基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # torch.Size([5,3])

# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1,end=10,steps=21))

torch.Size([5, 3])
tensor([[0.9111, 0.0109, 0.5932],
        [0.2445, 0.4080, 0.2126],
        [0.9091, 0.4911, 0.4362],
        [0.9318, 0.0077, 0.4371],
        [0.5757, 0.9926, 0.3548]])
tensor([[-1.1193,  1.1064,  1.3843],
        [-1.1291, -1.0001, -1.0651],
        [ 0.4632, -1.2397,  0.0511],
        [ 0.2052,  0.5703, -0.3827],
        [ 0.2986,  0.3237, -1.5686]])
tensor([[ 0.0877, -0.4179, -1.6081],
        [ 0.2308,  0.1075, -0.3540],
        [ 1.5501, -1.3986, -2.2311],
        [ 0.9779, -1.2297, -0.4834],
        [-0.7580, -0.8289, -1.7385]])
tensor([ 1.0000,  1.4500,  1.9000,  2.3500,  2.8000,  3.2500,  3.7000,  4.1500,
         4.6000,  5.0500,  5.5000,  5.9500,  6.4000,  6.8500,  7.3000,  7.7500,
         8.2000,  8.6500,  9.1000,  9.5500, 10.0000])


In [93]:
tensor = torch.rand(3,4)

print(f"Shape of tensor:\n {tensor.shape}\n")
print(f"Datatype of tensor:\n {tensor.dtype}\n")
print(f"Device tensor is stored on:\n {tensor.device}\n")

Shape of tensor:
 torch.Size([3, 4])

Datatype of tensor:
 torch.float32

Device tensor is stored on:
 cpu



In [94]:
# 检查pytorch是否支持GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)

print(tensor)
print(tensor.device)

tensor([[0.7262, 0.1205, 0.6991, 0.0571],
        [0.5102, 0.0528, 0.9373, 0.5132],
        [0.5879, 0.9001, 0.2753, 0.0796]])
cpu


In [95]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [96]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1 * 3)
print(t1.shape)

tensor([[3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.],
        [3., 0., 3., 3., 3., 0., 3., 3., 3., 0., 3., 3.]])
torch.Size([4, 12])


In [97]:

# 计算两个张量之间矩阵乘法的几种方式。 y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# print(y1)
# print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
# print(y3)


# 计算张量逐元素相乘的几种方法。 z1, z2, z3 最后的值是一样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [98]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [99]:
np_arr = z1.numpy()
np_arr

array([[1., 0., 1., 1.],
       [1., 0., 1., 1.],
       [1., 0., 1., 1.],
       [1., 0., 1., 1.]], dtype=float32)