In [29]:
import numpy as np


In [30]:
# 创建ndarray数组

print(np.array([1, 2, 3, 4.4, 5], np.int16))
print('\n', np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]]))
print('\n', np.zeros([2, 3]))
print('\n', np.ones([2, 3]))
print('\n', np.eye(3, 4))
print('\n', np.arange(1, 12, 3))
print('\n', np.random.random())
print('\n', np.random.random(2))
print('\n', np.random.random([2, 3]))
print('\n', np.random.normal(0, 1, [2, 3]))


[1 2 3 4 5]

 [[1 4 7]
 [2 5 8]
 [3 6 9]]

 [[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

 [ 1  4  7 10]

 0.9809741568276885

 [0.32465292 0.39316896]

 [[0.10881624 0.85799109 0.11446372]
 [0.69125383 0.21020667 0.51372312]]

 [[ 0.50110976 -0.020461   -0.13460236]
 [-0.05963704  1.23688717 -0.20441786]]


In [31]:
arr = np.random.randint(3, 6, (4, 3))
arr


array([[3, 4, 5],
       [3, 3, 5],
       [5, 3, 3],
       [4, 4, 5]])

In [32]:
arr[:, :2]


array([[3, 4],
       [3, 3],
       [5, 3],
       [4, 4]])

In [33]:
for i, j, k in arr:
    print(i, j, k)


3 4 5
3 3 5
5 3 3
4 4 5


In [34]:
arr.ndim


2

In [35]:
arr.size


12

In [36]:
arr.shape


(4, 3)

In [37]:
arr.dtype


dtype('int32')

In [38]:
3 in arr


True

In [39]:
6 in arr


False

In [40]:
arr.reshape((3, 2, 2))


array([[[3, 4],
        [5, 3]],

       [[3, 5],
        [5, 3]],

       [[3, 4],
        [4, 5]]])

In [41]:
arr[:2, np.newaxis]


array([[[3, 4, 5]],

       [[3, 3, 5]]])

In [42]:
arr.T


array([[3, 3, 5, 4],
       [4, 3, 3, 4],
       [5, 5, 3, 5]])

In [43]:
arr.flatten() - 1.2


array([1.8, 2.8, 3.8, 1.8, 1.8, 3.8, 3.8, 1.8, 1.8, 2.8, 2.8, 3.8])

In [44]:
arr - np.array([1, 5, 10])


array([[ 2, -1, -5],
       [ 2, -2, -5],
       [ 4, -2, -7],
       [ 3, -1, -5]])

In [45]:
[arr.sum(), arr.prod(), arr.mean(), arr.var(), arr.std()]


[47, 9720000, 3.9166666666666665, 0.7430555555555555, 0.8620067027323833]

In [46]:
[arr, arr.argmax(), arr.argmin()]


[array([[3, 4, 5],
        [3, 3, 5],
        [5, 3, 3],
        [4, 4, 5]]),
 2,
 0]

In [47]:
floatArr = np.random.random((2, 3)) * 30
[floatArr, floatArr.argmax(), floatArr.argmin(), np.ceil(floatArr),
 np.floor(floatArr), np.rint(floatArr)]


[array([[ 9.15114173, 12.0475931 , 25.30076343],
        [23.26280323, 25.1166377 ,  7.79483385]]),
 2,
 5,
 array([[10., 13., 26.],
        [24., 26.,  8.]]),
 array([[ 9., 12., 25.],
        [23., 25.,  7.]]),
 array([[ 9., 12., 25.],
        [23., 25.,  8.]])]

In [48]:
floatArr.sort()
floatArr


array([[ 9.15114173, 12.0475931 , 25.30076343],
       [ 7.79483385, 23.26280323, 25.1166377 ]])

In [49]:
import torch


In [50]:
tensor = torch.arange(2, 20, 2.5, dtype=torch.int)
tensor


tensor([ 2,  4,  6,  8, 10, 12, 14, 16], dtype=torch.int32)

In [51]:
t1 = tensor.reshape((4, 2))
t1


tensor([[ 2,  4],
        [ 6,  8],
        [10, 12],
        [14, 16]], dtype=torch.int32)

In [52]:
t1 @ t1.T


tensor([[ 20,  44,  68,  92],
        [ 44, 100, 156, 212],
        [ 68, 156, 244, 332],
        [ 92, 212, 332, 452]], dtype=torch.int32)

In [53]:
t1.T @ t1


tensor([[336, 400],
        [400, 480]], dtype=torch.int32)

In [54]:
t1.matmul(t1.T)


tensor([[ 20,  44,  68,  92],
        [ 44, 100, 156, 212],
        [ 68, 156, 244, 332],
        [ 92, 212, 332, 452]], dtype=torch.int32)

In [55]:
torch.rand_like(torch.tensor([[1, 2], [3, 4]], dtype=torch.float16))


tensor([[0.2148, 0.9531],
        [0.0181, 0.0122]], dtype=torch.float16)

In [56]:
t2 = torch.arange(1, 5, 1, dtype=torch.int).reshape((2, 2))
print(t2)
print(torch.matmul(t1.T, t1, out=t2))
t2


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[336, 400],
        [400, 480]], dtype=torch.int32)


tensor([[336, 400],
        [400, 480]], dtype=torch.int32)

In [63]:
m1 = np.arange(1, 5).reshape([2, 2])
m2 = np.arange(5, 9).reshape([2, 2])
[m1, m2, m1 @ m2, m1 * m2, m1 - m2, m2 + m2, m1 + m2.T]


[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[19, 22],
        [43, 50]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[10, 12],
        [14, 16]]),
 array([[ 6,  9],
        [ 9, 12]])]

In [66]:
m1 - np.array([1, 2])


array([[0, 0],
       [2, 2]])

In [74]:
np.save('m1', m1)
np.load('./m1.npy')


array([[1, 2],
       [3, 4]])