In [1]:
import torch
data = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
data


tensor([[1., 2.],
        [3., 4.]])

In [2]:
import numpy as np

np_array = np.array([[1, 2], [3, 4]])
data2 = torch.from_numpy(np_array)
data2


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [3]:
data3 = torch.rand_like(data)
data3


tensor([[0.8219, 0.7038],
        [0.1371, 0.2305]])

In [4]:
[torch.rand([2, 3]), torch.zeros([2, 3]), torch.ones(
    [2, 3]), torch.eye(3), torch.empty([2, 3])]


[tensor([[0.0583, 0.6285, 0.5362],
         [0.4770, 0.1011, 0.8299]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]])]

In [5]:
# 均匀分布
print(torch.rand(5, 3))
# 标准正态分布
print(torch.randn(5, 3))
# 离散正态分布
print(torch.normal(mean=.0, std=1.0, size=(5, 3)))
# 线性间隔向量(返回一个1维张量，包含在区间start和end上均匀间隔的steps个点)
print(torch.linspace(start=1, end=10, steps=22))


tensor([[0.0874, 0.4470, 0.0483],
        [0.3529, 0.3378, 0.7295],
        [0.5969, 0.2437, 0.7842],
        [0.4859, 0.4159, 0.5602],
        [0.1854, 0.2595, 0.0402]])
tensor([[-1.2263, -2.5988,  0.3338],
        [ 0.4639, -0.7412,  0.3622],
        [-3.1784, -0.9163,  0.9026],
        [ 0.0381,  0.7960, -1.0966],
        [-0.1233, -0.4018,  1.0412]])
tensor([[ 0.3863,  0.9301,  0.8087],
        [-1.6336,  0.6479, -1.1664],
        [ 1.8635, -0.0471, -0.2111],
        [ 0.6194, -0.1278,  1.9268],
        [-0.3114,  0.9337,  0.3022]])
tensor([ 1.0000,  1.4286,  1.8571,  2.2857,  2.7143,  3.1429,  3.5714,  4.0000,
         4.4286,  4.8571,  5.2857,  5.7143,  6.1429,  6.5714,  7.0000,  7.4286,
         7.8571,  8.2857,  8.7143,  9.1429,  9.5714, 10.0000])


In [6]:
torch.cuda.is_available()


False

In [7]:
torch.cat([torch.eye(3), torch.eye(3)])


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [8]:
torch.stack([torch.eye(3), torch.eye(3)])


tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]],

        [[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])

In [9]:
torch.stack([torch.eye(3), torch.eye(3)]).std()


tensor(0.4851)

In [1]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10, requires_grad=True)  # requires_grad=True 表示我们要对 A 求导
b = torch.randn(10, requires_grad=True)
c = torch.randn(1, requires_grad=True)
x = torch.randn(10, requires_grad=True)


# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c

# 生成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)


C:\Users\admin\AppData\Local\Temp\ipykernel_15568\451713609.py:12: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression.png'