In [108]:
import numpy as np

In [109]:
a = [1,2,3]
a

[1, 2, 3]

In [ ]:
# 创建ndarry对象，指定数据类型为float32
arr = np.array([1,2,3], float)
arr

array([1, 2, 3])

In [111]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]],dtype=np.float32)
a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [112]:
a = np.zeros([ 2, 3]) # 2 x 3
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [113]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [114]:
# 创建等差数列
a2 = np.arange(1,5,0.5,dtype=np.float16)    
a2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [115]:
# 创建单位矩阵（对角矩阵）
a3 = np.eye(4)
a3  # 可以应用在one-hot 编码

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [116]:
# 随机数
a4 = np.random.random(3)  # 模型运算参数初始化
a4 # 生成一个包含 3 个随机浮点数的一维数组，这些随机数的取值范围在 0（包含）到 1（不包含）之间。

array([0.74124122, 0.22011711, 0.50663042])

In [117]:
# 正态分布的随机数组 
# 中间值（均值μ）、标准差σ、生成的随机数的数量
# normal 正态
a5 = np.random.normal(0, 2, 5)
a5

array([-1.70885956,  0.03276065,  0.04799806, -0.9767416 ,  1.1985053 ])

数组访问


In [118]:
a6 = np.array([(1, 2, 3, 4),(5, 6, 7, 8)])
print(a6)
print()
print(a6[:,1])  # 选取所有行的第 2 列

[[1 2 3 4]
 [5 6 7 8]]

[2 6]


In [119]:
for i in a6: print(i)
print()
for i in a5: print(i)

[1 2 3 4]
[5 6 7 8]

-1.708859562022663
0.03276064727355498
0.04799805923875285
-0.9767416035070933
1.198505297169487


In [120]:
a7 = np.array([(1, 2, 3),(4,5,6),(7,8,9)])
print(a7[0])  # 第一行
i,j,k = a7[0] # 用逗号分隔，可以同时赋值给多个变量
print(i,j,k)

[1 2 3]
1 2 3


ndarray.ndim：数组的维度（数组轴个数），秩  
ndarray.shape：数组在每个维度上的大小，例如2行3列  
ndarray.size：数组元素的总个数，相当于.shape中所有元素的乘积   
ndarray.dtype：数组中元素的类型

In [121]:
print(a7.ndim)
print(a7.shape)
print(a7.size)
print(a7.dtype)

2
(3, 3)
9
int32


In [122]:
a7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

数组的基本操作

In [123]:
print(3 in a7) # 检测是否存在某个元素
print(10 in a7)
print(10 not in a7)
print((1,2,3) in a7)

True
False
True
True


In [124]:
print((1,2) in a7)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

np.zeros([2, 3, 4])：这里传递给 np.zeros 函数的是一个列表 [2, 3, 4]。列表是 Python 中一种可变的序列类型，可以随时修改其元素。  
np.zeros((2, 3, 4))：这里传递的是一个元组 (2, 3, 4)。元组是 Python 中一种不可变的序列类型，一旦创建，其元素不能被修改。  
 
最佳实践：在实际使用中，推荐使用元组 (2, 3, 4) 来指定数组形状，因为数组的形状通常是固定不变的，而元组的不可变性更符合这一特性。此外，在 NumPy 的文档和示例中，也更常见使用元组来表示数组形状。

In [ ]:
# a8 = np.zeros([2,3,4])
a8 = np.zeros((2,3,4))
a8 # 以上2种写法结果都一样

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
a8.reshape(24)  # 修改形状, 从 2*3*4 -> 1*24

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 创建一个包含 0 到 11 共 12 个整数的一维 NumPy 数组
# 然后将其重塑为一个形状为 (3, 4) 的二维数组。
a9 = np.arange(12).reshape(3, 4)  
a9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 加载图像数据
# img.shape(1,3,120,120) 1个样本，3个颜色通道（三原色），120x120（高x宽）的图像

In [ ]:
# 转置 transpose 行变列，列变行
a10 = np.array(([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 8,  9, 10, 11]]))
a10.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
print(a10.T)
a10.transpose()
# print(a10)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a11 = a10.flatten # 将多维数组转换为一维数组
a11()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a10.reshape(12) # 3x4 -> 12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
print(a10) 
a10.shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(3, 4)

增加维度

In [ ]:
a12 = a10[np.newaxis,:,:]
print(a12)
a12.shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


(1, 3, 4)

In [ ]:
a12 = a10[:,np.newaxis,:]
print(a12)
a12.shape

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


(3, 1, 4)

In [ ]:
a12 = a10[:,:,np.newaxis]
print(a12)
a12.shape

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


(3, 4, 1)

数学操作

In [137]:
a = np.ones((2, 2))
b = np.array([(-1,1),(-1,1)])
print(a)
print()
print(b)

[[1. 1.]
 [1. 1.]]

[[-1  1]
 [-1  1]]


In [127]:
a+b

array([[0., 2.],
       [0., 2.]])

In [128]:
a-b

array([[2., 0.],
       [2., 0.]])

In [129]:
a*b

array([[-1.,  1.],
       [-1.,  1.]])

In [130]:
a/b

array([[-1.,  1.],
       [-1.,  1.]])

In [135]:
a.sum  # <function ndarray.sum>
a.sum()

4.0

In [146]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print()
print(b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [ ]:
a*b # 逐元素相乘

array([[ 5, 12],
       [21, 32]])

In [148]:
a/b 

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a.prod() # 乘积

24

数据组织结构形式：数组、矩阵  
维度

平均数、方差、标准差、最大值、最小值

In [157]:
arr1 = np.array([[1, 2], [3, 4]])
print(np.mean(arr1)) # 平均数
print(np.var(arr1)) # 方差
print(np.std(arr1)) # 标准差
print(np.max(arr1)) # 最大值
print(np.min(arr1)) # 最小值

2.5
1.25
1.118033988749895
4
1


In [162]:
# 最大值的索引、最小值的索引
print(arr1.argmax())
print(arr1.argmin())

3
0


In [178]:
# 平均数、方差、标准差、最大值、最小值
arr = np.array([[1.1, 2.1, 3, 4.9]])
print(np.mean(arr)) # 平均数
print(arr.mean()) # 平均数

2.7750000000000004
2.7750000000000004


In [179]:
# print(arr.ceil()) 
print(np.ceil(arr))  # 向上取整,进一位
print(np.floor(arr))  # 向下取整
print(np.round(arr))  # 四舍五入

[[2. 3. 3. 5.]]
[[1. 2. 3. 4.]]
[[1. 2. 3. 5.]]


升序排序 sort 

In [206]:
arr2 = np.random.randint(0,10,(2, 2, 4)) # 生成一个形状为 (2, 2, 4) 的随机整数数组，范围是 0 到 10（不包含 10）
print(arr2)
arr2.sort() # 调用sort()方法并不直接返回排序后的数组，而是返回一个对象，该对象有一个属性是排序后的数组。
arr2

[[[4 9 5 1]
  [8 8 9 3]]

 [[1 9 9 8]
  [4 8 2 6]]]


array([[[1, 4, 5, 9],
        [3, 8, 8, 9]],

       [[1, 8, 9, 9],
        [2, 4, 6, 8]]])

In [195]:
print(arr2.sort())
arr = arr2.sort()
print(arr)


None
None


In [205]:
arr3 = np.random.randint(0,10,size=(6))
print(arr3)
arr3.sort() # 调用sort()方法并不直接返回排序后的数组，而是返回一个对象，该对象有一个属性是排序后的数组。
arr3

[2 8 4 3 2 4]


array([2, 2, 3, 4, 4, 8])

线性代数 linear algebra   
numpy.linalg  
矩阵 matrix



In [220]:
# 维度相同的时候，直接按位相乘
a13 = np.array([1, 2, 3])
b13 = np.array([1, 2, 3])
print(a13 * b13)
print(a13 @ b13)
print(a13.dot(b13))

[1 4 9]
14
14


In [216]:
a14 = np.array([[1, 2], [3, 4]])
b14 = np.array([[5, 6], [7, 8]])
print(a14)
print()
print(b14)
print()
print(a14*b14)
print()
print(a14.dot(b14))

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]

[[19 22]
 [43 50]]


In [218]:
# 使用np.dot()进行矩阵乘法
result_dot = np.dot(a14, b14)
result_dot

array([[19, 22],
       [43, 50]])

In [219]:
# 使用@进行矩阵乘法
result_at = a14 @ b14
result_at

array([[19, 22],
       [43, 50]])

1x5+2x7=19 1x6+2x8=22  
3x5+4x7=43 3x6+4x8=50


In [226]:
# a15 = np.random.randn(4, 2)
a15 = np.random.randint(1, 10, (4, 2))
print(a15)
print()
b15 = np.array([1,1])
a15+b15

[[9 5]
 [5 3]
 [7 2]
 [8 5]]



array([[10,  6],
       [ 6,  4],
       [ 8,  3],
       [ 9,  6]])

### NumPy ⼴播机制  
⼴播 (Broadcast) 是 numpy 对不同形状 (shape) 的数组进⾏数值计算的⽅式，对数
组的算术运算通常在相应的元素上进⾏。  
如果两个数组 a 和 b 形状相同，即满⾜
a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相
同，且各维度的⻓度相同。  

In [227]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [228]:
# 当运算中的 2 个数组的形状不同时，numpy 将⾃动触发⼴播机制
a = np.array([(1,2), (2,2), (3,3), (4,4)]) # shape(4,2)
b = np.array([-1,1]) # shape(2)-> shape(1,2) -> shape(4,2) [ -1,1],[-1,1],[-1,1],[-1
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])

In [229]:
# 当运算中的 2 个数组的形状不同时，numpy 将⾃动触发⼴播机制
a = np.array([(1,2), (2,2), (3,3), (4,4)]) # shape(4,2)
b = np.array([-1,1,1,1]) # shape(2)-> shape(1,2) -> shape(4,2) [ -1,1],[-1,1],[-1,1],[-1
a + b

ValueError: operands could not be broadcast together with shapes (4,2) (4,) 