In [3]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b)

[1 2 3]


In [4]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a = np.zeros((3,3), int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
a = np.arange(1, 10 ,0.5)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [7]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
a = np.random.random((3,3))
a

array([[0.17181223, 0.01893192, 0.6498578 ],
       [0.40068017, 0.84913507, 0.15919599],
       [0.92963004, 0.79686907, 0.65729149]])

In [9]:
mu,sigma = 0,0.1
a = np.random.normal(5, 10, 10)
a

array([20.93253518, 23.91110147,  0.49469949, -4.94310495,  6.1266066 ,
       11.62347526, 11.09854457, -8.51720952,  7.61052248,  8.04989037])

In [10]:
# a = np.array([[1,2],[3,4],[5,6]])
a = np.arange(1,19,1).reshape(3,2,3)
print(a)
print()
print(a[:,:2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [11]:
a = np.arange(1,7,1).reshape(2,3)
print(a)
print()
for i,j,k in a:
    print(i,j,k)

[[1 2 3]
 [4 5 6]]

1 2 3
4 5 6


In [12]:
a = np.arange(1,19,1).reshape(2,3,3)
print(a)
for i,j,k in a:
    print(i,j,k)
b = np.array([1,2,3,4])
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[1 2 3] [4 5 6] [7 8 9]
[10 11 12] [13 14 15] [16 17 18]
[1 2 3 4]


In [13]:
a = np.arange(1,10,1).reshape(3,3)
print(a)
a.reshape(9)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
a = np.zeros((2,3,4))
a


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
a.reshape(24)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [16]:
a = np.arange(1,7,1).reshape(1,2,3)
print(a,a.shape)
print(a.T,a.T.shape)

[[[1 2 3]
  [4 5 6]]] (1, 2, 3)
[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]] (3, 2, 1)


In [17]:
a = np.arange(1,7).reshape(2,3)
b = np.ones((3,3))
a@b


array([[ 6.,  6.,  6.],
       [15., 15., 15.]])

In [40]:
a = np.arange(12).reshape(3,1,4)
b = np.ones((5,4,6))
print(a)
print(np.dot(a,b))

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
[[[[ 6.  6.  6.  6.  6.  6.]
   [ 6.  6.  6.  6.  6.  6.]
   [ 6.  6.  6.  6.  6.  6.]
   [ 6.  6.  6.  6.  6.  6.]
   [ 6.  6.  6.  6.  6.  6.]]]


 [[[22. 22. 22. 22. 22. 22.]
   [22. 22. 22. 22. 22. 22.]
   [22. 22. 22. 22. 22. 22.]
   [22. 22. 22. 22. 22. 22.]
   [22. 22. 22. 22. 22. 22.]]]


 [[[38. 38. 38. 38. 38. 38.]
   [38. 38. 38. 38. 38. 38.]
   [38. 38. 38. 38. 38. 38.]
   [38. 38. 38. 38. 38. 38.]
   [38. 38. 38. 38. 38. 38.]]]]


In [19]:
a = np.arange(1,5).reshape(2,2)
b = np.ones((2,2))
print((a@b))
print(np.dot(a,b))

[[3. 3.]
 [7. 7.]]
[[3. 3.]
 [7. 7.]]


In [20]:
a = np.random.random((3,3))
print(a)
np.savetxt('a.txt',a)
b = np.loadtxt('a.txt')
b

[[0.62833197 0.59355244 0.01491377]
 [0.69769299 0.83414415 0.8668504 ]
 [0.42403274 0.26620463 0.27957723]]


array([[0.62833197, 0.59355244, 0.01491377],
       [0.69769299, 0.83414415, 0.8668504 ],
       [0.42403274, 0.26620463, 0.27957723]])

In [42]:
a = np.ones((1,4,3,3,4))
b = np.ones((1,3,4,6))
# print(a)
print((a@b).shape)
print((a@b))

(1, 4, 3, 3, 6)
[[[[[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]]


  [[[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]]


  [[[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]]


  [[[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]]]]
