In [2]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b)

[1 2 3]


In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a = np.zeros((3,3), int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
a = np.arange(1, 10 ,0.5)
a

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [6]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
a = np.random.random((3,3))
a

array([[0.24857252, 0.88681101, 0.74287208],
       [0.52573032, 0.01292301, 0.31853695],
       [0.97841343, 0.28188361, 0.97340787]])

In [8]:
mu,sigma = 0,0.1
a = np.random.normal(5, 10, 10)
a

array([ 4.74713309,  7.96178415, 12.40723437, 12.97176329, 10.69191901,
       -2.2922589 , -0.02290621, -2.73099943, 14.3553996 ,  8.56493927])

In [9]:
# a = np.array([[1,2],[3,4],[5,6]])
a = np.arange(1,19,1).reshape(3,2,3)
print(a)
print()
print(a[:,:2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [10]:
a = np.arange(1,7,1).reshape(2,3)
print(a)
print()
for i,j,k in a:
    print(i,j,k)

[[1 2 3]
 [4 5 6]]

1 2 3
4 5 6


In [11]:
a = np.arange(1,19,1).reshape(2,3,3)
print(a)
for i,j,k in a:
    print(i,j,k)
b = np.array([1,2,3,4])
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[1 2 3] [4 5 6] [7 8 9]
[10 11 12] [13 14 15] [16 17 18]
[1 2 3 4]


In [12]:
a = np.arange(1,10,1).reshape(3,3)
print(a)
a.reshape(9)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
a = np.zeros((2,3,4))
a


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
a.reshape(24)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [15]:
a = np.arange(1,7,1).reshape(1,2,3)
print(a,a.shape)
print(a.T,a.T.shape)

[[[1 2 3]
  [4 5 6]]] (1, 2, 3)
[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]] (3, 2, 1)


In [16]:
a = np.arange(1,7).reshape(2,3)
b = np.ones((3,3))
a@b


array([[ 6.,  6.,  6.],
       [15., 15., 15.]])

In [ ]:
a = np.arange(48).reshape(3,1,4,4)
b = np.ones((3,4,6))
# print(a)
#高维dot运算，第一个矩阵-1维==第二个矩阵-2维
#用第一个矩阵的最后一维和第二个矩阵的倒数第二维做点积运算，其他维度做外积
#运算后维度为第一个矩阵除了最后一维，第二个矩阵除了倒数第二维
print(np.dot(a,b).shape) 
#高维@运算，最后两维做点积运算，其他维度广播
#运算后的维度为，其他维度广播后的维度，加上后两位点成后的维度
print((a@b).shape) 

(3, 1, 4, 3, 6)
(3, 3, 4, 6)


In [ ]:
a = np.arange(1,5).reshape(2,2)
b = np.ones((2,2))
print((a@b))
print(np.dot(a,b))

[[3. 3.]
 [7. 7.]]
[[3. 3.]
 [7. 7.]]


In [ ]:
a = np.random.random((3,3))
print(a)
np.savetxt('a.txt',a)
b = np.loadtxt('a.txt')
b

[[0.62833197 0.59355244 0.01491377]
 [0.69769299 0.83414415 0.8668504 ]
 [0.42403274 0.26620463 0.27957723]]


array([[0.62833197, 0.59355244, 0.01491377],
       [0.69769299, 0.83414415, 0.8668504 ],
       [0.42403274, 0.26620463, 0.27957723]])

In [ ]:
a = np.ones((1,4,3,3,4))
b = np.ones((1,3,4,6))
# print(a)
print((a@b).shape)
print((a@b))

(1, 4, 3, 3, 6)
[[[[[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]]


  [[[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]]


  [[[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]]


  [[[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]

   [[4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]
    [4. 4. 4. 4. 4. 4.]]]]]
