In [1]:
import torch
import numpy as np
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [2]:
a = np.array(data)
print(a)
x_np = torch.from_numpy(a)
x_np

[[1 2]
 [3 4]]


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [3]:
b = torch.rand_like(x_np,dtype=torch.float)
b

tensor([[0.2068, 0.7682],
        [0.5820, 0.5667]])

In [4]:
a = torch.rand((2,3))
print(f"Random Tensor: \n {a} \n")

Random Tensor: 
 tensor([[0.3529, 0.7256, 0.4900],
        [0.9351, 0.5110, 0.8073]]) 



In [5]:
m = torch.ones(5,3,dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)
print(f"m:\n{m} \n n\n:{n}")
torch.normal(mean=.0,std=1.0,size=(5,3))
print(torch.arange(0,10,1))
print(torch.linspace(0,9,10,dtype=torch.int))


m:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) 
 n
:tensor([[0.4151, 0.2497, 0.5916],
        [0.8409, 0.3266, 0.7861],
        [0.3442, 0.0475, 0.1114],
        [0.0373, 0.2074, 0.1439],
        [0.3618, 0.6789, 0.5779]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [6]:
tensor = torch.ones(3,4,dtype=torch.double)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float64
cpu


In [7]:
tensor = torch.arange(60).reshape(3,4,5)
print(tensor[:,:,::])
print(tensor[1:,:3,::2])
print(torch.flip(tensor, dims=[0,1]))

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
tensor([[[20, 22, 24],
         [25, 27, 29],
         [30, 32, 34]],

        [[40, 42, 44],
         [45, 47, 49],
         [50, 52, 54]]])
tensor([[[55, 56, 57, 58, 59],
         [50, 51, 52, 53, 54],
         [45, 46, 47, 48, 49],
         [40, 41, 42, 43, 44]],

        [[35, 36, 37, 38, 39],
         [30, 31, 32, 33, 34],
         [25, 26, 27, 28, 29],
         [20, 21, 22, 23, 24]],

        [[15, 16, 17, 18, 19],
         [10, 11, 12, 13, 14],
         [ 5,  6,  7,  8,  9],
         [ 0,  1,  2,  3,  4]]])


In [8]:
torch.cuda.is_available()

False

In [9]:
tensor = torch.ones(4,4)
print(tensor[0])
print(tensor[:,0])
print(tensor[:,-1])
tensor[:,1] = 0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
#dim参数，指定在哪个维度上进行拼接，可倒数
tensor1 = torch.ones(4,4)
t1 = torch.cat([tensor1,tensor1],dim=0)
print(t1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
#高维张量的cat 操作，需要保证其他维度的大小一致
tensor1 = torch.ones(4,4,4)
t1 = torch.cat([tensor1,tensor1],dim=0)
print(t1.shape)
tensor2 = torch.arange(32).reshape(4,2,4)
print(tensor2)
t1 = torch.cat([tensor1,tensor2],dim=1)
print(t1)

torch.Size([8, 4, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31]]])
tensor([[[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]],

        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]],

        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.]]])


In [12]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)

#out参数，指定输出的张量
y3 = torch.rand_like(tensor)
print(torch.matmul(tensor,tensor.T))

#torch.dot()只能计算一维张量的点积
tensor1 = torch.ones(4)
print(torch.dot(tensor1,tensor1.T))

z1 = tensor*tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor(4.)
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


C:\Users\bucci\AppData\Local\Temp\ipykernel_5884\3175096295.py:12: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  print(torch.dot(tensor1,tensor1.T))


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [13]:
agg = torch.ones_like(tensor,dtype=int).sum()
print(agg)
agg_item = agg.item()
print(agg_item,type(agg_item))

tensor(16)
16 <class 'int'>


In [14]:
tensor = torch.ones(4,4)
tensor.add(5)
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [15]:
#numpy和tensor之间的转换，共享内存，修改一个会影响另一个
t = torch.ones(5)
print(t)
n = t.numpy()
n +=1
print(t)

n = np.ones(5)
t = torch.from_numpy(n)
np.add(n,1,out=n)
print(t)

tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [56]:
from torchviz import make_dot
A = torch.randn((10,2),requires_grad=True)
b = torch.randn((2,3),requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn((3,2),requires_grad=True)
#x^T@A + b@x +c

result1 = torch.matmul(A,x.T)[:2,:2] + b@x + c
result2 = torch.matmul(A,x.T)[:3,:3] + x@b + c
print(result1)
print(result2)

dot = make_dot(result1,params={"A":A,"b":b,"c":c,"x":x})
dot2 = make_dot(result2,params={"A":A,"b":b,"c":c,"x":x})
dot.render('dot')
dot2.render('dot2')


tensor([[ 0.2795, -0.4586],
        [-1.4240, -1.3557]], grad_fn=<AddBackward0>)
tensor([[-0.0243, -1.3823, -0.5615],
        [-0.9631, -1.0480, -0.5816],
        [-0.5453, -0.9644, -0.7422]], grad_fn=<AddBackward0>)


'dot2.pdf'

In [33]:
from torchviz import make_dot
A = torch.randn((2,3),requires_grad=True)
B = torch.randn((3,2),requires_grad=True)

#x^T@A + b@x +c
result1 = A@B
result2 = B@A
print(result1)
print(result2)
dot = make_dot(result1,params={"A":A,"B":B})
dot2 = make_dot(result2,params={"A":A,"B":B})
dot.render('NEWdot')
dot2.render('NEWdot2')

tensor([[ 0.3297, -0.1304],
        [ 0.8220,  0.3325]], grad_fn=<MmBackward0>)
tensor([[ 0.1074, -0.1422,  0.1918],
        [ 0.5848,  0.2608, -0.2118],
        [-0.3034, -0.2870,  0.2940]], grad_fn=<MmBackward0>)


'NEWdot2.pdf'