In [75]:
import torch
import numpy as np
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [76]:
a = np.array(data)
print(a)
x_np = torch.from_numpy(a)
x_np

[[1 2]
 [3 4]]


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [77]:
b = torch.rand_like(x_np,dtype=torch.float)
b

tensor([[0.2771, 0.1061],
        [0.7535, 0.1903]])

In [78]:
a = torch.rand((2,3))
print(f"Random Tensor: \n {a} \n")

Random Tensor: 
 tensor([[0.8173, 0.7971, 0.6594],
        [0.3679, 0.2867, 0.5153]]) 



In [79]:
m = torch.ones(5,3,dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)
print(f"m:\n{m} \n n\n:{n}")
torch.normal(mean=.0,std=1.0,size=(5,3))
print(torch.arange(0,10,1))
print(torch.linspace(0,9,10,dtype=torch.int))


m:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) 
 n
:tensor([[0.4202, 0.6564, 0.5753],
        [0.9307, 0.1062, 0.2747],
        [0.2130, 0.6418, 0.3911],
        [0.5622, 0.8458, 0.1325],
        [0.1708, 0.2764, 0.7434]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [80]:
tensor = torch.ones(3,4,dtype=torch.double)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float64
cpu


In [81]:
tensor = torch.arange(60).reshape(3,4,5)
print(tensor[:,:,::])
print(tensor[1:,:3,::2])
print(torch.flip(tensor, dims=[0,1]))

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
tensor([[[20, 22, 24],
         [25, 27, 29],
         [30, 32, 34]],

        [[40, 42, 44],
         [45, 47, 49],
         [50, 52, 54]]])
tensor([[[55, 56, 57, 58, 59],
         [50, 51, 52, 53, 54],
         [45, 46, 47, 48, 49],
         [40, 41, 42, 43, 44]],

        [[35, 36, 37, 38, 39],
         [30, 31, 32, 33, 34],
         [25, 26, 27, 28, 29],
         [20, 21, 22, 23, 24]],

        [[15, 16, 17, 18, 19],
         [10, 11, 12, 13, 14],
         [ 5,  6,  7,  8,  9],
         [ 0,  1,  2,  3,  4]]])


In [82]:
torch.cuda.is_available()

False

In [83]:
tensor = torch.ones(4,4)
print(tensor[0])
print(tensor[:,0])
print(tensor[:,-1])
tensor[:,1] = 0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [84]:
#dim参数，指定在哪个维度上进行拼接，可倒数
tensor1 = torch.ones(4,4)
t1 = torch.cat([tensor1,tensor1],dim=0)
print(t1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [85]:
#高维张量的cat 操作，需要保证其他维度的大小一致
tensor1 = torch.ones(4,4,4)
t1 = torch.cat([tensor1,tensor1],dim=0)
print(t1.shape)
tensor2 = torch.arange(32).reshape(4,2,4)
print(tensor2)
t1 = torch.cat([tensor1,tensor2],dim=1)
print(t1)

torch.Size([8, 4, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31]]])
tensor([[[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]],

        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]],

        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.]]])


In [86]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)

#out参数，指定输出的张量
y3 = torch.rand_like(tensor)
print(torch.matmul(tensor,tensor.T))

#torch.dot()只能计算一维张量的点积
tensor1 = torch.ones(4)
print(torch.dot(tensor1,tensor1.T))

z1 = tensor*tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor(4.)
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [87]:
agg = torch.ones_like(tensor,dtype=int).sum()
print(agg)
agg_item = agg.item()
print(agg_item,type(agg_item))

tensor(16)
16 <class 'int'>


In [88]:
tensor = torch.ones(4,4)
tensor.add(5)
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


In [89]:
#numpy和tensor之间的转换，共享内存，修改一个会影响另一个
t = torch.ones(5)
print(t)
n = t.numpy()
n +=1
print(t)

n = np.ones(5)
t = torch.from_numpy(n)
np.add(n,1,out=n)
print(t)

tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [90]:
from torchviz import make_dot
A = torch.randn((10,2),requires_grad=True)
b = torch.randn((2,3),requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn((3,2),requires_grad=True)
#x^T@A + b@x +c

result1 = torch.matmul(A,x.T)[:2,:2] + b@x + c
result2 = torch.matmul(A,x.T)[:3,:3] + x@b + c
print(result1)
print(result2)

dot = make_dot(result1,params={"A":A,"b":b,"c":c,"x":x})
dot2 = make_dot(result2,params={"A":A,"b":b,"c":c,"x":x})
dot.render('dot')
dot2.render('dot2')


tensor([[-3.6511,  1.9345],
        [ 1.0756,  1.8011]], grad_fn=<AddBackward0>)
tensor([[-0.9655, -0.2247, -0.9404],
        [ 1.0092,  0.1915, -1.0977],
        [-2.7795,  0.5020,  1.1176]], grad_fn=<AddBackward0>)


'dot2.pdf'

In [91]:
from torchviz import make_dot
A = torch.randn((2,3),requires_grad=True)
B = torch.randn((3,2),requires_grad=True)

#x^T@A + b@x +c
result1 = A@B
result2 = B@A
print(result1)
print(result2)
dot = make_dot(result1,params={"A":A,"B":B})
dot2 = make_dot(result2,params={"A":A,"B":B})
dot.render('NEWdot')
dot2.render('NEWdot2')

tensor([[-1.6144,  0.5596],
        [ 4.0733, -0.0240]], grad_fn=<MmBackward0>)
tensor([[ 0.4866, -1.0626,  0.5772],
        [-1.7353, -1.9119, -1.2541],
        [-0.2303,  0.0773, -0.2131]], grad_fn=<MmBackward0>)


'NEWdot2.pdf'