In [3]:
import numpy as np

In [ ]:
a = [1,2,3,4] 
print(a)
b = np.array(a)
b

[1, 2, 3, 4]


array([1, 2, 3, 4])

In [ ]:
#创建数组，指定数据类型
a = np.array([1,2,3],float) 
a

array([1., 2., 3.])

In [ ]:
#创建多维数组
a2 = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)],dtype=float)
print(a2)
a2.shape  

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


(4, 3)

In [ ]:
#numpy创建特殊数组
#创建两个2行3列,全为0的数组
a3 = np.zeros((2,2,3),dtype=int)
a3

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
#创建全为1的数组
a4 = np.ones((3,3))
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
#创建等差数列，
a5 = np.arange(1,10,0.6)
a5

array([1. , 1.6, 2.2, 2.8, 3.4, 4. , 4.6, 5.2, 5.8, 6.4, 7. , 7.6, 8.2,
       8.8, 9.4])

In [ ]:
#创建对角线1的数组，降维
a6 = np.eye(4)
print(a6)
a6.reshape(16)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [ ]:
#[0,1))之间平均分布的随机数组,指定长度
np.random.random(5)


array([0.15076143, 0.27575826, 0.17528239, 0.07035452, 0.77857711])

In [78]:
#生成指定长度，符合正态分布的随机数组
mu,sigma =1,0.2
np.random.normal(mu,sigma,5)

array([1.00185476, 0.92059762, 0.9050447 , 0.75072169, 0.999957  ])

In [113]:
#numpy数组的访问,支持切片每个维度
a7 = np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
print(a7[0])#输出第0个
print()
print(a7[1:])#输出从第1到最后（包含1）
print()
print(a7[:2]) #输出第2到开始（不包含2）
print()
print(a7[1: , 1:])  #输出第1到最后,第1到最后
print()
a7[1][2]#输出第1个，第2个值

[1 2 3]

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 2 3]
 [4 5 6]]

[[ 5  6]
 [ 8  9]
 [11 12]]



6

In [4]:
#numpy数组遍历
a8 = np.array([1,2,3])
for i in a8:
    print(i)

1
2
3


In [ ]:
#多维数组遍历
a9 = np.array([(1,2,3),(4,5,6),(7,8,9)])
for i,o,p in a9:
    print(i*o*p)

6
120
504


In [16]:
#数组常用属性

b1 = np.array([(1,2,3),(4,5,6),(7,8,9)],dtype=float)
#数组的维度（数组轴的个数），等于秩
print('ndim',b1.ndim)
# 数组的⼤⼩。为⼀个表⽰数组在每个维度上⼤⼩的整数元组。例如⼆维数组中，表⽰数组的’ ⾏数’ 和’ 列数”
print('shape',b1.shape)
#数组元素的总个数，等于 shape 属性中元组元素的乘积
print('size',b1.size)
#表⽰数组中元素类型的对象
print('dtype',b1.dtype)

ndim 2
shape (3, 3)
size 9
dtype float64


In [ ]:
#numpy数组的基本操作
#检测数值是否在数组中
b2 = np.array([(1,2,3),(4,5,6)])
print(2 in b2)
print(9 in b2)

True
False


In [37]:
#数组的重排列，例如将⼀个 3 维数组转变为 1 维（元素数⼀定要保持不变）
b3 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b3)
b3.reshape(9)
print()
print(b3.reshape(9))
print()
b3.transpose()#转置
print(b3.transpose())
b3.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
#把多维数组转换为⼀维数组，注意每个元组的⻓度是相同的
b4 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b4)
b4.flatten()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#增加维度
b5 = np.array([2,3,4,5])
b5.shape

(4,)

In [46]:
b5 = b5[:,np.newaxis]
b5
b5.shape

(4, 1, 1)

In [65]:
#NumPy 数组的数学操作
#加减乘除
q=np.ones([2,2])
w=np.array([(-1,1),(-1,1)])
print(q)
print(w)
print()
q+w
print(q+w)
print()
q-w
print(q-w)
print()
q*w
print(q*w)
print()
q/w
print(q/w)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]

[[-1.  1.]
 [-1.  1.]]

[[-1.  1.]
 [-1.  1.]]


In [70]:
#求和、求积
s1 = np.array([1,2,3,4])
print(s1.sum())

s1.prod()


10


24

In [75]:
#平均数，⽅差，标准差，最⼤值，最⼩值
s2 = np.array([9,6,5,1])
print("mean:",s2.mean())
print("var:", s2.var())
print("std:", s2.std())
print("max:", s2.max())
print("min:", s2.min())

mean: 5.25
var: 8.1875
std: 2.8613807855648994
max: 9
min: 1


In [79]:
#最⼤与最⼩值对应的索引值：argmax,argmin:
#取元素值上限，下限，四舍五⼊：ceil, floor, rint
s3 = np.array([2.4, 4.8, 9.9])
print("argmax:", s3.argmax())
print("argmin:", s3.argmin())
print("ceil:", np.ceil(s3))
print("floor:", np.floor(s3))
print("rint:", np.rint(s3))

argmax: 2
argmin: 0
ceil: [ 3.  5. 10.]
floor: [2. 4. 9.]
rint: [ 2.  5. 10.]


In [106]:
#升序
s4 = np.array([14,10,17,1.3,11,15,13.2])
s4.sort()
s4

array([ 1.3, 10. , 11. , 13.2, 14. , 15. , 17. ])

In [101]:
import numpy as np
# 定义两个简单的矩阵
m1 = np.array([(1, 2), (3, 4)], dtype=np.float32)
m2 = np.array([(5, 6), (7, 8)], dtype=np.float32)
              
# 使⽤ np.dot 进⾏矩阵乘法
result_dot = np.dot(m1, m2)

# 使⽤ @ 运算符进⾏矩阵乘法
result_at = m1 @ m2

print("矩阵 1:")
print(m1)
print("矩阵 2:")
print(m2)
print("使⽤ np.dot 得到的矩阵乘法结果:")
print(result_dot)
print("使⽤ @ 运算符得到的矩阵乘法结果:")
print(result_at)
print("使⽤ @ 运算符得到的矩阵乘法结果:")
print(result_at)
# 创建⼀个全零矩阵，⽤于存储⼿动推演的结果
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
# 外层循环：遍历 matrix1 的每⼀⾏
# i 表⽰结果矩阵的⾏索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每⼀列
    # j 表⽰结果矩阵的列索引
    for j in range(m2.shape[1]):
        # 初始化当前位置的结果为 0
        manual_result[i, j] = 0
        # 内层循环：计算 matrix1 的第 i ⾏与 matrix2 的第 j 列对应元素的乘积之和
        # k 表⽰参与乘法运算的元素索引
        for k in range(m1.shape[1]):
            # 打印当前正在计算的元素
            print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
             # 将 matrix1 的第 i ⾏第 k 列元素与 matrix2 的第 k ⾏第 j 列元素相乘，并累
            manual_result[i, j] += m1[i, k] * m2[k, j]
        # 打印当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")
            
print("⼿动推演结果:")
print(manual_result)

矩阵 1:
[[1. 2.]
 [3. 4.]]
矩阵 2:
[[5. 6.]
 [7. 8.]]
使⽤ np.dot 得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使⽤ @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
使⽤ @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

⼿动推演结果:
[[19. 22.]
 [43. 50.]]


In [ ]:
#⽂件操作
np.save ('123.npy',manual_result)


In [108]:
np.load ('123.npy')

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [114]:
#NumPy ⼴播机制
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [ ]:
a = np.array([(1,1), (2,2), (3,3), (4,4)])
print(a.shape)
b = np.array([3,3])#4个[3,3]
print(b.shape)
a * b

(4, 2)
(2,)


array([[ 3,  3],
       [ 6,  6],
       [ 9,  9],
       [12, 12]])

In [ ]:
#pytorch 张量
import torch

data =([1,2],[3,4]) 

torch.tensor(data)

tensor([[1, 2],
        [3, 4]])

In [133]:
import numpy as np
np_array1 = np.array([(1,2,3),(4,5,6)])

data1 =torch.from_numpy(np_array1)
data1

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [141]:
#参照已知张量,创建新的
data2=torch.ones_like(data1)
print(data2)
data2=torch.zeros_like(data1)
print(data2)
data2=torch.rand_like(data1,dtype=torch.float32)#创建随机数时候指定张量类型
print(data2)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[0.9330, 0.1119, 0.6882],
        [0.4550, 0.8621, 0.3334]])


In [143]:
#使用随机值或常量值
shape = (4,5)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3475, 0.6795, 0.5560, 0.1269, 0.9067],
        [0.7205, 0.8398, 0.3070, 0.0224, 0.4944],
        [0.7118, 0.3185, 0.3829, 0.6262, 0.5962],
        [0.2032, 0.4145, 0.4234, 0.8597, 0.1075]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [149]:
# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(5,3, dtype=torch.double)#双精度
n = torch.rand_like(m, dtype=torch.float)
# 获取tensor的⼤⼩
print(m.size()) # torch.Size([5,3])
# 均匀分布
print(torch.rand(5,3))
# 标准正态分布
print(torch.randn(5,3))
# 离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
# 线性间隔向量(返回⼀个1维张量，包含在区间start和end上均匀间隔的steps个点
print(torch.linspace(start=1,end=5,steps=12))

torch.Size([5, 3])
tensor([[0.6529, 0.9064, 0.1513],
        [0.2266, 0.0638, 0.7167],
        [0.9584, 0.2249, 0.3886],
        [0.5951, 0.3845, 0.1420],
        [0.5481, 0.6934, 0.4441]])
tensor([[-0.3197,  1.5590, -0.1356],
        [-0.5416,  0.5842,  0.6489],
        [-0.2995,  1.9865, -0.6612],
        [-2.1185, -0.3004, -0.9796],
        [ 1.0672, -1.3770, -2.1603]])
tensor([[-0.5929,  0.1696,  2.1559],
        [-1.1999, -0.6092, -0.6659],
        [-1.6852,  0.1938, -1.3117],
        [-1.2000,  0.6953, -0.1696],
        [-0.2592,  1.2165, -0.2483]])
tensor([1.0000, 1.3636, 1.7273, 2.0909, 2.4545, 2.8182, 3.1818, 3.5455, 3.9091,
        4.2727, 4.6364, 5.0000])


In [ ]:
tensor = torch.rand([2,3],dtype=torch.float64)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")#创建在内存中

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float64
Device tensor is stored on: cpu


In [ ]:
# 设置张量在GPU上运算
if torch.cuda.is_available():#需要cuda环境
    device = torch.device('cuda')#GPU不行= =
    tensor = tensor.to(device)
print(tensor)
print(tensor.device)

#M系列芯片
if torch.backends.mps.is_available():
    device = torch.device('mps')#GPU不行= =
    tensor = tensor.to(device)
print(tensor)
print(tensor.device)


tensor([[0.1111, 0.7721, 0.4142],
        [0.6041, 0.6428, 0.9616]], dtype=torch.float64)
cpu
tensor([[0.1111, 0.7721, 0.4142],
        [0.6041, 0.6428, 0.9616]], dtype=torch.float64)
cpu


In [ ]:

data4 =torch.arange(1,17,).reshape(4,4)   #([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)]) 
tensor = torch.tensor(data4)
print('First row: ', tensor[0])#第一行
print('First column: ', tensor[:, 0])#所有行第一列
print('Last column:', tensor[..., -1])#所有行的最后一列
tensor[:,1] = 0 #第一列都为0
print(tensor)

First row:  tensor([1, 2, 3, 4])
First column:  tensor([ 1,  5,  9, 13])
Last column: tensor([ 4,  8, 12, 16])
tensor([[ 1,  0,  3,  4],
        [ 5,  0,  7,  8],
        [ 9,  0, 11, 12],
        [13,  0, 15, 16]])


C:\Users\MLoong\AppData\Local\Temp\ipykernel_17696\1461880843.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(data4)


In [186]:
#使⽤ torch.cat ⽤来连接指定维度的⼀系列张量
t1 = torch.cat([tensor, tensor, tensor], dim=1)#
print(t1)
print(t1.shape)
print()
#使⽤ torch.stack ⽤来连接指定维度的⼀系列张量
t1 = torch.stack([tensor, tensor, tensor], dim=0)#
print(t1)
print(t1.shape)


tensor([[ 1,  0,  3,  4,  1,  0,  3,  4,  1,  0,  3,  4],
        [ 5,  0,  7,  8,  5,  0,  7,  8,  5,  0,  7,  8],
        [ 9,  0, 11, 12,  9,  0, 11, 12,  9,  0, 11, 12],
        [13,  0, 15, 16, 13,  0, 15, 16, 13,  0, 15, 16]])
torch.Size([4, 12])

tensor([[[ 1,  0,  3,  4],
         [ 5,  0,  7,  8],
         [ 9,  0, 11, 12],
         [13,  0, 15, 16]],

        [[ 1,  0,  3,  4],
         [ 5,  0,  7,  8],
         [ 9,  0, 11, 12],
         [13,  0, 15, 16]],

        [[ 1,  0,  3,  4],
         [ 5,  0,  7,  8],
         [ 9,  0, 11, 12],
         [13,  0, 15, 16]]])
torch.Size([3, 4, 4])


In [200]:
# 计算两个张量之间矩阵乘法的⼏种⽅式。 y1, y2, y3 最后的值是⼀样的 dot
tensor=torch.arange(1,10,dtype=torch.float32).reshape(3,3)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)
# 计算张量逐元素相乘的⼏种⽅法。 z1, z2, z3 最后的值是⼀样的。
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)
print(z2)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [207]:
#如果⼀个单元素张量，例如将张量的值聚合计算，可以使⽤ item() ⽅法将其转换为Python 数值
tensor2 = torch.arange(1,16,dtype=torch.float32).reshape(3,5)
print(tensor2)
agg = tensor2.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]])
120.0 <class 'float'>


In [ ]:
#in_place
#张量内部的值，直接被修改
print(tensor2,'\n')
tensor2.add_(10)
print(tensor2)

tensor([[ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.]]) 

tensor([[16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]])


In [ ]:
from torchviz import make_dot
# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * A + b * x + c 
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\MLoong\AppData\Local\Temp\ipykernel_17696\2394107829.py:8: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:3729.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression.png'