In [13]:
import numpy as np


In [4]:
for i in range(1, 11):
    print(i/10, np.log(i/10))

0.1 -2.3025850929940455
0.2 -1.6094379124341003
0.3 -1.2039728043259361
0.4 -0.916290731874155
0.5 -0.6931471805599453
0.6 -0.5108256237659907
0.7 -0.35667494393873245
0.8 -0.2231435513142097
0.9 -0.10536051565782628
1.0 0.0


# Load training data

get 50 of type_0, and 50 of type_1

In [15]:
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)
X.shape, y.shape
# X[:5]
# y[:5]
# print(X)
# print(y)
y1 = y[0:50]
y2 = y[50:100]
new_y = np.concatenate((y1, y2), axis=0)
new_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
def load_sampleing_data():
    X, y = load_iris(return_X_y=True)
    sample_set_A = X[0:50]
    sample_set_B = X[50:100]
    sample_set = np.concatenate((sample_set_A, sample_set_B), axis=0)

    category_A = y[0:50]
    category_B = y[50:100]
    category_set = np.concatenate((category_A, category_B), axis=0)
    return sample_set, category_set


In [27]:
from sklearn.model_selection import train_test_split
def get_train_test_data(sample_set, category_set, test_size=0.2):
    train_sample_set, test_sample_set, train_category_set, test_category_set = train_test_split(sample_set, category_set, test_size=test_size, random_state=42, shuffle=True)
    return train_sample_set, test_sample_set, train_category_set, test_category_set


In [28]:
sample_set, category_set = load_sampleing_data()
train_sample_set, test_sample_set, train_category_set, test_category_set = get_train_test_data(sample_set, category_set)
print(train_sample_set, test_sample_set, train_category_set, test_category_set)
print(train_sample_set.shape, test_sample_set.shape, train_category_set.shape, test_category_set.shape)

[[5.7 2.8 4.5 1.3]
 [5.6 3.  4.1 1.3]
 [5.  3.4 1.6 0.4]
 [4.4 3.2 1.3 0.2]
 [5.6 2.5 3.9 1.1]
 [5.7 4.4 1.5 0.4]
 [5.  3.5 1.3 0.3]
 [5.7 2.9 4.2 1.3]
 [4.9 3.1 1.5 0.1]
 [6.3 2.5 4.9 1.5]
 [4.8 3.4 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [6.  3.4 4.5 1.6]
 [5.2 3.4 1.4 0.2]
 [5.  2.3 3.3 1. ]
 [5.4 3.9 1.7 0.4]
 [5.6 3.  4.5 1.5]
 [6.7 3.1 4.4 1.4]
 [5.  3.2 1.2 0.2]
 [5.4 3.9 1.3 0.4]
 [5.  3.3 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [5.2 3.5 1.5 0.2]
 [5.1 3.8 1.5 0.3]
 [5.5 2.4 3.7 1. ]
 [5.  3.  1.6 0.2]
 [6.  2.2 4.  1. ]
 [4.3 3.  1.1 0.1]
 [4.8 3.4 1.9 0.2]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [4.4 3.  1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [6.  2.9 4.5 1.5]
 [4.6 3.4 1.4 0.3]
 [5.6 2.9 3.6 1.3]
 [5.5 3.5 1.3 0.2]
 [5.5 2.5 4.  1.3]
 [6.3 3.3 4.7 1.6]
 [5.7 2.8 4.1 1.3]
 [6.5 2.8 4.6 1.5]
 [5.  3.5 1.6 0.6]
 [7.  3.2 4.7 1.4]
 [5.8 2.7 4.1 1. ]
 [5.1 3.8 1.6 0.2]
 [6.2 2.2 4.5 1.5]
 [5.9 3.  4.2 1.5]
 [6.2 2.9 4.3 1.3]
 [5.7 2.6 3.5 1. ]
 [4.5 2.3 1.3 0.3]
 [6.6 2.9 4.

In [34]:
theta = np.random.randn(4)
theta

array([ 0.71585026, -1.04000303, -1.04449097,  0.83505086])