In [1]:
import numpy as np
a = [1,2,3]
b = np.array(a)
b

array([1, 2, 3])

In [2]:
a = np.array([1,2,3],float)
a

array([1., 2., 3.])

In [3]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
a 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a = np.zeros((3,4),dtype = float)
a 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
a = np.arange(1,10,0.3)
a

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
       8.8, 9.1, 9.4, 9.7])

In [11]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
a = np.random.random(5)
a

array([0.26535338, 0.43199591, 0.45743995, 0.21528814, 0.0212151 ])

In [18]:
mu,sigma = 0, 0.1
a = np.random.normal(mu,sigma,5)
a

array([ 0.01730427,  0.04444697, -0.11973847, -0.08130224, -0.10487705])

In [ ]:
a = np.array([(1,2),(3,4),(5,6)])
a[0]
a[1:]
a[1][1]
a[:,:1]
a[:,:]

array([[1],
       [3],
       [5]])

In [31]:
a = np.array((1,2,3))
for i in a:
  print(i)

1
2
3


In [35]:
a = np.array([(1,2),(3,4),(5,6)])
for i,j in a:
  print(i*j)

2
12
30


In [ ]:
a = np.array([(1,2,3), (4,5,6), (7,8,9)])
print("ndim",a.ndim) #维度
print("shape",a.shape) #形状
print("size",a.size) #元素个数
print("dtype",a.dtype) #数据类型


ndim 2
shape (3, 3)
size 9
dtype int32


In [ ]:
a = np.array([(1,2),(3,4)])
print(3 in a ) #
print(5 in a )

True
False


In [ ]:
a = np.zeros([2,3,4])
a
b = a.reshape(a.size) #展平成一维数组
a
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [58]:
a = np.array([[1,2,3],(4,5,6),(7,8,9)])
a
a.transpose() #转置 (可以用.T)
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a = np.array([(1,2),(3,4),(5,6)])
a.flatten() #展平成一维数组

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([1,2,3])
a = a[:,np.newaxis] #增加一维
a = a[:,np.newaxis]
a
a.shape #形状

(3, 1, 1)

In [ ]:
 a = np.ones((2,2))
 b = np.array([(-1,1),(-1,1)]) 
 print(a)
 print(b)
 
 a + b
 a - b
 a * b
 a / b
 
 

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]


array([[-1.,  1.],
       [-1.,  1.]])

In [ ]:
a = np.array([1,2,1])
a.sum() #求和
a.prod() #求积

2

In [82]:
a = np.array([5,3,1])
a
print("mean",a.mean()) #求均值
print("var",a.var()) #求方差
print("std",a.std()) #求标准差
print("min",a.min()) #求最小值
print("max",a.max()) #求最大值


mean 3.0
var 2.6666666666666665
std 1.632993161855452
min 1
max 5


In [83]:
a = np.array([1.2,3.8,4.9])
print("argmax",a.argmax()) #求最大值的索引
print("argmin",a.argmin()) #求最小值的索引
print("ceil", np.ceil(a)) #向上取整
print("floor",np.floor(a)) #向下取整
print("rint",np.rint(a)) #四舍五入


argmax 2
argmin 0
ceil [2. 4. 5.]
floor [1. 3. 4.]
rint [1. 4. 5.]


In [ ]:
a = np.array([16,31,12,28,22,31,48])
a.sort() #排序


AxisError: axis 1 is out of bounds for array of dimension 1

In [109]:
#定义两个简单的矩阵
m1 = np.array([[1, 2], [3, 4]] , dtype=np.float32)
m2 = np.array([[5, 6], [7, 8]] , dtype=np.float32)
# 使用np.dot函数计算矩阵乘法
result_dot = np.dot(m1, m2)
print(result_dot)
# 使用 @ 运算符进行矩阵乘法
result_at = m1 @ m2
print(result_at)

print("矩阵1 :")
print(m1)
print("矩阵2 :")
print(m2)
print("使用 np.dot 矩阵乘法结果 :")
print(result_dot)


print("使⽤ @ 运算符得到的矩阵乘法结果:")
print(result_at)
# 创建⼀个全零矩阵，⽤于存储⼿动推演的结果
# 结果矩阵的⾏数等于 matrix1 的⾏数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0], m2.shape[1]), dtype=np.float32)
# 外层循环：遍历 matrix1 的每⼀⾏
# i 表⽰结果矩阵的⾏索引
for i in range(m1.shape[0]):
  # 中层循环：遍历 matrix2 的每⼀列
  # j 表⽰结果矩阵的列索引
  for j in range(m2.shape[1]):
    # 初始化当前位置的结果为 0
    manual_result[i, j] = 0
    # 内层循环：计算 matrix1 的第 i ⾏与 matrix2 的第 j 列对应元素的乘积之和
    # k 表⽰参与乘法运算的元素索引
    for k in range(m1.shape[1]):
      # 打印当前正在计算的元素
      print(f"{m1[i, k]} * {m2[k, j]} = {m1[i, k] * m2[k, j]}")
      # 将 matrix1 的第 i ⾏第 k 列元素与 matrix2 的第 k ⾏第 j 列元素相乘，并累
      manual_result[i, j] += m1[i, k] * m2[k, j]
    # 打印当前位置计算完成后的结果
  print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i, j]}\n")
  
print("⼿动推演结果:")
print(manual_result)

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]
矩阵1 :
[[1. 2.]
 [3. 4.]]
矩阵2 :
[[5. 6.]
 [7. 8.]]
使用 np.dot 矩阵乘法结果 :
[[19. 22.]
 [43. 50.]]
使⽤ @ 运算符得到的矩阵乘法结果:
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

⼿动推演结果:
[[19. 22.]
 [43. 50.]]
