In [1]:
import torch
import numpy as np


In [3]:

data = [[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [11]:
x_ones = torch.ones_like(x_data)
x_ones
x_rand = torch.rand_like(x_data,dtype=torch.float32) #覆盖x_data的数据类型
x_rand

tensor([[0.1390, 0.4455],
        [0.8489, 0.3798]])

In [14]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor,ones_tensor,zeros_tensor
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7261, 0.9440, 0.4538],
        [0.9412, 0.1122, 0.3581]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [22]:
# 基于现有tensor构建，但使⽤新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

# 获取tensor的大小
print(m.size()) # 输出：torch.Size([5, 3])

# 均匀分布
z = torch.rand(5,3)
# 标准正态分布
z = torch.randn(5,3)
# 离散正态分布
z = torch.normal(mean= .0, std=1.0,size=(5,3) )
z 

torch.Size([5, 3])


tensor([[ 0.9069,  0.8733,  1.4251],
        [ 1.2052,  0.2578,  0.4423],
        [-0.8137, -0.4854,  0.5000],
        [-0.0886, -0.7007, -0.8063],
        [-1.1262,  0.3225, -0.3218]])

In [26]:
tensor = torch.rand(3,4)
print(f'shape of tensor ：{tensor.shape}')
print(f'Datatype of tensor : {tensor.dtype}')
print(f'device of tensor : {tensor.device}')

shape of tensor ：torch.Size([3, 4])
Datatype of tensor : torch.float32
device of tensor : cpu


In [27]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")          # a CUDA device object
   

In [ ]:
tensor = torch.rand(4,4)
tensor
print('First row',tensor[0])
print('First column',tensor[:,0])
print('Last column',tensor[:,-1])
tensor[:,1] = 0
print(tensor)

First row tensor([0.7006, 0.3871, 0.8329, 0.1644])
First column tensor([0.7006, 0.3481, 0.9978, 0.2918])
Last column tensor([0.1644, 0.2232, 0.7124, 0.0647])
tensor([[0.7006, 0.3871, 0.8329, 0.1644],
        [0.3481, 0.7049, 0.5887, 0.2232],
        [0.9978, 0.6475, 0.9350, 0.7124],
        [0.2918, 0.5288, 0.9663, 0.0647]])


In [31]:
# tensor的运算 
# 计算两个张量之间矩阵乘法的几种方法 y1,y2,y3 最后的值是一样的dot 
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)
y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)

# 计算张量逐元素相乘的几种方法， ,z1,z2,z3 最后的值是一样的
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)


tensor([[1.3615, 1.0437, 1.8456, 1.2246],
        [1.0437, 1.0145, 1.5132, 1.0577],
        [1.8456, 1.5132, 2.7965, 1.5832],
        [1.2246, 1.0577, 1.5832, 1.3028]])
tensor([[1.3615, 1.0437, 1.8456, 1.2246],
        [1.0437, 1.0145, 1.5132, 1.0577],
        [1.8456, 1.5132, 2.7965, 1.5832],
        [1.2246, 1.0577, 1.5832, 1.3028]])


tensor([[0.4909, 0.1498, 0.6937, 0.0270],
        [0.1211, 0.4969, 0.3466, 0.0498],
        [0.9956, 0.4192, 0.8743, 0.5075],
        [0.0852, 0.2796, 0.9338, 0.0042]])

In [34]:
tensor = torch.rand(4,4)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,type(agg_item))


8.715234756469727 <class 'float'>


In [36]:
print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor([[0.0073, 0.9727, 0.8256, 0.5737],
        [0.1975, 0.8490, 0.8843, 0.6112],
        [0.1523, 0.8226, 0.8213, 0.2509],
        [0.6733, 0.0476, 0.0803, 0.9458]]) 

tensor([[5.0073, 5.9727, 5.8256, 5.5737],
        [5.1975, 5.8490, 5.8843, 5.6112],
        [5.1523, 5.8226, 5.8213, 5.2509],
        [5.6733, 5.0476, 5.0803, 5.9458]])


In [37]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [38]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n,1,out = n )
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [2]:
import torch
from torchviz import make_dot

# 定义矩阵 A，向量 b 和常数 c
A = torch.randn(10, 10,requires_grad=True)
b = torch.randn(10,requires_grad=True)
c = torch.randn(1,requires_grad=True)
x = torch.randn(10, requires_grad=True)
# 计算 x^T * A + b * x + c
result = torch.matmul(A, x.T) + torch.matmul(b, x) + c
# ⽣成计算图节点
dot = make_dot(result, params={'A': A, 'b': b, 'c': c, 'x': x})
# 绘制计算图
dot.render('expression', format='png', cleanup=True, view=False)

C:\Users\zhang\AppData\Local\Temp\ipykernel_41352\3594221820.py:10: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  result = torch.matmul(A, x.T) + torch.matmul(b, x) + c


'expression.png'

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
  
print(sigmoid(2))

0.8807970779778823
